eclipse-hono/hono

- adapters/rest/pom.xml
- adapters/rest/src/main/java/org/eclipse/hono/adapter/rest/BinaryHttpRequestMapping.java
- adapters/rest/src/main/java/org/eclipse/hono/adapter/rest/RestProtocolAdapter.java
- adapters/rest/src/test/java/org/eclipse/hono/adapter/rest/RestProtocolAdapterTest.java
- adapters/rest/src/test/resources/logback-test.xml
- bom/pom.xml
Telemetry data is supplied by devices using HTTP PUT requests without
expecting any response body.
@hekonsek,
I have tried to re-factor according to what my comments in #3. I do not want to impose these changes without us agreeing on what we want to achieve. I therefore creatad this PR in order to not loose my changes and discuss how we want to proceed :-)
> Support telemetry data upload.

- example/readme.md
- server/src/main/java/org/eclipse/hono/authentication/AuthenticationService.java
- server/src/main/java/org/eclipse/hono/telemetry/impl/BaseTelemetryAdapter.java
Fixed typo on qpid-sasldb name Docker images in the example README.md
> Fixed few typos on summary methods

- client/src/main/java/org/eclipse/hono/client/TelemetrySender.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- example/src/main/java/org/eclipse/hono/example/ExampleReceiver.java
- example/src/main/java/org/eclipse/hono/example/ExampleSender.java
Added the possibility to send application properties in the message f…or TelemetrySender and related implementation
Changed examples accordigly to show how using application properties in a telemetry message
> Added the possibility to send application properties in the telemetry message

- adapters/mqtt-vertx/pom.xml
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/Application.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/Config.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/MqttAdapterFactory.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx/src/main/resources/logback-spring.xml
- adapters/pom.xml
- adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/Application.java
- adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/VertxBasedRestProtocolAdapter.java
- bom/pom.xml
Run as verticle and start the Vert.x MQTT server.
> Added first step implementation for the MQTT adapter 

- adapters/lwm2m/pom.xml
- adapters/lwm2m/src/main/java/org/eclipse/hono/adapter/lwm2m/ApplicationConfig.java
- adapters/lwm2m/src/main/java/org/eclipse/hono/adapter/lwm2m/observation/TelemetryForwarder.java
- application/src/main/resources/permissions.json
- bom/pom.xml
- example/docker/docker-compose.yml
Hi Hono-Devs,
I updated the `lwm2m` adapter on the `add_lwm2m`-branch so that it works again with the current version of hono. 
Main changes were: 
* Adapted code to compile with new hono version 
* Added 'build docker image'-step to lwm2m adapter
* Included lwm2m adapter in `example`-project docker-compose file.
If the PR succeeds we will create another PR with an update to leshan-1.0.0-M1.
Best regards
Chris
> Updated lwm2m-adapter on add_lwm2m-branch

- adapters/lwm2m/pom.xml
- adapters/lwm2m/src/main/java/org/eclipse/hono/adapter/lwm2m/ApplicationConfig.java
- adapters/lwm2m/src/main/java/org/eclipse/hono/adapter/lwm2m/LeshanDemoServer.java
- adapters/lwm2m/src/main/java/org/eclipse/hono/adapter/lwm2m/observation/TelemetryForwarder.java
- adapters/lwm2m/src/main/java/org/eclipse/hono/adapter/lwm2m/security/AbstractHonoBasedSecurityRegistry.java
- core/src/test/java/org/eclipse/hono/connection/ConnectionFactoryImplTest.java
Hi,
as promised in our last PR, here the update to leshan 1.0.0-M1 for the LWM2M branch.
Signed-off-by: Daniel Maier <Daniel.Maier@bosch-si.com>
> Update to Leshan 1.0.0-M1

- adapters/http-vertx-base/pom.xml
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/pom.xml
- adapters/rest-vertx/pom.xml
- adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/VertxBasedRestProtocolAdapter.java
A base class has been extracted out of VertxBasedRestProtocolAdapter to be used for HTTP-based protocol adapters.
> [#98] Base class for HTTP protocol adapters

- adapters/mqtt-vertx/src/main/fabric8/hono-adapter-mqtt-vertx-dc.yml
- adapters/rest-vertx/src/main/fabric8/hono-adapter-rest-vertx-dc.yml
- application/src/main/fabric8/hono-app-dc.yml
- dispatchrouter/src/main/fabric8/dispatch-router-dc.yml
- dispatchrouter/src/main/fabric8/dispatch-router-svc.yml
Changed dispatch router 5673 port name to "downstream" for the OpenShift deployment
> Added liveness probes to all OpenShift "deployments"

- application/src/main/resources/application.yml
- server/src/main/java/org/eclipse/hono/server/HonoServer.java
- server/src/test/java/org/eclipse/hono/server/HonoServerTest.java
- site/content/component/hono-server.md
> [#152] Small usability enhancement for configuring an insecure port

- site/content/component/hono-server.md
> fixed documentation item list rendering for hugo (newline missing)

- pom.xml
- site/build-site.sh
- site/pom.xml
Signed-off-by: Ingo Maas <ingo.maas@bosch-si.com>
> Mavenize Hono site: build Hono site using Maven

- site/content/api/Telemetry-API.md
- site/content/deployment/docker-swarm.md
> mini fixes to documentation.

- site/content/api/Credentials-API.md
This is a first draft. Comments, improvement suggestions etc welcome :-)
I would be interested in other opinions regarding the response payload. I wonder whether it would be better to include the *device_id* in the payload instead of the message properties only. Or maybe *also* include it in the payload ...
> Add Credentials API for managing, retrieving device credentials.

- adapters/mqtt-vertx/src/main/fabric8/hono-adapter-mqtt-vertx-dc.yml
- adapters/rest-vertx/src/main/fabric8/hono-adapter-rest-vertx-dc.yml
> Fix indentation for livenessProbe/initialDelaySeconds value

- application/src/main/resources/permissions.json
- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
- server/src/main/java/org/eclipse/hono/application/HonoApplication.java
- server/src/test/resources/permissions.json
- service-base/src/main/java/org/eclipse/hono/service/amqp/BaseEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsEndpoint.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsEndpointTest.java
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/jms/RegistrationTestSupport.java
3rd step towards credentials API in Hono (endpoint and service instantiation in Hono, client part will follow afterwards).
> [#169] Provide credentials API endpoint in Hono

- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
- server/src/main/java/org/eclipse/hono/server/MessageForwardingEndpoint.java
- server/src/test/java/org/eclipse/hono/telemetry/TelemetryMessageFilterTest.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/BaseEndpoint.java
- service-base/src/test/java/org/eclipse/hono/service/registration/RegistrationMessageFilterTest.java
- tests/src/test/java/org/eclipse/hono/tests/jms/RegistrationTestSupport.java
Refactoring for being consistant on using MessageHelper constants
> Renamed correlation-id constant name as a system property

- adapters/mqtt-vertx/pom.xml
- adapters/rest-vertx/pom.xml
- application/pom.xml
Signed-off-by: Oliver Fischer <oliver.fischer@bosch-si.com>
> using openjdk 8 as docker base image for hono components

- server/src/main/java/org/eclipse/hono/server/MessageForwardingEndpoint.java
- server/src/test/java/org/eclipse/hono/server/HonoServerTest.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/BaseEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/impl/RequestResponseEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationEndpoint.java
First refactoring to reduce the code duplication introduced by the credentials API (some more to follow).
> [#181] Common base class for registration and credentials API endpoints.

- client/src/main/java/org/eclipse/hono/client/CredentialsClient.java
- client/src/main/java/org/eclipse/hono/client/RegistrationClient.java
- client/src/main/java/org/eclipse/hono/client/RequestResponseClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
- core/src/main/java/org/eclipse/hono/util/CredentialsResult.java
- core/src/main/java/org/eclipse/hono/util/RegistrationResult.java
- core/src/main/java/org/eclipse/hono/util/RequestResponseResult.java
Second refactoring for common base classes for request response APIs - focussed on the client implementation.
> [#181] Common base class for request response client implementations.

- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/MessageSender.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- tests/src/test/java/org/eclipse/hono/tests/client/ClientTestBase.java
> [#194] MQTT Protocol Adapter send PUBACK only when remote has accepted the message

- bom/pom.xml
- jmeter/.gitignore
- jmeter/pom.xml
- jmeter/readme.md
- jmeter/src/main/java/org/eclipse/hono/jmeter/HonoReceiverSampler.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSampler.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
- pom.xml
> JMeter plugin

- jmeter/src/jmeter/hono_jmeter_runtime.jmx
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
Added Swing UI and default JMeter project.
> UIs and default project for JMeter [#190]

- jmeter/src/jmeter/hono_jmeter_runtime.jmx
- jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSampler.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoServerOptionsPanel.java
New configuration options for the service and usage of second client.
> Support for device registry as own/new service

- site/content/component/auth-server.md
- site/content/component/device-registry.md
- site/content/component/hono-server.md
Some additional minor documentation fixes included as well.
> [#203] Documentation completed for device registry.

- site/content/deployment/openshift.md
> Openshift step by step deployment description updated.

- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- example/src/main/java/org/eclipse/hono/example/ExampleReceiver.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
> [#239] Disconnect handler with reconnect strategy for Hono REST PA.

- dispatchrouter/pom.xml
- dispatchrouter/src/main/fabric8/deployment.yml
> Moved router startup command from YML descriptor to the POM file

- jmeter/src/jmeter/hono_jmeter_runtime.jmx
- jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSampler.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
- fix in setting repository host from UI
- changed port property to allow better use of variables
- close vert.x thread at cleanup
> JMeter plugin changes

- service-base/src/main/java/org/eclipse/hono/service/registration/BaseDeviceRegistryServer.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/SimpleDeviceRegistryServer.java
Introduced new parent class and moved logic.
> [#259] Provide device registry in hono-service-base.

- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
Added a new class HttpServiceBase in hono-service-base to provide HTTP
service support.
> [#259] Add HttpServiceBase.

- service-base/src/main/java/org/eclipse/hono/service/AbstractApplication.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/HealthCheckProvider.java
- service-base/src/main/java/org/eclipse/hono/service/HealthCheckServer.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/BaseEndpoint.java
See PRs #287 and #290 for discussion.
> [#259] Move health check from service to application level.

- example/src/main/java/org/eclipse/hono/example/AppConfiguration.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
Fixes the issue reported in https://github.com/eclipse/hono/issues/332 for Hono Example Receiver and Hono JMeter Plugin
Signed-off-by: Balasubramanian <balasubramanian.azhagappan@bosch-si.com>
> setting DNS resolution to rotate DNS servers

- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java
Added few more logging messages to MQTT adapter
Changed log levels for some logging messages in the MQTT adapter
> Logging improvements on the MQTT adapter

- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsHttpEndpoint.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
- site/content/api/Credentials-API.md
Added Credentials API HTTP REST endpoint with only add operation
Implemented add credentials operation in the FileBasedCredentialsService
> Initial implementation of Credentials API HTTP endpoint

- core/src/main/java/org/eclipse/hono/util/CredentialsResult.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
> This change makes the empty CredentialsResult method generic

- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/RegistrationRestServerTest.java
Test for `DeviceRegistryRestServer`.
> Add DeviceRegistryRestServerTest

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
This is the second PR following #357 (as agreed in #338)
Whenever a message with timestamp is received (timestamp either in payload or as application property), message delivery is calculated (as _receivedTime - timeInPayload_) and added to total delivery time.
Now when sample is called, the sampling time for Hono Receiver is calculated as follows:
_totalSampleDeliveryTime  / messageReceivedCount_
Signed-off-by: Balasubramanian <balasubramanian.azhagappan@bosch-si.com>
> Hono JMeter Plugin: using mean value of all messages delivery time in Hono Receiver

- example/src/main/config/hono-service-messaging-config-enmasse.yml
- example/src/main/deploy/openshift/addresses.json
- example/src/main/deploy/openshift/common.sh
- example/src/main/deploy/openshift/enmasse_deploy.sh
- site/content/deployment/enmasse.md
First stab at integrating Hono with EnMasse.
https://github.com/dejanb/hono/blob/enmasse/site/content/deployment/enmasse.md contains basic instructions how to start and test things. I'll work on more formal documentation when we agree that this is the proper way to go.
> EnMasse integration

- core/src/main/java/org/eclipse/hono/util/JwtHelper.java
> Fix error message and file name to all error messages

- service-base/src/main/java/org/eclipse/hono/service/AbstractApplication.java
This change does re-write the startup code in way that it does handle
a failed initialization chain. It removed an unnecessary compose
element at the end of the chain and uses a CompletableFuture instead
of the CountDownLatch to wait for the final result.
This way the final result may receive any exception thrown by the
startup chain of futures and immediately shutdown outside of the vertx
context.
----
Please note: this is not a fix for #432
> Properly handle a failed initialization

- client/src/main/java/org/eclipse/hono/client/impl/AbstractConsumer.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetryConsumerImpl.java
This change aligns the consumer QoS with the producer QoS for telemetry data.
> Fix misaligned QoS settings

- adapters/http-vertx/src/main/resources/logback-spring.xml
- adapters/kura/src/main/resources/logback-spring.xml
- adapters/mqtt-vertx/src/main/resources/logback-spring.xml
- services/auth/src/main/resources/logback-spring.xml
- services/device-registry/src/main/resources/logback-spring.xml
- services/messaging/src/main/resources/logback-spring.xml
This change does print out the exception of a failed connection attempt. Which really helps when finding connection issues 😉
> Log cause of failed connection attempt

- client/src/main/java/org/eclipse/hono/client/impl/EventSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- services/messaging/src/main/java/org/eclipse/hono/event/impl/ForwardingEventDownstreamAdapter.java
This effectively fixes the memory leak for me. But I am not sure if this is the right solution.
@dejanb: Could you check if this is the way to fix this?!
> [#454] Fix memory leak in TelemetrySenderImpl and EventSenderImpl

- client/src/main/java/org/eclipse/hono/client/impl/AbstractConsumer.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/EventConsumerImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetryConsumerImpl.java
- merged creation of receivers
- delegate error in open attach
- added logs for detach and failed open
> [#459] Open handler fail delegate; close handler added; logs

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- site/content/user-guide/http-adapter.md
This is the 3rd part of adding support for gateways.
It adds support for HTTP based gateways.
> [#416] Support devices acting as gateways in HTTP adapter.

- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- core/src/test/java/org/eclipse/hono/util/TenantConstantsTest.java
- example/src/main/deploy/openshift/openshift_deploy.sh
- service-base/src/main/java/org/eclipse/hono/service/tenant/TenantMessageFilter.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/BaseTenantServiceTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/TenantAmqpEndpointTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/TenantMessageFilterTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/DeviceRegistryTestUtils.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
Due to squashed base commits, it was problematic to rebase the original PR #476 .
Inside this rebased PR all commits (squashed to single commits into senseful units) are contained.
> Tenant API Tests.

- client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
- core/src/main/java/org/eclipse/hono/util/Constants.java
- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- core/src/test/java/org/eclipse/hono/util/CredentialsConstantsTest.java
- core/src/test/java/org/eclipse/hono/util/TenantConstantsTest.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsMessageFilter.java
- service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java
- service-base/src/main/java/org/eclipse/hono/service/tenant/TenantHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/tenant/TenantMessageFilter.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsAmqpEndpointTest.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsMessageFilterTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/BaseTenantServiceTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/TenantAmqpEndpointTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/TenantMessageFilterTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/DeviceRegistryTestUtils.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/TenantsRestServerTest.java
PR purely for merging combined commits from [#481]
> Hono tenant api http endpoints

- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- core/src/main/java/org/eclipse/hono/util/TenantResult.java
- service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
> Fix a few warnings cause by generics

- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
Allowing HonoClient implementation to be extensible so that specific custom implementations can be instantiated without replicating the whole HonoClient implementation. 
The following methods will enable custom client instances to be instantiated
```
HonoClientImpl#newRegistrationClient()
HonoClientImpl#newCredentialsClient()
```
and enables cleanup by using the following methods
```
HonoClientImpl#removeRegistrationClient() 
HonoClientImpl#removeCredentialsClient()
```
Signed-off-by: Bala Azhagappan <balasubramanian.azhagappan@bosch-si.com>
> Making the HonoClient implementation extensible

- site/content/admin-guide/device-registry-config.md
- site/content/user-guide/device-registry.md
> Document http access to the Tenant API of the device registry.

- legal/legal/NOTICE.md
As this touches legal, I think an additional pair of eyes is required.
> Update the notice file, 2018, more precise

- pom.xml
As this is a legal matter another set of eyes might be appropriate.
> Add @ctron as committer to the project as suggested by @sophokles73

- example/src/main/deploy/openshift/common.sh
- example/src/main/deploy/openshift/enmasse_deploy.sh
- example/src/main/deploy/openshift/openshift_deploy.sh
- example/src/main/deploy/openshift/openshift_undeploy.sh
- services/device-registry/src/main/fabric8/registry-pvc.yml
- site/content/deployment/openshift.md
This drops the special handling for the PV/PVC and uses the (newly added) Minishift pre-created PVs.
> Drop special PV handling for minishift

- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
> [#591] Trivial fix of a possible NPE in HonoClientImpl

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
- core/src/main/java/org/eclipse/hono/util/Constants.java
- legal/legal/NOTICE.md
> [Http Adapter] Add support for publishing data with QoS 1

- client/src/main/java/org/eclipse/hono/client/HonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
- core/src/main/java/org/eclipse/hono/connection/ConnectionFactory.java
- core/src/main/java/org/eclipse/hono/connection/impl/ConnectionFactoryImpl.java
- core/src/test/java/org/eclipse/hono/connection/impl/ConnectionFactoryImplTest.java
- example/src/main/java/org/eclipse/hono/example/AppConfiguration.java
- service-base/src/main/java/org/eclipse/hono/service/auth/delegating/DelegatingAuthenticationServiceConfig.java
- services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/auth/AuthServerAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/ClientTestBase.java
This PR fixes the OSGi client instatiation issue reported in #586. I also aligns both pattern of the `HonoClient` and `ConnectionFactory`.
> #586 Fix OSGi client instantiation

- client/src/main/java/org/eclipse/hono/client/CommandClient.java
- client/src/main/java/org/eclipse/hono/client/HonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TenantClientImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
- client/src/test/java/org/eclipse/hono/client/impl/SimpleRequestResponseResult.java
- client/src/test/java/org/eclipse/hono/client/impl/TenantClientImplTest.java
- core/src/main/java/org/eclipse/hono/util/BufferResult.java
- core/src/main/java/org/eclipse/hono/util/CommandConstants.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- site/content/release-notes.md
Business Application side of Command and Control:
- changed String/JSON to Buffer in the base classes to support binary content.
- new CommandClient to send commands, which expects a result.
- in this implementation a pair of links is created for each device
> Client implementation for Command and Control

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
- core/src/main/java/org/eclipse/hono/util/EventConstants.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducer.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/LoggingConnectionEventProducer.java
- site/content/release-notes.md
These two commits are a base for discussion towards connection events as described in #565.
The PR is not intended to be merged right away, but to check out the direction.
Please check the second commit to see the actual changes as the first commit only contains code formatter changes.
> Connection events implementation

- site/content/user-guide/http-adapter.md
Signed-off-by: Sebastian Poehn <sebastian.poehn@bosch-si.com>
> http-adapter: Document 403 for disabled Protocol Adapter

- client/src/main/java/org/eclipse/hono/client/HonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoClientImplTest.java
Initial implementation of issue #500. the implementation mimics how the `shutdown` call is implemented.
@sophokles73 @calohmn
> Provide support for HonoClient#disconnect()

- site/content/community/get-in-touch.md
- site/content/community/project-call.ics
Add project call to the "get-in-touch" section.
I would like to encourage everyone to test out the ICS file: works-for-me™
> Add bi-weekly project call

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
@sophokles73: this PR fixes a minor bug in the adapter
> [#643] Bugfix - AMQP Adapter

- jmeter/src/jmeter/load-test-messaging-router.sh
Signed-off-by: Benjamin Cabé <benjamin.cabe@eclipse-foundation.org>
> Fix typos in AMQP jmeter launch script

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
Change in the JMeter plugin:
This improves error messages whenever there's a TimeoutException in `HonoSender.send()` - as in the scenario reported in #671.
> [#671] JMeter-Plugin: Improve error message in case of a TimeoutException

- client/pom.xml
- client/src/main/java/org/eclipse/hono/client/MessageSender.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/java/org/eclipse/hono/client/impl/EventSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
- core/src/main/java/org/eclipse/hono/tracing/MessageAnnotationsInjectAdapter.java
- core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/command/CommandResponseSenderImpl.java
> [#319] Add support for tracing messages being sent by AbstractSender.

- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
- core/src/main/java/org/eclipse/hono/util/LinkHelper.java
> [#677] Free link resources after links are closed.

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
Fix for #684:
Messages without required sender time information are counted as errors now, causing the SampleResult to become unsuccessful.
> [#684] Improve error handling in JMeter HonoReceiver

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
This fixes #683.
Also log output and SampleResult response message have been improved (no commas or duplicate info in response message any more).
> [#683] Ensure the timestamp on the JMeter SampleResult is always set

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
Fix regarding #671:
Correction regarding handling of TimeoutException during send().
> [#671] JMeter HonoSender: handling of TimeoutException

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
Fix for #699:
Add basic consistency check for request time calculation.
> [#699] JMeter plugin HonoReceiver: add check for request time calculation

- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSamplerUI.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
Fix alignment/indents of endpoint combo box.
> JMeter HonoSenderSamplerUI layout fix

- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterBase.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/EventAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/ClientTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/client/DeviceEventClientIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/DeviceTelemetryClientIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/EventClientIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/MessagingClientTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/client/TelemetryClientIT.java
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/amqp/logback-spring.xml
- tests/src/test/resources/auth/permissions.json
@sophokles73: first try on the AMQP adapter integration test. for some reason some of the tests are failing, so i temporarily marked them as `ignore` (while i investigate and allow you to look at the overall setup of the tests).
> [#643] AMQP Adapter integration tests

- client/src/main/java/org/eclipse/hono/client/MessageConsumer.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractConsumer.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
Improve log output by adding info about remaining credit.
> JMeter plugin: Improve sender log output

- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterBase.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
@sophokles73: this patch includes telemetry ITs for the adapter.
> [#643] Telemetry based integration tests for the AMQP adapter.

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- client/src/main/java/org/eclipse/hono/client/RegistrationClient.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
This is the last step for adding OpenTracing support.
> [#319] Support tracing of RegistrationClient requests.

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
@sophokles73: At the moment the AMQP adapter does not respond to Close frame emitted by a client when it wants to close the underlying connection. If a client emits its close frame, it waits forever without receiving the corresponding close frame from the server. This patch fixes that..
> [#643] respond to Close frame emitted by clients

- cli/pom.xml
- cli/src/main/java/org/eclipse/hono/cli/AbstractCliClient.java
- cli/src/main/java/org/eclipse/hono/cli/AbstractClient.java
- cli/src/main/java/org/eclipse/hono/cli/AmqpSend.java
- cli/src/main/resources/application.yml
@sophokles73 This integrates the command-line for the amqp adapter into the hono `cli` module.
> [#643] AMQP adapter CLI

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpAdapterMetrics.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttAdapterMetrics.java
- deploy/src/main/deploy/influxdb.conf
- service-base/src/main/java/org/eclipse/hono/service/metric/MetricConfig.java
- service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
- service-base/src/main/java/org/eclipse/hono/service/metric/NullCounterService.java
- service-base/src/main/java/org/eclipse/hono/service/metric/NullGaugeService.java
- services/messaging/src/main/java/org/eclipse/hono/messaging/MessagingMetrics.java
- site/content/release-notes.md
Records the payload size for MQTT and HTTP messages by measuring the payload body.
> Implement payload size metrics

- cli/src/main/java/org/eclipse/hono/cli/AmqpSend.java
@sophokles73: currently, the amqp command-line client tries to connect anonymously to the adapter if the username and password arguments are `null`. we should also check for empty username and password (as used in the examples for unauthenticated clients).
> [#643] AMQP command-line client: Check empty username & password

- deploy/src/main/config/grafana/dashboard-definitions/grafana_dashboard.json
Fixed Grafana: Names of instances for Command and Control in MQTT #769
> [#769] Fix Grafana: Names of instances for Command and Control in MQTT

- site/content/user-guide/http-adapter.md
It is actually 404 NOT FOUND
Signed-off-by: Sebastian Poehn <sebastian.poehn@bosch-si.com>
> docu: Correct disabled device for http adapter

- site/content/user-guide/amqp-adapter.md
@sophokles73 This patch includes documentation for SASL external in the AMQP adapter user-guide
> [#643] Include documentation for SASL EXTERNAL

- service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java
- service-base/src/test/java/org/eclipse/hono/service/amqp/RequestResponseEndpointTest.java
- services/auth/src/main/java/org/eclipse/hono/service/auth/impl/AuthenticationEndpoint.java
- services/messaging/src/main/java/org/eclipse/hono/messaging/MessageForwardingEndpoint.java
- tests/src/test/java/org/eclipse/hono/tests/jms/DeviceRegistrationIT.java
- tests/src/test/java/org/eclipse/hono/tests/jms/RegistrationTestSupport.java
This PR will fix both #753 and #756.
> [#735, #756] Fix service flooding and memory leak

- bom/pom.xml
- core/pom.xml
- core/src/main/java/org/eclipse/hono/util/BasePassword.java
- core/src/main/java/org/eclipse/hono/util/ClearTextPassword.java
- core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
- core/src/main/java/org/eclipse/hono/util/EncodedPassword.java
- core/src/main/java/org/eclipse/hono/util/MessageDigestPasswordEncoder.java
- core/src/main/java/org/eclipse/hono/util/PasswordEncoderFactory.java
- service-base/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordCredentials.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordCredentialsTest.java
- site/content/api/Credentials-API.md
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsAmqpIT.java
This is an implementation based on Spring Security Crypto module with some modification to be better suited for Hono.
I'll add CQ and docs when we decide to proceed with this.
> #688 - add support for more flexible password encoding

- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
- core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
To prevent a link based memory leak, sender and receiver links are
currently freed in their close handlers. However, the close handler
is only called if the remote peer reacts with a detach frame after the
client closed the link. Now a timer is created additionally to
supervise if there should be no detach frame from the remote to free
the link resources then.
> Free link resources for HonoClient if remote peer did not send detach.

- service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
- service-base/src/main/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationService.java
- service-base/src/main/java/org/eclipse/hono/service/registration/CompleteRegistrationService.java
- service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
- service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java
This is some initial work toward https://github.com/eclipse/hono/issues/783
here is what I have came up with
This is WIP, as the relevant tests need to be adjusted still. Please feel free to comment and suggest improvements!
> [WIP]Device registry api refactor

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DropwizardBasedCoapAdapterMetrics.java
Add implements CoapAdapterMetrics to DropwizardBasedCoapAdapterMetrics.
> Fix coap metrics.

- service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsService.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsServiceTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyCredentialsService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
Same architecture as the device Registration API.
> split credential API regarding mandatory and optional operations.

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAdapterProperties.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAuthenticationHandler.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapErrorResponse.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapPreSharedKeyHandler.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/PreSharedKeyDeviceIdentity.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/CoapRequestHandler.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/ExtendedDevice.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxBasedCoapAdapter.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxCoapResource.java
> Add DTLS pre-shared-key authentication.

- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoCommander.java
In Jmeter test setup, user defined variables can be provided (Example: ${honoTenant} to be substituted by DEFAULT_TENANT). Samplers receive substituted values. In case of CommanderSampler, these variables were not being substituted. This PR fixes that issue.
> Fixed issue with substitution of User Defined Variables in Jmeter custom sampler for C&C (CommanderSampler)

- jenkins/Hono-Nightly-Pipeline.groovy
- jenkins/Hono-PipelineUtils.groovy
Pipeline script for Hono nightly build
> Pipeline script for Hono nightly build

- jenkins/Hono-Nightly-Pipeline.groovy
Fixed description of nightly build
>  Fixed javadoc - nightly build pipeline

- jenkins/Hono-Website-Pipeline.groovy
Pipeline for Hono-Website build job
> [ #557] Added pipeline for Hono-Website build job

- site/content/concepts/command-and-control.md
@sophokles73. C&C concepts updated! now we have two separate tables for request/response properties
> [#784] Minor update of C&C concepts guide.

- jenkins/Hono-PipelineUtils.groovy
- jenkins/Hono-Release-Pipeline.groovy
Pipeline for Hono-Release build job
> [#557] Added pipeline for Hono Release

- jenkins/Hono-Deploy-Eclipse-Pipeline.groovy
- jenkins/Hono-Deploy-Maven-Central-Pipeline.groovy
- jenkins/Hono-PipelineUtils.groovy
Added pipelines to build and deploy hono artifacts  to the maven central and the eclipse repos.
> [#557] Added pipelines to deploy artifacts to maven central and eclipse repos

- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
Added two hooks to AbstractProtocolAdapterBase:
- onCommandConnectionLost which is invoked when the connection is lost
- onCommandConnectionEstablished which is invoked when the connection is
(re-)established.
These methods can be overridden by subclasses (protocol adapters) to implement
adapter specific behavior for handling the loss and (re-)establishment of the connection
used for receiving commands.
> Add hooks invoked during Command connection re-establishment.

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
> [#895] Don't create error span if no client certs were given

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
> [#909] Check tenant config when processing command response

- service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java
- service-base/src/main/java/org/eclipse/hono/service/tenant/TenantService.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/BaseTenantServiceTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/CompleteBaseTenantServiceTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyTenantService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
> [#914] Add SpanContext param to TenantService methods

- core/src/main/java/org/eclipse/hono/util/ClearTextPassword.java
- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
- core/src/test/java/org/eclipse/hono/util/ClearTextPasswordTest.java
- core/src/test/java/org/eclipse/hono/util/CredentialsObjectTest.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsService.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsServiceTest.java
- site/content/user-guide/device-registry.md
> [#871] Add hashing of plaintext passwords to Credentials API.

- core/src/main/java/org/eclipse/hono/util/EventBusMessage.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteCredentialsService.java
- service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsService.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
- service-base/src/test/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsServiceTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyCredentialsService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
> [#914] Create span for CredentialsService.get

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
This prevents the "upload event" and "upload telemetry" OpenTracing spans to be left unfinished in case the client connected to the HTTP protocol adapter has prematurely closed the connection.
> Ensure OpenTracing span is finished if connection is closed prematurely

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
As part of the `AbstractProtocolAdapterBase.sendDisconnectedTtdEvent` invocation, there are 3 OpenTracing spans being created.
This PR sets a common parent for these spans so that they don't appear as single traces.
> Mqtt Adapter: Create span for sending a disconnected event

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
Similar to #989 - here concerning the AMQP adapter:
As part of the `AbstractProtocolAdapterBase.sendDisconnectedTtdEvent` invocation, there are 3 OpenTracing spans being created.
This PR sets a common parent for these spans so that they don't appear as single traces.
> AMQP Adapter: Create span for sending a detach event

- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
Test method was missing the `@Test` annotation and didn't work.
> Reactivate unused testCallbacksInvokedOnReconnect test

- client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
> [#1020] Fix wrong exceptions being thrown

- client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoClientImplTest.java
- site/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/client/HonoClientImplIT.java
> [#1013] Fix wrong exception being thrown on SASL handshake failure.

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
Amqp and http adapter base classes are refactored to use the method `AbstractProtocolAdapterBase.isAdapterEnabled(tenantObject)`.
> Use common method for checking if tenant is enabled for adapter

- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
> Fix JavaDoc.

- service-base/src/main/java/org/eclipse/hono/service/auth/EventBusAuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/auth/HonoSaslAuthenticatorFactory.java
In preparation for adding a unit test for that class.
> [#1015] Move EventBusAuthenticationService class to top level

- client/src/main/java/org/eclipse/hono/client/AuthenticationServerClient.java
- core/src/main/java/org/eclipse/hono/util/AuthenticationConstants.java
- service-base/src/main/java/org/eclipse/hono/service/auth/AbstractHonoAuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/auth/AuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/auth/BaseAuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/auth/EventBusAuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/auth/HonoSaslAuthenticator.java
- service-base/src/test/java/org/eclipse/hono/service/auth/EventBusAuthenticationServiceTest.java
- services/auth/src/main/java/org/eclipse/hono/service/auth/impl/FileBasedAuthenticationService.java
> [#1015] Use error codes for failed AuthenticationService requests

- client/src/main/java/org/eclipse/hono/client/StatusCodeMapper.java
- service-base/src/main/java/org/eclipse/hono/service/auth/EventBusAuthenticationService.java
Fix regarding status code handling and Javadoc fixes/improvements.
> Fix regarding status code handling

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- deploy/src/main/deploy/example-device-identities.json
- example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
Adopting some inspection results, etc.
> Minor fixes and improvements

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/CommandContext.java
This adds handling for the `Modified` outcome sent back from a device as part of processing a command.
(Became apparent as part of working on #997.)
> AMQP adapter: Handle 'modified' outcome received from device

- deploy/src/main/deploy/openshift/hono-template.yml
- deploy/src/main/deploy/resource-descriptors/prometheus/instance.yml
This fixes up PR #1061, changing the S2I deployment to the model
> Update S2I deployment to follow actuator removal

- eclipse/hono-code-style.xml
Changed properties setting to Java 1.8 language level to 11.
Needs testing in Eclipse.
I did not examine if there are other properties that should be changed or added for Java 11.
> Language level 11 in code style.

- deploy/src/main/deploy/kubernetes/kubernetes_deploy.sh
> [#1024] Fix script based Kubernetes deployment

- service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
- service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
This fixes #1103 and relates to #930:
The "last-via" property is now also written if the device connects directly (not through a gateway). 
It is now made sure that the 'assertRegistration' results are not cached for devices having multiple 'via' entries.
> [#930][#1103] Fixes regarding handling of "last-via" property.

- deploy/pom.xml
> [#1131] Add maven filters for processing helm resources

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- site/content/release-notes.md
The protocol adapters have been changed to use the
TenantClientFactory instead of the HonoClient.
> [#780] Use TenantClientFactory instead of HonoClient.

- service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
1. Instead of framing url on every request now it is changed during @PostConstruct.
2. Method `queryForSumInPrometheus` is refactored to `executeQuery` so that it can be reused by the next PR to check limits based on data volume.
> [#927] Improve Prometheus based limits implementation.

- adapters/lora-vertx/pom.xml
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/KerlinkProvider.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/LoraTestUtil.java
- bom/pom.xml
For the tests to work the `wiremock` dependency is needed.
I also had to change the visibility of two fields, so they are accessible by tests.
> Add Kerlink Provider tests

- site/content/faq.md
Add FAQ page and a couple of questions to start with.
> [#1035] Add FAQ section to documentation.

- deploy/src/main/deploy/helm/templates/dispatch-router/dispatch-router-extlb-svc.yaml
- deploy/src/main/deploy/helm/templates/dispatch-router/dispatch-router-route.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-extlb-svc.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-route.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-sec-route.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yml
- deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-extlb-svc.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-route.yml
- deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-sec-route.yml
- deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-extlb-svc.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-route.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-sec-route.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-extlb-svc.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-route.yaml
- deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-sec-route.yaml
- deploy/src/main/deploy/helm/templates/hono-service-auth/hono-service-auth-route.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-amqps-route.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-deployment.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-extlb-svc.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-http-route.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-https-route.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-svc.yaml
- deploy/src/main/deploy/helm/values.yaml
- site/content/deployment/azure-aks-helm.md
- Added templates "*extlb*.yaml" of services to expose ports on load balancer.
- Added Azure conditions to current services
- Added "imagePrefix" in values and changed deployments to be able to set private container registry.
- Added "azure" in values to be able to apply AKS deployment template.
- Added tutorial  
Signed-off-by: Sergiy Poplavskyi <spopla@microsoft.com>
> Added deployment templates and tutorial for AKS deployment with Helm 

- bom/pom.xml
- deploy/src/main/deploy/docker/swarm_deploy.sh
- deploy/src/main/deploy/docker/swarm_undeploy.sh
> [#1055] Add option to deploy Jaeger in docker swarm

- client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java
> Fix: Javadoc in CachingClientFactory.

- service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
> Fix: Javadoc in CredentialsApiAuthProvider.

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
In the _HTTP adapter_, before uploading command responses from devices, it is being checked that if the device is registered and the adapter is enabled or not. This PR addresses this missing part in the _MQTT adapter_.
> MQTT Adapter: Add checks before uploading command responses.

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
In _HTTP_ and _MQTT_ _adapters_, before uploading command responses from devices, it is being checked that if the device is registered and the adapter is enabled or not. This PR addresses this missing part in the _AMQP adapter_.
> AMQP Adapter: Add checks before uploading command responses.

- site/content/release-notes.md
Updated release notes for PRs #1181 and #1184
> Update release notes for PRs #1181 and #1184

- service-base/src/main/java/org/eclipse/hono/service/http/HonoBasicAuthHandler.java
- service-base/src/test/java/org/eclipse/hono/service/http/HonoBasicAuthHandlerTest.java
Fix for issue #1183 by using a `RoutingContextDecorator`.
> [#1183] Fix internal server error when sending malformed authentication header

- bom/pom.xml
- client/src/test/java/org/eclipse/hono/client/impl/RegistrationClientImplTest.java
- core/pom.xml
- service-base/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/auth/AuthTokenHelperImpl.java
- service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationAssertionHelperImpl.java
* Update to version 0.10.6
* Use -api, -impl, and -jackson modules
* Drop the use of deprecated JJWT APIs
* Fix a misuse of the key material (testing only)
> Upgrade to JJWT 0.10.6

- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
I've encountered some unit test timeouts when running tests locally.
Therefore I've adapted some timeouts slighty.
> Increase/fix some test timeouts.

- adapters/lora-vertx/pom.xml
- adapters/pom.xml
- bom/pom.xml
- cli/pom.xml
- client/pom.xml
- core/pom.xml
- service-base/pom.xml
- services/pom.xml
- tests/pom.xml
As discussed in https://github.com/eclipse/hono/pull/1195
Signed-off-by: Trystram Jean-Baptiste <jbtrystram@redhat.com>
> remove junit4 and use Junit5 vintage engine for all the tests

- deploy/src/main/deploy/helm/templates/hono-service-auth/hono-service-auth-deployment.yaml
- site/content/deployment/azure-aks-helm.md
Signed-off-by: Sergiy Poplavskyi <spopla@microsoft.com>
> Fix container image uri in hono-auth deployment template, fix AKS tutorial

- adapters/amqp-vertx/pom.xml
- adapters/coap-vertx/pom.xml
- adapters/http-vertx/pom.xml
- adapters/kura/pom.xml
- adapters/lora-vertx/pom.xml
- adapters/mqtt-vertx/pom.xml
- pom.xml
- services/auth/pom.xml
- services/device-registry/pom.xml
Fixes #1136: Adding docker push to maven build
> docker push profile added to maven build

- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
For #930:
This resolves a TODO in `DelegatedCommandSenderImpl` concerning handling of non-accepted command messages.
Such scenarios now cause `DelegatedCommandSenderImpl.sendMessageAndWaitForOutcome()` to return a *succeeded* Future, so that the contained `ProtonDelivery` object can be passed on to the originating command sender.
Furthermore, tracing and logging of the received delivery update in the corresponding methods of `AbstractSender` is now done in a common method.
> [#930] Fix command error handling; unify tracing/logging

- service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCompleteCredentialsServiceTest.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
The credentials tests did not wait for the credential registration to be complete before retrieving the data.
> Abstract credentials test race condition

- client/src/main/java/org/eclipse/hono/client/CommandContext.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandler.java
- client/src/test/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandlerTest.java
Related to #930:
Refactor `DelegateViaDownstreamPeerCommandHandler`, replacing `applyDelegatedMessageDeliveryResultToCommandContext` with a new `CommandContext#disposition` method.
Adapt `CommandContext.flow` to skip flowing credits if prefetch is non-zero (otherwise `ProtonReceiverImpl` would throw an `IllegalStateException`).
This is needed because the command context `delivery` *may* now come from the tenant-scoped consumer that has automatic credit handling (in contrast to the device-specific consumer).
> Add CommandContext.disposition(); skip flowing credits if prefetch set

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
- core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
- core/src/test/java/org/eclipse/hono/tracing/TracingHelperTest.java
Also adding a unit test for `TracingHelper`.
> Minor tracing fixes/improvements

- site/static/api/device-registry-v1.yaml
This fixes a wrong/missing reference to the "Deleted" response. This doesn't change the API itself.
> Fix up a reference issue wit the "deleted" response

- site/homepage/config.toml
> [#1109] Disable section with users of Hono on landing page.

- client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
- client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
- core/src/main/java/org/eclipse/hono/util/DeviceConnectionConstants.java
- core/src/main/java/org/eclipse/hono/util/DeviceConnectionResult.java
- service-base/src/main/java/org/eclipse/hono/service/deviceconnection/BaseDeviceConnectionService.java
- service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
- service-base/src/test/java/org/eclipse/hono/service/deviceconnection/BaseDeviceConnectionServiceTest.java
This is for #1245:
Add interfaces and base implementation classes for the new Device Connection API.
> [#1245] Add new Device Connection API classes

- site/homepage/content/release-notes.md
> [#1109] Fix links to API spec in release-notes.

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
PR for #1288. If code looks fine to you I will try to provide a test for this, tested it so far in our deployment with system tests.
> Fix for #1288 flowLatency delays creation of senders unnecessarily long

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
This is to make handling of incoming messages more robust.
Otherwise errors like this don't appear in the logs at all:
````
AMQPjava.lang.NullPointerException: null
AMQP	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
AMQP	at org.eclipse.hono.util.ResourceIdentifier.fromString(ResourceIdentifier.java:154)
AMQP	at org.eclipse.hono.client.impl.CommandConsumerFactoryImpl.lambda$newTenantScopedCommandConsumer$10(CommandConsumerFactoryImpl.java:194)
AMQP	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$15(HonoConnectionImpl.java:699)
AMQP	at io.vertx.proton.impl.ProtonReceiverImpl.onDelivery(ProtonReceiverImpl.java:206)
AMQP	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:163)
AMQP	at …
```
> Handle errors occurring in receiver messageHandler

- client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java
> [#1286] Handle error when creating client

- site/readme.md
See https://github.com/bsinno/hono/tree/PR/docu_release_process/site for the rendering of the checkbox characters.
> Add description of the release process regarding the documentation.

- site/homepage/content/release-notes.md
Release notes has been updated with information about #1262.
> [#1262] Update release notes.

- cli/pom.xml
- cli/src/test/java/org/eclipse/hono/cli/app/ReceiverTest.java
This PR is to migrate unit tests under module `hono-cli`  to junit5.
> Migrate unit tests under module hono-cli to junit5

- client/src/main/java/org/eclipse/hono/client/Command.java
- client/src/test/java/org/eclipse/hono/client/CommandTest.java
- site/documentation/content/api/Command-And-Control-API.md
> [#1339] Improve handling of command correlation ID.

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
This serves as a preparation for #896, for which the `getTenantConfiguration` invocation shall be put first in the `upload*Message()` methods of the protocol adapters.
Objective of this PR:
- reduce indentation levels
- reduce exit points of the methods, combining error handling and metric reporting
> Refactor upload*Message() methods

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProvider.java
- core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
- services/device-registry-legacy/src/main/java/org/eclipse/hono/deviceregistry/DeviceRegistryAmqpServer.java
- tests/src/test/java/org/eclipse/hono/tests/registry/legacy/LegacyDeviceRegistrationHttpIT.java
Typos and minor issues have been addressed in this PR.
> Fix typos and minor issues

- site/homepage/content/_index.md
> Fix page title landing page.

- site/homepage/content/getting-started/index.md
- site/homepage/content/sandbox.md
> Fix broken links on the homepage.

- site/documentation/content/user-guide/mqtt-adapter.md
Minor fixes in message limit documentation for _MQTT_ Adapter.
> Minor fixes in message limit documentation for MQTT Adapter.

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttProtocolAdapterProperties.java
- client/src/main/java/org/eclipse/hono/client/AuthenticationServerClient.java
- client/src/main/java/org/eclipse/hono/client/MessageSender.java
- client/src/test/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandlerTest.java
- core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- service-base/src/main/java/org/eclipse/hono/service/limiting/DefaultConnectionLimitManager.java
> Fix typos.

- site/documentation/content/concepts/resource-limits.md
- site/documentation/content/user-guide/amqp-adapter.md
- site/documentation/content/user-guide/http-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
This PR contains the user guide and release notes updates corresponding to the issue #1284.
> [#1284] Update documentation with message limits for command and control

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/CredentialsManagementHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementHttpEndpoint.java
- tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
As suggested in https://github.com/eclipse/hono/issues/1366
> Add a spec version in the API management URLs

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandHandler.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- core/src/main/java/org/eclipse/hono/util/TenantObject.java
- core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
- service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
- service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
- service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java
- service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
This PR is implementation for #1330.
> [#1330] Report metrics based on minimum message size

- site/homepage/content/getting-started/index.md
> update getting started guide to the new management API

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
- service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
- service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java
- service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
- site/homepage/content/release-notes.md
This PR is implementation for #1381.
> [#1381] COAP adapter reports metrics based on minimum message size

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/Adapter.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/ResourceLimits.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
- service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/documentation/static/latest/api/device-registry-v1.yaml
- tests/src/test/java/org/eclipse/hono/tests/CrudHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java
- tests/src/test/resources/logback-test.xml
* rename *limits* property to *resource-limits* to match Tenant API
* add missing mapping of *minimum-message-size*
> Fix device registry

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
This is a preparation for #1396, making it easier to intercept SASL Authentication credentials once they have been parsed.
> Refactor AmqpAdapterSaslAuthenticatorFactory

- site/homepage/content/getting-started/index.md
> Fixed broken links from Getting started guide to API documentation.

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- core/src/main/java/org/eclipse/hono/util/TenantObject.java
- core/src/main/java/org/eclipse/hono/util/TenantTracingConfig.java
- core/src/main/java/org/eclipse/hono/util/TracingSamplingMode.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- service-base/src/test/java/org/eclipse/hono/service/http/TenantTraceSamplingHandlerTest.java
- service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
> [#1406] Add trace sampling mode properties in the Management API spec

- service-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericCredential.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericSecret.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordSecret.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/PskSecret.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateCredential.java
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateSecret.java
- service-base/src/main/java/org/eclipse/hono/service/management/device/Device.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/ResourceLimits.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/TrustedCertificateAuthority.java
- service-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- tests/src/test/java/org/eclipse/hono/tests/Tenants.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsHttpIT.java
The setter property methods for all the management API
value objects should return that value object to allow
for chain invocations.
> Chain API calls for Management API value objects.

- service-base/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
- service-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- service-base/src/test/java/org/eclipse/hono/service/management/credentials/SecretsTest.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
This should allow encoding datetime values both with and without timezone offset. The value will be decoded without the offset.
> [#1378] Support datetime format with timezone offset

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterConstants.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslResponseContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContextTenantAndAuthIdProvider.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactoryTest.java
- service-base/src/main/java/org/eclipse/hono/service/tenant/BaseExecutionContextTenantAndAuthIdProvider.java
> [#1396] Implement trace sampling mode option in AMQP adapter

- service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredTenantManagementAdapter.java
This should have been included in #1433.
> Also drop the type argument for the Tenant Managment API

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/Command.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandlerTest.java
- site/documentation/content/concepts/command-and-control.md
- site/documentation/content/user-guide/mqtt-adapter.md
> [#1480] MQTT-Adapter: fix wrong topic for commands sent to gateway; add documentation

- site/documentation/content/concepts/resource-limits.md
- site/homepage/content/release-notes.md
This PR updates the user guide and the release notes for the feature in #1337.
> [#1337] Update user guide and release notes.

- site/homepage/content/release-notes.md
> [#1482] Replace "Depreciation" by "Deprecation" in release notes.

- site/homepage/content/release-notes.md
Fix broken links in the release notes.
> Fix broken links in the release notes.

- site/homepage/static/css/custom.css
The font sizes of the homepage and the documentation part differ greatly, as both use different Hugo themes. To better align them, this PR increases the font size (and line spacing) of the homepage.
> Increase font size of homepage to look more like the documentation.

- site/documentation/content/user-guide/amqp-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
- Add information on connection event to the AMQP and MQTT Adapters user guide.
> Improve documentation.

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ActilityProvider.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ActilityProviderTest.java
> Parse actility meta data properly

- site/documentation/content/deployment/helm-based-deployment.md
Updated Azure guide after https://github.com/eclipse/hono/commit/114c5a1c8782bf2da007973dc07cad58ead71934
Signed-off-by: Kai Zimmermann <kai.zimmermann@microsoft.com>
> Adapt Azure guidance to helm changes.

- site/documentation/content/concepts/device-identity.md
Add the Management API to the concept and remove references to already
removed optional operations in Device Registration API.
> [#1553] Update concept documentation of "Device Registration".

- site/documentation/content/concepts/command-and-control.md
- site/documentation/content/concepts/device-identity.md
- site/documentation/content/concepts/device-notifications.md
- site/documentation/content/concepts/tenancy.md
This PR contains various updates and improvements to the concept pages in the documentation. To make the review easier it is split into separate commits.
> Update concept documentation

- site/documentation/content/user-guide/http-adapter.md
Fixes some minor issues, mainly small copy and paste errors.
> Various small fixes and harmonizations in the HTTP User Guide.

- client/src/main/java/org/eclipse/hono/client/Command.java
- client/src/main/java/org/eclipse/hono/client/CommandConsumerFactory.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandHandlerWrapper.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandler.java
- client/src/main/java/org/eclipse/hono/client/impl/DestinationCommandConsumer.java
- client/src/main/java/org/eclipse/hono/client/impl/DeviceSpecificCommandConsumer.java
- client/src/main/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandConsumer.java
- client/src/test/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImplTest.java
This is for #1523.
To come in further PRs:
- usage in HTTP, MQTT and AMQP adapter
- integration tests
> [#1523] Enable gateways to subscribe for commands of a specific device

- site/documentation/content/deployment/create-kubernetes-cluster.md
- site/documentation/content/deployment/helm-based-deployment.md
Added notes regarding incompatibilities with Kubernetes 1.16.
> [#1534] Document limitations when deploying to Kubernetes 1.16.

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
> [#1523] HTTP adapter: Let gateways subscribe for commands of a specific device

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
> [#1523] AMQP adapter: Let gateways subscribe for commands of a specific device

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
> [#1523] MQTT adapter: Let gateways subscribe for commands of a specific device

- site/documentation/content/user-guide/amqp-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
> [#1523] Document cases for gateways subscribing for device commands

- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/CommandEndpointConfiguration.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpCommandEndpointConfiguration.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpCommandEndpointConfiguration.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttCommandEndpointConfiguration.java
This is for #1523.
Note that the tests will fail until #1578, #1577 and #1579 are merged. I will rebase this PR then.
EDIT: branch is rebased now.
> [#1523] Add integration tests for gateways subscribing for device commands

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/auth/AuthoritiesImpl.java
- service-base/src/main/java/org/eclipse/hono/service/VertxBasedHealthCheckServer.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
This PR contains some code optimisations and a minor fix.
> Minor fixes and improvements.

- deploy/src/main/deploy/helm/values.yaml
- site/homepage/config.toml
- site/homepage/content/getting-started/index.md
- site/homepage/content/release-notes.md
- site/homepage/layouts/partials/footer.html
Fixes a couple of links. No need to add this to the "docfix" branch for 1.0 because it does not contain changes in the documentation.
> Fix links.

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAdapterProperties.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapErrorResponse.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
Added OpenTracing instrumentation analogously to HTTP adapter.
> [#1392] Track processing of CoAP requests using OpenTracing.

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraConstants.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/FireflyProvider.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoriotProvider.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/LoriotProviderTest.java
- adapters/lora-vertx/src/test/resources/payload/loriot.uplink.json
- site/homepage/content/release-notes.md
> added loriot lora provider + updated firefly provider to provide bandwidth

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- cli/src/main/java/org/eclipse/hono/cli/adapter/AmqpCliClient.java
- cli/src/main/java/org/eclipse/hono/cli/adapter/CommandAndControlClient.java
- cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
Fixes usage of deprecated API in AMQP and CoAP adapters and the CLI
> Vertx 3.8.3 step3

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/KuraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandler.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
- services/device-connection/pom.xml
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/Application.java
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionService.java
- services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionServiceTest.java
Fix usage of deprecated API in MQTT, Kura and HTTP adapters and Device Connection service
> Vertx 3.8.3 step4

- example/src/main/java/org/eclipse/hono/devices/HonoHttpDevice.java
- example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/AbstractClient.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoCommander.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
- jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
- services/auth/src/main/java/org/eclipse/hono/service/auth/impl/Application.java
- services/auth/src/main/java/org/eclipse/hono/service/auth/impl/FileBasedAuthenticationService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/Application.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedDeviceBackend.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationServiceTest.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
- services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/MapBasedDeviceConnectionServiceTest.java
Addresses usage of deprecated API in JMeter plugin, Auth service and example Device Registry
> Vertx 3.8.3 step5

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
> [#1653] Prevent the commandConsumer from not getting closed

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
> [#1673] Let checkConnected() wait on concurrent connect attempts

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
> [#1687] Close root span if connection got closed prematurely

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/PropertyBag.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/PropertyBagTest.java
- core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
> [#1336] Extract span context from incoming MQTT message

- client/src/main/java/org/eclipse/hono/client/ConnectionLifecycle.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClientFactory.java
- client/src/main/java/org/eclipse/hono/client/impl/ConnectionLifecycleWrapper.java
- client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/DeferredConnectionCheckHandler.java
- client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/DownstreamSenderFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/GatewayMapperImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TenantClientFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/AbstractTenantTimeoutRelatedClientFactoryTest.java
- client/src/test/java/org/eclipse/hono/client/impl/DownstreamSenderFactoryImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
> [#1691] Add isConnected(timeout); use it in client factories

- service-base/src/main/java/org/eclipse/hono/service/management/credentials/EventBusCredentialsManagementAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/management/device/EventBusDeviceManagementAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
> [#1701] Finish spans in management API event bus adapters

- deploy/src/main/deploy/helm/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
- deploy/src/main/deploy/helm/templates/hono-service-device-connection/hono-service-device-connection-secret.yaml
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionService.java
- services/device-connection/src/test/resources/logback-test.xml
Also improved initial connect behavior by means of repeatedly trying to
establish the connection.
> Include connection to grid in readiness check

- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
In this PR, the adapter base class has been extended to check the connection duration limit before accepting any connection request from devices.
> [#1716] Extend protocol adapters to check for connection duration limit.

- site/documentation/content/api/tenant/index.md
- site/documentation/content/concepts/resource-limits.md
- site/documentation/content/user-guide/amqp-adapter.md
- site/documentation/content/user-guide/kura-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
This PR furnishes required documents and release notes for the issue #1716.
> [#1716] Update documentation and release notes.

- site/documentation/content/deployment/resource-limitation.md
The information regarding limiting the overall connection time has been updated.
> [#1716] Update documentation for limiting the overall connection time.

- bom/pom.xml
Upgraded Spring Framework to 5.2.3.RELEASE
Upgraded Spring Boot to 2.2.4.RELEASE
Upgraded Spring Security to 5.2.2.RELEASE
> [#1754] Upgrade to latest Spring releases

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraConstants.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/FireflyProvider.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/FireflyProviderTest.java
> Add mic to FireFly Lora adapter

- service-base/src/main/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementHttpEndpoint.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/documentation/content/user-guide/device-registry.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java
> [#1736] Make the body optional in tenant creation request

- service-base/src/main/java/org/eclipse/hono/service/management/credentials/AbstractCredentialsManagementHttpEndpoint.java
Also doesn't invoke `decodeCredentials()` twice anymore.
> Use better fitting exception type in decodeCredential

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Config.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Config.java
> Fix http/lora/sigfox metrics

- service-base/src/main/java/org/eclipse/hono/service/registration/AbstractRegistrationService.java
- services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyRegistrationService.java
> Handle potential failures in resolveGroupMembers()

- client/src/main/java/org/eclipse/hono/client/Command.java
- client/src/test/java/org/eclipse/hono/client/CommandTest.java
> Add wrong tenant to validation error message.

- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- service-base/src/main/java/org/eclipse/hono/service/registration/AbstractRegistrationAmqpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/registration/EventBusRegistrationAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationAmqpEndpoint.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AutowiredRegistrationAmqpEndpoint.java
> Refactor Registration AMQP endpoint not to use event bus

- site/homepage/content/release-notes.md
The release notes has been updated for the issue #1823.
> [#1823] Update release notes

- site/documentation/content/user-guide/http-adapter.md
> Fix example unauthenticated device.

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/PreSharedKeyDeviceIdentity.java
> Extend open-tracing to include misformed PSK indentities.

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
The unused constants in `FileBasedTenantBackend` have been removed.
> Remove unused constants.

- site/documentation/content/user-guide/coap-adapter.md
> Add coap user-guide.

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionInfoTest.java
> [#1272] Add tracing in HotrodBasedDeviceConnectionInfo

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- client/src/main/java/org/eclipse/hono/client/ProtocolAdapterCommandConsumerFactory.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
> [#1272] Add SpanContext parameter to createCommandConsumer()

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDeviceRegistryUtils.java
In the _MongoDb_ based device registry implementation, a method that checks if the given error is due to the version mismatch or not and then categorizes the given error, is now pulled up to the `MongoDbDeviceRegistryUtils`. Thereby it can be reused by the `tenant` and `credentials` implementations.
> [#1679] Pull up a utility method for reuse in MongoDB based device registry implementation

- client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java
- client/src/test/java/org/eclipse/hono/client/impl/CachingClientFactoryTest.java
> [#1720] Ensure getOrCreateClient result handler doesn't get called twice

- legal/src/main/resources/legal/NOTICE.md
- pom.xml
@sophokles73 There is also one more place in `NOTICE.md` to be updated. Can `Copyright 2016-2019 Bosch Software Innovations GmbH` be simply replaced with `Copyright 2016-2020 Bosch.IO GmbH` in that file?
> Update developers organization details.

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/DeviceDto.java
Added the missing JavaDoc for `DeviceDto.getDeviceId()`.
> Add missing JavaDoc

- cli/src/main/java/org/eclipse/hono/cli/app/Receiver.java
- cli/src/main/java/org/eclipse/hono/cli/app/ReceiverStatistics.java
- cli/src/main/resources/application.yml
No big thing, nor brilliant, but from time to time it helps to see changes in the performance easier.
> Add simple receiver statistic to cli client.

- service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecks.java
- service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecksConfig.java
- service-base/src/test/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecksTest.java
- site/documentation/content/admin-guide/common-config.md
- site/homepage/content/release-notes.md
add timeout for Prometheus queries
> [#1865] Hono resource limits : add timeout for Prometheus queries

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
- client/src/main/java/org/eclipse/hono/client/ProtocolAdapterCommandConsumerFactory.java
- client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DelegatingDeviceConnectionAmqpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
- services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionServiceTest.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java
> [#1858] Use ttd as command consumer lifespan

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ChirpStackProvider.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ChirpStackProviderTest.java
- adapters/lora-vertx/src/test/resources/payload/chirpStack.uplink.json
> added ChirpStack lora provider

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
This is for #1632 (and relates to #1732):
A timeout, while waiting for a delivery update for a command sent to a device, now not only leads to the command AMQP link with the device to be detached but also causes the command consumer to be closed.
> [#1632] Close command consumer on closed device link

- site/documentation/content/api/management/device-registry-v1.yaml
fixes https://github.com/eclipse/hono/issues/1929
> [#1929] remove hashed password deprecation comment

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/Cache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
- client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DelegatingDeviceConnectionAmqpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
- services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionServiceTest.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
- site/documentation/content/api/device-connection/index.md
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java
> [#1858] Add 'updateOnly' param to setCommandHandlingAdapterInstance

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
When a device doesn't acknowledge a command message in time, the protocol adapter will also add a metrics entry now - with ProcessingOutcome `UNDELIVERABLE` (like it is done when there is a disposition update timeout when sending messages downstream).
> Report metrics on timeout sending cmd to device

- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/TableManagementStore.java
* Close SQL connections when using connections
* Translate not found to "false"
> Minor fixes to the JDBC store implementation

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
> [#1953] Check credits before sending command to device

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
> [#1951] Close all command consumers on connection close

- services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbUtils.java
> [#1679] Add tests for MongoDB based tenant services

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
Use the utility method `MongoDbDeviceRegistryUtils.isDuplicateKeyError(...)` in `MongoDbBasedRegistrationService` to check if the error is caused due to duplicate keys.
> Use a utility method to check the duplicate key error

- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java
https://github.com/eclipse/hono/issues/1949
> encode credentials in username

- bom/pom.xml
Also update corresponding netty and proton-j patch versions.
This fixes #1937.
> [#1937] Upgrade to vertx 3.9.1

- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
> Check URI length for coap PUT.

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
time.
Use MemoryBasedConnectionLimitStrategy as default for maximum
connections.
> Adapt configuration for maximum connections and dtls retransmission

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCache.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/AbstractBasicCacheTest.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCacheTest.java
> [#1977] Implement remove(key,value) for a RemoteCache

- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
This fixes the issue that some spans created during Command & Control handling are missing in the overall traces.
Only needed for 1.2.x.
> 1.2.x: Ensure Tracer gets autowired into HonoConnection

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
> [#2032] Fix error in reconnect delay calculation

- site/documentation/content/admin-guide/file-based-device-registry-config.md
- site/documentation/content/concepts/device-provisioning/index.md
- site/documentation/content/concepts/tenancy.md
- site/documentation/content/user-guide/file-based-device-registry.md
- site/documentation/content/user-guide/mongodb-based-device-registry.md
- site/homepage/content/release-notes.md
This is to be merged after PR #2027
> [#1679] Add user guide and release notes

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
> #1856 negative authenticated connection count

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- bom/pom.xml
Requires Californium 2.3.0 release, scheduled for 16.06.2020.
So, on hold, as preview.
> Use async psk for dtls

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Device.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Status.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DeviceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/StatusTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
> [#1960] add status section for devices in API spec

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
Replace also the MessageHelper with the TracingHelper.
> Fix wrong tag "device-id" by replacing it with "auth-id".

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
> [#2030] Handle closed MQTT connection during CONNECT processing

- client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
> [#2074] Prevent IllegalStateException if request is already cancelled

- client/src/main/java/org/eclipse/hono/client/impl/AmqpAdapterClientFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandResponseSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/DownstreamSenderFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/EventSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- core/src/main/java/org/eclipse/hono/config/ClientConfigProperties.java
- core/src/main/java/org/eclipse/hono/util/AddressHelper.java
- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- core/src/test/java/org/eclipse/hono/util/AddressHelperTest.java
- site/documentation/content/admin-guide/hono-client-configuration.md
Implements support for #2070
There's still documentation missing, but I'd withhold that until we have agreed upon the implementation.
> [#2070] Implement downstream address rewrite feature

- core/src/main/java/org/eclipse/hono/config/AbstractConfig.java
- core/src/main/java/org/eclipse/hono/config/AuthenticatingClientConfigProperties.java
- core/src/main/java/org/eclipse/hono/config/ClientConfigProperties.java
- core/src/main/java/org/eclipse/hono/config/KeyLoader.java
- core/src/main/java/org/eclipse/hono/config/ProtocolAdapterProperties.java
- core/src/main/java/org/eclipse/hono/config/ServerConfig.java
- core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
While working on Quarkus PoC I found some improvements we need to in our configuration classes. The idea is to bring that in as a separate PR (as some other improvements not related to Quarkus directly).
The main changes are:
* Defining default values for every property
* Adapting proper property names with getter/setter methods
* Using better suited classes for properties
> Improve configuration classes

- site/documentation/content/api/management/device-registry-v1.yaml
> Add searchDevicesForTenant operation in openAPI

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContextTenantAndAuthIdProvider.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/RequestDeviceAndAuth.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResourceTest.java
> [#1395] Implement trace sampling mode option in CoAP adapter

- core/src/main/java/org/eclipse/hono/annotation/HonoTimestamp.java
- core/src/main/java/org/eclipse/hono/util/ConnectionDuration.java
- core/src/main/java/org/eclipse/hono/util/DataVolume.java
- core/src/main/java/org/eclipse/hono/util/LimitedResource.java
- core/src/main/java/org/eclipse/hono/util/ResourceLimitsPeriod.java
- core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
- service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecks.java
- service-base/src/test/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecksTest.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantApiTests.java
Also introduced base class for common properties.
> Make resource limit related DTOs immutable

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandler.java
- core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
- service-base/src/main/java/org/eclipse/hono/service/http/HonoBasicAuthHandler.java
- service-base/src/main/java/org/eclipse/hono/service/http/X509AuthHandler.java
- service-base/src/test/java/org/eclipse/hono/service/http/X509AuthHandlerTest.java
> [#2144] Fix "authenticate device" span having no parent

- service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecks.java
For the resource limit checks, the `cache_hit` tracing tag is currently only set to `false`, i.e. it is only set in case there was no cache hit.
This PR now sets the `cache_hit` tag consistently in all cases.
> Set 'cache_hit' tag consistently

- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/CrudHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
This should be merged after #2136
> [#2112] Add integration tests for search devices operation

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
The HTTP adapter now tracks the reception of a command in a separate "wait for command" span.
This allows for easier filtering in Jaeger for HTTP requests that have opened a command consumer.
In this span the reception of the command message is now logged explicitly, with details of the command message.
For the HTTP adapter, there are generally 2 separate traces involved in processing a command:
- The trace for the HTTP request from the device
- The trace that gets started when the command message initially gets received in Hono. (This trace is always separate because at the point of starting it, there is no association to the HTTP request from the device yet.)
This PR adds logging events to these two traces that were previously only set in one of them.
(Corresponding changes to the CoAP …
> Improve Command & Control related tracing.

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
- core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
- core/src/test/java/org/eclipse/hono/util/ResourceIdentifierTest.java
- service-base/src/main/java/org/eclipse/hono/service/BaseExecutionContextTenantAndAuthIdProvider.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/SubjectDnCredentials.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordCredentials.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/X509AuthProvider.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordCredentialsTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/X509AuthProviderTest.java
- service-base/src/test/java/org/eclipse/hono/service/http/TenantTraceSamplingHandlerTest.java
- services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java
- site/homepage/content/release-notes.md
> [#2135] Remove single tenant mode

- service-base/src/main/java/org/eclipse/hono/service/auth/device/AuthHandler.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/ChainAuthHandler.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/ExecutionContextAuthHandler.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/ChainAuthHandlerTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/ExecutionContextAuthHandlerTest.java
Further preparation for #2115.
> Apply minor AuthHandler improvements and add tests

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- client/pom.xml
- client/src/main/java/org/eclipse/hono/client/MessageNotProcessedException.java
- client/src/main/java/org/eclipse/hono/client/MessageUndeliverableException.java
- client/src/main/java/org/eclipse/hono/client/NoConsumerException.java
- client/src/main/java/org/eclipse/hono/client/SendMessageTimeoutException.java
- client/src/main/java/org/eclipse/hono/client/ServerErrorException.java
- client/src/main/java/org/eclipse/hono/client/ServiceInvocationException.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- client/src/main/resources/org/eclipse/hono/client/ServiceInvocationException_messages.properties
- client/src/test/java/org/eclipse/hono/client/ServerErrorExceptionTest.java
- client/src/test/java/org/eclipse/hono/client/ServiceInvocationExceptionTest.java
- site/documentation/content/user-guide/coap-adapter.md
- site/documentation/content/user-guide/http-adapter.md
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
Also improve the corresponding documentation for the HTTP adapter and CoAP adapter.
This fixes #2166.
> [#2166] Improve 503 error messages in HTTP adapter

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMapping.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
- site/documentation/content/admin-guide/mqtt-adapter-config.md
> Orig address and content type added to headers which are passed to the mapper

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/util/TenantObject.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/http/AuthHandlerTools.java
> [#2260] Check if adapter enabled for tenant earlier on

- clients/adapter-amqp/pom.xml
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandRouterClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedTenantCommandRouterClient.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedTenantCommandRouterClientTest.java
- clients/adapter-amqp/src/test/resources/logback-test.xml
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandRouterClient.java
- core/src/main/java/org/eclipse/hono/util/CommandRouterConstants.java
- core/src/main/java/org/eclipse/hono/util/Constants.java
> [#2029] Add Command Router client

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslPlainAuthHandler.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandler.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandlerTest.java
- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/DeviceCredentialsAuthProvider.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordCredentials.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/X509AuthProvider.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java
> [#2292] Adopt authInfo properties in credentials clientContext

- jenkins/Hono-Deploy-Eclipse-Pipeline.groovy
- jenkins/Hono-Deploy-Maven-Central-Pipeline.groovy
- jenkins/Hono-Nightly-Pipeline.groovy
> Add JDBC device-registry maven deployment to pipelines

- client/src/main/java/org/eclipse/hono/client/StatusCodeMapper.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandResponseSender.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSender.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/AmqpClientUnitTestHelper.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandResponseSenderTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedTenantCommandRouterClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSenderTest.java
> [#2247] Map client to server error on sender creation

- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
- site/documentation/content/user-guide/amqp-adapter.md
The user guide for the AMQP adapter was unclear about which properties
are required/optional in messages uploaded by clients.
> [#2341] Improve AMQP adapter user guide

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisioner.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceStatus.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpointTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/RegistrationServiceTests.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- tests/src/test/resources/deviceregistry/application.yml
- tests/src/test/resources/qpid/qdrouterd-with-broker.json
This pull request depends on https://github.com/eclipse/hono/pull/2094 being merged first.
So I guess it makes sense to review the second commit only.
Note however that this PR partially shares changes with #2359 and #2360 in order to not depend these being merged before.
> #2053 implicit device registration file registry

- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceDto.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDto.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDtoTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- tests/src/test/resources/deviceregistry-mongodb/application.yml
This pull request depends on #2094 being merged first.
So I guess it makes sense to review the second commit only.
Note however that this PR partially shares changes with #2358 and #2359 in order to not depend on these being merged before.
> #2053 implicit device registration mongodb registry

- client/src/main/java/org/eclipse/hono/client/Command.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommand.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandContext.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandTest.java
- clients/adapter/pom.xml
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Command.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandResponse.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Commands.java
- clients/adapter/src/test/java/org/eclipse/hono/adapter/client/command/CommandsTest.java
- clients/adapter/src/test/resources/logback-test.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/kafka/client/HonoTopic.java
- clients/kafka-common/src/main/java/org/eclipse/hono/kafka/util/RecordUtil.java
- clients/kafka-common/src/test/java/org/eclipse/hono/kafka/util/RecordUtilTest.java
This is for #2273:
Also improve Javadocs of Command related classes and consolidate replyToId handling in Commands class.
> [#2273] Add KafkaBasedCommand class

- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/TableManagementStore.java
- services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/device/base.postgresql.sql.yaml
- services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/device/base.sql.yaml
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- tests/src/test/resources/deviceregistry-jdbc/application.yml
This pull request depends on #2094 being merged first.
So I guess it makes sense to review the second commit only.
Note however that this PR partially shares changes with #2358 and #2360  in order to not depend these being merged before.
> #2053 implicit device registration jdbc registry

- site/documentation/content/api/event-kafka/index.md
- site/documentation/content/api/kafka-api/index.md
- site/documentation/content/api/telemetry-kafka/index.md
> [#2415] Add document "Kafka-based APIs".

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommand.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandTest.java
> [#2273] Add usage of "response-expected" Kafka header

- cli/src/main/java/org/eclipse/hono/cli/app/KafkaReceiver.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/telemetry/kafka/KafkaBasedEventSender.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/telemetry/kafka/KafkaBasedTelemetrySender.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientFactoryImpl.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/AbstractKafkaConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/CachingKafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaProducerConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/CachingKafkaProducerFactoryTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaProducerConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigPropertiesTest.java
Corresponding discussion:
https://github.com/eclipse/hono/pull/2440#discussion_r565363789
> Set a unique client.id property in AbstractKafkaConfigProperties

- site/documentation/content/user-guide/file-based-device-registry.md
- site/documentation/content/user-guide/jdbc-based-device-registry.md
Add a warning to the JDBC and file based registry user guides, indicating which operations defined by the API are not supported by these registries.
> Update user guide regarding unsupported operations by the file and JDBC device registries

- jenkins/Hono-Website-Pipeline-Declarative.groovy
- site/build-site.bat
- site/build-site.sh
- site/documentation/config.toml
- site/documentation/layouts/partials/custom-footer.html
- site/documentation/layouts/partials/custom-header.html
- site/documentation/layouts/partials/header.html
- site/documentation/layouts/partials/menu.html
- site/homepage/layouts/partials/head.html
- site/pom.xml
The Learn theme has been upgraded to latest minor version 2.5.0.
Also replaced deprecated Hugo function/property references.
> Upgrade Hugo theme for documentation

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
This fixes #2465.
(Issue was that `tenantTracker.result()` was used without assuring that `tenantTracker` is already succeeded.)
Code is also more in line now with how command responses are handled in the other adapters.
> [#2465] Fix potential NPE when handling command response

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/CredentialsServiceImpl.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/AbstractJdbcRegistryTest.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/JdbcBasedRegistrationServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
> Support caching of credentials in JDBC registry

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionsManager.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/Subscription.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
For #2064:
This is in preparation of adding support for different kinds of MQTT subscriptions, notably a subscription on an error topic.
> [#2064] Extract AbstractSubscription out of CommandSubscription

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
Also move "getErrorCondition(Throwable)" out of adapter base class.
That method is only needed for the AMQP adapter.
> Use "client facing error message" in AMQP adapter

- site/documentation/content/admin-guide/common-config.md
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
This adds documentation for #2402.
> [#2402] Document how to select messaging based on the tenant

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/PropertyBag.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/PropertyBagTest.java
> [#2495] Fix PropertyBag parsing errors

- cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
- cli/src/main/java/org/eclipse/hono/cli/app/Receiver.java
- cli/src/test/java/org/eclipse/hono/cli/app/ReceiverTest.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/AmqpApplicationClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClient.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClientFactoryTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/KafkaApplicationClient.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
- clients/application/src/main/java/org/eclipse/hono/application/client/ApplicationClient.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoClientImplIT.java
More Info https://github.com/eclipse/hono/pull/2498#issuecomment-786652254
> [#2478] Rename ApplicationClientFactory to ApplicationClient

- CODEOWNERS
This PR contains the updated code owners list as agreed in the Hono community call on 25.02.2021.
> Update code ownership as agreed in the Hono community call 

- adapter-base/src/main/java/org/eclipse/hono/adapter/resourcelimits/PrometheusBasedResourceLimitChecks.java
Ensure that concurrent resource limit checks are finished on their original vert.x context.
> Ensure no vertx context switch done on resource limit check

- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/TheThingsStackProvider.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/TheThingsStackProviderTest.java
- adapters/lora-vertx/src/test/resources/payload/theThingsStack.uplink.json
https://github.com/eclipse/hono/issues/2515
> hono-2515: Add LoRa provider for the things stack

- site/homepage/content/release-notes.md
> add TheThingsStack support to release notes

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/lora-vertx-base/pom.xml
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraCommand.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/SubscriptionKey.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/ChirpStackProvider.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/FireflyProvider.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/JsonBasedLoraProvider.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProvider.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/LoriotProvider.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/providers/ChirpStackProviderTest.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/providers/LoraProviderTestBase.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/providers/LoriotProviderTest.java
- core/src/main/java/org/eclipse/hono/util/CommandEndpoint.java
- core/src/main/java/org/eclipse/hono/util/RegistrationAssertion.java
- core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Device.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/homepage/content/release-notes.md
https://github.com/eclipse/hono/issues/2482
> hono-2482: Command and control for lora adapter

- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- services/device-registry-base/pom.xml
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisioner.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisionerTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
> #2475 Migrating device registries to new messaging client

- tests/src/test/java/org/eclipse/hono/tests/AssumeMessagingSystem.java
- tests/src/test/java/org/eclipse/hono/tests/AssumeMessagingSystemCondition.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryJmsQoS1IT.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
> #2469 Using MessagingType in AssumeMessagingSystem

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
This fixes #2521:
The connect() method has been refactored so that a connection attempt along with potential retries is handled in a separate inner class named "ConnectionAttempt". The old implementation allowed for separate connect() invocations to potentially lead to separate, concurrent retry loops (if invoked while the other attempt was in the reconnectDelay timer). This is not possible any more. With the encapsulation in the ConnectionAttempt class, an attempt can now be cancelled, aborting a potentially ongoing reconnectDelay timer. This is used in the disconnect() and shutdown() methods.
> [#2521] Let disconnect() abort an ongoing connection attempt

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MessageMapping.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMapping.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
- core/src/main/java/org/eclipse/hono/util/RegistrationAssertion.java
- core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Device.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpointTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DeviceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/homepage/content/release-notes.md
> add command mapper to mqtt adapter

- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
- tests/src/test/resources/commandrouter/application.yml
This PR migrates all ITs testing One Way Commands to the Kafka profile.
> #2469 Adapt integration tests for one way commands to Kafka

- deploy/src/main/deploy/example-permissions.json
- deploy/src/main/sandbox/sandbox-permissions.json
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/CommandConsumerFactory.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/CommandTargetMapper.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandTargetMapperImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- site/documentation/content/admin-guide/command-router-config.md
- site/homepage/content/release-notes.md
- tests/src/test/resources/auth/permissions.json
- tests/src/test/resources/commandrouter/application.yml
> [#2542] Use tenant trace sampling mode in Command Router

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumer.java
Make sure the KafkaConsumer is created in the vert.x context of the start() method (relates to #2562) and disable auto-commit.
> Improve KafkaBasedInternalCommandConsumer

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClient.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
> [#2402] Use messaging network set for tenant in Command Router

- site/documentation/content/api/management/device-registry-v1.yaml
> [#2194] Clarify documentation regarding password hashes.

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumerTest.java
> [#2590] Use broker default replication factor for internal topic

- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
The integration tests for AMQP adapter still use methods from `ApplicationClientFactory`
to send commands. This has been replaced now with methods from `ApplicationClient`.
> [#2478] Use ApplicationClient to send commands in integration tests

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
Minor refactoring and logging improvements.
> Apply minor improvements to KafkaBasedCommandSender

- core/src/main/java/org/eclipse/hono/util/CommandEndpoint.java
> isValidUri should not be serialized in device registry

- cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
- cli/src/main/java/org/eclipse/hono/cli/app/AbstractApplicationClient.java
- cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
- cli/src/main/java/org/eclipse/hono/cli/app/Receiver.java
- cli/src/main/resources/application.yml
> [#2599] Replace legacy northbound client with new interface in CLI.

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
Currently the correlation id is stored in a collection after successfully sending a
command. There is a chance that the command response is received by the Kafka
consumer before the correlation id is even stored. This has been fixed now by storing
the correlation id before calling the send command method. If sending a command
fails, then the corresponding correlation id is removed from the collection.
> Fix sending commands and receiving responses over Kafka

- site/documentation/content/deployment/helm-based-deployment.md
Note that this requires https://github.com/eclipse/packages/pull/215, otherwise there will be image-pull errors if using SNAPSHOT images.
> Improve docs for deploying in minikube

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceAndGatewayAutoProvisioner.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DeviceAndGatewayAutoProvisionerTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceBackend.java
It includes several refactoring that are required for sending auto-provisioned
event notification during auto-provisioning of devices/gateways.
> [#2665] Prepare for sending event notification during auto-provisioning of devices/gateways

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- adapters/amqp-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/amqp/quarkus/Application.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/spring/Config.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/quarkus/Application.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/spring/Config.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/Application.java
- adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/spring/Config.java
- adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Config.java
- adapters/lora-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/lora/quarkus/Application.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Config.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/spring/Config.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Config.java
- service-base-quarkus/pom.xml
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractServiceApplication.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/metric/MeterRegistryProducer.java
- service-base/src/main/java/org/eclipse/hono/service/ComponentNameProvider.java
- service-base/src/main/java/org/eclipse/hono/service/metric/PrometheusScrapingResource.java
- services/auth-quarkus/src/main/java/org/eclipse/hono/authentication/quarkus/Application.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
> Enable collection of JVM metrics in Quarkus based components

- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
> [#2690] Fix NPE in case of empty command payload

- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClient.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClientTest.java
A "get tenant" service invocation that failed immediately (with no asynchronous decoupling in between) caused that failure to be put in the `ProtonBasedTenantClient#pendingRequests` map and be used for later "get tenant" invocations.
This is the main fix for #2705.
The added test that reproduces the bug with the old `ProtonBasedTenantClient` code is `testGetTenantSucceedsWhenCreditRestored`.
> [#2705] Fix pendingRequests handling in tenant client

- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
Fix for #2704:
If tenant is already removed or disabled, corresponding command consumers will be closed.
> [#2704] Check LoRa adapter command consumers on tenant timeout

- bom/pom.xml
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
> [#2706] Document required versions of Kafka

- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
The registration of a command consumer is skipped now during handling of a message from a LoRa network gateway if there is no command endpoint defined in the gateway device registration data. 
Handling of command messages for such a gateway would fail anyway because of the missing command endpoint.
It is also made sure that the LoRa adapter "process message" span gets finished before the root span.
This relates to #2704, not creating a consumer in the first place if the gateway device isn't configured accordingly.
> LoRa adapter: Check for command endpoint before creating consumer

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
This adds a `FOLLOWS_FROM` span reference from the HTTP/CoAP ttd request trace to the command-handling trace started in the Command Router.
Also decouples the closing of the command consumer from the request handling trace spans by means of an extra `FOLLOWS_FROM` span, the motivation being that the request handling trace span ("POST"/"PUT") gets finished before the span for closing the command consumer anyway.
Before:
With this PR:
> Improve HTTP/CoAP C&C tracing

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceBackend.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceDto.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/DeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceBackend.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceManagementService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDeviceRegistryUtils.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java
- services/device-registry-mongodb/src/test/resources/logback-test.xml
This is the second step of refactoring the MongoDB based registry implementation (#2110).
A final PR will introduce a DAO for accessing credentials data.
> [#2110] Add Device DAO for accessing device collection

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
> [#2765] Fix command consumer not receiving initial commands

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumerTest.java
> [#2767] Add rate-limit to AsyncHandlingAutoCommitKafkaConsumer

- site/documentation/static/css/hugo-theme.css
> [#2725] Add fix for TOC indentation in documentation.

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumerTest.java
- test-utils/kafka-test-utils/src/main/java/org/eclipse/hono/kafka/test/KafkaMockConsumer.java
> [#2780] Wait for record future completion before commit

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
This is for #2830:
Waiting for the "partitionsFor()" result isn't needed, in the end it only counts whether the topic got added to the list of subscribed topics. By skipping this result check, the whole topic subscription check takes one consumer poll() iteration (with 1s default poll timeout) less than before.
> [#2830] Improve ensureTopicIsAmongSubscribedTopicPatternTopics()

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
This is for #2803:
Previously, the ensurePositionsHaveBeenSetIfNeeded() method was invoked from the vert.x thread, meaning that another partition assignment could have already taken place. This then could lead to the "You can only check the position for partitions assigned to this consumer." error. Now, the method gets invoked on the Kafka consumer polling thread.
> [#2803] Fetch offset positions directly on partition assignment

- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/AmqpApplicationClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClient.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClientTest.java
> [#2834] Invoke consumer close handler on remote disconnect

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumerTest.java
- test-utils/kafka-test-utils/src/main/java/org/eclipse/hono/kafka/test/KafkaMockConsumer.java
This is for #2843.
When a partition gets assigned for the first time to the `AsyncHandlingAutoCommitKafkaConsumer`, the initial partition
offset gets committed on the first offset commit.
This makes sure that a record published during a following rebalance doesn't get skipped.
> [#2843] Mark initially assigned partitions for offset commit

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImplTest.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/CachingKafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaProducerFactory.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/CachingKafkaProducerFactoryTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedEventSenderTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedTelemetrySenderTest.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
> [#2836] Refactor KafkaProducerFactory

- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
> [#2857] Limit message TTL to tenant's max-ttl with Kafka.

- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
Giving tracing spans created for closing client connections on server shutdown a dedicated operation name.
That makes them stand out from spans created when clients themselves close the connection.
> Improve tracing/logging on AMQP/MQTT server shutdown

- legal/pom.xml
So that it can be used in the hono-extras project.
See https://github.com/eclipse/hono-extras/issues/12.
> Publish hono-legal jar again

- bom/pom.xml
Updated Spring Boot to 2.5.5,
updated Spring to 5.3.10
updated Spring Security to 5.5.2
Fixes #2876
> Upgrade to latest Spring projects

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumerTest.java
This fixes #2921:
With the new rate-limiting approach, the poll invocations won't get paused for too long, meaning the consumer won't leave the active consumer group in case of prolonged high load.
> [#2921] Improve command processing rate-limiting

- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/KerlinkProvider.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderCustomContentType.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderCustomContentTypeTest.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
- adapters/lora-vertx-base/src/test/resources/payload/kerlink-custom-content-type.uplink.json
- adapters/lora-vertx-base/src/test/resources/payload/kerlink.uplink.json
> Kerlink lora provider newer version added

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
Skips unnecessary periodic commit attempts.
> Skip periodic commit if rebalance in progress

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- core/src/main/java/org/eclipse/hono/util/Futures.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
> [#2919] Set overall timeout for Command Router command processing

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
Retry of periodic commit should be done right after rebalance in that case.
Error handling was wrong here - the `RebalanceInProgressException` is actually returned in the `OffsetCommitCallback` parameter of `commitAsync`, not thrown directly in `commitAsync`.
This has become clear via logs like:
```
periodic commit failed: org.apache.kafka.common.errors.RebalanceInProgressException: Offset commit cannot be completed since the consumer is undergoing a rebalance for auto partition assignment. You can try completing the rebalance by calling poll() and then retry the operation. [client-id: cmd-router-consumer-4f4fae11-98ad-44e3-9fde-d9ef95130187]
```
This might actually resolve some integration test errors happening because a periodic offset commit was done too late - when the corresponding …
> Fix handling of periodic commit failure while rebalance in progress

- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImplTest.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/AbstractKafkaConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/CommonKafkaClientConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/CachingKafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/KafkaProducerConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/KafkaProducerFactory.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSenderTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/producer/CachingKafkaProducerFactoryTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/producer/KafkaProducerConfigPropertiesTest.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationSender.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationReceiverTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationSenderTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaConsumerConfigPropertiesTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaProducerConfigPropertiesTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedEventSenderTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedTelemetrySenderTest.java
- site/homepage/content/release-notes.md
This is the last PR for #2953.
> [#2953] Use retries when trying to create Kafka producer

- bom/pom.xml
- clients/notification-amqp/pom.xml
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/NotificationAddressHelper.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationSender.java
- clients/notification-amqp/src/test/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiverTest.java
- clients/notification-amqp/src/test/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationSenderTest.java
- clients/notification-amqp/src/test/resources/logback-test.xml
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/NotificationTopicHelper.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationConstants.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationReceiver.java
- clients/pom.xml
- services/device-registry-base/pom.xml
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistryNotificationsIT.java
- tests/src/test/resources/auth/permissions.json
- tests/src/test/resources/qpid/qdrouterd-with-broker.json
> [#2983] Add AMQP-based notification clients

- bom/pom.xml
> Update to use Californium 2.7.0.

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
> [#3016] Remove consumer metrics for deleted topics

- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/FireflyProvider.java
- site/homepage/content/release-notes.md
> [#3031] allow unconfirmed data from firefly as uplink

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ErrorSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
> [#3039] set topic in mqttContext when message is mapped

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
> [#3057] Add workaround for vertx-auth-mongo hash creation issue

- core/pom.xml
> [#3069] Fix non-existing maven property in "embed-dependencies"

- adapters/mqtt-vertx-base/pom.xml
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttTestBase.java
> [#293] Close MQTT connection when tenant/device is deleted/disabled

- adapters/amqp-vertx-base/pom.xml
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx-base/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
> [#3079] Close AMQP connection when tenant/device is deleted/disabled

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
For example concerning a case where a MQTT message exceeding the max message size was received.
> Improve tracing/logging on MQTT protocol errors

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/HttpContext.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/MapBasedTelemetryExecutionContext.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/ProtocolAdapter.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/TelemetryExecutionContext.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/HttpContextTest.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/ResourceTestBase.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandler.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandlerTest.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- site/homepage/content/release-notes.md
> Move TelemetryExecutionContext to adapter-base module

- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/providers/LiveObjectsProvider.java
- adapters/lora-vertx-base/src/test/java/org/eclipse/hono/adapter/lora/providers/LiveObjectsProviderTest.java
- adapters/lora-vertx-base/src/test/resources/payload/liveObjects.uplink.json
- site/homepage/content/release-notes.md
> [#3154] Add support for Live Objects to Lora adapter

- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/CommandResponder.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/EventSender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/TelemetrySender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/TraceableCommandResponder.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/TraceableEventSender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/TraceableTelemetrySender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/AbstractAmqpAdapterClientSender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/AmqpAdapterClientCommandResponseSender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/AmqpAdapterClientEventSenderImpl.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/AmqpAdapterClientTelemetrySenderImpl.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/AmqpAdapterClientSenderTestBase.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/CommandResponderTest.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/EventSenderTest.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/TelemetrySenderTest.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/devices/AmqpExampleDevice.java
- examples/protocol-gateway-example/src/main/java/org/eclipse/hono/example/protocolgateway/controller/ProtocolGateway.java
- site/homepage/content/release-notes.md
> [#3163] Do not let AMQP device client send arbitrary properties

- services/device-registry-jdbc-quarkus/src/main/java/org/eclipse/hono/deviceregistry/jdbc/quarkus/AmqpServerFactory.java
- services/device-registry-jdbc-quarkus/src/main/java/org/eclipse/hono/deviceregistry/jdbc/quarkus/KafkaMetricsSupportProducer.java
- services/device-registry-jdbc-quarkus/src/main/java/org/eclipse/hono/deviceregistry/jdbc/quarkus/NotificationSenderProducer.java
- services/device-registry-mongodb-quarkus/src/main/java/org/eclipse/hono/deviceregistry/mongodb/quarkus/AmqpServerFactory.java
- services/device-registry-mongodb-quarkus/src/main/java/org/eclipse/hono/deviceregistry/mongodb/quarkus/KafkaMetricsSupportProducer.java
- services/device-registry-mongodb-quarkus/src/main/java/org/eclipse/hono/deviceregistry/mongodb/quarkus/NotificationSenderProducer.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
- site/homepage/content/release-notes.md
> [#3158] Add support for Kafka client metrics in device registry

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceRegistryBasedCertificateVerifier.java
The change is done as preparation for migration to Californium 3.x.
> Simplified server names validation at COAP adapter

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAdapterProperties.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapEndpointFactory.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceInfoSupplier.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceRegistryBasedCertificateVerifier.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceRegistryBasedPskStore.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/VertxCoapResource.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/impl/ConfigBasedCoapEndpointFactory.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/CoapProtocolAdapterMockSupport.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/ResourceTestBase.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResourceTest.java
- bom/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
Also-by: Achim Kraus <achim.kraus@bosch.io>
> Migrate to Californium 3.2.0.

- bom/pom.xml
> [#3196] Upgrade Californium to 3.4.0

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/CoapContextTest.java
Legacy support for tenants with devices where old versions fails to
process piggybacked responses. Enable piggybacked responses, if device
indicates a newer version succeeding to process piggybacked responses
using the URI-query-parameter "piggy".
> Add device specific piggybacked responses.

- adapters/base-quarkus/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/LICENSE.logstash-gelf.txt
- legal/src/main/resources/legal/NOTICE.md
- legal/src/main/resources/legal/hono-maven.deps
- services/base-quarkus/pom.xml
- site/documentation/content/admin-guide/monitoring-tracing-config.md
> [#3161] Add quarkus-logging-gelf dependency

- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/InternalErrorTracer.java
> [#3185] Add interceptor for internal CoAP errors

- demo-certs/create_certs.sh
Exit the script, if openssl or keytool reports an error.
Use JAVA_HOME to locate the keytool only if provided.
Fixes issue #3246
> Exit create certs on error.

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- site/documentation/content/user-guide/http-adapter.md
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
Fix for #3279.
This relates to https://github.com/eclipse/hono/pull/3230#discussion_r864471337 and https://github.com/eclipse/hono/pull/3230#discussion_r864477878.
> [#3279] Fix handling of PUT requests with hono-ttd query param

- site/build-site.bat
- site/build-site.sh
- site/documentation/config.toml
- site/documentation/layouts/partials/custom-header.html
- site/documentation/static/css/theme-hono.css
This fixes the issue that when searching in documentation pages via CTRL+F, the browser doesn't scroll to the findings.
> Update to latest Hugo documentation theme version

- adapter-base/src/main/java/org/eclipse/hono/adapter/resourcelimits/DataVolumeAsyncCacheLoader.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/resourcelimits/DataVolumeAsyncCacheLoaderTest.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericSenderLink.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/RequestResponseClient.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/SendMessageSampler.java
- service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
- service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
- site/documentation/content/api/Metrics.md
- site/homepage/content/release-notes.md
> [#3272] Rename metrics

- adapter-base/src/main/java/org/eclipse/hono/adapter/HttpContext.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/HttpContextTest.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
> [#3295] Fix HTTP adapter request URI parts not getting decoded

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServerSpanHelper.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
> [#3297] Set fixed span name for invalid HTTP requests

- adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
> [#3305] Apply authHandler only on LoRa provider HTTP routes

- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractSubscription.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/ErrorSubscription.java
- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- site/homepage/content/release-notes.md
.. when both are requested for same device
Signed-off-by: Marinov Avgustin <Avgustin.Marinov@bosch.io>
> [#3314] Fix skipping command or error subscription in MQTT adapter

- service-base/src/main/java/org/eclipse/hono/service/tracing/DropBySpanNamePrefixSampler.java
- service-base/src/main/java/org/eclipse/hono/service/tracing/RateLimitingSampler.java
- service-base/src/main/java/org/eclipse/hono/service/tracing/SamplerProducer.java
- site/documentation/content/admin-guide/monitoring-tracing-config.md
> [#3318] Add rate-limiting OpenTelemetry tracing sampler

- adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClientProvider.java
- clients/client-common/src/test/java/org/eclipse/hono/client/util/MessagingClientProviderTest.java
- site/documentation/content/admin-guide/amqp-network-config.md
- site/documentation/content/admin-guide/common-config.md
- site/documentation/content/admin-guide/file-based-device-registry-config.md
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
- site/documentation/content/admin-guide/jdbc-device-registry-config.md
- site/documentation/content/admin-guide/mongodb-device-registry-config.md
- site/homepage/content/release-notes.md
> [#3306] Change default messaging network to Kafka

- service-base/src/main/java/org/eclipse/hono/service/AbstractServiceApplication.java
Preventing the DEBUG log output of a stacktrace on normal shutdown, which might be taken as if there was something wrong at first glance.
> Log stacktrace of vert.x shutdown only if closed unexpectedly

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
This fixes #3340.
I've chosen to let this option be set via system property/environment variable only. It is an option for a special scenario only and doesn't fit well into existing command router/protocol adapter property structures.
> [#3340] Add option to disable delivery failure command responses

- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/CommandResponseResource.java
- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/EventResource.java
- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/TelemetryResource.java
- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
- adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
- adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResourceTest.java
> [#3301] Use request URI pattern as Span name

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
Refactoring of HTTP adapter
- single place command consumer close
- single method & class handling waiting for command
Fix for non terminating duUploadMessage pipeline
Signed-off-by: Marinov Avgustin <Avgustin.Marinov@bosch.io
> [#3366] Fix of non-closing future in HTTP adapter

- core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
- service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/DaoProducer.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDaoTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDaoTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDaoTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java
> [#2809] Prevent unhandled MongoDB client exceptions

- service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
Request body isn't being logged anymore and inclusion of stacktrace of a client error exception is omitted (usually not needed, e.g. `AbstractHttpEndpoint` already logs it).
> Adapt HTTP error logging

- jenkins/Hono-Deploy-Maven-Central-Pipeline-Declarative.groovy
> [#3369] Deploy all client modules to Maven Central

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
> [#2355] Close tenant-scoped links when not needed anymore

- .gitmodules
- jenkins/Hono-Website-Pipeline-Declarative.groovy
- site/build-site.bat
- site/build-site.sh
- site/documentation/.gitignore
- site/homepage/.gitignore
Use gitmodules for pulling in the Hugo themes used for building the web site instead of explicitly cloning the repositories.
> Use gitmodules for website themes

- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractServiceClient.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommand.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractCommandProcessingQueue.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractMappingAndDelegatingCommandHandler.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandProcessingQueue.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandProcessingQueue.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedMappingAndDelegatingCommandHandler.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueueTest.java
> [#2923] Add ProtonBasedCommandProcessingQueue

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
The Hono client CommandConsumer class doesn't fit very well in `ProtonBasedCommandConsumerFactoryImpl` (no consumer for a specific device created there).
> Use own CommandConsumer inner class

- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
- site/documentation/content/user-guide/mqtt-adapter.md
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
> [#3412] Clarify MQTT topic content used for gateway command

- jenkins/Hono-Website-Pipeline-Declarative.groovy
The website build jon has been changed to push the HTML pages generated by Hugo the Hono's website repo at
https://github.com/eclipse-hono/hono-website
Fixes #3405
> [#3405] Push generated HTML pages to GitHub repo

- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
Adopting the fix made in #3278 to 2.1.x.
> Fix KafkaApplicationClient startup in example application

- .github/workflows/ci.yml
- bom/pom.xml
> [#3411] Mongodb compatibility tests

- adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/LoraCommandSubscriptions.java
- adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/app/Application.java
- adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/app/LoraCommandSubscriptionsFactory.java
- adapters/lora/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
> [#2726] Shared command consumer map for Lora adapter verticles

- adapters/lora/src/main/java/org/eclipse/hono/adapter/lora/providers/ChirpStackV4Provider.java
- adapters/lora/src/test/java/org/eclipse/hono/adapter/lora/providers/ChirpStackV4ProviderTest.java
- adapters/lora/src/test/resources/payload/chirpStackV4.uplink.json
- site/homepage/content/release-notes.md
> [#3444] downstream support for chirpstack V4

- adapters/parent/pom.xml
- bom/pom.xml
- services/parent/pom.xml
- site/documentation/content/admin-guide/monitoring-tracing-config.md
> Add support for using JSON format when logging to console

- adapter-base/src/main/java/org/eclipse/hono/adapter/auth/device/jwt/JwtAuthProvider.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/auth/device/jwt/JwtAuthProviderTest.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/JwtAuthHandler.java
- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- service-base/src/main/java/org/eclipse/hono/service/auth/ExternalJwtAuthTokenValidator.java
Implemented a task to automatically disconnect mqtt devices, connected via JWT authentication, once their provided JWT expires.
> [#3441] Automatically disconnect mqtt devices, connected via JWT authentication, once JWT expires

- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/JwtAuthHandler.java
- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/JwtAuthHandlerTest.java
- service-base/src/main/java/org/eclipse/hono/service/auth/ExternalJwtAuthTokenValidator.java
- site/documentation/content/concepts/device-identity.md
This is for #3441
As a follow-up on
https://github.com/eclipse-hono/hono/pull/3451#discussion_r1064156006 the JwtAuthHandler has been changed to read the tenant Id from a JWT's "tid" claim instead of the "iss" claim. This allows for the "iss" claim to be used for determining where the public key to use for validating the JWS signature should be looked up from, e.g. the tenant configuration or device credentials.
> Read tenant from JWT's "tid" claim

- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
* await for sending of message is made to timeout on some period
* if there is a send error when not expected - test fails
Signed-off-by: Marinov Avgustin <Avgustin.Marinov@bosch.io>
> [#3321] MQTT test improvements

- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
> Simplify MQTT ITs that expect error messages

- bom/pom.xml
- pom.xml
Updated some dependencies and Maven plugins to latest versions
> Update dependencies and Maven plugins

- clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumer.java
- clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumerTest.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubBasedAdminClientManager.java
Fix [#3497]: increased performance by not listing topics & subscriptions, rather try to create them and catch the exception.
- remove listing of topics & subscriptions
- try to create topics & subscriptions and catch the exception if they already exist
> [#3497] Increase performance of Pub/Sub topic and subscription creation

- legal/src/main/resources/legal/NOTICE.md
The legal entity type of Controlant is hf. not ehf.
> Fix the legal entity type of Controlant in the copyright holders

- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
Updated to Cf 3.8.0
Fixes #3505
> Bump Eclipse Californium version

- bom/pom.xml
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/readme.md
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
Also updated Kafka container image used for ITs to version 3.5.0.
Fixes #3558
> Use Kafka in Raft mode for running integration tests

- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- site/homepage/content/release-notes.md
> Upgrade to Californium 3.10.0

- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- site/homepage/content/release-notes.md
> Update CoAP adapter to use Eclipse Californium 3.11.0

- site/homepage/content/community/blog-load-tests-coap.md
- site/homepage/content/community/presentations.md
Bosch Digital has executed load tests of Hono few months ago.
The page in the PR is presenting the outcomes.
As discussed in one of the community meeting, the information provided could help in setting up Hono and understanding its limits.
> Blog post for CoAP load tests
