- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
The issue while converting the sorting field of type _JsonPointer_ to _MongoDB_ specific field in `MongoDbDocumentBuilder.withDeviceSortOptions(...)` is fixed with this PR. Also the corresponding test is updated.
> Fix sorting of devices during search devices operation in MongoDB device registry

- site/documentation/content/api/management/device-registry-v1.yaml
This corrects a note, making it more explicit that a tenant must exist
when creating a device. It also lists the error code to report in such
cases.
> Update spec. Add missing information.

- core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
- core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
- site/homepage/content/release-notes.md
This is the first step for #2135.
> [#2135] Mark single-tenant mode methods as deprecated

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandler.java
- client/src/main/java/org/eclipse/hono/client/CommandContext.java
- core/src/main/java/org/eclipse/hono/util/ExecutionContext.java
- core/src/main/java/org/eclipse/hono/util/GenericExecutionContext.java
- core/src/main/java/org/eclipse/hono/util/TelemetryExecutionContext.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/AuthHandler.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/ExecutionContextAuthHandler.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoClientBasedAuthProvider.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProviderTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java
The Hono `AuthHandler` (in package `org.eclipse.hono.service.auth.device`) now uses an AuthProvider that also supports working with an `ExecutionContext`. This makes `TraceContext` serialization/deserialization unnecessary in scenarios where a
`HonoClientBasedAuthProvider` is used with such a Hono `AuthHandler`.
This is a preparation for #2115.
As a next step, `HonoClientBasedAuthProvider<T>` should better be renamed to the more generic `DeviceCredentialsAuthProvider<T>` (`ExecutionContextDeviceCredentialsAuthProvider<T>` would be more specific but a bit long).
> Pass on execution context from Hono AuthHandler to AuthProvider

- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
- services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionServiceTest.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
The recent change towards returning 404 for the "Remove command-handling adapter instance" operation (see #2066) didn't
match the most recent API definition as introduced in #1940. Therefore reverting that change here and again returning 412 instead of 404.
See the corresponding comment in #2066.
> Let removeCommandHandlingAdapterInstance return 412 again

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
With this PR, while registering devices, the existence of the tenant is now being verified using `TenantInformationService`.
> [#2131] Check for tenant existence in device registration operations in MongoDB device registry

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
This fixes #2155.
The first commit fixes the command delivery potentially not getting updated in the CoAP adapter.
The second commit improves the overall Command & Control related tracing in the CoAP adapter by adopting the corresponding changes done for the HTTP adapter (#2153).
> Fix command delivery not getting released, improve tracing

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslExternalAuthHandler.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslPlainAuthHandler.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslResponseContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/util/AuthenticationConstants.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/X509Authentication.java
The AMQP adapter authentication handling has been refactored to use `ExecutionContextAuthHandler` instances.
This allows removing duplicate code concerning the parsing of credentials, now done using the existing `CredentialsApiAuthProvider#getCredentials` implementations.
This is a preparation for #2115.
> Use AuthHandlers for AMQP adapter authentication

- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- services/device-registry-base/pom.xml
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateCredential.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
The Device Registry Management API allows the underscore character to be
used in the auth-id property of credentials. The corresponding pattern
used for validating the authId property in the CommonCredential class
has been updated accordingly.
> [#2175] Accept underscore in auth-id property

- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- service-base/src/test/java/org/eclipse/hono/service/VertxBasedHealthCheckServerTest.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
When using `vertxTestContext.checkpoint()`, tests should not rely on `vertxTestContext.completeNow()` to be called as the checkpoints already complete the context.
Otherwise the context might get completed prematurely, causing unexpected behaviour like `@AfterEach`/`@AfterAll` methods getting run before the test method is really finished.
> Use VertxTestContext checkpoints consistently

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslResponseContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/CoapContextTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResourceTest.java
- adapters/kura/src/test/java/org/eclipse/hono/adapter/kura/impl/KuraProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandlerTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/MqttContextTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/X509AuthHandlerTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapterTest.java
- client/src/main/java/org/eclipse/hono/client/CommandContext.java
- core/src/main/java/org/eclipse/hono/tracing/SpanContextHolder.java
- core/src/main/java/org/eclipse/hono/util/ExecutionContext.java
- core/src/main/java/org/eclipse/hono/util/GenericExecutionContext.java
- core/src/main/java/org/eclipse/hono/util/MapBasedExecutionContext.java
- core/src/main/java/org/eclipse/hono/util/MapBasedTelemetryExecutionContext.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
This is for #2115:
Require the `MapBasedExecutionContext` classes to have a non-null `Span` object. This is a preparation for having the authentication handler classes apply a trace sampling priority on the span of the `ExecutionContext`.
> [#2115] Add ExecutionContext#getTracingSpan

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- client/src/main/java/org/eclipse/hono/client/Command.java
- client/src/main/java/org/eclipse/hono/client/CommandResponse.java
- client/src/main/java/org/eclipse/hono/client/impl/AdapterInstanceCommandHandler.java
- client/src/main/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandler.java
- client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
- core/src/test/java/org/eclipse/hono/util/ResourceIdentifierTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
- services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java
This fixes #2180.
Improve error handling by explicitly checking for an empty string when creating a `ResourceIdentifier`.
Fix exception handling and javadoc comments concerning resource addresses.
> [#2180] Fix NPE if ResourceIdentifier string is empty

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java
Recently removing of private info from credentials using `CommonCredential.stripPrivateInfo()` has been incorporated in `AbstractCredentialsManagementService`. _MongoDB_ registry implementation already makes use of this abstract class. Hence invocation of `stripPrivateInfo()` has been removed from the _MongoDB_ registry implementation.
> Remove redundant stripping of private info while fetching credentials in MongoDB device registry

- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskSecret.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
The device registry implementations do no longer include the (secret)
shared key of PSK credentials in the result set of the Management API's
get credentials operation.
> [#2184] Strip shared key from PSK credentials

- adapters/coap-vertx-base/pom.xml
- adapters/pom.xml
Fixes no logs being printed out when running the unit tests in module hono-adapter-http-vertx-base and hono-adapter-mqtt-vertx-base.
> Add missing dependency for printing test log output

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
With this PR, the MongoDB device registry supports wildcard matching in search devices operation. The supported wildcard characters are  `*`  and `?`.
> Extend search devices operation to support wildcards in the MongoDB device registry

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
This fixes a potential NPE when sending a command with an empty (ie. unsupported) payload to an MQTT device.
(This NPE caused the command to be released via the exception handling.)
> MQTT adapter: Fix NPE in case command payload is null

- bom/pom.xml
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioning.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/Credentials.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/CredentialsDtoTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsApiTests.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
The supported credentials types now require the secrets array to be
non-empty.
> [#2215] Make secrets array mandatory

- core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
Also removed obsolete parameter type and improved documentation of
credentials and secrets objects.
> Remove auth-id and credentials type regex pattern from API

- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceManagementSearchDevicesTest.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- tests/pom.xml
Follow up of issue #1995. This implementation on the search devices operations only support paging ( and it may not be consistent).
Filtering and sorting should be implemented using databases features.
This is a draft PR to make sure we agree on the shape of things while I write a few integration tests :smiley: 
> [#1958]  implementation of the search devices operation for the file-based registry

- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
With this PR, the file-based device registry supports wildcard matching in search devices operation. The supported wildcard characters are  `*`  and `?`.
> Extend search devices operation to support wildcards in the file-based device registry

- .github/workflows/ci.yml
- jmeter/pom.xml
- tests/pom.xml
The job uses a build matrix for the different device registry implementations. The jobs are run in parallel on separate VMs.
> Add GitHub Actions workflow for CI build and running integration tests

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/CredentialsDto.java
- site/documentation/content/api/management/device-registry-v1.yaml
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
The registry implementations now accept X.509 credentials in update
Credentials requests. The registry now also removes existing credentials
on record that do not match any of the credentials in an update
Credentials request's body.
> [#2174][#2183] Accept X.509 credentials

- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
This should free up some resources.
EDIT:
When a telemetry message with Qos1 gets sent and the northbound consumer doesn't acknowledge the message by sending a delivery update, a timeout will occur in the protocol adapter after some time. 
The problem here is, that the message is considered as "in flight" still, most notably from the point of view of the AMQP messaging network (e.g. the Qpid dispatch router). This message counts towards the link capacity configured in the router.
This all means that if one sends as many messages as configured as the router link capacity to the north bound application, and if the northbound application doesn't send a delivery update for any of these, then any further messages will result in a "no credit" error when the adapter tries to send them to the …
> Release and settle delivery when waiting for update timed out

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/devices/AmqpExampleDevice.java
- service-base/src/main/java/org/eclipse/hono/service/auth/BaseAuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
Make use of `ServiceInvocationException.extractStatusCode()` method instead of duplicating the same code.
> Use the existing static method to get status codes for exceptions

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/main/java/org/eclipse/hono/util/QoS.java
- core/src/main/java/org/eclipse/hono/util/TelemetryExecutionContext.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
The UNKNOWN QoS level has no particular meaning but prevents the QoS
class from being used in the new client implementation (#2168).
> Remove UNKNOWN QoS level

- client/src/main/java/org/eclipse/hono/client/ServiceInvocationException.java
- client/src/test/java/org/eclipse/hono/client/ServiceInvocationExceptionTest.java
* Fix by replacing `Optional.of(...)` with `Optional.ofNullable(...)`
* Add tests to verify status code extraction
> Fix the static method to extract status code from exceptions

- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
Account for the fact that Credentials service implementations might
filter out disabled or currently not valid secrets.
@ctron Can you check if this does the trick for the JDBC registry implementation?
> Fix unit test

- client/src/main/java/org/eclipse/hono/client/Command.java
- client/src/test/java/org/eclipse/hono/client/CommandTest.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Command.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
This fixes #2234:
Commands now get rejected if they have a non-null body section that is not supported.
This is a conservative approach in that it still allows the body section to be an `amqp-value` (not documented in the API), not wanting to break existing consumer applications.
Also introduce a getPayloadSize() method, preventing copy of body section bytes.
> [#2234] Reject command message with unsupported body section

- core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
- core/src/test/java/org/eclipse/hono/util/CredentialsObjectTest.java
- site/homepage/content/release-notes.md
`CredentialsObject.getCandidateSecrets(...)` is used to retrieve valid secrets.  Currently the secrets are filtered based on their validity period regardless of whether the status is enabled or not. This has been fixed now, so that the disabled secrets are filtered out.
> Fix retrieval of valid secrets by filtering out disabled secrets

- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/pom.xml
- bom/pom.xml
- pom.xml
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- test-utils/pom.xml
- test-utils/service-base-test-utils/pom.xml
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
The module contains reusable classes that are helpful with implementing
unit tests for multiple Hono components.
This is just the first step illustrating the idea. The remaining adapter tests will be migrated once this PR is merged.
The *test-utils* module could also be the home for additional modules, e.g. *core-utils*. it could also be the home of the utility classes described by #1641
> Add test-utils module

- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/SQL.java
Some tests as below fail during the Hono CI build. The reasons is that the URL namely `jdbc:h2:/jobs/genie.hono/Hono CI Pipeline/workspace/services/device-registry-jdbc/target/data/d222ff86-346d-413b-b40e-17fb48004579` contains space characters. This causes issue while creating an URI object to get the JDBC database type. This has been fixed by encoding unsafe characters in the URL.
```
[ERROR] Tests run: 16, Failures: 0, Errors: 16, Skipped: 0, Time elapsed: 3.971 s <<< FAILURE! - in org.eclipse.hono.deviceregistry.jdbc.impl.JdbcBasedCredentialsServiceTest
[ERROR] testUpdateCredentialsSupportsRemovingExistingCredentialsAndSecrets{VertxTestContext}  Time elapsed: 0.009 s  <<< ERROR!
java.lang.IllegalArgumentException: Illegal character in opaque part at index 29: …
```
> Fix Hono CI build by encoding unsafe characters while creating URI

- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/SQL.java
This is related to the PR #2252. There is one more place where the URI creation should be fixed by encoding unsafe characters such as space in the URL string. This PR fixes it.
> [#2252] Fix error while creating URI by encoding unsafe characters

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionsManager.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
- client/src/main/java/org/eclipse/hono/client/ProtocolAdapterCommandConsumer.java
- client/src/main/java/org/eclipse/hono/client/impl/AdapterInstanceCommandHandler.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandHandlerWrapper.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- core/src/main/java/org/eclipse/hono/util/Pair.java
- core/src/test/java/org/eclipse/hono/util/PairTest.java
No 'disconnectedTtdEvent' is now sent anymore when a command consumer is obviously not registered anymore
because its associated command handling adapter instance entry has already been removed or overwritten.
This resolves both cases described in #2244.
> [#2244] Skip sendDisconnectedTtdEvent if consumer not mapped

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
- client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
- services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionServiceTest.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java
This reverts #1926 and makes the method behave according to the API spec again, returning a failed Future if the entry wasn't removed.
Motivated by discussion here: https://github.com/eclipse/hono/pull/2251#discussion_r505417615.
> Use void future in client removeCommandHandlingAdapterInstance()

- core/src/main/java/org/eclipse/hono/util/TenantObject.java
- core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509AuthenticationTest.java
- service-base/src/test/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducerTest.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/NoopTenantService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
The TenantObject now requires the mandatory properties tenant-id and
enabled to be specified in the constructor.
> Make tenant ID property mandatory

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
Fix concerning the changes done for #2115:
A 404 error when fetching the tenant in the PreCredentialsValidationHandler should be interpreted as a "bad credentials" error (401).
This lead to the wrong status code in corresponding HTTP adapter responses.
Only applies to the yet-unreleased 1.5 Hono version.
> [#2115] Fix wrong exception if tenant not found in PreCredentialsValidationHandler

- client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java
- clients/adapter-amqp/pom.xml
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/AbstractServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/SenderCachingServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSender.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
The implementation reuses the existing vertx-proton based
implementations but replaces the existing factories.
In a subsequent PR the protocol adapters will be refactored to use the new TelemetrySender and EventSender instead of the existing DownstreamSenderFactory.
> [#2267] Add implementation of Telemetry and EventSender

- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/SenderCachingServiceClient.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/telemetry/EventSender.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/telemetry/TelemetrySender.java
* With PR #2259, the tenant identifier is made mandatory for the `TenantObject`. The `EventSender.sendEvent(...)` and `TelmetrySender.sendTelemetry(...)` methods throwing `IllegalArgumentException` in case of no tenant identifier, is obsolete. This has been fixed in the JavaDoc.
* Minor improvement by replacing `stream().forEach()` with `forEach()`
> Fix javadoc in TelmetrySender and EventSender

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/PropertyBag.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/PropertyBagTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/util/TelemetryExecutionContext.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- service-base/src/test/java/org/eclipse/hono/service/http/HttpContextTest.java
- test-utils/service-base-test-utils/pom.xml
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
The protocol adapters now create downstream messages using the new
MessageHelper.newMessage() method which accepts a Map of properties to
include in the message.
This is in preparation for the adapters being refactored to use the new
TelemetrySender and EventSender instead of the legacy DownstreamSender.
> Create downstream message from properties gathered from context

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/Application.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- bom/pom.xml
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSender.java
- service-base/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducer.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- service-base/src/test/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducerTest.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
Added implementations of the adapter client's TelemetrySender and
EventSender interfaces which wrap the existing vertx-proton based
"legacy" DownstreamSender.
> [#2267] Add AMQP 1.0 based Telemetry/EventSender implementation

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResourceTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/Application.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/AbstractServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/AbstractRequestResponseClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClient.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509AuthenticationTest.java
- service-base/src/test/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducerTest.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
Added implementations of the adapter client's TenantClient interface
which simply wraps the existing vertx-proton based
"legacy" TenantClientImpl.
This is the most straight forward implementation which simply delegates all method invocations to TenantClientImpl.
This also means that caching of response messages from the Tenant service is still done inside of TenantClientImpl instances.
This might/should be improved in the future to provide caching at the ProtonBasedTenantClient level in order to be able to return caches values even if the connection/link to the service is (currently) unavailable.
> [#2267] Add AMQP 1.0 based TenantClient implementation

- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/Application.java
- adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- client/src/main/java/org/eclipse/hono/client/CommandTargetMapper.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandTargetMapperImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/CommandTargetMapperImplTest.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/registry/DeviceRegistrationClient.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
Added implementations of the adapter client's DeviceRegistrationClient
interface which simply wraps the existing vertx-proton based
"legacy" RegistrationClientImpl.
In order to be able to use the legacy CommandTargetMapper, its direct
dependency on RegistrationClientFactory and
BasicDeviceConnectionClientFactory has been replaced with a
CommandTargetMapperContext interface which provides access to the
required functionality. Existing code using the CommandTargetMapper with
the legacy client will need to be adapted. For convenience, the
CommandTargetMapper.createContext() method can be used to get an
implementation based on RegistrationClientFactory and
BasicDeviceConnectionClientFactory.
> [#2267] Add AMQP 1.0 based DeviceRegistrationClient implementation

- adapters/base-quarkus/pom.xml
- adapters/http-vertx-quarkus/src/main/docker/Dockerfile.jvm
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/MetricsFactory.java
- adapters/mqtt-vertx-quarkus/src/main/docker/Dockerfile.jvm
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/MetricsFactory.java
- bom/pom.xml
- service-base-quarkus/pom.xml
- tests/pom.xml
- tests/readme.md
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
The ITs can now be run by activating the "protocol-adapters-quarkus"
Maven profile.
> Use Maven profile for running Quarkus based adapters in ITs

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/Application.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedCredentialsClient.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
- service-base/src/main/java/org/eclipse/hono/service/auth/device/X509AuthProvider.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProviderTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java
- service-base/src/test/java/org/eclipse/hono/service/auth/device/X509AuthProviderTest.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
Added implementations of the adapter client's CredentialsClient
interface which simply wraps the existing vertx-proton based
"legacy" CredentialsClientImpl.
> [#2267] Add AMQP 1.0 based CredentialsClient implementation

- client/src/main/java/org/eclipse/hono/client/ProtocolAdapterCommandConsumerFactory.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
The ProtocolAdapterCommandConsumerFactory's dependency on the legacy
DeviceConnectionClientFactory has been replaced by an interface that
provides access to the required command handling adapter instance
information. This is a preliminary step for introducing a new
DeviceConnectionClient to the adapter-client module.
> [#2267] Decouple command consumer from device connection client factory

- client-device-connection-infinispan/pom.xml
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- client/pom.xml
- client/src/test/java/org/eclipse/hono/client/AbstractAmqpAdapterClientDownstreamSenderTestBase.java
- client/src/test/java/org/eclipse/hono/client/CommandTest.java
- client/src/test/java/org/eclipse/hono/client/device/amqp/internal/AmqpAdapterClientCommandConsumerTest.java
- client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
- client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
- client/src/test/java/org/eclipse/hono/client/impl/AbstractTenantTimeoutRelatedClientFactoryTest.java
- client/src/test/java/org/eclipse/hono/client/impl/AdapterInstanceCommandHandlerTest.java
- client/src/test/java/org/eclipse/hono/client/impl/CachingClientFactoryTest.java
- client/src/test/java/org/eclipse/hono/client/impl/CommandClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/CommandTargetMapperImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/CredentialsClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/DownstreamSenderFactoryImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/EventConsumerImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/EventSenderImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoClientUnitTestHelper.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandlerTest.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/RegistrationClientImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/TelemetrySenderImplTest.java
- client/src/test/java/org/eclipse/hono/client/impl/TenantClientImplTest.java
- test-utils/core-test-utils/pom.xml
- test-utils/core-test-utils/src/main/java/org/eclipse/hono/test/TracingMockSupport.java
- test-utils/core-test-utils/src/main/java/org/eclipse/hono/test/VertxMockSupport.java
- test-utils/service-base-test-utils/pom.xml
Move `VertxMockSupport` from `hono-client` to `core-test-utils`; introduce `TracingMockSupport` class.
> Add MockSupport classes in core-test-utils

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/MicrometerBasedAmqpAdapterMetrics.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/Config.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/MicrometerBasedCoapAdapterMetrics.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/Config.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/MicrometerBasedHttpAdapterMetrics.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/Application.java
- adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/Config.java
- adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Config.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Config.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MicrometerBasedMqttAdapterMetrics.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/Application.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Config.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractProtocolAdapterApplication.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/ProtocolAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducerConfig.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
The collaborators required by protocol adapters are not injected using
autowiring anymore. This allows for shifting responsibility of object
instantiation/initialization from AbstractProtocolAdapterBase to the
Spring Boot/Quarkus configuration classes which helps with hiding
implementation details from the adapter implementation classes.
> [#2267] Do not use Spring autowiring for adapters anymore

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/ApplicationConfig.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/CommandConsumerFactory.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
For #2029:
Using `org.eclipse.hono.util.Lifecycle` instead of `ConnectionLifecycle` in `CommandConsumerFactory`.
> [#2029] Refactor CommandConsumerFactory in the Command Router

- site/homepage/layouts/partials/scripts.html
- site/homepage/static/css/custom.css
This removes the carousel from the adopter's section on the homepage to increase the stability. The logos are now simply displayed as a vertical list with automatically adjusts to small window sizes.
> [#2197] Remove carousel from adopters list.

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
* The integration tests for the search devices operation have not been running as it expects
the system property `hono.deviceregistry.supportsSearchDevices` set to true. This property
has been renamed to  `deviceregistry.supportsSearchDevices` in the `pom.xml` of _tests_ 
module but not in the corresponding test class. This has been fixed now to use the renamed
property in the test class.
* Integration tests corresponding to the search devices operation have been disabled for the 
JDBC based device registry as it doesn't implement this operation.
* When the data type of a filter value is string and the value doesn't contain any search wild 
card characters then that filter has been ignored by the MongoDB device registry. This has 
been fixed.
* When there are no filters specified in the …
> Fix search devices operation and integration tests

- client/src/main/java/org/eclipse/hono/client/HonoConnection.java
- client/src/main/java/org/eclipse/hono/client/impl/AsyncCommandClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractProtocolAdapterApplication.java
HonoConnectionImpl#tracer needs to be set explicitly, otherwise the NoopTracer is used.
> Fix tracing for Quarkus based adapters

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
The HTTP adapter suffered from a bug when a client sent an event and set a device level QoS to something different than 1 or set no device level QoS at all. In any case the event was sent with QoS 1 but the message property indicating the device level QoS to the northbound application (which should always be 1 as this is the only supported QoS for events) was wrong.
> [#2288] Fixing device level QoS forwarding of events for HTTP adapter.

- legal/src/main/resources/legal/NOTICE.md
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
tenantAdapterStore should use `tenantsProperties().getAdapter()` instead of `tenantsProperties().getManagement()`
I noticed this small bug while working on #2317 .
> tenantAdapterStore should use tenantsProperties().getAdapter()

- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
The HTTP adapter suffered from a bug when a client sent an event and set a device level QoS to something different than 1 or set no device level QoS at all. In any case the event was sent with QoS 1 but the message property indicating the device level QoS to the northbound application (which should always be 1 as this is the only supported QoS for events) was wrong.
> [#2288] Add integration tests verifying forwarding of QoS level in downstream messages

- push_hono_images.sh
include `hono-service-device-registry-jdbc` image in the images handled by `push_hono_images.sh` script
> Include hono-service-device-registry-jdbc image in pushed images

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
The HTTP adapter suffered from a bug when a client sent an event and set a device level QoS to something different than 1 or set no device level QoS at all. In any case the event was sent with QoS 1 but the message property indicating the device level QoS to the northbound application (which should always be 1 as this is the only supported QoS for events) was wrong.
> [#2288] Fixing device level QoS forwarding of events for HTTP adapter

- bom/pom.xml
Update to latest image versions for use in the integration tests.
> Update to Artemis 2.13.0, Qpid router 1.14.0 image versions

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/ApplicationConfig.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
When processing Command Router API requests, the original vert.x context of the CommandRouterAmqpServer needs to be restored at the end, because the commandConsumerFactory has switched to the context in which the downstream AMQP connection is used.
This fixes issues with the Command Router component sending invalid AMQP frames or throwing exceptions when handling the requests.
I'm also working on a more general fix concerning verticle handling/communication in the Command Router component, which shall use multiple `ProtonBasedCommandConsumerFactoryImpl` instances and thereby use multiple downstream AMQP connections.
> [#2029] Fix Command Router AMQP server vert.x context issues

- .github/workflows/ci.yml
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandContext.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandRouterCommandConsumerFactoryImpl.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedDelegatingCommandConsumerFactory.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedDeviceConnectionClient.java
- deploy/src/main/deploy/example-permissions.json
- deploy/src/main/sandbox/sandbox-permissions.json
- jenkins/Hono-Deploy-Eclipse-Pipeline.groovy
- jenkins/Hono-Deploy-Maven-Central-Pipeline.groovy
- jenkins/Hono-Nightly-Pipeline.groovy
- push_hono_images.sh
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractProtocolAdapterApplication.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
- tests/pom.xml
- tests/readme.md
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/auth/permissions.json
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/commandrouter/application.yml
- tests/src/test/resources/commandrouter/cache-config.xml
- tests/src/test/resources/commandrouter/logback-spring.xml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
- tests/src/test/resources/qpid/qdrouterd-with-broker.json
This is for #2029.
This adds a `org.eclipse.hono.adapter.client.command.CommandConsumerFactory` implementation that uses the new Command Router component.
For the integration tests, a new maven profile `command-router` is added to let the tests run using the Command Router component.
The GitHub action workflow has been adapted to use that profile in the test-run that uses the jdbc device registry (so that the other test-runs still use the old command routing mechanism).
> [#2029] Use Command Router in adapters and integration tests

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/Cache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/EmbeddedCache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCache.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/AbstractBasicCacheTest.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/EmbeddedCacheTest.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCacheTest.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/infinispan/EmbeddedCacheConfig.java
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/EmbeddedCacheConfig.java
- site/documentation/content/admin-guide/device-connection-config.md
This fixes #2068:
The `HotrodCache#checkForCacheAvailability()` method will now determine its outcome based on whether the last cache operation was successful or not. It will only "put" the connectionCheckKey/Value if the last cache operation took place more than 30s ago.
The `EmbeddedCache#checkForCacheAvailability()` method now only checks whether the cache instance was successfully obtained, not doing the "put" operation with connectionCheckKey/Value anymore.
> [#2068] Use cached connected check result in HotrodCache

- adapters/pom.xml
- core/src/main/java/org/eclipse/hono/config/VertxProperties.java
- services/pom.xml
- site/documentation/content/admin-guide/common-config.md
- tests/pom.xml
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/auth/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/commandrouter/application.yml
- tests/src/test/resources/deviceconnection/application.yml
- tests/src/test/resources/deviceregistry-jdbc/application.yml
- tests/src/test/resources/deviceregistry-mongodb/application.yml
- tests/src/test/resources/deviceregistry/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
All of Hono's service components now include Netty's native transport
libraries by default. The libraries are license compatible with EPL so
there is no reason to not include them by default and then allow users
to simply enable native transport using the existing configuration
property.
> Include native transport libs by default

- deploy/src/main/sandbox/artemis/broker.xml
- tests/src/test/resources/artemis/broker.xml
This fixes #2333:
This fixes the issue of broker queues not getting created when event messages are sent and of event messages getting forwarded to multiple consumers.
Integration tests verifying the behaviour will be added in a separate PR (prepared by @kaniyan).
> [#2333] Use ANYCAST routing type in broker config

- bom/pom.xml
As a consequence, updated vert.x downstream dependency on Jackson to
2.11.3.
Also upgraded to latest Quarkus release 1.9.2.Final which depends on
vert.x 3.9.4.
> Upgrade to vert.x 3.9.4

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
This patch fixes #2338 by setting "application/octet-stream" as the content-type if nothing is set (analogous to the MQTT adapter).
> [#2338] Fix NPE in AMQP adapter when content-type is null.

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
A not-set 'Content-Type' header caused an empty String to be returned by getContentType() although 'null' was
documented in the javadoc.
Since the AMQP message anyway gets the "application/octet-stream" content type in that case, the getContentType() method now returns "application/octet-stream" as the default (returning 'null' would have produced an NPE down the line).
Related to #2338.
Another option would have been returning `null` here and throwing a "BAD_REQUEST" error in the calling method when sending telemetry/events. That would be in accordance with the documentation as the content-type header is required, but I'd rather not introduce such a behaviour change that may break clients, instead keeping the behaviour analogous with MQTT and AMQP adapters (the CoAP adapter returns …
> Fix getContentType() returning empty string

- service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
- site/homepage/content/release-notes.md
This reverts the behaviour introduced in the last commit of using CONTENT_TYPE_OCTET_STREAM as default.
Instead, null is returned to also enable usage of the tenant default content type if set.
Applies the getContentType() change suggested in #2340 (but omits the other changes to keep this only a small change in 1.4.x).
> 1.4.x: Let getContentType() return null if no header is set

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
- adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMapping.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSender.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/telemetry/EventSender.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/telemetry/TelemetrySender.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
- service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
This makes it possible that a content-type defined in the defaults of a tenant can be used as fallback.
This provides an alternative fix for #2338.
See also discussion in #2340 (changes regarding usage of "application/octet-stream" as default will go in separate PR).
> Allow null contentType in Event/Telemetry Sender

- service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
Fix for #2346 (1.3.x):
Using the tenant maxTtl as the ttl parameter value in the `MessageHelper.newMessage()` invocation has been removed since
the tenant maxTtl will be taken into account in `MessageHelper.newMessage()` anyway.
> 1.3.x: [#2346] Fix ConnectionEvent messages not getting sent

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
Preserving the behaviour of Hono 1.4, a command message sent to an AMQP device should have the 'to' address set as it was set on the AMQP message sent by the northbound application.
> Add 'to' address in AMQP device command message

- site/documentation/content/deployment/helm-based-deployment.md
- site/documentation/content/dev-guide/building_hono.md
- site/homepage/content/release-notes.md
This is for #2250.
Also adds release notes entry about inclusion of Jaeger in images on Docker Hub.
> [#2250] Use Jaeger profile in standard build instructions

- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/telemetry/EventSender.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/telemetry/TelemetrySender.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
Based on the discussion in #2340:
The "application/octet-stream" content type now gets applied as default in the setPayload() methods, provided the payload isn't null. The "payload not null" condition is now also used in the other places where the content type gets set.
This effectively means:
- non telemetry/event messages (e.g. command response messages), that aren't empty, get the "application/octet-stream" content type as default as well
- a telemetry/event AMQP message without payload and content type, sent to the AMQP adapter, will now be forwarded without a content type.
- a default content type defined in the tenant configuration will now only get applied if the payload isn't null (this probably only applies to telemetry/event AMQP messages without payload sent to the AMQP …
> Apply default content type in setPayload()

- .github/workflows/ci.yml
The integration test run that uses the MongoDB device registry is also using the Quarkus-based adapters now.
> Use quarkus adapters in integration tests on GitHub

- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandRouterCommandConsumerFactoryImpl.java
> [#2357] Skip closing tenant link on tenant timeout if still needed

- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
The connection attempt doesn't actually fail here (`isTrue()` missing after `assertThat(result.failed())`).
The connection getting closed after closing the session is already getting tested by `testRemoteSessionCloseTriggersReconnection()`.
In order to establish the behaviour that this test wants to verify, the `connect()` invocation would have to wait for the session `openHandler` to be called and only then finish the `connect` Future.
But that is also not done in the `ProtonConnectionImpl` default session handling.
> Remove non-working HonoConnectionImpl test

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MessageMapping.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMapping.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
- core/src/main/java/org/eclipse/hono/config/MapperEndpoint.java
@BobClaerhout @sophokles73 sorry, this took quiet sometime :-) This patch addresses the cases discussed in #2133
> No mapping service is configured for the gateway.
The default mapper now returns a `null` result in this case. The MQTT adapter checks for the presence of a null value and forwards the original message without any mapping
> Mapping service is configured for the gateway but invocation of the service results in an error status code.
We distinguish between success codes (2XX) and error codes (4XX, 5XX). The 200 status code results in a mapped message with the mapped payload and target address while status codes > 200 results in a mapped message with the original payload  and target address
> [#2133] Improve message mapping API

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
This addresses #2363 
The MQTT adapter now supports a tenant specific boolean configuration
property that allows to always include the tenant ID in the topic name
used for publishing command messages.
This can be used to allow protocol gateways to determine a device's
tenant from the topic name.
> Make inclusion of tenant ID configurable

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandler.java
Only done if gateway has subscribed specifically for the device the command is targeted at.
Not needed if command is forwarded to a gateway that has subscribed to commands for all its devices.
In that case the command is explicitly mapped to the gateway via the DeviceConnection API `getCommandHandlingAdapterInstances(tenant, deviceId, viaGateways, spanContext)` method, using the up-to-date via-gateway information.
(A gateway having subscribed specifically for the device is handled in the DeviceConnection service, as if the device had subscribed directly. The assignment to the gateway is only done in the target adapter instance logic in that case.)
I wanted to add integration tests here, clearing the via-gateways in the device registration data after a command subscription was done. But I …
> Invoke assertRegistration before sending command to gateway

- client/src/main/java/org/eclipse/hono/client/TenantClient.java
- client/src/main/java/org/eclipse/hono/client/TenantClientFactory.java
- client/src/main/java/org/eclipse/hono/client/impl/TenantClientImpl.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/AbstractHonoClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/AbstractRequestResponseServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/AbstractServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/RequestResponseClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClient.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/AbstractRequestResponseServiceClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/AmqpClientUnitTestHelper.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/RequestResponseClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/SimpleRequestResponseResult.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedTenantCommandRouterClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClientTest.java
This is the first step of #2381 
Responses from the Tenant service are now being stored in a cache that
is independent from the life cycle of the underlying connection to the
service.
> Introduce response caching at Tenant service client level

- client/src/main/java/org/eclipse/hono/client/RequestResponseClientConfigProperties.java
- clients/adapter-amqp/pom.xml
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/AbstractRequestResponseServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClient.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/AbstractRequestResponseServiceClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedCredentialsClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedDeviceRegistrationClientTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClientTest.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractProtocolAdapterApplication.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- service-base/src/main/java/org/eclipse/hono/service/cache/Caches.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/ApplicationConfig.java
- site/documentation/content/admin-guide/common-config.md
- site/documentation/content/admin-guide/hono-client-configuration.md
- site/homepage/content/release-notes.md
The registry service clients have been changed to use a Caffeine based
cache instead of org.eclipse.hono.cache.ExpiringValueCache.
The Caffeine cache is configured to expire values based on the
CacheDirective's max age that is contained in the RequestResponseResult
typed values.
Also, a single cache instance is being used per service which is shared
between all client instances.
The ProtonBasedTenantClient has been changed to make sure that only a
single request is issued to the Tenant service when multiple (parallel)
method invocations result in cache misses.
> [#2381] Use expiring Caffeine cache

- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/DownstreamSenderLink.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/SenderCachingServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandResponseSender.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSender.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/DownstreamSenderLinkTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/telemetry/amqp/ProtonBasedDownstreamSenderTest.java
The ProtonBasedDownstreamSender and ProtonBasedCommandResponseSender
have been refactored to use a wrapper around a sender link to forward
messages downstream which no longer depends on the legacy client.
Fixes #2387
> [#2387] Do not use legacy client's DownstreamSender in new client

- bom/pom.xml
- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/SQL.java
- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/DeviceStores.java
- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/TableAdapterStore.java
- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/device/TableManagementStore.java
- services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/device/base.postgresql.sql.yaml
- services/base-jdbc/src/main/resources/org/eclipse/hono/service/base/jdbc/store/tenant/base.sql.yaml
- services/base-jdbc/src/main/sql/postgresql/create.devices.sql
- services/base-jdbc/src/main/sql/postgresql/create.tenants.sql
- services/device-registry-jdbc/pom.xml
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/AbstractJdbcRegistryTest.java
* Adds DDL for Postgres and adapt queries  for Postgres syntax
* Provide workaround for the fact that vertx jdbc doesn't support arrays (https://stackoverflow.com/a/42295098 for details)
* Pass array parameter as CSV string and parse in query using DB specific functions
* Run Postgres tests with TestContainers and Postgres Docker image
* Fix failing tests for PostgreSQL
> Add integrations tests for Postgres in JDBC registry and fix issues

- cli/pom.xml
- cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
- cli/src/main/java/org/eclipse/hono/cli/app/KafkaReceiver.java
- cli/src/main/resources/application.yml
- cli/src/main/resources/logback-spring.xml
- cli/src/test/java/org/eclipse/hono/cli/app/KafkaReceiverTest.java
- cli/src/test/resources/logback-test.xml
This PR adds a receiver to the CLI that consumes telemetry data and events from Kafka. Please refer to "Start the Downstream Consumer" in https://github.com/eclipse/hono/pull/2216#issuecomment-730255279 for usage instructions.
This belongs to #8.
> [#8] Add Kafka receiver to CLI.

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/infinispan/EmbeddedCacheConfig.java
- services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/EmbeddedCacheConfig.java
Enable using an embedded cache for the device connection / command router service with the default options, without having to use a cache configuration file.
> Fix usage of embedded cache with default config

- .github/workflows/ci.yml
- bom/pom.xml
- services/device-registry-jdbc/pom.xml
- services/device-registry-mongodb/pom.xml
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java
- tests/pom.xml
The flapdoodle library used for starting an embedded Mongo DB before
running the unit tests of the Mongo DB based registry doesn't support
Mongo DB versions > 4.0.
The testcontainers framework provides more flexibility in that regard.
> Use Testcontainers for running MongoDB registry unit tests

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/ApplicationConfig.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/CommandConsumerFactory.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/CommandTargetMapper.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandTargetMapperImpl.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/MappingAndDelegatingCommandHandler.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/amqp/MappingAndDelegatingCommandHandlerTest.java
Thereby removing usage of the deprecated `org.eclipse.hono.client.CommandTargetMapper` class.
> Add own CommandTargetMapper in Command Router

- client/src/main/java/org/eclipse/hono/client/impl/AdapterInstanceCommandHandler.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedAdapterInstanceCommandHandler.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommand.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandContext.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandRouterCommandConsumerFactoryImpl.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedDelegatingCommandConsumerFactory.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedLegacyCommandContextWrapper.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedAdapterInstanceCommandHandlerTest.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Command.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandContext.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandHandlerWrapper.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandHandlers.java
The `AdapterInstanceCommandHandler` class has been marked as deprecated and a new corresponding class has been added, not using the deprecated Command(Context) classes anymore.
> Replace usage of deprecated Command classes

- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
The client previously Listened on the loopback address which lead to an address not being possible to bind to a port when the tests were run on a machine with a non-localost docker daemon.
This fixes #1345.
> [#1345] Making CoAP integration test client listen on wildcard address.

- adapters/base-quarkus/pom.xml
- adapters/http-vertx-quarkus/src/main/resources/reflection-config.json
- adapters/mqtt-vertx-quarkus/src/main/resources/reflection-config.json
- bom/pom.xml
- pom.xml
- site/documentation/content/dev-guide/building_hono.md
Upgraded to version 1.10.5. The Quarkus Caffeine extension no longer
registers all cache implementation classes for reflection during native
builds. Thus, the implementation classes required by Hono's adapters had
to be added manually to the reflection-config.json files.
See https://github.com/quarkusio/quarkus/issues/12961
> Upgrade to latest Quarkus version

- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioning.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
The Device Registry Management API's "update credentials" operation has
been extended to allow specifying the auth-id and validity period
implicitly by means of including a (Base64 encoded) client certificate
in the new "cert" property. This can be used instead of specifying the
client certificate's subject DN and public key's validity period
explicitly in the "auth-id" and "secrets" properties. This should make
setting the correct "auth-id" value much less error prone.
Fixes #2170
> [#2170] Support upload of client certificate for X.509 credentials

- site/documentation/content/concepts/device-provisioning/index.md
Hugo fails with the following error:
```
`"hono/site/documentation/content/concepts/device-provisioning/index.md:97:53": unterminated quoted string in shortcode parameter-argument: 'A unregistered device connects to a gateway which uses the 
'
```
This causes the Hono build to fail as well.
This fix removes a line break inside the "alt" string of a figure declaration.
> Fix build of documentation.

- bom/pom.xml
- clients/application-amqp/pom.xml
- clients/application-amqp/src/main/java/org/eclipse/hono/client/application/amqp/AmqpApplicationClientFactory.java
- clients/application-amqp/src/main/java/org/eclipse/hono/client/application/amqp/AmqpMessageContext.java
- clients/application-kafka/pom.xml
- clients/application-kafka/src/main/java/org/eclipse/hono/client/application/kafka/KafkaApplicationClientFactory.java
- clients/application-kafka/src/main/java/org/eclipse/hono/client/application/kafka/KafkaMessageContext.java
- clients/application-kafka/src/main/java/org/eclipse/hono/client/application/kafka/KafkaMessageProperties.java
- clients/application/pom.xml
- clients/application/src/main/java/org/eclipse/hono/client/application/ApplicationClientFactory.java
- clients/application/src/main/java/org/eclipse/hono/client/application/DownstreamMessage.java
- clients/application/src/main/java/org/eclipse/hono/client/application/DownstreamMessageImpl.java
- clients/application/src/main/java/org/eclipse/hono/client/application/Message.java
- clients/application/src/main/java/org/eclipse/hono/client/application/MessageConsumer.java
- clients/application/src/main/java/org/eclipse/hono/client/application/MessageContext.java
- clients/application/src/main/java/org/eclipse/hono/client/application/MessageProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/kafka/client/HonoTopic.java
- clients/kafka-common/src/main/java/org/eclipse/hono/kafka/client/tracing/KafkaTracingHelper.java
- clients/kafka-common/src/test/java/org/eclipse/hono/kafka/client/HonoTopicTest.java
- clients/pom.xml
This adds an interface for clients to be used by northbound applications, which removes the dependency from AMQP-specific types and allows to easily switch between AMQP-based and Kafka-based messaging.
This currently only supports downstream messaging. Support for command & control is to be added later.
This is the first step of #2392. Implementations of this interface are subject of subsequent pull requests to keep this PR smaller.
> Add transport protocol agnostic interface for northbound Hono-Client

- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/Command.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedAdapterInstanceCommandHandler.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommand.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedLegacyCommandContextWrapper.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedLegacyCommandWrapper.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedAdapterInstanceCommandHandlerTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandTest.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommand.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandTest.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Command.java
- test-utils/service-base-test-utils/src/main/java/org/eclipse/hono/service/test/ProtocolAdapterTestSupport.java
Refactor device/gateway related Command methods:
`getDeviceId()` has been renamed to `getGatewayOrDeviceId()` and `getOriginalDeviceId()` has been renamed to `getDevice()`. Also a `getGatewayId()` method has been added.
Refactor Command classes:
The new `Command` class now requires tenant/device information to be set and returns this kind of information even if the
command is otherwise invalid. This makes it easier to choose the command handler for a potentially invalid command.
Usage of the legacy command class inside the` ProtonBasedCommand` has been removed.
For the review it may be easier to look at the 2 commits separately.
> Refactor Command classes

- tests/pom.xml
- tests/readme.md
- tests/src/test/resources/coap/logback-spring.xml
- tests/src/test/resources/http/logback-spring.xml
- tests/src/test/resources/logback-test-include-dev.xml
- tests/src/test/resources/logback-test-include-prod.xml
- tests/src/test/resources/logback-test-include-trace.xml
- tests/src/test/resources/logback-test.xml
- tests/src/test/resources/mqtt/logback-spring.xml
When running the integration tests with the `logging.profile` parameter (e.g. `-Dlogging.profile=trace` ), the logging profile is currently only applied to the components started in the docker containers, not the integration tests themselves.
This PR fixes that.
Uses `<include resource="logback-test-include-${logging.profile}.xml"/>` to select/apply the loggers for the selected profile.
(Using `<if condition="some conditional expression">` instead would have allowed putting it all into logback-test.xml, but that would require the Janino library as an extra dependency.)
> Use logging.profile for integration test log levels

- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
This PR adds integration tests for auto-provisioning.
Before merging this PR 
https://github.com/eclipse/hono/pull/2358
https://github.com/eclipse/hono/pull/2360
https://github.com/eclipse/hono/pull/2359
need to be merged, so that tests will run successfully
> [#2053] Adding integration tests for gateway-based auto provisioning.

- client/src/main/java/org/eclipse/hono/client/Command.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/SenderCachingServiceClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommand.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandContext.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedInternalCommandSender.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedLegacyCommandWrapper.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommand.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Command.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/InternalCommandSender.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericSenderLink.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/GenericSenderLinkTest.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/MappingAndDelegatingCommandHandler.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/amqp/MappingAndDelegatingCommandHandlerTest.java
The Command Router now uses the new API for sending command messages to the target protocol adapter instance.
> Use the new API for sending to internal command endpoint

- pom.xml
- services/device-registry-jdbc/pom.xml
- services/device-registry-mongodb/pom.xml
The "no.docker" property has been replaced by "skipDockerTests", initialized to the "skipTests" value by default.
This re-enables the possibility to skip all tests via the -DskipTests maven argument.
> Fix -DskipTests not working for docker related tests

- services/device-registry-base/pom.xml
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisioner.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisionerConfigProperties.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisionerTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
> [#2393] Migrating to ProtonBasedDownstreamSender in AutoProvisioner.

- client/src/main/java/org/eclipse/hono/client/ResourceLimitExceededException.java
- client/src/main/java/org/eclipse/hono/client/StatusCodeMapper.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/resources/org/eclipse/hono/client/ServiceInvocationException_messages.properties
- client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
- client/src/test/java/org/eclipse/hono/client/impl/EventSenderImplTest.java
- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/amqp/RequestResponseClientTest.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericSenderLink.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/GenericSenderLinkTest.java
- site/homepage/content/release-notes.md
- tests/src/test/resources/amqp/logback-spring.xml
- tests/src/test/resources/coap/logback-spring.xml
- tests/src/test/resources/http/logback-spring.xml
- tests/src/test/resources/mqtt/logback-spring.xml
The AMQP based adapter client has been changed to throw a
ServerErrorException with a status code of 503 in case a downstream AMQP
container rejects a message with error condition
amqp:resource-limit-exceeded.
This allows protocol adapters to notify devices accordingly.
> Fix queue full handling

- site/documentation/content/api/command-and-control-kafka/index.md
This is for #2273:
Adds the specification for the Command & Control API for Kafka.
One of the main differences to the AMQP spec is that command response messages aren't targeted at a resource containing a "replyId" (like `command_response/${tenant_id}/${reply_id}`) but instead are written into the more general `hono.command_response.${tenant_id}` Kafka topic.
This means that no `reply-to` property/header is needed for the command message. Instead, to indicate that a command is supposed to trigger a response, ~~a `expect-response` header with a boolean value is used~~ the existence of the `correlation-id` header is used.
> [#2273] Add Command & Control API for Kafka spec

- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedDelegatingCommandConsumerFactory.java
Initialization of the factory involves creating a consumer link. Therefore the initialize() method should be called after connect() in order to prevent unnecessary link creation retries. That was also the behaviour in Hono 1.4.
Also prevents many log lines like these on startup:
````
17:47:00.210 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.i.ProtocolAdapterCommandConsumerFactoryImpl - recreate command consumer links
17:47:00.234 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.i.ProtocolAdapterCommandConsumerFactoryImpl - recreate command consumer links
17:47:00.254 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.i.ProtocolAdapterCommandConsumerFactoryImpl - recreate command consumer links
````
> Init command consumer factory after connect()

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/tracing/KafkaTracingHelper.java
`AbstractKafkaBasedDownstreamSender` is refactored and some methods are pulled up to the new base class `AbstractKafkaBasedMessageSender`. This is to prepare for the Kafka based command router component.
> [#2273] Prepare base classes for implementing Kafka based command router

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/AbstractKafkaConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaProducerConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigProperties.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaProducerConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigPropertiesTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
Also provide a way to define common config properties used in all the producer, consumer and admin client types.
> Add KafkaAdminClientConfigProperties class

- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericReceiverLink.java
- clients/application-amqp/pom.xml
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/AmqpApplicationClientFactory.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/AmqpMessageContext.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClientFactory.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedDownstreamMessage.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClientFactoryTest.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedDownstreamMessageTest.java
- clients/application-amqp/src/test/resources/logback-test.xml
- clients/application/src/main/java/org/eclipse/hono/application/client/DownstreamMessage.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/main/java/org/eclipse/hono/util/QoS.java
This adds a vertx-proton based implementation of #2392
In a next PR I will refactor the integration tests to use the new application client factory.
@b-abel would you mind to also take a look?
> [#2392] Add implementation of AMQP based application client factory

- client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/EventAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoClientImplIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/EventCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
- tests/src/test/resources/logback-test-include-dev.xml
- tests/src/test/resources/logback-test-include-trace.xml
This is for #2392
The integration tests now use the new application client for consuming
downstream telemetry and event messages.
> Refactor integration tests

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommand.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandTest.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/Command.java
- site/documentation/content/api/command-and-control-kafka/index.md
Rename the Kafka record header used for request/response commands. 
The new name better reflects the need for a response to be sent by the device because otherwise the sending application has to consider the execution of the command to have failed. The new name is also in line with the corresponding name in Eclipse Ditto.
> Use response-required instead of response-expected command header

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommand.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandTest.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumerTest.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandRouterCommandConsumerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/HonoTopic.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/HonoTopicTest.java
- service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
This is for #2273.
Adds a Kafka consumer used in protocol adapters for receiving commands forwarded by the Command Router component.
> [#2273] Add KafkaBasedInternalCommandConsumer

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
Use KafkaMessageHelper.createKafkaHeader() for the encoding of Kafka headers in AbstractKafkaBasedMessageSender. Encoding and decoding are error-prone operations that must produce stable results. Therefore I want to use a single class where both operations are implemented.
> [#8] Use KafkaMessageHelper in AbstractKafkaBasedMessageSender.

- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedInternalCommandConsumer.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandSender.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractMappingAndDelegatingCommandHandler.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
Ensure that once createCommandConsumer() in the Kafka-based CommandConsumerFactory succeeds, the relevant Kafka topic exists and is in the list of subscribed topics of the consumer.
> [#2273] Improve createCommandConsumer() in Command Router

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AuthHandlerTools.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandler.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoChainAuthHandler.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoHttpAuthHandler.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpAuthProviderAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandlerTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/HonoChainAuthHandlerTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/X509AuthHandlerTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
There are several classes in the service-base module which are only
relevant to HTTP based protocol adapters. These classes have therefore
been moved to the HTTP adapter base module.
This is also the first step towards splitting up the service-base module into a service-base and an adapter-base module. The latter is supposed to contain classes only which are useful for implementing protocol adapters while the former will be useful for implementing both (plain) services and protocol adapters. This way we will be able to more precisely define the service component's (transitive) dependencies, e.g. protocol adapters will have a dependency on the Infinispan based client while the Authentication server won't. In a further step, the service-base and adapter-base modules will then be refined to …
> Move HTTP adapter base classes to HTTP adapter module

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/KafkaApplicationClientFactory.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/DownstreamMessageConsumer.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/EventConsumer.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaDownstreamMessage.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/TelemetryConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumerKafkaMockConsumerTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumerMockitoTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/TestConsumer.java
This change aims to reduce the cases where the same Kafka record is consumed a second time.
If an error occurs while processing a message or when the consumer is stopped, the offsets for the already processed messages from the current batch are now committed. This is to prevent all messages from being processed again. Especially in case of errors during message processing, the same messages could otherwise be consumed again and again.
> [#8] Commit offsets when the Kafka consumer is interrupted.

- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
- client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
- client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoClientUnitTestHelper.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/amqp/RequestResponseClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedInternalCommandConsumer.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericSenderLink.java
- core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/AbstractRequestResponseEndpoint.java
- test-utils/client-test-utils/src/main/java/org/eclipse/hono/client/amqp/test/AmqpClientUnitTestHelper.java
This serves as an extra safeguard against using a link whose underlying connection was already disconnected.
Relates to #2472.
> Also check connection when checking for open link

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionsManager.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
As a preparation for #2064, the command subscription handling in the MQTT adapter has been refactored. 
Invalid subscriptions will now log an error entry in the tracing span, tracing when unsubscribing has been improved and proper handling of duplicate subscriptions (with same device id but different QoS or endpoint id) has been implemented. 
Also, an MQTT connection getting closed before the SUBACK can be sent will now prevent an event notification to be sent downstream.
> Improve MQTT subscription handling

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
The abstract MQTT adapter base class has been refactored, moving all `MqttEndpoint` related methods into a new `MqttDeviceEndpoint` inner class. This means the parameters related to the MQTT device connection don't have to be passed around in these methods anymore. This also makes it easier to add further MQTT device connection related fields (e.g. for #2064).
As a next step, the `MqttDeviceEndpoint` class could be moved out of the abstract MQTT adapter base class. 
This would then however require some visibility changes in `AbstractProtocolAdapterBase`, making methods public instead of protected.
> Refactor MqttEndpoint related methods

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/TrustedCertificateAuthority.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/TenantManagementServiceImpl.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantService.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/Tenants.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
Extend Device Registry Management API specification to include an optional identifier for a tenant's trust anchor.
> [#2456] Include an optional ID for a tenant's trust anchor

- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
This PR contains a Kafka based command response sender which enables the protocol adapters to forward command responses via the configured Kafka cluster. Also protocol adapters can be configured now to use this Kafka based command router.
> [2273] Support sending command response via Kafka

- site/build-site.bat
- site/build-site.sh
A recent change in the build scripts for the documentation causes that on each build images of the Hugo theme are deleted. While this step makes sense in the Jenkins pipeline, it is not necessary for local builds. Because the images are simply deleted from a directory under version control, this is always displayed as changes in my IDE, which is unnecessarily annoying. So just stopping to delete the files in the local builds is the simplest solution.
> Do not delete images from Hugo theme when building docs locally

- core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
- core/src/test/java/org/eclipse/hono/util/ResourceIdentifierTest.java
This is for #2495:
First commit:
Trying to create a `ResourceIdentifier` with an empty endpoint segment caused an NPE.
Since I don't see a use case for supporting an empty endpoint segment in `ResourceIdentifier` objects, I've now made it explicit that the endpoint segment must not be empty.
Therefore, an `IllegalArgumentException` is now thrown instead, documented in the javadocs of the factory methods.
Places where a `ResourceIdentifier` gets created from a String should be adapted now, replacing the parameter String not-null-or-empty check with `ResourceIdentifier.isValid(resource)`. I'll see to that after this PR gets merged.
2nd commit:
Refactor ResourceIdentifier constructors/factory methods: Using only one constructor now, making fields final. Also improving javadocs.
>  [#2495] Fix ResourceIdentifier NPE in case of empty endpoint

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/MultiMessagingSenders.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/MultiMessagingSendersTest.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx-base/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- test-utils/adapter-base-test-utils/src/main/java/org/eclipse/hono/adapter/test/ProtocolAdapterTestSupport.java
This PR belongs to #2402. It adds support for selecting the messaging system at the tenant level. 
Protocol adapters start AMQP-based event senders *and* Kafka-based event senders (if the configuration for both is provided). At the tenant, a new property is added to select which messaging to use.
> [#2402] Use the messaging system configured on the tenant

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaMessageHelper.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaMessageHelperTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumerKafkaMockConsumerTest.java
This PR adds support for time-to-live (TTL) headers to the Kafka-based clients. It fixes #2477.
> [#2477] Support time-to-live (TTL) header in Kafka-based clients

- clients/application/src/main/java/org/eclipse/hono/application/client/DownstreamMessage.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- core/src/main/java/org/eclipse/hono/util/TimeUntilDisconnectNotification.java
This is done as preparation for adapting ITs to Kafka. When ITs are based upon DownstreamMessage, `DownstreamMessage#getTimeUntilDisconnectNotification ` can be used to obtain the time until disconnect notification instead of `TimeUntilDisconnectNotification.fromMessage(msg)`.
> #2469 Adding getTimeUntilDisconnectNotification() to DownstreamMessage

- adapter-base/src/main/java/org/eclipse/hono/adapter/MultiMessagingSenders.java
Fixes a wrong name of a private method inside the class `MultiMessagingSenders` (it is not only for event senders but also for other senders).
> Fix internal method name in MultiMessagingSenders

- cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractHonoClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSender.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClientTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application/pom.xml
- clients/application/src/main/java/org/eclipse/hono/application/client/ApplicationClient.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaMessageHelper.java
- core/src/main/java/org/eclipse/hono/util/MessageHelper.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
This PR is for #2478. It extends the northbound application client to support sending commands asynchronously.  Support for sending one-way/synchronous commands and consuming command responses will be addressed in the next PRs. 
This PR has been implemented on top of code from PR #2497 and that should be merged first.
> [#2478] Extend the northbound application client to support sending commands asynchronously

- bom/pom.xml
- clients/adapter-kafka/pom.xml
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/telemetry/kafka/KafkaBasedEventSenderTest.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/telemetry/kafka/KafkaBasedTelemetrySenderTest.java
- test-utils/kafka-test-utils/pom.xml
- test-utils/kafka-test-utils/src/main/java/org/eclipse/hono/kafka/test/KafkaClientUnitTestHelper.java
- test-utils/pom.xml
Pull up Kafka test helper class so that it can be used for the Kafka based north bound application tests
> [#2478] Pull up Kafka test helper class for reuse

- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/CommandContext.java
- client/src/main/java/org/eclipse/hono/client/impl/AdapterInstanceCommandHandler.java
- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandContext.java
- core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/AbstractRequestResponseEndpoint.java
Use a handler that will be invoked when a AMQP message delivery of a received message gets updated from the remote peer before the local receiver updates the delivery.
A corresponding scenario would be that the remote sender of the message only waits a limited time for the disposition update and afterwards aborts (i.e. releases) the delivery from the sender side. With the handler here, the receiver can get notified of such a delivery update.
> Handle received message delivery getting updated from remote

- adapter-base/pom.xml
- adapters/pom.xml
- client-device-connection-infinispan/pom.xml
- client/pom.xml
- clients/pom.xml
- core/pom.xml
- pom.xml
- service-base/pom.xml
- services/pom.xml
- site/documentation/content/dev-guide/building_hono.md
The build has been extended to support running the JaCoCo plugin for
gathering code coverage information when running unit tests.
By default, the plugin will be skipped. It can be activated by means of
setting the "jacoco.skip" Maven property to value "false".
This might be helpful for some downstream consumers of our code who need
some "proof-of-quality". We can also use this data to (sporadically)
asses whether we have some "blind spots" in our code that should be
tested more thoroughly.
> Support gathering of code coverage information

- tests/src/test/java/org/eclipse/hono/tests/AssumeMessagingSystem.java
- tests/src/test/java/org/eclipse/hono/tests/AssumeMessagingSystemCondition.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryJmsQoS1IT.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
This is a further preparation for migrating the ITs to Kafka.
Some tests do not make sense to be executed when ITs are run with Kafka as the Kafka "protocol" does not offer the same functionality as AMQP 1.0. 
For instance, it is not possible to determine if a consumer has actually processed the message (testUploadMessageFailsForNoConsumer) or there is no delivery state to be updated (testUploadQos1MessageFailsIfDeliveryStateNotUpdated).
The tests for the JMS client of Apache Qpid do also not make sense in a Kafka context as far as I can judge.
The implemented annotation can be used to skip those tests automatically when the Kafka profile is set.
> #2469 Making test execution messaging system specific by annotation

- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/AmqpApplicationClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSender.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSenderTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- test-utils/client-test-utils/src/main/java/org/eclipse/hono/client/amqp/test/AmqpClientUnitTestHelper.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
This PR extends northbound application client to send one way commands.
> [#2478] Extend northbound application client to send one way commands

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/DeviceDisabledOrNotRegisteredException.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/GatewayDisabledOrNotRegisteredException.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/TenantDisabledOrNotRegisteredException.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- client/src/main/resources/org/eclipse/hono/client/ServiceInvocationException_messages.properties
- site/documentation/content/user-guide/mqtt-adapter.md
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
This PR is to close the MQTT connection when one of the following terminal errors occur.
* The adapter is disabled for the tenant that the client belongs to.
* The device is disabled or not registered (provided that the device is not connected via a gateway).
* The gateway is disabled or not registered.
* The tenant is disabled or does not exist.
> [#2064] Close MQTT connection on terminal errors

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- client/src/test/java/org/eclipse/hono/client/impl/DisconnectHandlerProvidingConnectionFactory.java
- client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
This removes the unused 'disconnectHandler' param of the private connect() method.
Also makes sure that a disconnect doesn't cause the notifyDisconnectHandlers() method to be invoked twice if no reconnect attempt shall be done.
Preparation for  #2521.
> HonoConnectionImpl: Remove unused code, prevent duplicate disconnect handler invocation

- core/pom.xml
- core/src/main/java/org/eclipse/hono/connection/impl/ConnectionFactoryImpl.java
- core/src/test/java/org/eclipse/hono/connection/impl/ConnectionFactoryImplTest.java
This fixes #2543:
A failed open handler result now closes the connection, preventing the connectionResultHandler from getting invoked twice.
> [#2543] Prevent connectionResultHandler getting invoked twice

- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/AmqpMessageContextConditionalVerifier.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/EventAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/EventCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
This PR adapts the telemetry and event based integration tests to the new `ApplicationClient` interface so that they can be executed with an AMQP 1.0 network _or_ Kafka.
All Command and Control specific tests are skipped for the Kafka profile. The goal is to have the Kafka ITs in a state where they can be executed successfully. 
Skipped Tests:
- CommandAndControlAmqpIT:*
- CommandAndControlMqttIT:*
- CoapTestBase:testUploadMessagesWithTtdThatReplyWithCommand
- CoapTestBase:testUploadMessagesWithTtdThatReplyWithOneWayCommand
- HttpTestBase:testHandleConcurrentUploadWithTtd
- HttpTestBase:testUploadMessagesWithTtdThatReplyWithCommand
- HttpTestBase:testUploadMessagesWithTtdThatReplyWithOneWayCommand
As soon as the Command and Control implementation is complete those tests can be …
> #2469 Adapt integration tests for telemetry and events to Kafka

- .github/workflows/ci.yml
- site/documentation/content/admin-guide/command-router-config.md
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/readme.md
Also use Command Router per default in the integration tests.
This fixes #2535.
> [#2535] Remove "tech preview" status of Command Router

- adapter-base-quarkus/pom.xml
- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/KafkaRuntimeConfigProducer.java
- adapter-base-quarkus/src/test/java/org/eclipse/hono/adapter/quarkus/KafkaRuntimeConfigProducerTest.java
- adapter-base-quarkus/src/test/resources/application.yaml
- adapters/amqp-vertx-quarkus/src/main/resources/reflection-config.json
- adapters/coap-vertx-quarkus/src/main/resources/reflection-config.json
- adapters/http-vertx-quarkus/src/main/resources/reflection-config.json
- adapters/lora-vertx-quarkus/src/main/resources/reflection-config.json
- adapters/mqtt-vertx-quarkus/src/main/resources/reflection-config.json
This fixes #2490. It adds support for messaging with Kafka to the Quarkus-based protocol adapters. It uses the Quarkus Kafka Extension which provides two features:
a) it parses the Kafka configuration and b) it provides fixes to the original Kafka client that are necessary to run it in GraalVM. The class `KafkaRuntimeConfigProducer` overwrites the config parsing so that it supports the Hono-specific prefixes for the Kafka configuration.
Initially, I implemented a custom Quarkus extension that parses Hono's Kafka configuration properties and provides them as beans. When testing it in native images, I found that the Kafka client needs a couple of fixes to run in GraalVM. Instead of implementing them on our own, we can simply include `quarkus-kafka-client` which already contains the fixes. …
> [#2490] Support Kafka messaging in Quarkus based Adapters.

- clients/adapter-amqp/pom.xml
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandRouterClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedDeviceConnectionClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClient.java
- clients/amqp-common/pom.xml
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractRequestResponseServiceClient.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/RequestResponseClient.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/AbstractRequestResponseServiceClientTest.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/RequestResponseClientTest.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/SimpleRequestResponseResult.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSender.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClient.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClientTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
This PR contains new methods added to the `ApplicationClient` which enables the client to send a command, wait and receive a response for that command. In order to keep this PR short and easier for review, it contains only AMQP 1.0 based implementation of these API methods. Kafka based implementation will be provided in the consecutive PR.
> [#2478] Part 1: Extend ApplicationClient to send commands and wait for command responses

- adapter-base-quarkus/src/test/java/org/eclipse/hono/adapter/quarkus/KafkaRuntimeConfigProducerTest.java
Refactoring of test `KafkaRuntimeConfigProducerTest`: uses AssertJ and removes duplicate assertions.
> [#2490] Improve unit test KafkaRuntimeConfigProducerTest

- clients/adapter-amqp/src/test/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedInternalCommandConsumerTest.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumerTest.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandHandlerWrapper.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandHandlers.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandRouterCommandConsumerFactory.java
Command processing in the adapters needs to be done in the correct vert.x context. Otherwise there will for example be concurrency issues in the AMQP adapter concerning the AMQP connection to the device used for sending the command. 
Since there is only *one* KafkaBasedInternalCommandConsumer instance where commands are received, command handlers explicitly need to be run on the correct context. (That isn't a problem with the  ProtonBasedInternalCommandConsumer since its (multiple) instances use the same context as the corresponding adapter verticles.)
> Run command handler in correct vert.x context

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- site/documentation/content/user-guide/amqp-adapter.md
- site/homepage/content/release-notes.md
This PR closes the issue #2545.
Now the _AMQP_ adapter closes the connection to the device if one of the following terminal errors occur.
* The adapter is disabled for the tenant that the client belongs to.
* The authenticated device or gateway is disabled or not registered.
* The tenant is disabled or does not exist.
>  [#2545] Close AMQP device connection on terminal errors

- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/KafkaRuntimeConfigProducer.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- tests/src/test/resources/commandrouter/application.yml
Using "hono.kafka" instead of "hono.command.kafka" follows the convention used in the protocol adapters.
> Use "hono.kafka" config prefix in Command Router

- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
Increasing the test setup timeout by 2s to accomodate for the extra time for creation/propagation of Kafka topics created during setup.
> Increase test setup timeout for Kafka integration tests

- service-base-spring/src/main/java/org/eclipse/hono/service/spring/AbstractApplication.java
- service-base-spring/src/main/java/org/eclipse/hono/service/spring/AbstractBaseApplication.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/Application.java
The old name of that method in AbstractBaseApplication is a relict from when the method was called after deployServiceVerticles() in the run() method. But deployServiceVerticles() is now only contained in the AbstractApplication subclass.
> Rename postRegisterServiceVerticles() to postDeployVerticles()

- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/RequestResponseClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSender.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClient.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application/src/main/java/org/eclipse/hono/application/client/ApplicationClient.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
Currently the method defined in `ApplicationClient` to send a command and receive a response returns an object of type `Future<BufferResult>`. `org.eclipse.hono.util.BufferResult` is not _protocol agnostic_ as it's constructor takes `ApplicationProperties` as one of the parameters and so it's parent class `RequestResponseResult`. 
One approach is to make it protocol agnostic by replacing with `Map<String, Object>` or `org.eclipse.hono.application.client.MessageProperties` and updating all the classes that use it.
On the other hand, could also use `DownstreamMessage<MessageContext>` instead of `BufferResult` as we already do in case of command response consumer in the north-bound side. IMHO it suits better than the `BufferResult` as command response is also a downstream message and also …
> [#2478] Prepare for Kafka based north-bound API implementation to send commands and receive responses

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigProperties.java
This PR adds a Kafka based implementation to send commands and receive responses by the north bound side.
In order keep the PR small, the other PR #2571 needs to be merged first.
> [#2478] Add kafka based implementation to send commands and receive responses by the north bound side

- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClient.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
The JavaDoc of the `sendCommand()` methods in the class `CommandSender` defines that the returned future fails if the response does not contain a status code with 2xx. This commit adds that the status code is taken into account in `KafkaBasedCommandSender`.
> Respect status when sending synchronous command via Kafka

- client/src/main/java/org/eclipse/hono/client/CommandClient.java
- client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClient.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClientTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
This conforms to the C&C API definition that the message body of a command response with an error status MAY contain a detailed description of the error that occurred.
> Use payload of error command response as exception message

- cli/README.md
This adds a README file to the module `cli` with some example commands. This makes it easier to find the right commands and parameters for receiving messages and sending commands, especially with the new variants for Kafka-based messaging.
> Add README file with usage examples to the CLI module

- client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/RequestResponseClient.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/RequestResponseClientTest.java
- site/homepage/content/release-notes.md
> [#2615] Fix sample.timeout() being invoked for each request

- examples/hono-client-examples/pom.xml
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleConstants.java
- examples/hono-client-examples/src/main/resources/logback.xml
- site/documentation/content/dev-guide/java_client_consumer.md
This replaces the legacy northbound client (`ApplicationClientFactory`) in the module `hono-example-client` with the new client (`ApplicationClient`).
> Replace legacy northbound client with new interface in example application

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandContext.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandSender.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
This is for #2480:
This is needed because records with an offset smaller than one already received get skipped in the target protocol adapter (see #2596).
Records handled in the Command Router `mapAndDelegateIncomingCommandMessage` method may overtake each other because determining the target protocol adapter instance may involve a different number of data grid requests and therefore may vary in duration.
> [#2480] Ensure command records get routed in the original order

- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandSender.java
- clients/adapter-kafka/src/test/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandConsumerTest.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaRecordHelper.java
This is for #2480:
After a command router has crashed (via a hard kill, not properly closing the Kafka consumer, so that last partition offsets aren't committed), some command records may get sent again on the internal topic.
This change here skips these records in the consumer that reads from this topic by keeping track of the already handled offsets concerning the original tenant-based command topic.
> [#2480] Skip duplicate command records

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImplTest.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AbstractAtLeastOnceKafkaConsumer.java
This is for #2623.
Makes sure the created Kafka consumers get stopped when the `KafkaApplicationClient` is stopped.
This behaviour is analogeous to closing a `ProtonBasedApplicationClient`, where by closing the underlying AMQP connection all receivers are also stopped.
> [#2623] Close created Kafka consumers when client is stopped

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CertificateDeviceResolver.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceInfoSupplier.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/PskDeviceResolver.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
Adapt callback custom argument from String to AdditionalInfo to support
both PSK and x509.
Introduce DeviceInfoSupplier as common callback for PSK and x509.
> Add dtls-x509 support for coap-adapter.

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumerHelper.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
This is for [#2480].
This serves as a preparation for adding manual offset commits for the Kafka consumer used in the Command Router.
A `HonoKafkaConsumer` class has been introduced here, extracted from the existing code in the `KafkaBasedCommandConsumerFactoryImpl`.
In a subsequent PR, a `ManualOffsetCommitKafkaConsumer` subclass shall be introduced. Preparations for that, including usage of a workaround (using reflection) to allow doing synchronous offset commits when partitions are revoked, are included here.
> [#2480] Refactor Command Router Kafka classes

- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
Any device registration operation first checks if the given tenant exists or not
using tenant information service. Currently the device registry implementations
use a `NoopTenantInformationService` as there is no tenant information bean is
exposed in their `ApplicationConfig`. This has been fixed now.
> Expose tenant information service needed for tenant existence check in device registry

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumerHelper.java
- clients/kafka-common/src/main/resources/META-INF/native-image/org.eclipse.hono/hono-client-kafka-common/reflection-config.json
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumerTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumerTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/KafkaMockConsumer.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
This is for #2480.
This adds an extended HonoKafkaConsumer that automatically commits partition offsets corresponding to the latest record per partition whose (asynchronous) processing has been marked as completed (provided all its preceding records are also completed).
This consumer is used for receiving commands in the Command Router.
In contrast to the default `enable.auto.commit` behaviour, identical offsets are skipped during successive commits. (They are recommitted after a certain time to prevent them from reaching their retention time.) This helps in case a corresponding partition just got deleted. Not trying to commit the offset then means the consumer won't block/retry for a long time in this case - see https://github.com/eclipse/hono/issues/2623#issuecomment-824906383.
> [#2480] Implement and use Kafka consumer with own auto-commit

- clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClient.java
- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisioner.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/DefaultTenantInformationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/NoopTenantInformationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/TenantInformationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioning.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AutoProvisionerTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/AutoProvisioningTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
For more details refer to the [discussion thread](https://github.com/eclipse/hono/pull/2647#discussion_r628183627).
* `TenantInformation.getTenant(...)` returns a result that contains `Tenant` instead of `TenantObject`.
* `AutowiredTenantInformationService` internally makes use of `TenantManagementService` instead of `TenantService`.
> [#2272] Refactor tenant information service

- service-base/src/main/java/org/eclipse/hono/service/http/ComponentMetaDataDecorator.java
- service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
- service-base/src/main/java/org/eclipse/hono/service/http/TracingHandler.java
- service-base/src/main/java/org/eclipse/hono/service/http/WebSpanDecorator.java
- service-base/src/test/java/org/eclipse/hono/service/http/HttpUtilsTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpointTest.java
When the HTTP adapter receives a request with a URI that contains illegal characters, there are 4 ERROR log entries created each time, all from places in the code where either a log entry or tracing span output gets written (in `ComponentMetaDataDecorator` and `DefaultFailureHandler`).
Example:
````
ERROR io.vertx.core.http.impl.HttpServerRequestImpl Failed to create abs uri
java.net.URISyntaxException: Illegal character in query at index 20: /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21
at java.base/java.net.URI$Parser.fail(Unknown Source)
at java.base/java.net.URI$Parser.checkChars(Unknown Source)
at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
at java.base/java.net.URI$Parser.parse(Unknown Source)
at …
```
> Prevent ERROR logs for requests with invalid URI

- core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
This fixes a potential NPE in `HonoProtonHelper.isLinkOpenAndConnected`.
It occurs for example when a command message got sent to an AMQP device and there is a timeout waiting for the disposition update, while the transport of the underlying AMQP connection already got closed (with the AMQP link still locally marked as open however). The NPE in that case leads to the command message not getting released.
````
java.lang.NullPointerException: null
at org.eclipse.hono.util.HonoProtonHelper.isLinkOpenAndConnected(HonoProtonHelper.java:183)
at org.eclipse.hono.adapter.amqp.VertxBasedAmqpProtocolAdapter.lambda$onCommandReceived$65(VertxBasedAmqpProtocolAdapter.java:998)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:923)
````
> AMQP adapter: Fix command not getting released in case device already disconnected

- site/homepage/content/release-notes.md
This adds the automatic schema creation feature of the JDBC-based device registry to the release notes.
> [#2587] Add schema creation to release notes.

- adapters/base-spring/pom.xml
- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- services/command-router/pom.xml
- services/device-connection/pom.xml
- services/device-registry-file/pom.xml
- services/device-registry-jdbc/pom.xml
- services/device-registry-mongodb/pom.xml
This is done via the added `jaeger-micrometer` dependency.
This includes for example `jaeger_tracer_reporter_spans_total` metrics. Analyzing such metrics with value `dropped` can help in determining whether the reporter max queue size (`JAEGER_REPORTER_MAX_QUEUE_SIZE` env variable, default 100) should potentially be increased.
> Enable reporting of jaeger client metrics

- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
Includes update of `org.apache.thrift:libthrift` from `0.13.0` to `0.14.1` (includes fix for CVE-2020-13949).
> Update Jaeger to 1.6.0

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
The protocol adapter AMQP consumers on the internal command address will now only be used if the AMQP consumer is actually configured.
Needed for a setup that only uses a Kafka messaging network.
> Make the AMQP network config non-mandatory in the adapters

- site/documentation/content/api/management/device-registry-v1.yaml
- site/documentation/layouts/shortcodes/swagger.html
- site/documentation/static/css/hono.css
- site/homepage/content/getting-started/index.md
Fix sandbox URL in [management API swagger UI](https://www.eclipse.org/hono/docs/api/management/) and make it obvious that the "Try it out" button refers to the sandbox. Also hide the "Try it out" button for non-stable Hono versions.
> Update Sandbox URL in API docs, document "try it out" feature

- site/homepage/content/release-notes.md
This adds to the release notes that the CLI and the example application now support Kafka.
> Add Kafka support in CLI and example application to release notes.

- service-base-quarkus/pom.xml
- service-base-quarkus/src/main/resources/META-INF/native-image/org.eclipse.hono/hono-service-base-quarkus/reflection-config.json
Jaeger tracing currently doesn't work when using quarkus-native images and a jaeger sampling configuration that uses the sampling strategies defined in the Jaeger Collector component (i.e. using the RemoteControlledSampler).
This seems caused by the reflection used in conjunction with the `io.jaegertracing.internal.samplers.HttpSamplingManager` class.
There, a `SamplingStrategyResponse` object is deserialized from the JSON response using gson, which makes use of reflection to do so. That means that, at least with the current `quarkus-jaeger` code, a reflection config has to be defined in places where the JaegerTracer is used (see also https://github.com/quarkusio/quarkus/issues/10402#issuecomment-845717069).
This PR adds that. 
Hope would be that …
> Fix jaeger RemoteControlledSampler not working in quarkus native images

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractAutoProvisioningEventSender.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/DeviceKey.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/EdgeDeviceAutoProvisioner.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/EdgeDeviceAutoProvisionerTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
* Helper methods to send auto-provisioned events have been pulled
  up to a new `AbstractAutoProvisioningEventSender` for reuse thereby
  preparing for the issue #2665.
* Edge device auto-provisioning doesn't require tenant information
  service anymore but rather takes a tenant instance as an argument
  which is provided by the `AbstractRegistrationService`. The code has
  also been optimised so that the `AbstractRegistrationService`
  now uses `getTenant()` instead of `tenantExists()` to check if a tenant
  exists and also passes this tenant instance as an argument to the
  auto-provisioning helper method.
* `AutoProvisioner` has been renamed to `EdgeDeviceAutoProvisioner` to suit
  the actual purpose of that class and also the constructor has been
  adapted to replace the various …
> [#2265] Refactor auto-provisioning of edge devices

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/limiting/MemoryBasedConnectionLimitStrategy.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/limiting/MemoryBasedConnectionLimitStrategyTest.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- core/src/main/java/org/eclipse/hono/config/ServerConfig.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractServiceApplication.java
- services/auth-quarkus/src/main/java/org/eclipse/hono/authentication/quarkus/Application.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/mqtt/application.yml
The protocol adapters use the MemoryBasedConnectionLimitStrategy to
determine the number of connections that can be established with devices
based on the memory available to the adapter process.
The adapters currently assume to be running on a standard Java VM and
therefore assess the minimum amount of memory required for running to be
100MB (excluding memory allocated for device connections).
When using the Quarkus based native images, the memory footprint of the
adapters is significantly lower. This is now reflected in the MQTT and
AMQP adapters which first check the type of VM they are running on and
then adapt the minimum required memory accordingly.
Fixes #2675
> Adapt connection limit strategy to VM being used

- cli/src/main/resources/application.yml
In current Spring Boot versions the property "spring.profiles" is deprecated and should be replaced by "spring.config.activate.on-profile". 
This PR does that change in the application.yml of the CLI.
> Update Spring Boot config in CLI.

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
Most notably catch an IllegalStateException thrown by MqttEndpointImpl.publish() if the connection is
already disconnected.
Up to now this was misleadingly written as an "Connection not accepted yet" error in the trace, with such an exception being logged:
````
WARN org.eclipse.hono.tracing.TracingHelper An unexpected error occurred!
java.lang.IllegalStateException: Connection not accepted yet
at io.vertx.mqtt.impl.MqttEndpointImpl.checkConnected(MqttEndpointImpl.java:734)
at io.vertx.mqtt.impl.MqttEndpointImpl.write(MqttEndpointImpl.java:712)
at io.vertx.mqtt.impl.MqttEndpointImpl.publish(MqttEndpointImpl.java:458)
at io.vertx.mqtt.impl.MqttEndpointImpl.publish(MqttEndpointImpl.java:440)
at io.vertx.mqtt.impl.MqttEndpointImpl.publish(MqttEndpointImpl.java:50)
at …
```
> Catch exception publishing command to MQTT device

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/RegistrationLimits.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbBasedRegistrationConfigProperties.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/documentation/content/user-guide/mongodb-based-device-registry.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
The Mongo DB based registry now supports enforcement of registration
limits configured at the tenant level. In particular, the maximum number
of devices and the maximum number of credentials per device can be set
in a tenant's registration-limits property.
Fixes #2626
> Add support for limiting registration entries at tenant level

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx-base/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapErrorResponse.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/TelemetryResourceTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- client/src/main/java/org/eclipse/hono/client/ServiceInvocationException.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedCommandContext.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedInternalCommandSender.java
- clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/command/amqp/ProtonBasedLegacyCommandContextWrapper.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedCommandContext.java
- clients/adapter-kafka/src/main/java/org/eclipse/hono/adapter/client/command/kafka/KafkaBasedInternalCommandSender.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/CommandContext.java
- clients/adapter/src/main/java/org/eclipse/hono/adapter/client/command/InternalCommandSender.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
This is for #2661.
This is a preparation for letting the KafkaBasedCommandContext send Command Response messages in the release/modify/reject methods. The new Throwable param allows an error message and an error status code to be given.
In the first commit:
Move/rename the `AbstractProtocolAdapterBase#getClientFacingErrorMessage()` method to the `ServiceInvocationException` class.
Also fix setting of an error message in CoapErrorResponse.
> [#2661] Use Throwable param in CommandContext methods

- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImplTest.java
This addresses #2705
Actually, there has not been an endless loop as far as I can tell but the list of tenant IDs to re-activate routing for had grown larger and larger over time ...
> Prevent endless loop when re-activating command routing

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/MessagingClients.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClient.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumerTest.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueueTest.java
This is a preparation for #2661, passing a `CommandResponseSender` to the `KafkaBasedCommandContext` constructor.
In a followup commit, the sender will then get used in the release/modify/reject methods to send delivery error command response messages.
> [#2661] Pass CommandResponseSender to KafkaBasedCommandContext

- adapter-base/pom.xml
- adapter-base/src/test/java/org/eclipse/hono/adapter/metric/MicrometerBasedMetricsTest.java
- adapters/pom.xml
- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- service-base/src/main/resources/org/eclipse/hono/service/metric/legacy.properties
- services/pom.xml
- site/documentation/content/admin-guide/monitoring-tracing-config.md
- site/documentation/content/api/Metrics.md
- site/homepage/content/release-notes.md
The Maven profiles for compiling in support for exporting collected
metrics to a Graphite or InfluxDB back end have been removed as there
doesn't seem to be any demand for it.
Fixes #2695
> Remove support for exporting metrics to Graphite or InfluxDB

- client/src/main/java/org/eclipse/hono/client/ServiceInvocationException.java
- client/src/test/java/org/eclipse/hono/client/ServiceInvocationExceptionTest.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/devices/HonoHttpDevice.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceAndGatewayAutoProvisioner.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DeviceAndGatewayAutoProvisionerTest.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedCredentialsClient.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedRegistrationClient.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedRequestResponseClient.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedTenantClient.java
We have many `exception instanceof ServerErrorException` and `exception instanceof ClientErrorException` conditions in the code.
These wouldn't match for plain `ServiceInvocationException` instances. Therefore, this PR makes `ServiceInvocationException` abstract.
I've also removed 3 constructors with tenant param in order to reduce the overall number of constructors.
> Make ServiceInvocationException abstract

- client/src/main/java/org/eclipse/hono/client/CommandResponse.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandAlreadyProcessedException.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandResponse.java
- core/src/main/java/org/eclipse/hono/util/CommandConstants.java
- tests/src/test/java/org/eclipse/hono/tests/GenericKafkaSender.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
This is for #2661.
In the release/modify/reject methods of the `KafkaBasedCommandContext`, a Kafka error command response message will be published now, provided the original command is a request/response command with a correlation id.
> [#2661] Send Kafka command response message on delivery error

- site/documentation/content/api/command-and-control-kafka/index.md
- site/documentation/content/api/command-and-control/index.md
This is for #2661:
Adds documentation for the new feature that the Command Router or a protocol adapter sends an error command response message if a Kafka request/response command message couldn't be delivered to the device (or can't be processed by it).
Also improves the documentation of the AMQP command & control spec regarding the `released` and `rejected` delivery outcomes.
> [#2661] Document Hono sending Kafka error command responses

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/Cache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandRouterClient.java
- clients/command-amqp/src/test/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandRouterClientTest.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterClient.java
- service-base/src/main/java/org/eclipse/hono/service/commandrouter/CommandRouterService.java
- service-base/src/main/java/org/eclipse/hono/service/commandrouter/DelegatingCommandRouterAmqpEndpoint.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- site/documentation/content/api/command-router/index.md
This fixes #2732.
The last known gateway of a device isn't set right away anymore. Instead, all such device-to-gateway mappings happening in a time frame of 400ms are sent to the Command Router as part of a batch request.
It is ensured that these requests don't exceed a certain size and not too many such requests are made at once.
> [#2732] Set last known gateway as part of batch request

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
This fixes #2741:
Fix `HonoKafkaConsumer#start()` getting completed before offset positions are reset (for "latest" reset strategy).
This might have caused records published right after the start() completion to not be read.
Also fix `start()` getting completed before the partition assignment is complete in case of topics that get auto-created during subscription. Again this might have caused records to not be read. Fixed by explicitly reading metadata for the subscription topics (and thereby triggering auto-creation if enabled) before the subscribe() invocation.
> [#2741] Fix HonoKafkaConsumer not consuming initial records

- bom/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
This is for #2745:
Also making sure that closing the consumer objects triggers handling of the lost partition assignment.
Also the other contained resources get closed on closing the `KafkaBasedCommandConsumerFactoryImpl` instance.
Added an integration test as well.
This doesn't reproduce the exact same scenario leading to the exception in #2745 (forcing a partition assignment to be moved from one consumer to another doesn't seem easy). Instead, this lets the relevant `KafkaCommandProcessingQueue.setCurrentlyHandledPartitions()` method also be invoked when closing the consumer - this was missing anyway. The integration test closes one consumer and afterwards adds a new one, all while command records are still being processed.
> [#2745] Fix handling of revoked Kafka partitions

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/tracing/KafkaTracingHelper.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedEventSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedTelemetrySender.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- tests/src/test/java/org/eclipse/hono/tests/GenericKafkaSender.java
Span names for sending messages downstream using Kafka are now the same as when using AMQP (not always "send message" anymore).
> Use specific tracing span names when publishing Kafka records

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandToBeReprocessedException.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueueTest.java
Related to  #2751:
Skips sending an error command response message in case command handling got cancelled because the topic partition assignment got revoked. In this case the command will be handled again by the other consumer that the topic partition got newly assigned to.
> Skip error command response if partition revoked

- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedInternalCommandConsumer.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandContext.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandHandlerWrapper.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandHandlers.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
This adds a `FOLLOWS_FROM` span reference from the "handle command" span in the command handling trace started in the Command Router to the span in the preceding trace where the command consumer was created in the protocol adapter.
This is only enabled for short-lived command consumers, i.e. those that get created in the HTTP/CoAP adapters for ttd requests.
Compared with the span reference added in  #2755, this is the link in the other direction.
> Improve Command Router C&C tracing

- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- services/device-registry-base/pom.xml
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/CryptVaultBasedFieldLevelEncryption.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/FieldLevelEncryption.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskSecret.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/PskSecretTest.java
- services/device-registry-mongodb/pom.xml
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/AbstractMongoDbBasedRegistryConfigProperties.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java
- site/documentation/content/admin-guide/mongodb-device-registry-config.md
- site/homepage/content/release-notes.md
- tests/src/test/resources/deviceregistry-mongodb/application.yml
- tests/src/test/resources/deviceregistry-mongodb/encryptionKeys.yml
The Mongo DB based registry has been extended to (transparently)
encrypt/decrypt pre-shared keys when writing/reading credentials to/from
the Mongo DB collection.
Fixes #2717
> Add support for encrypting PSKs in Mongo DB based registry

- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceDto.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDaoTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDaoTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDaoTest.java
The DAOs have been changed to keep an instance's original creation time
when updating the instance.
Fixes #2774
> Fix updating of status properties

- cli/src/main/java/org/eclipse/hono/cli/app/AbstractApplicationClient.java
- cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
- cli/src/main/resources/application.yml
- site/documentation/content/user-guide/amqp-adapter.md
- site/homepage/content/release-notes.md
- site/homepage/content/sandbox.md
I noticed a couple of properties that are set in the configuration file of the CLI component which set values that do not really match a recommended Hono setup. So, this PR does not resolve the issue #1486 and does not change the logic of the CLI. It is an intermediary step that updates some defaults.
The goal is to improve the comprehensibility of the file `application.yml` and thereby also the usability of the tool.
The main points are:
1. all usage instructions documented within the Hono project should behave as before
1. this PR does only change defaults for the profiles for the usage as a northbound client and not for the profiles `amqp-send` and `amqp-command`
1. one exception to the point above is the hostname. Which changes from localhost to the sandbox address in the southbound …
> Rework cli profiles

- bom/pom.xml
- legal/src/main/resources/legal/NOTICE.md
The actual wildfly elytron version used is `1.15.1.Final`.
> Fix wrong wildfly elytron version used in NOTICE file

- client-device-connection-infinispan-quarkus/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/quarkus/InfinispanRemoteConfigurationProperties.java
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/src/test/resources/commandrouter/clustered-cache/application.yml
- tests/src/test/resources/infinispan/hono-data-grid.xml
The Quarkus based variants of Hono's components now support configuring
the Hot Rod client with a key and/or trust store in order to enable TLS
connections and to authenticate using a client certificate.
Fixes #2789
> Add support for configuring a trust and key store in Device Connection Client

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
A MongoDB error will now be traced before mapping it to a ServerErrorException, so that the 'error.object' in the trace contains more info than just "org.eclipse.hono.client.ServerErrorException: Error Code: 500".
> Improve error tracing in MongoDB classes

- services/base-jdbc/src/main/java/org/eclipse/hono/service/base/jdbc/store/AbstractStore.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementSearchTenantsTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/Services.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/TenantManagementServiceImpl.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/TenantServiceTest.java
- services/device-registry-jdbc/src/test/resources/logback-test.xml
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
This is the first PR in a series to fix #2471
The registry implementations have been changed to return a JSON object
with an "error" property in response bodies for failed requests to the
"tenants" resources.
> Return proper error detail in tenants resource responses

- services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceManagementService.java
- site/homepage/content/release-notes.md
The MongoDb based DeviceManagementService erroneously removed the
original device registration when trying to register a new device using
the existing device's ID.
Fixes #2795
> Keep original registration when rejecting duplicate

- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDao.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- site/homepage/content/release-notes.md
The MongoDB based Credentials service implementation does not use the
existing index for finding credentials by tenant, auth-id and type.
Instead, all documents of the tenant are scanned one by one for matching
auth-id and type.
The credentials DAO has been changed to create another compund index on
the credentials array documents' auth-id and type fields which is then
used by Mongo DB to determine the (small) set of documents matching the
auth-id and type before comparing with the required tenant ID.
Fixes #2792
> Use index when finding credentials by type and auth-id

- services/device-registry-jdbc/pom.xml
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/CredentialsServiceImpl.java
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsApiTests.java
The (optional) client context provided by protocol adapters when
invoking the Credentials service's "get Credentials" operation is now
also being considered by the JDBC based service implementation.
Fixes #2310
> Support matching credentials against client context in JDBC based registry

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/util/Assertions.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementSearchDevicesTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/DeviceManagementServiceImpl.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/RegistryServiceTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
This is step 2 in a series of PR to fix #2471 
The registry implementations have been changed to return a JSON object
with an "error" property in response bodies for failed requests to the
"devices" resources.
> Return proper error detail in devices resource responses

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CredentialsManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/CredentialsManagementServiceImpl.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java
The registry implementations have been changed to return a JSON object
with an "error" property in response bodies for failed requests to the
"credentials" resources.
Fixes #2471
> Return proper error detail in credentials resource responses

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsServiceTestBase.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/JdbcBasedCredentialsServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
An error getting/parsing credentials in the device registry is currently not handled correctly, leading to an NPE like:
```
[vert.x-eventloop-thread-3] DEBUG o.e.h.d.s.c.AbstractCredentialsService - converting error to response
java.lang.NullPointerException: null
at org.eclipse.hono.deviceregistry.service.credentials.AbstractCredentialsService.lambda$get$1(AbstractCredentialsService.java:170)
at io.vertx.core.Future.lambda$compose$3(Future.java:368)
at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
at io.vertx.core.Future.lambda$otherwise$7(Future.java:540)
at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
at …
```
> Fix error-handling when getting credentials

- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
- core/src/main/java/org/eclipse/hono/util/KubernetesContainerUtil.java
- legal/src/main/resources/legal/NOTICE.md
For #2028:
With this PR, the adapter instance id format gets changed to `[pod_name]_[container_id]_[counter]` if running in Kubernetes.
> [#2028] Change adapter instance id format

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/AbstractMessageSenderConnectionEventProducer.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/ConnectionEventProducer.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/LoggingConnectionEventProducer.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/monitoring/HonoEventConnectionEventProducerTest.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx-base/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
This adds a `SpanContext` parameter to the methods of the `ConnectionEventProducer` interface.
This prevents `get Tenant by ID` spans in the AMQP/MQTT adapter with no parent span, where it is unclear just by looking at the tracing span to which overall operation/request this belongs to.
> Use SpanContext param in ConnectionEventProducer methods

- core/src/main/java/org/eclipse/hono/config/AuthenticatingClientConfigProperties.java
- core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/config/DeviceServiceProperties.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/config/TenantServiceProperties.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbBasedRegistrationConfigProperties.java
- site/documentation/content/admin-guide/jdbc-device-registry-config.md
- site/documentation/content/admin-guide/mongodb-device-registry-config.md
- site/homepage/content/release-notes.md
The MongoDB and JDBC based registries have been changed to allow for the
configuration of a regular expression that is used by the
PasswordCredential class to validate the authentication identifier (user
name). The regular expression is read from a System property by the
PasswordCredential class because it is instantiated by the Jackson
framework when unmarshalling a JSON string and I can currently not think
of any other way of passing it in.
Fixes #2559
> Make regex for validating hashed-password auth-ids configurable

- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
The (partial) unique index defined on the tenant's trusted-ca array is
defined using an $exists expression on the trusted-ca property.
This causes tenants with an empty trusted-ca array to also be indexed.
The Tenant class' trustedCertificateAuthorities field has been annotated
to only be included in its JSON representation when the collection is
not empty.
Fixes #2819
> Prevent tenants from having empty CA array

- deploy/src/main/sandbox/hono-values.yml
The Kafka server had returned a wrong IP address of the broker to clients. To fix this, the domain name of the sandbox is now explicitly set as the "loadBalancerIP" at the external service for Kafka. The "auto-discovery" of the load balancer IP at the Bitnami Helm chart is now disabled.
> Fix Kafka configuration on Sandbox

- site/documentation/content/user-guide/device-registry.md
The page "Device Registries" maintains the URL path that the file based registry used to have when it was the only supported implementation. It links to the current implementations but the JDBC based one was missing. This adds it.
> Documentation: Add the JDBC device registry to page "Device Registries".

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaRecordHelper.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaRecordHelperTest.java
- clients/telemetry-amqp/src/test/java/org/eclipse/hono/client/telemetry/amqp/ProtonBasedDownstreamSenderTest.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- site/homepage/content/release-notes.md
Fixes #2854.
Set a given "TTL" property (in seconds) in the Kafka-based downstream senders in the Kafka header in milliseconds. When evaluating if a consumed message is expired, interpret the TTL header as milliseconds.
> [#2854] Fix: TTL header in downstream messages with Kafka

- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandResponseSender.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommand.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandTest.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandResponse.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
- site/documentation/content/api/command-and-control-kafka/index.md
This fixes #2846:
Kafka command message headers with the `delivery-failure-notification-metadata` prefix are now adopted for the corresponding command response message sent in case of a command delivery failure.
> [#2846] Add support for defining failure-notification headers

- service-base-quarkus/src/main/resources/META-INF/native-image/org.eclipse.hono/hono-service-base-quarkus/reflection-config.json
Relates to changes made in #2856:
When deploying the IoT packages Hono helm chart using the 1.10 SNAPSHOT images, the Hono components don't start.
There is this exception in the logs:
```
java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class org.eclipse.hono.config.FileFormat
at io.smallrye.config.SmallRyeConfig.requireConverter(SmallRyeConfig.java:466)
at io.smallrye.config.ConfigMappingContext.getConverter(ConfigMappingContext.java:113)
at io.smallrye.config.ConfigMappingContext.lambda$getValueConverter$4(ConfigMappingContext.java:92)
at java.util.HashMap.computeIfAbsent(HashMap.java:1133)
at io.smallrye.config.ConfigMappingContext.getValueConverter(ConfigMappingContext.java:89)
at org.eclipse.hono.config.quarkus.GenericOptions-1742833832Impl.<init>(Unknown …
```
> [#2831] Fix Quarkus native 'No Converter registered' exception

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpoint.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpointTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/DeviceManagementServiceImpl.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/CredentialsDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/DeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedCredentialsDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDeviceDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceManagementService.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
The Registry Management API has been extended with an operation to
delete all devices (and their credentials) of a tenant.
Both the Mongo DB and the JDBC based registry implementations support
this operation.
Fixes #2793
> Support deletion of all devices of a tenant

- site/homepage/content/getting-started-kafka/index.md
This removes the unnecessary definition of the environment variable `KAFKA_IP` from the instructions for the sandbox.
> Improve Kafka messaging guide.

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
Setting a much lower 'max.poll.interval.ms' value may lessen the impact of UNKNOWN_TOPIC_OR_PARTITION errors while trying to commit offsets but may also cause "leave group" requests and rebalances if poll invocations get delayed for some reason. Therefore better to stick to the default 'max.poll.interval.ms' if no such value is configured explicitly.
> Use Kafka consumer 'max.poll.interval.ms' default

- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericSenderLink.java
- clients/telemetry-amqp/src/main/java/org/eclipse/hono/client/telemetry/amqp/ProtonBasedDownstreamSender.java
This fixes #2842.
The added `GenericSenderLink` field here is admittedly not very pretty. But this way of doing the logging in `GenericSenderLink` itself (as opposed to doing it in the invoking method like `sender.sendAndWaitForOutcome(msg, span).onFailure(t -> log.info("[...]"))`) means that more details  (e.g. delivery states) will be logged, providing more input for error analysis.
> [#2842] Log errors sending event messages on INFO level again

- .github/workflows/ci.yml
- tests/pom.xml
- tests/readme.md
The Spring Boot based Command Router component hasn't been tested in the GitHub Actions integration tests recently.
This PR changes the workflow to do that again.
In order to still use only 3 test runs and still test both AMQP and Kafka messaging using quarkus images (quarkus images being the default now in the IoT packages Hono deployment), I've changed one quarkus test run configuration to use a Spring Boot Command Router.
> Include Spring Boot Command Router in Github Actions workflow

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- bom/pom.xml
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/CachingKafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/KafkaClientMetricsSupport.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/KafkaMetricsConfig.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/KafkaMetricsOptions.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/MicrometerKafkaClientMetricsSupport.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/metrics/NoopKafkaClientMetricsSupport.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/metrics/MicrometerKafkaClientMetricsSupportTest.java
- service-base/pom.xml
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
This fixes #2848.
Kafka client metrics are now reported for the Kafka consumers and producers in the Hono protocol adapters and the Command Router.
Also includes an update of the micrometer version - in version 1.7.4 there are some fixes regarding Kafka metrics.
> [#2848] Add Kafka client metrics

- bom/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/HonoTopic.java
- clients/notification-kafka/pom.xml
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/KafkaBasedNotificationReceiver.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/KafkaBasedNotificationSender.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/NotificationTopicHelper.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/KafkaBasedNotificationReceiverTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/KafkaBasedNotificationSenderTest.java
- clients/notification/pom.xml
- clients/notification/src/main/java/org/eclipse/hono/notification/AbstractNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationConstants.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationReceiver.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationSender.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationTypeResolver.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/CredentialsChangeNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/LifecycleChange.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotification.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/CredentialsChangeNotificationTest.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotificationTest.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotificationTest.java
- clients/pom.xml
- services/device-registry-base/pom.xml
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/notification/NotificationFactory.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/notification/NotificationFactoryTest.java
- test-utils/kafka-test-utils/src/main/java/org/eclipse/hono/kafka/test/KafkaClientUnitTestHelper.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
This comes from the discussion in #2905. It contains:
- a Notification API for the Device Registry
- client implementations of the Device Registry Notification API for Kafka
The would put the AMQP based notification receiver in the existing module _hono-client-registry-amqp_.
This is an alternative to #2917.
> [#2837] Add Device Registry specific Notification API

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueue.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
Using ~[StickyAssignor](https://kafka.apache.org/27/javadoc/org/apache/kafka/clients/consumer/StickyAssignor.html)~ [CooperativeStickyAssignor](https://kafka.apache.org/27/javadoc/org/apache/kafka/clients/consumer/CooperativeStickyAssignor.html) as default partition assignment strategy for the command router Kafka consumer.
Compared to the default assignor (RangeAssignor) this produces a more balanced and sticky assignment.
> Set default Kafka command consumer assignment strategy

- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedInternalCommandConsumer.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
- clients/command/src/main/java/org/eclipse/hono/client/command/InternalCommandConsumer.java
* The creation of the internal command topic in Kafka is now coupled to the adapter's readiness check. If the creation
of that topic fails then the adapter is not set to ready.
* If the topic creation fails, then the internal command consumer retries to create that topic.
> [#2910] Handle internal command topic creation failure

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
This resolves #2925.
Along with this change, the `HonoKafkaConsumer#ensureTopicIsAmongSubscribedTopicPatternTopics` method could be changed so that the result Future is completed earlier (without waiting for the consumer rebalance). But this changes the timing in the integration tests (first command subscription finishes sooner, but first command takes longer to be received), so that adaptations are needed there. This will go in a separate PR then.
> [#2925] Use "earliest" offset reset strategy for Kafka command consumer

- adapter-base-quarkus/src/test/java/org/eclipse/hono/adapter/quarkus/QuarkusPropertyBindingTest.java
- adapter-base-quarkus/src/test/resources/application.yaml
- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientOptions.java
> [#2941] Fix handling of empty string Kafka config property values

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/EmbeddedCache.java
This prevents the following NPE:
```
INFO org.eclipse.hono.deviceconnection.infinispan.client.BasicCache  error trying to stop connection(s) to cache
java.lang.NullPointerException: null
at org.infinispan.commons.util.concurrent.NonReentrantLock.unlock(NonReentrantLock.java:83)
at org.infinispan.client.hotrod.counter.impl.NotificationManager.stop(NotificationManager.java:185)
at org.infinispan.client.hotrod.counter.impl.RemoteCounterManager.stop(RemoteCounterManager.java:89)
at org.infinispan.client.hotrod.RemoteCacheManager.stop(RemoteCacheManager.java:473)
at org.eclipse.hono.deviceconnection.infinispan.client.BasicCache.lambda$stop$0(BasicCache.java:90)
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.ja …
```
> Fix NPE when cache.stop() called more than once

- bom/pom.xml
- tests/pom.xml
Addresses #2949 
This release contains the fix for
https://issues.apache.org/jira/browse/DISPATCH-2259 and thus allows us
to re-enable SNI in the Auth Server.
I have created [CQ23833](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23833) for tracking the dependency.
> Upgrade to Qpid Dispatch Router 1.17.1

- adapters/base-quarkus/pom.xml
- adapters/base-spring/pom.xml
- services/base-quarkus/pom.xml
- services/base-spring/pom.xml
- services/command-router/pom.xml
- services/device-connection/pom.xml
Hono's components have been using the "vertx.cacheDirBase" system
property to set the directory where vert.x should store files resolved
via the class path.
With vert.x 4 the semantics of this property's value has changed which
might lead to incompatibilities (see
https://github.com/eclipse-vertx/vert.x/issues/4168).
The system property is no longer set for Hono components because the
default behavior is to create a subfolder in the JVM's tmpdir to which
the running process will (usually) have write access.
Fixes #2946
> Use default vert.x cache directory

- .github/workflows/ci.yml
- tests/pom.xml
The integration test profiles to be run on GitHub Actions have been
modified to better reflect the preferred setup. The deprecated Device
Connection service has been removed from the three profiles altogether
in order to reuse the slot for an additional setup with the Command
Router.
> Run ITs with preferred profiles

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-quarkus/src/test/java/org/eclipse/hono/adapter/quarkus/QuarkusPropertyBindingTest.java
- adapter-base-quarkus/src/test/resources/application.yaml
- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientOptions.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaClientOptionsTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/metrics/KafkaMetricsOptionsTest.java
- clients/kafka-common/src/test/resources/application.yaml
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
- site/homepage/content/release-notes.md
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
The Quarkus based components did not support the "defaultClientIdPrefix"
configuration property of the Kafka client.
Fixes #2960
> Pick up Kafka client ID prefix configuration property

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- site/documentation/content/api/command-and-control-kafka/index.md
- site/homepage/content/release-notes.md
> [#2945] Add tenant_id header for Kafka-based command response

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/AdapterInstanceStatusProvider.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
- core/src/main/java/org/eclipse/hono/util/CommandConstants.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/AdapterInstanceStatusService.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusService.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupService.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupServiceTest.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
This fixes #2901:
The `hono.command_internal.[adapterInstanceId]` Kafka topics associated with dead adapter instances are now deleted with some delay in the Command Router component.
This relies on the `KubernetesBasedAdapterInstanceStatusService` (as the only `AdapterInstanceStatusService` implementation right now) to recognize dead adapter instances.
> [#2901] Let command_internal topics be deleted in the Command Router

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
Correction regarding #2947:
If `stop()` was already called (e.g. from another verticle), the result Future shouldn't be failed.
Otherwise the whole verticle undeployment would be logged as failed:
```
ERROR  io.vertx.core.impl.DeploymentManager  Undeploy failed
io.vertx.core.impl.NoStackTraceThrowable: stop already called
```
> Don't let stop() fail if cache already stopped

- adapter-base-quarkus/pom.xml
- adapter-base/pom.xml
- client-device-connection-infinispan/pom.xml
- clients/kafka-common/pom.xml
- service-base-quarkus/pom.xml
- services/auth-base/pom.xml
When running unit-tests in modules that use the `quarkus-junit5` module, there is this log output:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/user/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.1.0.Final/slf4j-jboss-logmanager-1.1.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/user/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Slf4jLoggerFactory]
```
Log levels defined in `logback-test.xml` don't get applied.
> Fix test-logging in modules that use quarkus-junit5

- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedDownstreamMessage.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaDownstreamMessage.java
- clients/application/src/main/java/org/eclipse/hono/application/client/DownstreamMessage.java
- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- core/src/main/java/org/eclipse/hono/util/ResourceLimits.java
- core/src/main/java/org/eclipse/hono/util/TenantConstants.java
- core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
This is preparatory work for adding support for setting a TTL on downstream telemetry and command response messages (#2702).
> Prep work for supporting ttl on all message types

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientOptions.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaClientOptionsTest.java
- clients/kafka-common/src/test/resources/application.yaml
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
- site/homepage/content/release-notes.md
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
This fixes #2967. 
It reverts some changes of PR #2962. Property defaultClientIdPrefix is not intended to be changed by configuration.
> [#2967] Remove support for Kafka client ID prefix configuration property

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationOptions.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationProperties.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/QuarkusPropertyBindingTest.java
- client-device-connection-infinispan/src/test/resources/application.yaml
The [Infinispan HotRod client config](https://docs.jboss.org/infinispan/12.1/apidocs/org/infinispan/client/hotrod/configuration/package-summary.html) allows setting the ciphers to be used in the SSL handshake via the property `infinispan.client.hotrod.ssl_ciphers`.
Unfortunately, there are no corresponding getter/setter methods on the `ConfigurationProperties` object, so that the property isn't adopted in the Spring-based Command Router component.
For the Quarkus-based component, the property can also not be set.
As for the motivation for setting this property:
When using the Boring SSL library, on each connection attempt the following warning is logged:
```
BoringSSL doesn't allow to enable or disable TLSv1.3 ciphers explicitly. 
```
This can be quite misleading. Explicitly setting the …
> Enable setting SSL ciphers in HotRod config

- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/NotificationTopicHelper.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationTypeResolver.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/AllDevicesOfTenantDeletedNotification.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/AllDevicesOfTenantDeletedNotificationTest.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementServiceTest.java
When deleting all devices of a tenant at once, the device registry implementations do not report which devices have been deleted. It is therefore impossible to send out individual change notifications for each device. 
This PR adds a new notification type `DevicesOfTenantDeletedNotification` to inform about this event as suggested by https://github.com/eclipse/hono/pull/2924#discussion_r754078670.
> [#2837] Publish notification if all devices of a tenant are deleted.

- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/KafkaBasedNotificationReceiver.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/NotificationTopicHelper.java
The method `NotificationTopicHelper.getTopicName()` is used on the sender side as well.
> Fix JavaDoc in NotificationTopicHelper

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientFactory.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaClientFactoryTest.java
- core/src/main/java/org/eclipse/hono/util/Futures.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupService.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupServiceTest.java
This is the first part of the fix for #2953, using retries when trying to create Kafka admin clients in the protocol adapters and the command router.
> [#2953] Use retries when trying to create Kafka admin client

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaClientFactoryTest.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/KafkaBasedNotificationReceiver.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupService.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
The second part of the fix for #2953.
> [#2953] Use retries when trying to create Kafka consumer

- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
> [#2904] Use separate Kafka producer configs in Command Router

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSender.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/producer/AbstractKafkaBasedMessageSenderTest.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedEventSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedTelemetrySender.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- tests/src/test/java/org/eclipse/hono/tests/GenericKafkaSender.java
This is preparatory work for #2702
The AbstractKafkaBasedMessageSender's send* methods have been changed to
require an OpenTracing Span to be passed in which will not be finished
by the send method anymore. The subclasses and test cases have been
adapted accordingly. With this change the classes are better in line
with the approach used in Hono in gerneral, i.e. the component creating
a Span should also be responsible for finishing it.
Some (now) obsolete send* methods have been removed as well.
> [#2702] Improve Kafka client class hierarchy

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/AbstractKafkaConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigProperties.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/KafkaProducerConfigProperties.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/producer/KafkaProducerConfigPropertiesTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaConsumerConfigPropertiesTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaProducerConfigPropertiesTest.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- site/homepage/content/release-notes.md
This fixed #2906.
Default client ID contains the Kubernetes Pod name and container ID now.
> [#2906] Improve Kafka client ID creation

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx-base/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CommandResponseResource.java
- adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/CommandResponseResourceTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandResponseSender.java
- clients/command-amqp/src/test/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandResponseSenderTest.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContext.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandContextTest.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandTest.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandContext.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandResponseSender.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/AbstractMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandler.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedMappingAndDelegatingCommandHandlerTest.java
- services/command-router-base/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaCommandProcessingQueueTest.java
- test-utils/adapter-base-test-utils/src/main/java/org/eclipse/hono/adapter/test/ProtocolAdapterMockSupport.java
- test-utils/kafka-test-utils/src/main/java/org/eclipse/hono/kafka/test/KafkaClientUnitTestHelper.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
This is more (final?) prep-work for #2702 
The CommandResponseSender interface's sendResponse method has been
extended to require tenant configuration and a registration assertion to
be provided in order to better resemble the TelemetrySender and
EventSender interfaces.
The sender implementations have not (yet) been extended to include the
default properties in the downstream command response in order to keep
the scope of this commit smaller.
The CommandResponseSender implementations as well as the TelemetrySender and
EventSender implementation will be adapted accordingly in the next (final?) PR, bringing
it all together.
> [#2702] Allow inclusion of defaults in command response messages

- client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/MessagingClientProvider.java
- service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/server/DeviceRegistryAmqpServer.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/server/DeviceRegistryHttpServer.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
For #2983:
This reduces the number of notification senders (and corresponding AMQP connections) in the device registry from 13 to 2 (one for each server verticle).
Similarly, there is only 1 eventSenderProvider for each server verticle being used now.
Also fixes handling of spring profiles in the JDBC device registry (#2997).
Changes in the device registry `ApplicationConfig` files here could also be seen as making them less dependent on Spring dependency injection (endpoint objects are no beans anymore, they are added explicitly to the server objects). This is also helpful for a potential future migration to Quarkus.
Also includes a fix that will prevent `HonoConnectionImpl` reconnect attempts (and corresponding errors) if Vert.x has already been closed (see 1st commit).
> [#2983] Use one notification sender per server verticle

- adapter-base-quarkus/pom.xml
- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/pom.xml
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractRequestResponseServiceClient.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/AnnotatedCacheKey.java
- clients/client-common/src/test/java/org/eclipse/hono/client/util/AnnotatedCacheKeyTest.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NoOpNotificationReceiver.java
- clients/registry-amqp/pom.xml
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClientTest.java
- core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
- services/command-router-base/pom.xml
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- test-utils/core-test-utils/src/main/java/org/eclipse/hono/test/VertxMockSupport.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantAmqpIT.java
This fixes #2984.
The clients for the device registry APIs may register receivers for notifications of the device registry that are used to remove
objects from the response cache if the corresponding data has changed.
I have created new classes for the cache keys. The reason is that before, some elements of the keys were concatenated (like "${tenantId}-${deviceId}"). This makes it difficult to find e.g. all keys for a tenant.
Previously, the name of the API operation in question was part of the keys. I left it out because none of the clients provide multiple operations. If that ever changes, it's easy to add the operation to the key. @sophokles73 Is this ok for you? Or am I missing something?
Sometimes data that is not part of the key is needed to find affected cache entries. For example, …
> [#2984] Clean Caches on Device Registry Notifications

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/Cache.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCache.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/AbstractBasicCacheTest.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
The Cache interface's put methods have been changed to no longer return
the previous value from the cache because the DeviceConnectionInfo
implementation does not require it.
> Do not require cache to return previous value

- tests/pom.xml
- tests/readme.md
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationApiTests.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
The ITs currently rely on multiple different system properties for
configuring the registry implementation's capabilities.
The capabilities are now determined by means of a single property only.
> Use single registry type property for configuring capabilities

- adapter-base-quarkus/pom.xml
- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/pom.xml
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClientTest.java
- services/command-router-base/pom.xml
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
This is for #2984 and is related to #2983. It addresses the TODO mentioned in https://github.com/eclipse/hono/pull/2996#discussion_r771359986.
Use ProtonBasedNotificationReceiver. Also add integration test for testing adapter registration client cache invalidation triggered via notifications.
> [#2984] Use ProtonBasedNotificationReceiver

- site/documentation/content/admin-guide/command-router-config.md
- site/documentation/content/admin-guide/common-config.md
- site/documentation/content/admin-guide/device-connection-config.md
- site/documentation/content/admin-guide/file-based-device-registry-config.md
- site/documentation/content/admin-guide/jdbc-device-registry-config.md
- site/documentation/content/admin-guide/kafka-config.md
- site/documentation/content/admin-guide/mongodb-device-registry-config.md
- site/homepage/content/release-notes.md
Also apply corrections to the messaging sections of the other admin guides.
This fixes #2936.
> [#2936] Add Kafka broker configuration guide

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
This fixes #3014:
Enable offset auto-commit on internal command topic consumer so that offsets get properly reset after a partition re-assignment (e.g. due to Kafka node restart). Also fix the mechanism that skips already handled commands, preventing duplicate handling in case initial record handling found no command handler or got an error fetching tenant information.
> [#3014] Fix handling on cmd consumer re-joining consumer group

- client-device-connection-infinispan/src/main/resources/META-INF/native-image/org.eclipse.hono/client-device-connection-infinispan/native-image.properties
- client-device-connection-infinispan/src/main/resources/META-INF/native-image/org.eclipse.hono/client-device-connection-infinispan/reflection-config.json
The Infinispan client module has been changed to explicitly add the
WildFly security providers required for performing SASL handshakes with
the Infinispan server.
Fixes #3027
> Explicitly register additional security providers

- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/NotificationAddressHelper.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationSender.java
- clients/notification-amqp/src/test/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiverTest.java
- clients/notification-amqp/src/test/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationSenderTest.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationReceiver.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationSender.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/NotificationTopicHelper.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationReceiverTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationSenderTest.java
- clients/notification/src/main/java/org/eclipse/hono/notification/AbstractNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NoOpNotificationReceiver.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationReceiver.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationType.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationTypeResolver.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/AllDevicesOfTenantDeletedNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/CredentialsChangeNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotification.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/AllDevicesOfTenantDeletedNotificationTest.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/CredentialsChangeNotificationTest.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotificationTest.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotificationTest.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClientTest.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistryNotificationsIT.java
Preparation for #3017:
Combine static properties of `AbstractNotification` sub classes into new `NotificationType` class, getting rid of `AbstractNotification` sub class specific code in several places.
> Add NotificationType class

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractAdapterConfig.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractProtocolAdapterApplication.java
- adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/spring/Application.java
- adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/spring/Application.java
- adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/spring/Application.java
- adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Application.java
- adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Application.java
- adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/spring/Application.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Application.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationConstants.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationEventBusSupport.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationTypeResolver.java
- clients/notification/src/test/java/org/eclipse/hono/notification/NotificationEventBusSupportTest.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClientTest.java
- clients/registry-amqp/src/test/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClientTest.java
- core/src/main/java/org/eclipse/hono/util/Constants.java
- core/src/main/java/org/eclipse/hono/util/WrappedLifecycleComponentVerticle.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/spring/ApplicationConfig.java
- tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantAmqpIT.java
Refactoring in preparation for #3017:
Usage of the vert.x event bus should allow for more flexibility in adding multiple consumers for device registry notifications.
> Pass on device registry notifications via vert.x event bus

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/MessagingKafkaProducerConfigProperties.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaProducerConfigProperties.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
This fixes #2888:
Setting these Kafka producer defaults:
```
delivery.timeout.ms: 2500
request.timeout.ms: 750
max.block.ms: 500
```
This means the overall timeout for sending messages (e.g. telemetry/event) is 3s (max.block.ms + delivery.timeout.ms).
Each request has a timeout of 750ms, allowing for 3 retries.
See [KIP-91](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=66851583).
> [#2888] Adapt Kafka producer default timeout values

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/server/DeviceRegistryAmqpServer.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/server/DeviceRegistryHttpServer.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementServiceTest.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/Application.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/DeviceManagementServiceImpl.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/TenantManagementServiceImpl.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/AbstractJdbcRegistryTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/Application.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceManagementService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantManagementService.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedTenantManagementSearchTenantsTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantServiceTest.java
2nd refactoring in preparation for #3017, following #3033:
Device Registry notifications are first sent on the vert.x event bus in the device registry, to be then handled by the NotificationSender, publishing them to Kafka or the AMQP messaging system.
Having the notifications on the event bus makes it easier to let them be handled in other places in the device registry, e.g. in the Kafka producers for sending auto-provisioning events (#3017).
> Use vert.x event bus with NotificationSender.

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigProperties.java
- clients/notification-kafka/src/main/java/org/eclipse/hono/client/notification/kafka/KafkaBasedNotificationReceiver.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
- site/homepage/content/release-notes.md
This is for #2979.
Using the poll timeout configured in `KafkaConsumerConfigProperties` in the `HonoKafkaConsumer` instances.
> [#2979] Use configured poll timeout in HonoKafkaConsumer

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapter-base-spring/src/main/java/org/eclipse/hono/adapter/spring/AbstractMessagingClientConfig.java
- clients/command-kafka/pom.xml
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSender.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandResponseSenderTest.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/CachingKafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/KafkaProducerFactory.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/producer/KafkaProducerHelper.java
- clients/telemetry-kafka/pom.xml
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedEventSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedTelemetrySender.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSenderTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedEventSenderTest.java
- clients/telemetry-kafka/src/test/java/org/eclipse/hono/client/telemetry/kafka/KafkaBasedTelemetrySenderTest.java
- services/command-router-base/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/ApplicationConfig.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/client/KafkaBasedEventSenderIT.java
This fixes #3017:
Kafka producer metrics regarding the telemetry, event and command-response topics of a tenant are removed when that
tenant got deleted.
> [#3017] Remove producer metrics when tenant is deleted

- site/documentation/content/concepts/device-identity.md
- site/documentation/content/user-guide/amqp-adapter.md
- site/documentation/content/user-guide/coap-adapter.md
- site/documentation/content/user-guide/http-adapter.md
- site/documentation/content/user-guide/kura-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
The (detailed) description of how devices are authenticated using the
information on record has been moved to the Device Identity concept
page's Authentication section in order to reduce text duplication.
The protocol adapter user guides now only describe the binding to the
concrete transport protocol.
> Improve documentation of device authentication

- core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/TenantDao.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantService.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantServiceTest.java
- site/documentation/content/api/management/device-registry-v1.yaml
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantApiTests.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
The Device Registry Management API has been extended to support an
"alias" property in the "Tenant" object. The alias is an optional
alternative identifier that the tenant may be looked up by.
The Mongo DB based Tenant service implementation has been extended to
include the alias when looking up a tenant by ID.
Signed-off-by: Kai Hudalla <kai.hudalla@bosch.io>
> [#2981] Extend Mongo DB registry to support tenant alias

- adapter-base/src/main/java/org/eclipse/hono/adapter/auth/device/TenantServiceBasedX509Authentication.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/auth/device/X509Authentication.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/auth/device/TenantServiceBasedX509AuthenticationTest.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/SaslExternalAuthHandler.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceRegistryBasedCertificateVerifier.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/X509AuthHandlerTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/X509AuthHandler.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/X509AuthHandlerTest.java
- service-base/src/main/java/org/eclipse/hono/service/auth/SniExtensionHelper.java
- service-base/src/test/java/org/eclipse/hono/service/auth/SniExtensionHelperTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedTenantDao.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttTestBase.java
This is for #2981
The MQTT adapter's X509 handler has been changed to retrieve and
consider the requested host names contained in the SNI extension
provided by the device in the TLS handshake.
The other protocol adapters will be updated in subsequent PRs as well.
> [#2981] Support usage of SNI to indicate tenant (MQTT adapter)

- core/src/main/java/org/eclipse/hono/config/ApplicationConfigProperties.java
- core/src/main/java/org/eclipse/hono/config/quarkus/ApplicationOptions.java
- service-base-quarkus/src/test/java/org/eclipse/hono/service/quarkus/QuarkusPropertyBindingTest.java
- service-base-quarkus/src/test/resources/application.yaml
- service-base-spring/src/main/java/org/eclipse/hono/service/spring/AbstractBaseApplication.java
- site/homepage/content/release-notes.md
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/commandrouter/clustered-cache/application.yml
- tests/src/test/resources/commandrouter/embedded-cache/application.yml
- tests/src/test/resources/deviceconnection/application.yml
- tests/src/test/resources/deviceregistry-jdbc-h2/application.yml
- tests/src/test/resources/deviceregistry-jdbc-postgres/application.yml
- tests/src/test/resources/deviceregistry-mongodb/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
This addresses #3045
Spring based application components had been using the value (default
20s) of the (undocumented) ApplicationConfigProperties#startupTimeout
property as the upper limit to wait for the component to start up.
In cases where the component's startup methods took longer to complete,
the component therefore shut down prematurely.
The property has been removed completely so that Spring based components
(like the device registry) no longer run into the timeout.
The Quarkus based components are not affected because they have never
considered this configuration property.
> #3045 Remove application startup timeout property

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
This is for #2981
The HTTP adapter's X509 handler has been changed to retrieve and
consider the requested host names contained in the SNI extension
provided by the device in the TLS handshake.
> [#2981] Support usage of SNI to indicate tenant (HTTP adapter)

- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DeviceRegistryBasedCertificateVerifier.java
- adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/impl/ConfigBasedCoapEndpointFactory.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
This is for #2981
The CoAP adapter's (client) certificate verifier has been changed to
retrieve and consider the requested host names contained in the SNI
extension provided by the device in the DTLS handshake.
> [#2981] Support usage of SNI to indicate tenant (CoAP adapter)

- tests/pom.xml
- tests/readme.md
Since the Quarkus based implementations are the default variant for some
time now, the integration tests are now also by default executed using
the Quarkus based images.
> Run ITs using the Quarkus based components by default

- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/SaslExternalAuthHandler.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/SaslPlainAuthHandler.java
- adapters/amqp-vertx-base/src/main/java/org/eclipse/hono/adapter/amqp/SaslResponseContext.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
This is for #2981
The AMQP adapter's SASL authenticator has been changed to
retrieve and consider the requested host names contained in the SNI
extension provided by the device in the TLS handshake.
> [#2981] Support usage of SNI to indicate tenant (AMQP adapter)

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/AbstractMessageSenderConnectionEventProducer.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/monitoring/ConnectionEventProducer.java
`sendConnectedEvent` and `sendDisconnectedEvent` may be invoked with an `authenticatedDevice` that is `null`.
This PR fixes the NPE that occurred in that case.
> Fix NPE concerning connection events of unauthenticated devices

- .github/workflows/ci.yml
- .github/workflows/native-images-tests.yml
- bom/pom.xml
- service-base-quarkus/pom.xml
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/TracerProducer.java
- tests/pom.xml
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/commandrouter/clustered-cache/application.yml
- tests/src/test/resources/commandrouter/embedded-cache/application.yml
- tests/src/test/resources/deviceregistry-mongodb/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/jaeger/default-sampling-strategies.json
- tests/src/test/resources/mqtt/application.yml
The sampler configuration is now defined in a central JSON config file
that is served by the Jaeger agent. This makes configuration easier to
maintain and also implicitly helps verifying that all necessary classes
have been registered for reflection when running the ITs with native
images.
> Use remote sampling configuration for running ITs

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttCommandEndpointConfiguration.java
The MQTT adapter no longer accepts the "+" wild card character for the
device ID in a topic filter used for subscribing to commands.
Fixes #3093
> [#3093] Remove support for wild card character in topic filter

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationOptions.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationProperties.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/InfinispanRemoteConfigurationPropertiesTest.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/QuarkusPropertyBindingTest.java
- client-device-connection-infinispan/src/test/resources/remote-cache-options.yaml
Also add support for configuring `infinispan.client.hotrod.default_executor_factory.*` HotRod client properties.
This is for #3106.
> [#3106] Allow nested HotRod config keys to be in camel-case

- adapters/base-quarkus/pom.xml
- services/base-quarkus/pom.xml
- site/documentation/content/admin-guide/secure_communication.md
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/src/test/resources/auth/application.yml
The configuration of the run-java.sh command used for starting the
Quarkus based components has been changed to no longer invoke the
quarkus-run.jar but to set a main class to execute. This allows for the
additional classpath (including the jars in the extensions folder) to be
considered by the application.
Fixes #3107
> [#3107] Fix support for extension jars

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MappedMessage.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MessageMapping.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMapping.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapterTest.java
- site/documentation/content/admin-guide/mqtt-adapter-config.md
- site/documentation/content/user-guide/mqtt-adapter.md
Not allowing the whole target address to be set in the MQTT adapter Message Mapping result, thereby making it clear that the tenant identifier can't be overridden.
I've also added a `tenant_id` HTTP header to the request sent by the `HttpBasedMessageMapping`.
Also copying of payload data for the Message Mapping is removed - this shouldn't be necessary anymore (issues were probably due to the message payload Buffer's ByteBuf getting duplicated to create a new MqttPublishMessage).
Handling of a mapped payload for a command response message has been fixed.
This is for #3083.
> [#3083] Only allow mapped target device id in MappedMessage

- client/src/main/java/org/eclipse/hono/client/StatusCodeMapper.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/GenericSenderLink.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/RequestResponseClient.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/ErrorConverter.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/impl/HonoConnectionImpl.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedRequestResponseClient.java
2nd step of #2933
Moved AMQP specific error conversion methods of StatusCodeMapper to
separate class in amqp-connection module in order to remove dependencies
to Proton-J.
> [#2933] Move AMQP specific error conversion methods

- core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
- service-base/src/main/java/org/eclipse/hono/service/http/ComponentMetaDataDecorator.java
- service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
- service-base/src/test/java/org/eclipse/hono/service/http/DefaultFailureHandlerTest.java
Also prevent `WARN` log entries on HTTP client errors.
This fixes #3136.
> [#3136] Preserve RoutingContext error status code

- site/documentation/content/admin-guide/command-router-config.md
As mentioned in https://github.com/eclipse/hono/pull/3109#issuecomment-1049629277:
The Quarkus based Command Router component doesn't support all HotRod client config properties.
Therefore, this PR explicitly lists all supported properties in the documentation.
> Document available HotRod client config properties

- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/impl/ConnectionFactoryImpl.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/impl/HonoConnectionImpl.java
- site/homepage/content/release-notes.md
Fixes #3143
The ConnectionFactoryImpl class also has a method for closing a ProtonConnection to a peer. However, it only does so when an attempt to establish a connection has timed out but the connection got established anyway, I do not see much value in tracking the closing of such a connection in the same way as we do when closing a connection that has actually been in use, as is the case with the HonoConnectionImpl. Refactoring the code would also require quite some effort which FMPOV is not worth it.
> Close TCP connection when disconnecting from peer

- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/config/ClientConfigProperties.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/impl/ConnectionFactoryImpl.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/impl/HonoConnectionImpl.java
- clients/amqp-connection/src/test/java/org/eclipse/hono/client/amqp/connection/impl/ConnectionFactoryImplTest.java
- core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
The ConnectionFactoryImpl has been changed to wait for a peer's close
frame before disconnecting the underlying TCP/TLS connection in cases
where a connect attempt has run into a timeout before the peer's open
frame has been received.
> Gracefully close connection after connect attempt has timed out

- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/AbstractRequestResponseServiceClientTest.java
- clients/amqp-common/src/test/java/org/eclipse/hono/client/amqp/SimpleRequestResponseResult.java
- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandRouterClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
- core/src/main/java/org/eclipse/hono/util/CredentialsResult.java
- core/src/main/java/org/eclipse/hono/util/RegistrationResult.java
- core/src/main/java/org/eclipse/hono/util/RequestResponseResult.java
- core/src/main/java/org/eclipse/hono/util/TenantResult.java
- service-base/src/main/java/org/eclipse/hono/service/commandrouter/CommandRouterResult.java
- site/homepage/content/release-notes.md
This is a first step towards #3148. I will create several additional PRs ...
The RequestResponseResult supports creating instances from a Proton-J
Message's application properties. The dependency on the
ApplicationProperties class has been removed. Instead, the constructors
now accept a Map containing the properties.
> [#3148] Remove Proton-J dependency from RequestResponseResult hierarchy

- adapter-base-quarkus/src/main/java/org/eclipse/hono/adapter/quarkus/AbstractProtocolAdapterApplication.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationEventBusSupport.java
- clients/notification/src/test/java/org/eclipse/hono/notification/NotificationEventBusSupportTest.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementService.java
- tests/src/test/java/org/eclipse/hono/tests/client/KafkaBasedEventSenderIT.java
Access to the static `WeakHashMap` in `NotificationEventBusSupport` has to be synchronized. This mainly applies to unit tests, where multiple Vertx instances are used.
This should fix unit test failures like this one:
```
23:16:39.831 [vert.x-eventloop-thread-0] WARN  i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: io.vertx.core.impl.future.FutureBase$$Lambda$760/0x0000000800550c40@454a5444
java.lang.IllegalStateException: Already a codec registered with name NotificationEventBusContainerLocalCodec
at io.vertx.core.eventbus.impl.CodecManager.registerCodec(CodecManager.java:116)
at io.vertx.core.eventbus.impl.EventBusImpl.registerCodec(EventBusImpl.java:184)
at org.eclipse.hono.notification.NotificationEventBusSupport.sendNotification(NotificationEventBusSupport.java:85) …
```
> Fix synchronization issue in event bus notification sender method

- adapters/amqp-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/amqp/quarkus/MetricsFactory.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/quarkus/MetricsFactory.java
- adapters/http-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/http/quarkus/MetricsFactory.java
- adapters/lora-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/lora/quarkus/MetricsFactory.java
- adapters/mqtt-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/mqtt/quarkus/MetricsFactory.java
- service-base-quarkus/src/main/java/org/eclipse/hono/service/quarkus/AbstractServiceApplication.java
- services/auth-quarkus/src/main/java/org/eclipse/hono/authentication/quarkus/Application.java
- services/device-registry-mongodb-quarkus/src/main/java/org/eclipse/hono/deviceregistry/mongodb/quarkus/Application.java
- site/homepage/content/release-notes.md
This is for #3157:
Fix setting of common metrics tags. They have to be set before metrics get registered via the corresponding Binders.
This is the fix for 1.12.x. I've deliberately kept it small. 
In the change for master, the `meterRegistry.config().commonTags()` invocation shall be only done in one place - in the `AbstractServiceApplication` base class (using a new service/adapter name getter).
> [#3157] Fix setting of common metrics tags in Quarkus based hono-auth and device registry (1.12.x)

- cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSender.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedDownstreamMessage.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClient.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSenderTest.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedRequestResponseCommandClientTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
Hono's north bound C&C API does not support including arbitrary
properties in command message. The application client module's
CommandSender's send methods, however, accept a Map of properties. It is
unclear, if and how these properties are forwarded to upstream devices.
The Map typed parameter has therefore been removed.
Fixes #3162
> [#3162] Do not send message properties to north bound C&C API

- cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSender.java
- clients/application-amqp/src/test/java/org/eclipse/hono/application/client/amqp/ProtonBasedCommandSenderTest.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/application/src/main/java/org/eclipse/hono/application/client/CommandSender.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
The C&C spec does not require a content type to be set when sending
commands. It also allows for commands that contain a payload but do not
specify a content type.
The CommandSender implementations have been adapted accordingly. Also,
the parameter order of the send methods have been changed so that
mandatory parameters come first.
> Allow sending non-empty commands without content type

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/KafkaCommandSender.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSender.java
- clients/application-kafka/src/test/java/org/eclipse/hono/application/client/kafka/impl/KafkaBasedCommandSenderTest.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommand.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedCommandTest.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaRecordHelper.java
- tests/src/test/java/org/eclipse/hono/tests/GenericKafkaSender.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
The Kafka specific north bound C&C API supports including *failure notification metadata* to be included in failure response messages created by the command router or adapters. The Kafka based application client has been extended to support including such meta data in command requests.
> Support sending of failure notification metadata

- tests/src/test/java/org/eclipse/hono/tests/EnabledIfDnsRebindingIsSupported.java
- tests/src/test/java/org/eclipse/hono/tests/EnabledIfDnsRebindingIsSupportedCondition.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
The integration tests verifying SNI based client authentication are now
run only if DNS rebinding for the nip.io domain works in the local
environment.
Fixes #3183
> [#3183] Only run SNI ITs if DNS rebinding for nip.io is supported

- examples/protocol-gateway-example/src/main/java/org/eclipse/hono/example/protocolgateway/ConfigurationProducer.java
- site/documentation/content/dev-guide/amqp_adapter_client.md
Addendum to #3201, adapting the documentation regarding the removed `AmqpAdapterClientFactory`.
> Adapt documentation related to AmqpAdapterClient

- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
This fixes #3193.
Don't set error tag on parent "upload telemetry/event" span in case of a "close consumer" error.
Also create "close consumer" span as direct child of "upload telemetry/event" span. This corresponds to the change a while back that made "upload telemetry/event" wait on the "close consumer" completion (https://github.com/eclipse/hono/commit/5d49e20cd9fc08db80ce79364d5380514df84080#diff-8a5c90291d6bfbbcbd7ae69c43de9a5a5e77532137e677c23fd3e655545d67c5R719).
> [#3193] Fix tracing of "close consumer" error

- site/documentation/content/user-guide/amqp-adapter.md
This is the second step of #2914 
The user guide's examples have been adapted to use the new Picocli based
command line client.
The getting started guides can only be updated when doing the Hono 2.0.0 release because these guides are not part of the versioned documentation.
> [#2914] Adapt AMQP adapter user guide

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/KafkaClientFactory.java
- core/src/main/java/org/eclipse/hono/util/LifecycleStatus.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupService.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/command-router-quarkus/src/main/java/org/eclipse/hono/commandrouter/quarkus/Application.java
- services/command-router-quarkus/src/test/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupServiceTest.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
This is for #3214
There is no direct relation between the command router and the topic
cleanup service. The clean up service has therefore been turned into a
Vert.x Verticle which is deployed separately (once only).
> [#3214] Decouple topic cleanup service from command router

- adapter-base/src/main/java/org/eclipse/hono/adapter/HttpContext.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/HttpContextTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandlerTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/lora-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapterProperties.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
- site/documentation/content/user-guide/http-adapter.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/resources/http/application.yml
This is the first step for #3199
The HTTP protocol adapter has been changed to allow authenticated
gateway devices to omit the tenant ID from the URI of requests
used to upload telemetry or event messages.
> [#3199] Allow gateways to omit tenant ID with HTTP adapter

- adapters/base-quarkus/pom.xml
- bom/pom.xml
- clients/amqp-connection/pom.xml
- clients/amqp-connection/src/test/java/org/eclipse/hono/client/amqp/tracing/MessageAnnotationsInjectExtractAdapterTest.java
- clients/kafka-common/pom.xml
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/tracing/KafkaHeadersInjectExtractAdapterTest.java
- core/pom.xml
- core/src/test/java/org/eclipse/hono/tracing/JsonObjectInjectExtractAdapterTest.java
- core/src/test/java/org/eclipse/hono/tracing/MultiMapInjectExtractAdapterTest.java
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- services/base-quarkus/pom.xml
- site/documentation/content/admin-guide/monitoring-tracing-config.md
- site/homepage/content/release-notes.md
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
Supporting the W3C Trace Context and W3C Baggage specifications should be sufficient.
Relates to #3190.
> Remove support for Jaeger context propagation

- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/RequestDeviceAndAuth.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
- adapters/coap-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
- adapters/coap-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/coap/ResourceTestBase.java
- site/documentation/content/user-guide/coap-adapter.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/resources/coap/application.yml
This is for #3199
The CoAP protocol adapter has been changed to allow authenticated
gateway devices to omit the tenant ID from the URI of requests
used to upload telemetry or event messages.
> [#3199] Allow gateways to omit tenant ID with CoAP adapter

- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
The last step of #3199
The MQTT protocol adapter has been changed to allow authenticated
gateway devices to omit the tenant ID from the topic of messages
used to upload telemetry or event messages.
> [#3199] Allow gateways to omit tenant ID with MQTT adapter

- service-base/src/main/java/org/eclipse/hono/service/quarkus/DropBySpanNamePrefixSampler.java
- service-base/src/main/java/org/eclipse/hono/service/quarkus/DropHttpRequestSpansSampler.java
- service-base/src/main/java/org/eclipse/hono/service/quarkus/SamplerProducer.java
Follow up of #3219:
With the new Quarkus version, traces for Vert.x event bus messages now get created (by means of [EventBusInstrumenterVertxTracer](https://github.com/quarkusio/quarkus/blob/2.8/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/EventBusInstrumenterVertxTracer.java)). This means the adapter traces will now include traces like
`notification.tenant-change-v1 send` with `notification.tenant-change-v1 receive` child spans (and corresponding traces for device and credentials changes). And the device registry/command router will contain `authentication.in send` traces (with `authentication.in receive` child span).
These traces just represent an implementation detail on how notification messages and the authentication …
> Drop event bus message spans

- site/documentation/content/api/command-and-control-kafka/index.md
- site/documentation/content/api/command-and-control/index.md
- site/documentation/content/api/event-kafka/index.md
- site/documentation/content/api/event/index.md
- site/documentation/content/api/telemetry-kafka/index.md
- site/documentation/content/api/telemetry/index.md
This is for #3218
The API names have been adapted in the documentation to always reflect
the underlying messaging infrastructure being used.
The Kafka based APIs have been moved up in the documentation to reflect
the fact that Kafka based messaging is the default with Hono 2.0.0.
> [#3218] Adapt API naming to better reflect messaging infrastructure

- site/documentation/content/user-guide/mqtt-adapter.md
Also mentioning (temporary) server errors as potential cause for failed command subscription attempts, in which case a retry should be performed.
> Improve MQTT adapter documentation concerning SUBACK packets

- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/app/Application.java
- adapters/coap-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/coap/TelemetryResourceTest.java
- core/src/main/java/org/eclipse/hono/util/CommandConstants.java
- site/documentation/content/user-guide/coap-adapter.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapCommandEndpointConfiguration.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/EventCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
The CoAP adapter now exposes its resources using short endpoint name
alternatives to the existing resources.
Fixes #3247
> [#3247] Support short endpoint names in CoAP adapter

- adapters/amqp-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- adapters/coap-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/coap-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/coap/CoapProtocolAdapterMockSupport.java
- adapters/coap-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/coap/TelemetryResourceTest.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
- adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
- adapters/lora-vertx-quarkus/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/lora-vertx-quarkus/src/test/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapterTest.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- clients/command-amqp/src/test/java/org/eclipse/hono/client/command/amqp/ProtonBasedInternalCommandConsumerTest.java
- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/command-kafka/src/test/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumerTest.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandConsumerFactory.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandHandlerWrapper.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandHandlers.java
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactory.java
- clients/command/src/test/java/org/eclipse/hono/client/command/CommandRouterCommandConsumerFactoryTest.java
This is for #3259:
The `AsyncHandlingAutoCommitKafkaConsumer` will now be used for receiving command messages in protocol adapters. This means that a rate limiting will be applied to limit the number of concurrently handled command messages, preventing adapters to reach load levels that could lead to timeouts.
> [#3259] Use AsyncHandlingAutoCommitKafkaConsumer in adapters

- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/KafkaAdminClientConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/KafkaConsumerConfigPropertiesTest.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/producer/KafkaProducerConfigPropertiesTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaConsumerConfigPropertiesTest.java
- clients/notification-kafka/src/test/java/org/eclipse/hono/client/notification/kafka/NotificationKafkaProducerConfigPropertiesTest.java
- demo-certs/ca_opts
- deploy/src/main/deploy/services.sh
- examples/protocol-gateway-example/scripts/create_hono_device.sh
- site/documentation/content/deployment/resource-limitation.md
- site/documentation/content/getting-started/_index.md
This is for #3092.
Rename adapter K8s service references, dropping the "-vertx" suffix.
> [#3092] Rename adapter K8s service references

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
This fixes #3266.
HTTP requests for which no specific route matches shall get a fixed tracing span name, not one corresponding to the request path.
> [#3266] Fix HTTP request span names

- adapters/amqp/pom.xml
- adapters/coap/pom.xml
- adapters/http/pom.xml
- adapters/lora/pom.xml
- adapters/mqtt/pom.xml
- adapters/parent/pom.xml
- adapters/pom.xml
- adapters/sigfox/pom.xml
- services/auth/pom.xml
- services/command-router/pom.xml
- services/device-registry-jdbc/pom.xml
- services/device-registry-mongodb/pom.xml
- services/parent/pom.xml
- services/pom.xml
- site/homepage/content/release-notes.md
> [#3092] Rename service and adapter "base-quarkus" modules

- adapter-base/pom.xml
- bom/pom.xml
- core/pom.xml
- pom.xml
- services/device-registry-base/pom.xml
- services/device-registry-jdbc/pom.xml
- services/device-registry-mongodb/pom.xml
- tests/pom.xml
Use `bcpkix-jdk18on` instead of `bcpkix-jdk15on` now (see https://www.bouncycastle.org/latest_releases.html).
> Update bouncycastle; make the dependency more explicit

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/InternalKafkaTopicCleanupService.java
This fixes #3275.
`vertx` is `null` in the `InternalKafkaTopicCleanupService` constructor.
> [#3275] Fix NPE on Command Router startup

- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/KafkaApplicationClient.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/impl/KafkaApplicationClientImpl.java
This makes it possible to be informed about when the client is ready without having to use a method of the `KafkaApplicationClientImpl` implementation.
> Add KafkaApplicationClient.addOnClientReadyHandler()

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
Related to #3287.
The device registration data `command-endpoint` JSON wasn't getting adopted if `defaults` was `null`.
> Fix 'command-endpoint' not getting set if 'defaults' is null

- core/src/main/java/org/eclipse/hono/util/CommandEndpoint.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Device.java
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationApiTests.java
The native executable based images of protocol adapters failed to
deserialize a registration assertion if it included command endpoint
information that had been configured for the device.
The CommandEndpoint class has been amended with the
@RegisterForReflection annotation and the registry ITs have been
extended to also verify the transfer of command endpoint info in the
registration assertion.
Fixes #3287
> Fix deserialization of CommandEndpoint class in native image

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
Relates to #3298:
This makes sure that HTTP requests with status 404 are marked with an error tracing tag.
> Add default error handler for HTTP requests with status 404

- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/impl/ConfigBasedCoapEndpointFactory.java
The CoAP adapter has been adapted to consider the reduced minimum RAM
requirement for starting on a Substrate VM when determining the maximum
number of connections supported by the adapter.
Fixes #3303
> Use SubstrateVM specific min RAM requirement

- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
- adapters/lora-vertx-base/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
- adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
- service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/DelegatingCredentialsManagementHttpEndpoint.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpoint.java
- services/device-registry-base/src/main/java/org/eclipse/hono/service/management/tenant/DelegatingTenantManagementHttpEndpoint.java
Remove the BodyHandler in createRouter because it is already added.
Add a default uploads directory when creating a bodyhandler.
Fix javadoc(createRouter).
Signed-off-by: Ivanova Suzana <Suzana.Ivanova@bosch.io>
> [#3263] Remove the BodyHandler.

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/HttpProtocolAdapterOptions.java
- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/HttpProtocolAdapterProperties.java
- core/src/main/java/org/eclipse/hono/config/ServerConfig.java
- core/src/main/java/org/eclipse/hono/config/ServerOptions.java
- core/src/test/java/org/eclipse/hono/config/ConfigMappingTest.java
- core/src/test/resources/server-options.yaml
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceConfigOptions.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceConfigProperties.java
- service-base/src/test/java/org/eclipse/hono/service/http/HttpServiceConfigOptionsTest.java
- service-base/src/test/resources/http-service-config-options.yaml
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/server/DeviceRegistryHttpServer.java
Move the idleTimeout property from ServerConfig to HttpProtocolAdapterProperties and HttpServiceConfigProperties.
Signed-off-by: Ivanova Suzana <Suzana.Ivanova@bosch.io>
> [#3263] Move Idle Timeout Configuration

- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
- adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ErrorSubscription.java
- adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- site/homepage/content/release-notes.md
when both are requested for same device
Signed-off-by: Marinov Avgustin <Avgustin.Marinov@bosch.io>
> [#3314] Fix skipping command or error subscription in MQTT adapter

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
- bom/pom.xml
- service-base/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/AbstractServiceApplication.java
- service-base/src/main/java/org/eclipse/hono/service/ApplicationConfigProperties.java
- service-base/src/main/java/org/eclipse/hono/service/ApplicationOptions.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/Application.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/AbstractAmqpServerFactory.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/NotificationSenderProducer.java
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/client/AmqpApplicationClientIT.java
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/commandrouter/clustered-cache/application.yml
- tests/src/test/resources/commandrouter/embedded-cache/application.yml
- tests/src/test/resources/deviceregistry-jdbc-h2/application.yml
- tests/src/test/resources/deviceregistry-jdbc-postgres/application.yml
- tests/src/test/resources/deviceregistry-mongodb/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/mqtt/application.yml
Added config properties for explicitly disabling AMQP 1.0 or Kafka based
messaging. This can be used to prevent Kafka/AMQP components from
starting up despite the connection properties having been set.
Fixes #3328
> Use Kafka based messaging for running ITs by default

- adapters/parent/pom.xml
- bom/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
- services/parent/pom.xml
Not needed any more after Quarkus 2.10.2 update (#3327).
> Remove obsolete jakarta.ws.rs-api dependency

- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- tests/src/test/java/org/eclipse/hono/tests/commandrouter/KafkaBasedCommandConsumerFactoryImplIT.java
> [#3339] Use configured Kafka consumer group id in Command Router

- tests/pom.xml
- tests/readme.md
- tests/src/test/java/org/eclipse/hono/tests/EnabledIfProtocolAdaptersAreRunning.java
- tests/src/test/java/org/eclipse/hono/tests/EnabledIfProtocolAdaptersAreRunningCondition.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/EventAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
- tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryJmsQoS1IT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/EventCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/CorsIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
- tests/src/test/java/org/eclipse/hono/tests/lora/LoraIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS0IT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/TelemetryMqttQoS1IT.java
The EnabledIfProtocolAdaptersAreRunning annotation has been added to
integration tests which allows to mark tests to be run only if a
particular type of protocol adapter has not been explicitly disabled.
A set of Maven properties has been added to selectively disable
particular protocol adapters. Profiles have been added to start a
particular type of protocol adapter only.
> Add support for disabling protocol adapters selectively in ITs

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
To fix the issue, it is necessary to call an empty closing handler
that actually overwrites the execution of "closeHandler"
in "setTtdRequestConnectionCloseHandler" to prevent "ctx.response().end()" from being called twice.
Signed-off-by: Ivanova Suzana <Suzana.Ivanova@bosch.io>
> [#2892] Fix IllegalStateException in HTTP Adapter

- adapters/http-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
- bom/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
- service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
Relates to #3327:
HTTP-server metrics are not needed any more for correct HTTP request span names. `MATCH_ALL_ROUTE_NAME` has been
adapted to match the name used by Quarkus.
Also the handling of requests with an invalid path gets improved here.
> [#3327] Apply tracing changes related to Quarkus 2.10.2 update

- clients/command-kafka/src/main/java/org/eclipse/hono/client/command/kafka/KafkaBasedInternalCommandConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- tests/pom.xml
This fixes #3312:
A restarting Kafka broker could have caused a timeout while waiting for the initial Kafka consumer rebalance in `subscribeAndWaitForRebalance()`, meaning that in this scenario the HonoKafkaConsumer couldn't get ready.
Also readiness-check log output in Kafka consumer classes gets improved here.
The changes are deliberately kept small here in order to reduce the potential impact when merging into 2.0.x.
I'm looking into doing some further improvements for 2.1.0, also in connection with #3349.
> [#3312] Remove timeout on initial subscribeAndWaitForRebalance()

- deploy/src/main/sandbox/hono-values.yml
- service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenFactory.java
- service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenValidator.java
- service-base/src/main/java/org/eclipse/hono/service/auth/JwtSupport.java
- service-base/src/main/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientConfigProperties.java
- service-base/src/main/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientOptions.java
- service-base/src/test/java/org/eclipse/hono/service/auth/delegating/AuthenticationServerClientOptionsTest.java
- service-base/src/test/resources/auth-server-client-options.yaml
- tests/src/test/java/org/eclipse/hono/tests/auth/AuthServerAmqpIT.java
RFC 8725 (https://datatracker.ietf.org/doc/html/rfc8725) recommends that
applications should make sure that a given key is used with exactly one
signature algorithm only. The validator has been extended with a
configuration property that enables a check which compares the signature
algorithm used in a token with the algorithm that has been specified in
the dynamically retrieved JWK set.
> [#3302] Support setting of alg on validating keys

- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/MongoDbBasedDao.java
The `MongoDbBasedDao` `@PreDestroy` `close()` method was not actually getting invoked on shutdown in the Hono Mongo DB device registry component.  (I'm not sure why - when testing I only saw a `@PreDestroy` method getting invoked on beans declared with the `@ApplicationScoped` annotation.)
In the Mongo DB device registry component, the vert.x mongoClient instance should get closed automatically when undeploying the Verticle it is used in (via the close hook added by the vert.x mongoClient). 
Therefore the `@PreDestroy` annotation looks superfluous here.
(Relates to #2809.)
> Remove PreDestroy annotation in MongoDbBasedDao

- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractRequestResponseServiceClient.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/SenderCachingServiceClient.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/CachingClientFactory.java
- clients/client-common/src/main/java/org/eclipse/hono/client/util/ClientFactory.java
- clients/client-common/src/test/java/org/eclipse/hono/client/util/CachingClientFactoryTest.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/ProtonBasedAmqpAdapterClient.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
This fixes #2660:
Concurrent `CachingClientFactory.getOrCreateClient()` invocations are now completed along with the initial creation request.
> [#2660] Prevent "already creating client for key" errors

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/AsyncHandlingAutoCommitKafkaConsumer.java
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- tests/src/test/java/org/eclipse/hono/tests/client/AsyncHandlingAutoCommitKafkaConsumerIT.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
Decoupling the used logic from the one used for the initial topic subscription.
Also letting the "subscribe" and "partitionsFor" invocations be invoked directly one after the other.
Relates to #3312.
> Refactor HonoKafkaConsumer topic subscription update

- adapters/parent/pom.xml
- services/parent/pom.xml
Images with exec permissions for ALL image files could be build by
enabling win-test-images profile:
* -Pwin-test-images
* env property WIN_TEST_IMAGES=true
or by explicitly overiding fabric8.permissions property
* -Dfabric8.permissions=auto
Signed-off-by: Marinov Avgustin <Avgustin.Marinov@bosch.io
> [#3372] Allow building of docker images for windows

- adapters/amqp/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotification.java
- clients/notification/src/main/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotification.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/DeviceChangeNotificationTest.java
- clients/notification/src/test/java/org/eclipse/hono/notification/deviceregistry/TenantChangeNotificationTest.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedCredentialsClient.java
- clients/registry-amqp/src/main/java/org/eclipse/hono/client/registry/amqp/ProtonBasedTenantClient.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/kafka/KafkaBasedCommandConsumerFactoryImpl.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/tenant/AbstractTenantManagementServiceTest.java
Looking at the code
```
DeviceChangeNotification notification;
// ...
if (notification.isEnabled()) {
```
the `notification.isEnabled()` check always seems strange to me. Is it checking whether the notification itself is enabled?
To make things more explicit, I've renamed 
`DeviceChangeNotification.isEnabled` to `DeviceChangeNotification.isDeviceEnabled` 
and `TenantChangeNotification.isEnabled` to `TenantChangeNotification.isTenantEnabled`
here.
The serialization format has been kept the same for compatiblity reasons.
> Rename notification 'enabled' field/getter

- core/src/main/java/org/eclipse/hono/util/CommandConstants.java
- core/src/test/java/org/eclipse/hono/util/CommandConstantsTest.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusService.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/KubernetesBasedAdapterInstanceStatusServiceTest.java
This is for #3379:
Fix potential synchronization issues and reduce possibility of false-positive `SUSPECTED_DEAD` findings in case K8s-API
infos get delayed. The latter is done by registering a started adapter pod already when its container is still in state 'ContainerCreating'.
> [#3379] Improve KubernetesBasedAdapterInstanceStatusService

- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
> [#3378] Fix NPE in case CoAP PUT URI device id is empty

- builder/HonoBuilder.dockerfile
- cli/pom.xml
- jenkins/Hono-Deploy-Eclipse-Pipeline-Declarative.groovy
- jenkins/Hono-Deploy-Maven-Central-Pipeline-Declarative.groovy
- jenkins/Hono-Nightly-Pipeline-Declarative.groovy
- jenkins/Hono-Release-Pipeline.groovy
- jenkins/Hono-Sonar-Pipeline.groovy
- jenkins/Hono-Website-Pipeline-Declarative.groovy
- site/documentation/content/getting-started/_index.md
Addresses #3360 
The build jobs have been changed to consistently use the
eclipse/hono-builder container image for building Hono. This image
contains specific versions of Maven, the GraalVM SDK with the
native-image compiler plugin and the UPX tool for compressing binary
artifacts.
The release build job has been extended with an additional invocation
of mvn clean install used to build the native executable of the CLI.
The native executable needs to be built in a separate run because in the
first build the JAR file artifacts are being signed by the Eclipse JAR
signer service which results in signature errors during the native
executable build.
> [#3360] Create native executable command line client

- cli/src/main/java/org/eclipse/hono/cli/CustomConfiguration.java
- cli/src/main/java/org/eclipse/hono/cli/adapter/amqp/AmqpAdapter.java
- cli/src/main/java/org/eclipse/hono/cli/app/CommandAndControl.java
- cli/src/main/java/org/eclipse/hono/cli/util/CommandUtils.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/EventSender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/TelemetrySender.java
- clients/device-amqp/src/main/java/org/eclipse/hono/client/device/amqp/impl/ProtonBasedAmqpAdapterClient.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/AmqpAdapterClientTestBase.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/impl/CommandResponderTest.java
- clients/device-amqp/src/test/java/org/eclipse/hono/client/device/amqp/impl/TelemetrySenderTest.java
The command line client has been changed to allow sending of messages to
the AMQP adapter that contain no body and no content-type.
It is at the discretion of the AMQP adapter to handle such messages in
an appropriate way. The CLI's error handling has been improved so that
it now always prints the error message received from the AMQP adapter.
Fixes #3390
> [#3390] Allow CLI to send empty messages with no content type

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBaseTest.java
- adapters/coap/src/main/java/org/eclipse/hono/adapter/coap/AbstractHonoResource.java
- adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/AbstractHonoResourceTest.java
- adapters/coap/src/test/java/org/eclipse/hono/adapter/coap/TelemetryResourceTest.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/DownstreamAmqpMessageFactory.java
- clients/amqp-connection/src/main/java/org/eclipse/hono/client/amqp/connection/AmqpUtils.java
- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandResponseSender.java
- clients/telemetry-kafka/src/main/java/org/eclipse/hono/client/telemetry/kafka/AbstractKafkaBasedDownstreamSender.java
- core/src/main/java/org/eclipse/hono/util/EventConstants.java
- site/documentation/content/user-guide/amqp-adapter.md
- site/documentation/content/user-guide/coap-adapter.md
- site/documentation/content/user-guide/http-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
- site/homepage/content/release-notes.md
- tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
The protocol adapters have been changed to
- accept empty telemetry and event messages from devices if the device
specifies an arbitrary non-empty content type.
- fall back to the application/octet-stream content type for non-empty
messages for which the device has not set a content type and for which
no default content type has been defined.
The adapter user guides have been adapted accordingly.
This should fix #3222
> [#3222] Handle empty messages uniformly across adapters

- site/documentation/content/user-guide/http-adapter.md
- site/documentation/content/user-guide/mqtt-adapter.md
All examples given in the adapter user guides now use the Sandbox' host
name instead of localhost.
Fixes #2716
> [#2716] Consistently use Sandbox host in user guides

- pom.xml
- site/documentation/content/dev-guide/building_hono.md
This is for #3345 
Use docker buildx for creating images for multiple platforms. This can be used when building the container images locally during the release process.
> [#3345] Support building images for the arm64 platform

- service-base/src/main/java/org/eclipse/hono/service/auth/JjwtBasedAuthTokenValidator.java
Setting an explicit span name on the `http://hono-service-auth:8088/validating-keys` GET requests, e.g. from the Command Router.
Otherwise the span name would just be `HTTP GET`.
> Set span name for request to get validation keys

- bom/pom.xml
- service-base/src/main/java/org/eclipse/hono/service/tracing/SamplerProducer.java
Prevent the Hono custom Sampler (provided by the `SamplerProducer`) to be wrapped by a parent-based Sampler. Otherwise child spans (e.g. event-bus message spans) can't be dropped.
Relates to the recent Quarkus 2.12.2 update and #3416.
> Fix tracing sampler configuration

- clients/notification/src/main/java/org/eclipse/hono/notification/NotificationEventBusSupport.java
- service-base/src/main/java/org/eclipse/hono/service/auth/EventBusAuthenticationService.java
- service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
Use `TracingPolicy.IGNORE` when sending event bus messages.
This is a preparation for when Quarkus takes this policy into account - see https://github.com/quarkusio/quarkus/issues/25417.
(It seems that creation of a tracing span for a _received_ event bus message can't currently be disabled. I.e. there's no equivalent to setting the `TracingPolicy` on a vert.x `HttpServer` for example.)
> Vert.x event bus message related improvements

- cli/src/main/java/org/eclipse/hono/cli/app/NorthBoundApis.java
- clients/amqp-common/src/main/java/org/eclipse/hono/client/amqp/AbstractServiceClient.java
- clients/application-amqp/src/main/java/org/eclipse/hono/application/client/amqp/ProtonBasedApplicationClient.java
- clients/application-kafka/src/main/java/org/eclipse/hono/application/client/kafka/KafkaApplicationClient.java
- clients/application/src/main/java/org/eclipse/hono/application/client/ApplicationClient.java
- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedCommandRouterClient.java
- clients/command-amqp/src/main/java/org/eclipse/hono/client/command/amqp/ProtonBasedInternalCommandConsumer.java
- clients/notification-amqp/src/main/java/org/eclipse/hono/client/notification/amqp/ProtonBasedNotificationReceiver.java
- core/src/main/java/org/eclipse/hono/util/Lifecycle.java
- examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/amqp/ProtonBasedCommandConsumerFactoryImpl.java
This is especially needed for the `KafkaApplicationClient`, letting a given handler be invoked when the Kafka producer
is ready.
Also introduce a lifecycleStatus in `AbstractServiceClient`, preventing successive start() invocations.
> Add ApplicationClient addOnClientReadyHandler()

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterBase.java
- adapters/amqp/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
- adapters/amqp/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
- site/documentation/content/admin-guide/command-router-config.md
- site/documentation/content/concepts/device-notifications/index.md
- site/documentation/content/user-guide/amqp-adapter.md
- site/homepage/content/release-notes.md
The CommandConsumers are not closed during shutdown. Sending of connected/disconnected events is moved to CommandRouter.
> [#2760] Optimized AMQP adapter shutdown

- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
- client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceToAdapterMappingErrorListener.java
- client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/CommandRouterServiceImpl.java
- site/homepage/content/release-notes.md
Command Router sends disconnectedTtdEvent in case of command from north bound Application to disconnected device. This happens only if the device is marked as connected to Adapter that was already shutdown.
> [#2760] North bound Application triggers disconnectedTtdEvent

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSender.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubMessageHelper.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactory.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherClient.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherClientImpl.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherFactory.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/CachingPubSubSubscriberFactory.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriber.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriberClient.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriberClientImpl.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/subscriber/PubSubSubscriberFactory.java
- clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSenderTest.java
- clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/PubSubMessageHelperTest.java
- clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactoryTest.java
- clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/subscriber/CachingPubSubSubscriberFactoryTest.java
- clients/telemetry-pubsub/src/main/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSender.java
- clients/telemetry-pubsub/src/test/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSenderTest.java
- site/documentation/content/admin-guide/pubsub-config.md
This PR is a prerequisite in order to use only Pub/Sub as messaging infrastructure. As part of this architecture we added a Pub/Sub based subscriber functionality.
Added new package for the new subscriber functionality.
Used Google's Subscriber to subscribe messages from Google Pub/Sub.
Moved Pub/Sub publisher functionality to publisher package.
Added unittests.
Update documentation.
> #3471 Add Pub/Sub subscriber functionality

- adapter-base/pom.xml
- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
- services/command-router/pom.xml
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/app/Application.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/pubsub/PubSubBasedCommandConsumerFactoryImpl.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/pubsub/PubSubBasedCommandProcessingQueue.java
- services/command-router/src/main/java/org/eclipse/hono/commandrouter/impl/pubsub/PubSubBasedMappingAndDelegatingCommandHandler.java
- services/command-router/src/test/java/org/eclipse/hono/commandrouter/impl/pubsub/PubSubBasedMappingAndDelegatingCommandHandlerTest.java
This is the last PR to use Pub/Sub as only messaging infrastructure. We added a Pub/Sub based implementation for Hono's Command Router API.
- Added new package to support a Pub/Sub based Command Router implementation.
- Integrate Command & Control implementation
> [#3471] Add Pub/Sub based Command Router implementation

- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSender.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubMessageHelper.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/CachingPubSubPublisherFactory.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherFactory.java
- clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/AbstractPubSubBasedMessageSenderTest.java
- clients/pubsub-common/src/test/java/org/eclipse/hono/client/pubsub/PubSubMessageHelperTest.java
- clients/telemetry-pubsub/src/main/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSender.java
- clients/telemetry-pubsub/src/test/java/org/eclipse/hono/client/telemetry/pubsub/PubSubBasedDownstreamSenderTest.java
Enable subtopic support in case Pub/Sub is used as the messaging infrastructure by checking if the topic contains subtopics and rerouting them to the respective Pub/Sub topic (e.g. MQTT topic event/exampleTenant/exampleDevice/subtopic to Pub/Sub topic exampleTenant.event.subtopic).
Implement a fallback mechanism in case the subtopic does not exist. In case the subtopic does not exist the message would instead get send to the "main" topic (e.g. telemetry or event).
> [#3488] Enable subtopics for downstream messages with Pub/Sub messaging infrastructure

- clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandSender.java
Fixed a bug preventing commands for a device being sent to the gateway representing the device if Pub/Sub is used as the messaging infrastructure resulting from the via header not being set.
> [#3471] Bug fix for commands via Pub/Sub 

- site/documentation/content/admin-guide/hono-kafka-client-configuration.md
Add documenation about dynamic config keys and the need to disambiguate them in the config file or as system properties. Also explain the need to use double underscore for properties that include a period in their key.
> Improve Kafka environment variable config documentation

- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementSearchDevicesTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementSearchTenantsTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
- tests/src/test/java/org/eclipse/hono/tests/registry/TenantManagementIT.java
Extended the unit and integration tests for the search API to use a larger set of entities so that paging functionality can be tested more meaningfully.
> Improve tests for Registry Management's search entities API

- clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumer.java
- clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumerTest.java
> [#3543] Acknowledge Pub/Sub messages on command_internal subscription when they are being processed by Hono

- CONTRIBUTING.md
- site/homepage/content/community/contributing.md
Removing the 'Signed-off-by' requirement as it isn't listed in the [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#resources-commit) anymore.
See the corresponding change in the `org.eclipse.dash.handbook` repo [here](https://gitlab.eclipse.org/eclipse/technology/dash/org.eclipse.dash.handbook/-/commit/ba80975702f666de587e9cd0003d821cb8f95d9a#13e7b2e3a22176dcc2d2d157775b7732dff45899_91_88).
> Update commit requirements in Contributing page

- .github/workflows/ci.yml
Use the fkirc/skip-duplicate-actions GitHub action to prevent duplicate workflow runs.
> Prevent duplicate workflow runs when pushing pull requests

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
- clients/command/pom.xml
- clients/command/src/main/java/org/eclipse/hono/client/command/CommandRoutingUtil.java
- clients/command/src/main/java/org/eclipse/hono/client/command/KubernetesContainerInfoProvider.java
- clients/command/src/main/java/org/eclipse/hono/client/command/ProtocolAdapterCommandConsumerFactoryImpl.java
- clients/command/src/test/java/org/eclipse/hono/client/command/KubernetesContainerInfoProviderTest.java
- clients/command/src/test/java/org/eclipse/hono/client/command/ProtocolAdapterCommandConsumerFactoryTest.java
> [#3537] Get K8s container id via K8s API.

- adapter-base/src/test/resources/application.yml
- adapters/amqp/src/test/resources/application.yml
- adapters/coap/src/test/resources/application.yml
- adapters/http-base/src/test/resources/application.yml
- adapters/lora/src/test/resources/application.yml
- adapters/mqtt-base/src/test/resources/application.yml
- bom/pom.xml
- cli/src/main/resources/application.yaml
- examples/protocol-gateway-example/src/main/resources/application.yml
- service-base/src/test/resources/application.yml
- services/auth-base/src/test/resources/application.yml
- services/command-router/src/test/resources/application.yml
- services/device-registry-base/src/test/resources/application.yml
- services/device-registry-jdbc/src/test/resources/application.yml
- services/device-registry-mongodb/src/main/resources/application.properties
- services/device-registry-mongodb/src/test/resources/application.yml
- tests/src/test/resources/amqp/application.yml
- tests/src/test/resources/auth/application.yml
- tests/src/test/resources/coap/application.yml
- tests/src/test/resources/commandrouter/clustered-cache/application.yml
- tests/src/test/resources/commandrouter/embedded-cache/application.yml
- tests/src/test/resources/deviceregistry-jdbc-h2/application.yml
- tests/src/test/resources/deviceregistry-jdbc-postgres/application.yml
- tests/src/test/resources/deviceregistry-mongodb/application.yml
- tests/src/test/resources/http/application.yml
- tests/src/test/resources/lora/application.yml
- tests/src/test/resources/mqtt/application.yml
Relates to #3547.
`quarkus.log.console.color` has been replaced by `quarkus.console.color`,
`quarkus.mongodb.native.dns.use-vertx-dns-resolver` is obsolete because usage of that resolver is now the default.
> Replace deprecated quarkus properties

- .github/workflows/ci.yml
- bom/pom.xml
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java
- site/documentation/content/admin-guide/mongodb-device-registry-config.md
- site/homepage/content/release-notes.md
Unit and integration tests have been changed to use Mongo 6.0 by default. CI workflow has been adapted to test against Mongo versions 4.4, 5.0, 6.0 and 7.0.
Support for Mongo 4.4 has been deprecated.
Fixes #3540
> Use Mongo 6.0 by default

- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/publisher/PubSubPublisherClientImpl.java
- site/homepage/content/release-notes.md
> [#3574] Fix wrong context used in PubSubPublisherClient.publish().

- clients/kafka-common/pom.xml
- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- clients/kafka-common/src/test/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumerTest.java
- test-utils/core-test-utils/src/main/java/org/eclipse/hono/test/JUnitTests.java
- tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
- tests/src/test/java/org/eclipse/hono/tests/client/HonoKafkaConsumerIT.java
- tests/src/test/resources/logback-test-include-prod.xml
This is the first step for #3558
The HonoKafkaConsumer has been adapted to explicitly enforce a rebalance in order to get assigned partitions for auto-created topics if the metadata.max.age.ms configuration property is not set or is set to a value greater than 500.
Kafka 3.5 seems to have changed its rebalancing behavior with regard to auto-created topics. Without this modification, the assignment of new partitions to the consumer will be deferred to after the metadata has become stale, which happens after 5 minutes if not explicitly overridden using the metadata.max.age.ms configuration property.
> Make HonoKafkaConsumer compatible with Kafka 3.5

- cli/src/main/java/org/eclipse/hono/cli/adapter/amqp/AmqpAdapter.java
- cli/src/main/java/org/eclipse/hono/cli/app/CommandAndControl.java
- cli/src/main/java/org/eclipse/hono/cli/util/ConnectionOptions.java
The AmqpAdapter and CommandAndControl classes have been changed to pass in a non-null ConfigurationPath when creating the JLine console builtins.
Fixes #3576
> Fix NPE when running CLI

- adapter-base/src/main/java/org/eclipse/hono/adapter/AbstractProtocolAdapterApplication.java
- clients/command-pubsub/src/main/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumer.java
- clients/command-pubsub/src/test/java/org/eclipse/hono/client/command/pubsub/PubSubBasedInternalCommandConsumerTest.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubBasedAdminClientManager.java
- clients/pubsub-common/src/main/java/org/eclipse/hono/client/pubsub/PubSubConfigProperties.java
- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/app/CommonConfigPropertiesProducer.java
Improved getOrCreateTopic/Subscription flow for Pub/Sub messaging infrastructure and changed the subscription expiration to never by adding the default ExpirationPolicy instance to the subscription
> [#3549] Improved getOrCreateTopic/Subscription flow for Pub/Sub

- cli/src/main/java/org/eclipse/hono/cli/adapter/amqp/AmqpAdapter.java
- cli/src/main/java/org/eclipse/hono/cli/app/NorthBoundApis.java
- cli/src/main/java/org/eclipse/hono/cli/util/ConnectionOptions.java
- examples/quickstart-python/README.md
- examples/quickstart-python/quickstart.py
- examples/quickstart-python/requirements.txt
- site/documentation/content/getting-started/_index.md
- site/documentation/content/user-guide/amqp-adapter.md
- site/homepage/content/release-notes.md
Addresses #3569
The command line client was still trying to connect to the insecure ports of the Sandbox.
This has been changed so that the client now uses the TLS endpoints and requires the user to specify a trust store for validating the server certificate.
The Getting Started guide has been adapted accordingly.
> Use TLS endpoint when connecting to Sandbox

- site/documentation/content/getting-started/_index.md
This fixes #3582 .
When connecting to a local Hono instance using the IP obtained from the K8s Service, the hostname verification as part of the TLS connection attempt will not work for the demo certs. Therefore the `--insecure` option has to be added to the `curl` and `mosquitto_pub/sub` commands. For `mosquitto_pub/sub`, the `--insecure` option will disable only the hostname verification. For `curl`, there is no separate command line option for that (equivalent to the `CURLOPT_SSL_VERIFYHOST` libcurl option), hence the need to use `--insecure`, disabling certificate checking. 
(There would be an alternative to `curl --insecure`, using the parameter  `--resolve "hono-service-device-registry.hono:28443:${REGISTRY_IP}"` and  `hono-service-device-registry.hono` as host in the URL, but this …
> [#3582] Fix env setup in 'Getting Started' guide.

- cli/src/main/java/org/eclipse/hono/cli/adapter/amqp/AmqpAdapter.java
- cli/src/main/java/org/eclipse/hono/cli/app/NorthBoundApis.java
- examples/quickstart-python/quickstart.py
- site/documentation/content/getting-started/_index.md
- site/documentation/content/user-guide/amqp-adapter.md
Follow-up of #3570:
The CLI `--ca-file` parameter shouldn't be required when connecting to the sandbox.
> Remove CLI ca-file requirement for sandbox connections.

- .github/workflows/native-images-tests.yml
- services/base-jdbc/src/main/resources/META-INF/native-image/org/eclipse/hono/hono-service-base-jdbc/native-image.properties
- services/base-jdbc/src/main/resources/META-INF/native-image/org/eclipse/hono/hono-service-base-jdbc/resources-config.json
- services/device-registry-jdbc/pom.xml
- tests/pom.xml
Changes needed for device registry JDBC to make native-image build succeeds and native-image integration tests run passes.
> [#3555] Device Registry JDBC native build

- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMapping.java
- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/impl/HttpBasedMessageMappingTest.java
> custom mapper should not always return a 503 when the mapping fails

- adapter-base/src/test/java/org/eclipse/hono/adapter/auth/device/x509/OCSPIntegrationTest.java
- pom.xml
Fix for #3588
Added support for "noDocker" Maven property for disabling OCSP integration tests based on Testcontainers when Docker is not available.
> Support disabling OCSP integration tests

- .github/workflows/ci.yml
- site/documentation/content/admin-guide/mongodb-device-registry-config.md
Removed integration tests against MongoDB 4.4, updated MongoDB registry documentation.
> Remove support for MongoDB 4.4

- deploy/src/main/sandbox/hono-values.yml
Adapted Kafka configuration properties to use single node Kafka instance in KRaft mode based on bitnami/kafka chart version ^26.8.
> Use KRaft mode for Sandbox deployment

- adapter-base/src/main/java/org/eclipse/hono/adapter/resourcelimits/PrometheusBasedResourceLimitCheckOptions.java
- adapter-base/src/main/java/org/eclipse/hono/adapter/resourcelimits/PrometheusBasedResourceLimitChecksConfig.java
- adapter-base/src/test/java/org/eclipse/hono/adapter/resourcelimits/PrometheusBasedResourceLimitCheckOptionsTest.java
- adapter-base/src/test/resources/resource-limit-check-options.yaml
Read `port` value into separate Prometheus specific option with default value `9090` and use it to instantiate Prometheus config.
> [#3647] Prometheus based limits check uses always port 9090

- cli/pom.xml
- legal/src/main/resources/legal/DEPENDENCIES
- legal/src/main/resources/legal/hono-maven.deps
The jline dependency version 3.23.0 used in the Hono CLI has a CVE assigned to it (CVE-2023-50572), therefore updating it.
> Update jline to 3.26.1.

- services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementService.java
- services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/device/AbstractDeviceManagementServiceTest.java
- services/device-registry-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/app/ConfigPropertiesProducer.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/app/HttpServerFactory.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/app/ManagementServicesProducer.java
- services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/DeviceManagementServiceImpl.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/AbstractJdbcRegistryTest.java
- services/device-registry-jdbc/src/test/java/org/eclipse/hono/deviceregistry/jdbc/impl/JdbcBasedRegistrationServiceTest.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/ConfigPropertiesProducer.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/HttpServerFactory.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/app/ManagementServicesProducer.java
- services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceManagementService.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDBBasedDeviceManagementSearchDevicesTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
- services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
- tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationApiTests.java
This is initial implementation idea I had and thought it should cover all the paths device is created to prevent creating any deivce with id which does not conform to the device id pattern.
I think I need to look at integration tests also but need to do that bit later.
> [#3608] Verify that auto-provisioned device ids match device id pattern

- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
- adapters/mqtt-base/src/test/java/org/eclipse/hono/adapter/mqtt/MqttContextTest.java
Initial simplified MQTT 5 support with using Vert.x MQTT 5 support methods.
> [#2955] MQTT 5 support

- adapters/mqtt-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
- bom/pom.xml
- site/documentation/content/user-guide/mqtt-adapter.md
- tests/pom.xml
- tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttTestBase.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt5/MqttConnectionIT.java
- tests/src/test/java/org/eclipse/hono/tests/mqtt5/MqttTestBase.java
MQTT5 defines new reason codes to be included in CONNACK packets when connection establishment fails. The abstract adapter base class has been changed accordingly.
Also added integration tests based on HiveMQ client for testing connection establishment.
Addresses #2955
> Fix MQTT5 Connect Reason Codes

- jenkins/Hono-Website-Pipeline-Declarative.groovy
- site/build-site.bat
- site/build-site.sh
The web site Jenkins build job had been failing sporadically. It seems like this was because of too little memory available on the JNLP container. The memory has been increased to 1GB to address this.
Also, the build job has been changed to use Hugo 0.123.8 which is the last Hugo version that is compatible with the used Hugo themes.
> Fix web site build job

- clients/kafka-common/src/main/java/org/eclipse/hono/client/kafka/consumer/HonoKafkaConsumer.java
- tests/src/test/java/org/eclipse/hono/tests/client/AsyncHandlingAutoCommitKafkaConsumerIT.java
> [#3669] Fix deletion of obsolete metrics in KafkaConsumer.

- tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
The MQTT based integration tests have been improved to correctly
detect and report the fact that not all one-way commands that have
been sent also have been processed by the device.
Fixes #3676
> Fix reporting of processed commands in ITs
