eclipse-hono/hono

config/pom.xml
config/qpid/policy/policies.json
example/readme.md

Added the "latest" tag for the qpid-default-config and qpid-sasldb Docker images during the build
Updated example readme in order to use the "latest" tag for the images started manually on the command line
Updated the policies.json with maxSessions (50) parameter in order to have more channels for the internal connection with the router

Added "latest" tag to Docker images and increased maxSessions for internal router connection

---

site/content/getting-started.md

While updating to M4 I found that the docker-compose command was not initially working anymore.
It needed a "docker swarm init" first, which I added to the getting started page under prerequisites in this pull request.
Tested with hugo locally before pushing.

Docker swarm init missing in doc

---

core/src/main/java/org/eclipse/hono/connection/ConnectionFactoryImpl.java

Fix for issue #106 : callback handler now called in case of connection failures as well.
Signed-off-by: kf <Karsten.Frank@bosch-si.com>

#106: Call connectionResultHandler in case of failed connection attempt.

---

adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/VertxBasedRestProtocolAdapter.java

As already discussed in #104 this PR updates the REST and MQTT adapters to no longer register a drain handler in case no credits are available. Instead, the client's request is rejected (REST adapter) or the connection closed (MQTT adapter).

Fix #104: Do not register drain handlers in protocol adapters

---

server/src/main/java/org/eclipse/hono/server/ForwardingDownstreamAdapter.java

Fix for wrong map key being used on activeSenders in onClientAttach().

Wrong map key in ForwardingDownstreamAdapter.onClientAttach()

---

core/src/test/java/org/eclipse/hono/connection/ConnectionFactoryImplTest.java

Hi,
me and all my colleagues that use windows get an error with this test. However if we increase the timeout all works fine. Perhaps an issue with different networking behavior on windows and linux.
This test lasts up to 2 seconds on my machine. Do you think this is still OK for a unit test? Or should we try to test this without real network operations (which could be hard in this case without mocking everything)? Do you have any hard limits on execution times for a single unit test? Perhaps this is already an integration test because it tries to connect to another component.
Signed-off-by: Daniel Maier <Daniel.Maier@bosch-si.com>

Increase test timeout to prevent build failures

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java

Use an empty string as default value for "spring.profiles.active" to prevent startup failure of REST adapter if no active profiles are set.

Prevent REST adapter startup failure if no active profiles are set

---

bom/pom.xml
pom.xml
server/pom.xml
server/src/main/java/org/eclipse/hono/server/HonoServer.java
server/src/test/java/org/eclipse/hono/server/HonoServerTest.java
server/src/test/java/org/eclipse/hono/server/StandaloneRegistrationApiTest.java
server/src/test/java/org/eclipse/hono/server/StandaloneTelemetryApiTest.java
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractServiceBaseTest.java

This PR consists of a new maven module "server-base" that contains the common functionality for implementing servers that listen on a secure and/or insecure port.
Applied to HonoServer only currently, but intended to serve as base for the protocol adapters as well.
Existing tests for the port determination are mainly moved to the new maven module and only a few AMQP(s) port checks remain in the "server" module. This would be similar in the protocol adapters in the future (not part of this PR).
Looking forward to comments, improvements, thoughts on the way I implemented it now.

Hono adapters dual port configuration 140

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java

Fix for `AbstractVertxBasedHttpProtocolAdapter#serviceUnavailable()`.

Fix serviceUnavailable() not setting the RETRY_AFTER header

---

client/src/main/java/org/eclipse/hono/client/CredentialsClient.java
client/src/main/java/org/eclipse/hono/client/HonoClient.java
client/src/main/java/org/eclipse/hono/client/RegistrationClient.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
server/src/test/java/org/eclipse/hono/server/StandaloneCredentialsApiTest.java

Last step (out of 4) to provide the get operation of the credentials API.
Includes the client plus tests.

[#169] Credentials API client (so far only get operation)

---

adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/Config.java
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/Config.java
application/src/main/java/org/eclipse/hono/application/ApplicationConfig.java
core/src/main/java/org/eclipse/hono/adapter/AdapterConfig.java
core/src/main/java/org/eclipse/hono/connection/ConnectionFactoryImpl.java
core/src/test/java/org/eclipse/hono/connection/ConnectionFactoryImplTest.java

Use "hono.registration.*" properties to configure the RegistrationServiceClient in protocol adapters.
If no such properties are configured (or to be exact, if no "hono.registration.host" property is set), the honoClient will be used as RegistrationServiceClient.
Adding information about this in the protocol adapter documentation is not included here - to be done in a follow-up commit.

Configurable RegistrationServiceClient in protocol adapters

---

example/docker/docker-compose.yml

"auth-server" corresponds to the common name in the auth server certificate.

Fix credentials / hono-auth service name in docker-compose.yml

---

example/docker/docker-compose.yml

In the example docker-compose file the REST adapter and MQTT adapter
are now configured to use the device registry microservice for all calls to the
registration API (instead of Hono server).
Openshift deployment not considered here (will follow).

[#203] Configure protocol adapters to device registry.

---

adapters/mqtt-vertx/src/main/fabric8/hono-adapter-mqtt-vertx-dc.yml
adapters/rest-vertx/src/main/fabric8/hono-adapter-rest-vertx-dc.yml
application/src/main/fabric8/hono-app-dc.yml
example/docker/docker-compose.yml
example/openshift/openshift_deploy.sh
services/device-registry/pom.xml
services/device-registry/src/main/fabric8/hono-device-registry-dc.yml
services/device-registry/src/main/fabric8/hono-device-registry-route.yml
services/device-registry/src/main/fabric8/hono-device-registry-svc.yml
site/content/deployment/openshift.md

Since for Openshift the auth server already uses the port 25671, the device registry now always binds
to port 26671 (openshift and docker swarm).

[#203] Add Openshift deployment for device registry.

---

client/src/main/java/org/eclipse/hono/client/HonoClient.java
client/src/main/java/org/eclipse/hono/client/MessageConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/EventConsumerImpl.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TelemetryConsumerImpl.java
client/src/test/java/org/eclipse/hono/client/impl/EventConsumerImplTest.java
jmeter/src/jmeter/hono_jmeter_runtime.jmx
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoReceiverSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java

- created AbstractConsumer
- moved methods to AbstractConsumer
- added variants with prefetch to factories and HonoClient
- added flow() to Consumer
- added prefetch property to JMeter consumer

[#269] Ability to set prefetch on client consumer (and also own flow control)

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java
service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractServiceBaseTest.java
tests/pom.xml

Eliminate code duplication from implementing the getters for each
specific vertx server (to only cover the ephemeral port determination).
Increase startup time for Hono Messaging in integration tests to 40 seconds.

[#271] Getters for secure and insecure port in common base class.

---

services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DeviceRegistryConfigProperties.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/StandaloneCredentialsApiTest.java

Previously, the credentials file was loaded from classpath.
This was broken due to removal from classpath and preventing the start
of the device registry component (if credentials endpoint enabled).
It is now repaired and aligned with the file based device registry
which directly uses the filesystem.

[#169] Filesystem based implementation for credentials.

---

service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
service-base/src/test/java/org/eclipse/hono/service/amqp/AmqpServiceBaseTest.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/SimpleDeviceRegistryServer.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessaging.java
services/messaging/src/test/java/org/eclipse/hono/messaging/HonoMessagingTest.java

Eliminate identical implementations that are part of HonoMessaging and
SimpleDeviceRegistrationService.

[#278] Move handle(Sender|Receiver)Open methods to base class.

---

adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/Application.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/Config.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/VertxBasedMqttProtocolAdapter.java
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/Application.java
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/Config.java
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/VertxBasedRestProtocolAdapter.java
service-base/src/main/java/org/eclipse/hono/service/AbstractApplication.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/Application.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/ApplicationConfig.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/Application.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DeviceRegistryAmqpServer.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessaging.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplication.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplicationConfig.java

Class AbstractApplication is no longer parametrized with service type
and configuration type. Services are now picked up dynamically at
startup if corresponding ObjectFactories are provided. The
targetBeanName now needs to be the name of an existing bean.
For discussion see #287.

[#259] Add support for multiple protocols per application.

---

service-base/src/main/java/org/eclipse/hono/service/registration/DeviceRegistryAmqpServerBase.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DeviceRegistryAmqpServer.java

Introduced base class DeviceRegistryAmqpServerBase and moved logic to there.

[#259] Provide device registry AMQP API in hono-service-base.

---

service-base/src/main/java/org/eclipse/hono/service/registration/DeviceRegistryRestServerBase.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DeviceRegistryRestServer.java

The implementation contains only the GET operation and the interface
is not yet exposed.

[#259] Add implementation of REST interface for device registration.

---

service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationHttpEndpoint.java

Device Registry REST API: Fix routes for 'missing content-type' requests [#314]

---

site/content/component/device-registry.md
site/content/getting-started.md

The JSON structure returned by GET, PUT and DELETE requests to the device registry looks like this
`
{
"data" : {
"enabled": true,
"ep": "IMEI4711"
},
"device-id" : "4711"
}
`
, with the field name "device-id" (see `BaseRegistrationService#getResultPayload()`).
In the documentation, there was still the field name "id" being used.

Use correct 'device-id' field in Device Registry REST API documentation

---

service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java

This PR allows the usage of all the methods defined in the Credential API  (`Add` / `Get` / `Update` / `Remove`) in subclasses of `BaseCredentialsService`. Until now it was just possible to use mandatory operations (`Get`).
See issue https://github.com/eclipse/hono/issues/321
Signed-off-by: Christian Schmid <Christian.Schmid3@bosch-si.com>

Allow all credentials api operations in subclasses of BaseCredentialsService

---

core/src/main/java/org/eclipse/hono/config/KeyLoader.java

Providing the missing name in the exception helps. Especially when the value can be configured and may be even looked up using the Eclipse variable system.

Provide the name of the missing file in the exception message

---

adapters/rest-vertx/pom.xml
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/Config.java
adapters/rest-vertx/src/main/java/org/eclipse/hono/adapter/rest/VertxBasedRestProtocolAdapter.java
adapters/rest-vertx/src/test/java/org/eclipse/hono/adapter/rest/VertxBasedRestProtocolAdapterTest.java

Ok here is the rebased Pull Request #329 this should make it easier to discuss the changes.
The descriptions is unchanged, so here it is again:
This is an implementation of Basic Auth for the REST Adapter similar to the MQTT adapter authentication.
**Description:**
Username/password authentication using standard HTTP Basic Auth mechanism. Vertx provides the boiler plate code for the handling of the HTTP header and the proper 4XX error codes on authentication failure.
The hono side of things is taken from the MQTT adapter. The same single/multi-tenant logic is used as in the aforementioned pull request. It is probably a good idea to
**Open points:**
hono/adapter/rest/credentials/VertxRestUser.java they are almost identical but was not sure wether the REST authentication approach is the way …

REST adapter Basic Auth

---

jmeter/src/main/java/org/eclipse/hono/jmeter/HonoReceiverSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/AbstractClient.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSamplerUI.java

As part of this PR a new feature for JMeter Hono plugin is provided. Hono JMeter plugin could now use the time stamp from the received message (set by the sender) for sampling. This is esspecially useful when a JMeter scenario contains delays between sending messages to Hono and receiving it. The time stamp can either be part of the payload (restricted currently to JSON format) or as Application property.
Signed-off-by: Balasubramanian balasubramanian.azhagappan@bosch-si.com

Hono JMeter Plugin: Using sender Time for sampling

---

client/src/main/java/org/eclipse/hono/client/HonoClient.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/HonoClientImplTest.java

Introduced flag to recognize if client was shutdown. Using this flag to stop reconnection and also fail new connection attempts when flag was set.
Note: Also with this fix in place we have still the issue that HonoClient gets connection only when connection establishment was successful, i.e. we can not stop NetClient re-connect attempts on shutdown(). This means if someone configures ProtonClient with many reconnection attempts, or even indefinite, and/or with huge interval, NetClient still tries to re-connect even after hono client shutdown.

Fix for #339 - Hono Client does not stop re-connect after shutdown()

---

site/build-site.bat
site/pom.xml

Hi Hono Devs,
I just tried to build the project site and found out that there's just a build script for *nix based operating systems.  
As I'm developing under windows I ported the script to a windows batch file.
Maybe you're interested in it.
Cheers
Chris

Hono Site: Added support for build on MS Windows

---

example/src/main/java/org/eclipse/hono/vertx/example/HonoEventConsumer.java
example/src/main/java/org/eclipse/hono/vertx/example/HonoEventSender.java
example/src/main/java/org/eclipse/hono/vertx/example/HonoTelemetryConsumer.java
example/src/main/java/org/eclipse/hono/vertx/example/HonoTelemetrySender.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoConsumerBase.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoSenderBase.java
site/content/user-guide/java_client_sender.md

In this commit, only the documentation of the Java sender is updated
and points to the provided classes in the example module.

[#409] Update documentation of java examples.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
core/src/main/java/org/eclipse/hono/config/ProtocolAdapterProperties.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
example/src/main/sandbox/hono-adapter-mqtt-vertx-config.yml
example/src/main/sandbox/hono-adapter-rest-vertx-config.yml

This is a proposal to allow Hono's protocol adapters to include JMS vendor properties to downstream messages as described in #420

Support JMS vendor properties in REST adapter.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpAdapterMetrics.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/KuraAdapterMetrics.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttAdapterMetrics.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
example/src/main/config/influxdb.conf
service-base/src/main/java/org/eclipse/hono/service/metric/MetricConfig.java
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java

- Use common template for tagging protocol adapter metrics in influxDB
- Add number of connected devices metric to MQTT adapter

[#406] and [#312], InfluxDB templates and metrics for device connections

---

service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java

When the handler gets called it is not clear if the connection was indeed successful.
This change actually checks the result and does print out a warning if it wasn't.

Print out a warning when the connection could not be established

---

service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java

This change fixes two additional locations where the result of the
connection attempt was actually ignored. The cause is now logged as a
warning.

Fix another location where the connection result was ignored

---

service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java

This change makes to static fields actually constant by applying the
final keyword.

Constants follow constants naming scheme but are non-constant

---

core/src/main/java/org/eclipse/hono/util/JwtHelper.java
service-base/src/main/java/org/eclipse/hono/service/auth/AuthTokenHelperImpl.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationAssertionHelperImpl.java

This change does pull up common code from JwtHelper derived classes back into JwtHelper.

De-duplicate code in JwtHelper derived classes

---

.gitignore
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpProtocolAdapterProperties.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/KuraAdapterProperties.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/pom.xml
client/pom.xml
core/pom.xml
core/src/main/java/org/eclipse/hono/config/ProtocolAdapterProperties.java
core/src/main/java/org/eclipse/hono/util/AmqpErrorException.java
example/pom.xml
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoSenderBase.java
jmeter/pom.xml
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoServerOptionsPanel.java
legal/pom.xml
legal/src/main/resources/checkstyle/default.xml
legal/src/main/resources/checkstyle/suppressions.xml
pom.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractApplication.java
service-base/src/main/java/org/eclipse/hono/service/auth/BaseAuthorizationService.java
service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java
services/messaging/src/test/resources/logging.properties
services/pom.xml
tests/pom.xml

This PR works on automatic code style validation with checkstyle.
The initial changes add a global checkstyle validation on all hono projects by adding the checkstyle plugin in a multi-module setup. Failing the build when violations are found.
This change only introduces a very limited check set in order to focus on the integration of checkstyle and not on fixing code issues. Fixing code issues would be the next step.
The setup is compatible with Eclipse Checkstyle and the M2Eclipse integration. Saving a file in Eclipse automatically triggers the validation and shows error markers right away.
The validation consists of two major elements. A new module containing the checks (`hono-code-style`) and the execution of the `checkstyle-maven-plugin`. The latter part is currently added to the …

Add code check validation with checkstyle

---

client/pom.xml
client/src/main/java/org/eclipse/hono/client/ServerErrorException.java
client/src/test/java/org/eclipse/hono/client/ServerErrorExceptionTest.java

This improves the ServerErrorException in way that it will
always provide an error message and never simply "null" as message.
If no message was provided a default one (derived from the error code)
will be generated.

Provide a default message in case none was provided

---

client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/EventSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
services/messaging/src/main/java/org/eclipse/hono/event/impl/ForwardingEventDownstreamAdapter.java
services/messaging/src/main/java/org/eclipse/hono/messaging/SenderFactoryImpl.java

This change removes the manual calls to settle() and enable autoSettle
on all senders.

Switch to auto-settle instead of manually settling

---

services/messaging/src/main/java/org/eclipse/hono/event/impl/EventEndpoint.java
services/messaging/src/main/java/org/eclipse/hono/messaging/MessageForwardingEndpoint.java
services/messaging/src/main/java/org/eclipse/hono/telemetry/impl/TelemetryEndpoint.java
services/messaging/src/test/java/org/eclipse/hono/messaging/MessageForwardingEndpointTest.java

This change uses optimized EnumSets instead of manually iterating
over the array.

Use Set and EnumSet instead of iterating over array

---

client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/HonoClientImplTest.java

This change sets the connection to 'null' when it is being handled is
disconnected. This will ensure future checks on the connection won't
consider it usable.

[#457] Clearing out connection after loss of connection

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/RegistrationClientImplTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java

This is the 2nd PR for adding support for gateway devices.
It adds an assertRegistration method variant to RegistrationClient accepting a gateway ID in order
to get an assertion for a device that is connected via a gateway.

[#416] Support gateway ID in RegistrationClient.

---

core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/main/java/org/eclipse/hono/util/TenantResult.java
example/src/main/config/example-tenants.json
example/src/main/config/hono-service-device-registry-config.yml
example/src/main/deploy/docker/swarm_deploy.sh
example/src/main/deploy/kubernetes/kubernetes_deploy.sh
service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantMessageFilter.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantService.java
services/device-registry/src/main/fabric8/deployment.yml
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/Application.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantsConfigProperties.java
services/device-registry/src/test/resources/tenants.json

This is the first PR for implementing the Tenant API in Hono.
Contained is the AMQP endpoint `/tenant`, the base service for the tenant service, an example file based implementation and the support for Docker Swarm and Kubernetes.
The example file based implementation is part of the Device Registry microservice.
Not in this PR are:
- tests
- RESTful interface for the tenant API
- Hono client for the tenant API
- Usage of the tenant API in protocol adapters, the registration and credentials API (tenant needs to be checked first)
- documentation (except for javadoc)
They will follow in different PRs soon.

Tenant API implementation for AMQP endpoint.

---

pom.xml

This change fixes the annoying error:
> Artifact has not been packaged yet. When used on reactor artifact,
unpack should be executed after packaging: see MDEP-98.
It does work around this issue by simply disabling the plugin execution
in the m2eclipse plugin. This means that the IDE builder will no longer
execute the step of packaging the legal files. However running maven
itself, even from within the IDE, will still perform this step.

Fix m2eclipse error "Artifact has not been packaged yet..."

---

client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java

[#497] Don't call the closeHook if opening the sender/receiver has failed

---

adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java

Making the CredentialsService, RegistrationService extensible and also allowing the corresponding client implementation to be extensible. Concrete implementations will be able to extend them as per their need.
Signed-off-by: Bala Azhagappan <balasubramanian.azhagappan@bosch-si.com>

Making the Registration and Credentials Service API extensible

---

services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java

The device registry does print out one line on "debug" level per loaded
device. This can really spam the log when you have a larger registry
for testing.
This change lowers the output to trace and adds a summary line on
"debug" level after the load is complete.

Prevent a large file based repository from spamming the log

---

core/src/main/java/org/eclipse/hono/util/BaseMessageFilter.java
core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleConstants.java
legal/src/main/resources/checkstyle/default.xml
service-base/src/main/java/org/eclipse/hono/service/auth/AuthorizationConstants.java

This change makes use of the checkstyle module "HideUtilityClassConstructor" in order to find utility-only classes which have an accessible constructor. If the class is a utility-only class creating a new instance from it is an error.
With a few exceptions Hono already follows this approach. So aside from adding the check only a few classes had to be fixed.

Check that constructors of utility-only classes are hidden

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpProtocolAdapterProperties.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java

This makes the API consumable by web applications (swagger-ui in my case).
The OPTIONS method is used by browsers to do a pre-flight validation,
and must be accessible without authentication. The web application will
then check for the precense and correctness of CORS related headers.
Signed-off-by: Sebastian Poehn <sebastian.poehn@bosch-si.com>

http-adapter: Implement OPTIONS method and add CORS handler

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoAuthHandlerImpl.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpAdapterMetrics.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/KuraAdapterMetrics.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttAdapterMetrics.java
core/src/main/java/org/eclipse/hono/config/FileFormat.java
core/src/main/java/org/eclipse/hono/config/KeyLoader.java
core/src/main/java/org/eclipse/hono/config/PemReader.java
core/src/main/java/org/eclipse/hono/util/EndpointType.java
core/src/main/java/org/eclipse/hono/util/Strings.java
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoReceiverSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/ServerOptionsPanel.java
legal/src/main/resources/checkstyle/default.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/metric/MetricConfig.java
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/NullCounterService.java
service-base/src/main/java/org/eclipse/hono/service/metric/NullGaugeService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
services/messaging/src/main/java/org/eclipse/hono/messaging/ForwardingDownstreamAdapter.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplicationConfig.java
services/messaging/src/main/java/org/eclipse/hono/messaging/MessageDiscardingDownstreamAdapter.java
services/messaging/src/main/java/org/eclipse/hono/messaging/MessageForwardingEndpoint.java
services/messaging/src/main/java/org/eclipse/hono/messaging/MessagingMetrics.java

This PR aims fixing #542 by adding a few codestyle checks and fixing the remaining violations detected. 
The checks enabled are:
* Require javadoc for public types and methods
* Require valid HTML, end of first sentence punctuation
* Check for empty javadocs and at-clauses
I did not enable the check to validate public (global) variables as too many javadocs would have been missing, so I think this might need further discussion. Although I would recommend to document publicly accessible fields. You can check the outcome by adding the following snipped to `default.xml` checkstyle file:
~~~xml
<module name="JavadocVariable">
<property name="scope" value="public"/>
</module>
~~~

Enable a few Javadoc codestyle checks

---

client/pom.xml
core/pom.xml
pom.xml

This change adds the maven-bundle-plugin in order to generate OSGi
metadata during the build. Currently only for core and client.
---
This PR is intended to let people see the changes introduced by adding OSGi support.

[#475]: Enable support for OSGi

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttAdapterMetrics.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java

This change does fix two issues with the MQTT connection count metrics.
The first issue is a simple mistake of calling increment instead of
decrement. The second issue ignores unauthenticated MQTT connections in
the metrics.

Fix MQTT message count metrics

---

service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java

Create response for delete tenant out of request in order to include correlation-id.
I am a little bit lost how to test this. I would favour to have an integration test, but as removing tenants is not part of public API you cannot use tenant client. However, I tested it manually and it works. Any suggestions how to test this in a realistic way?
Signed-off-by: Daniel Maier <daniel.maier@bosch-si.com>

Fix for #601 - Response for delete tenant is broken in BaseTenantService

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
core/src/main/java/org/eclipse/hono/util/CredentialsObject.java
core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/test/java/org/eclipse/hono/util/CredentialsObjectTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoChainAuthHandler.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/SubjectDnCredentials.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/X509AuthProvider.java
service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
site/content/api/Credentials-API.md
site/content/release-notes.md
site/content/user-guide/http-adapter.md
tests/pom.xml
tests/src/test/java/org/eclipse/hono/tests/CrudHttpClient.java
tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/http/EventHttpIT.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/http/TelemetryHttpIT.java
tests/src/test/resources/http/logback-spring.xml

This PR adds client based authentication to the HTTP adapter as required by #555. The PR includes the implementation of a corresponding vert.x-web AuthHandler, an AuthProvider for verifying the certificate, documentation and integration test cases for uploading telemetry and event messages using HTTP with basic auth as well as with client cert based auth.

Add client cert based auth to http adapter

---

site/content/getting-started.md
site/content/release-notes.md
site/content/user-guide/http-adapter.md

Update the release notes and http adapter use guide section to include uploading telemetry messages using QoS 1

[#526] release notes & user guide update

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/Config.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/Constants.java
core/src/main/java/org/eclipse/hono/util/EventConstants.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
core/src/main/java/org/eclipse/hono/util/MessageTap.java
core/src/main/java/org/eclipse/hono/util/TimeUntilDisconnectNotification.java
core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
core/src/test/java/org/eclipse/hono/util/MessageTapTest.java
example/src/main/java/org/eclipse/hono/devices/HonoHttpDevice.java
example/src/main/java/org/eclipse/hono/vertx/example/HonoEventConsumer.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoConsumerBase.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/http/HttpUtilsTest.java

Http clients of the HTTP protocol adapter can set the `ttd` AMQP property
for any command by using the `hono-ttd` HTTP header (scaled in seconds).
Northbound applications can register a specific callback that is invoked
if at the current time the device indicated it will still be connected.

Allow devices to indicate readiness-to-receive-messages (impl).

---

adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/main/resources/logback-spring.xml
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
example/src/main/config/hono-adapter-http-vertx-config.yml
example/src/main/config/hono-adapter-mqtt-vertx-config.yml
example/src/main/config/qpid/qdrouterd-with-broker.json
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/command/Command.java
service-base/src/main/java/org/eclipse/hono/service/command/CommandAdapter.java
service-base/src/main/java/org/eclipse/hono/service/command/CommandConnection.java
service-base/src/main/java/org/eclipse/hono/service/command/CommandConnectionImpl.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/command/CommandConnectionTest.java
tests/src/test/java/org/eclipse/hono/tests/command/CommandIT.java

- Abstract adapter can open receivers for Command and Control and send back a response.
- QPID dispatcher and MQTT/HTTP adapters in example configured.

Adapter side of the Command and Control API.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/Constants.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoConsumerBase.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java

This PR contains the fully working version of "void" commands for the HTTP adapter.
Included also is the extended example consumer, which now reacts to a notification callback (having been empty before) by trying to send a command upstream.
The result can be watched e.g. by using `curl`, like the following:
```
$ curl -X POST -i -u sensor1@DEFAULT_TENANT:hono-secret -H 'Content-Type: application/json' --data-binary '{"temp": 5}' http://localhost:8080/telemetry?hono-ttd=10
```
resulting in
```
HTTP/1.1 202 Accepted
hono-command: setBrightness
hono-cmd-req-id: 47#cmd-client-f577a018-32ba-4b14-bc1f-902acc77da12/28c2b33a-a5f7-4962-8dcf-316725583cb9
Content-Length: 82
{
"brightness" : 6,
"correlationId" : "0315ad62-32a1-497e-80d6-950dbf6d8f02"
}
```

Hono HTTP adapter Command and Control.

---

adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java

@sophokles73: This PR test the functionality of the AMQP adapter (unauthenticated devices)

[#643] Tests for AMQP Adapter

---

core/src/main/java/org/eclipse/hono/config/AbstractConfig.java
site/content/user-guide/http-adapter.md

* The `400 (Bad Request)` status code is not correctly formatted in the HTTP Adapter documentation. It should have a formatting similar to the `403 (Forbidden)` status code
* Bootstrapping a protocol adapter requires doing the ff. minimal checks:
* check if ports are configured correctly
* check if either a secure or non-secure port is enabled.
All these checks relies on making a call to `AbstractConfig#getKeyCertOptions()`. Each time such a call is made,we instantiate a new `KeyCertPathOptions` object and set the path to `key and `cert` files. 
This patch caches the instance so that it is used by subsequent calls.
@sophokles73

Improve service configuration

---

adapters/http-vertx-base/pom.xml
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/ComponentMetaDataDecorator.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/pom.xml
bom/pom.xml
core/pom.xml
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
core/src/main/java/org/eclipse/hono/util/ExecutionContext.java
legal/legal/NOTICE.md
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java

All standard adapters are instrumented using OpenTracing in order to be
able to track the processing of messages that have been uploaded by
devices.
In this first step, only the handlers for incoming HTTP requests and
published MQTT messages are instrumented, i.e. we only trace the
incoming request and the outcome of processing the request at a very
high level.

[#319] Add high level tracing to HTTP and MQTT adapters.

---

client/pom.xml
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java

The corresponding Spring library dependencies are declared *provided* in
the POM so the client artifact should be usable without Spring on the
classpath as well (e.g. in an OSGi environment).

[#319] Allow auto wiring of OpenTracing Tracer into HonoClientImpl.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterConstants.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
core/src/main/java/org/eclipse/hono/util/AuthenticationConstants.java
core/src/main/java/org/eclipse/hono/util/Constants.java
service-base/src/main/java/org/eclipse/hono/service/auth/AbstractHonoAuthenticationService.java

@sophokles73 
This patch extends the Amqp adapter to provide support for authenticating client devices. Currently, only the `SASL PLAIN` mechanism is supported.

[#643] Amqp Adapter - support for device authentication

---

core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java

With this PR it is possible to enable the usage of native TLS implementations in protocol adapters.
It does however not yet contain any dependency to a specific implementation.
To use native TLS a user still  has to add a concrete dependency to a specific `netty-tcnative` in the adapters maven dependencies.

Allow usage of native tls implementation in protocol adapters

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java

The protocol adapters include the sending of downstream telemetry and
event messages in the overall OpenTracing span for processing a request.

[#319] Include downstream messages in tracing.

---

jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoReceiverSamplerUI.java

This fixes #701:
Adds RadioButtons for the `useSenderTime` options to make clear what the default behaviour is.
Also fixes alignment and padding of the `endpoint` JLabeledChoice.

[#701] Improve JMeter plugin Receiver UI concerning useSenderTime options

---

jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java

This fixes #703:
Make the timeout for sending a message configurable.

[#703] JMeter plugin: Sender timeout configurable

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoAuthHandler.java
service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
service-base/src/test/java/org/eclipse/hono/service/auth/device/HonoAuthHandlerImplTest.java

A DefaultFailureHandler is now registered on the adapter's Router to
handle ServiceInvocationExceptions that have caused a RoutingContext to
fail. The handler creates an HTTP response corresponding to the
exception's fields.
The HttpUtils methods now fail the routing context with a
ServiceInvocationException instead of just a status code. This way we
can convey additional information to the client, e.g. the detail message
that is contained in the exception.

Improve error handling of HTTP adapter and HTTP based endpoints.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/X509AuthHandler.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/TenantClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TenantClientImpl.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java

The TenanClientImpl methods have been instrumented with OpenTracing API calls.
The protocol adapters invoke the variants of the TenantClient's methods that accept a SpanContext.

[#319] Support tracing of TenantClient requests.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/Config.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java

This patch improves the AMQP adapter code base to allow it to properly authenticate client devices using SASL PLAIN.
@sophokles73: These changes were included in the ITs patch. This split contains only changes made to the adapter code base.

amqp adapter - Improve device authentication

---

site/content/api/Metrics.md

This is a first version of documenting the existing Hono metrics which are considered API.
Currently it leaves out:
* Everything from the Kura adapter
* The AMQP specific metrics from the messaging service (e.g. `connections.downstream`, `link.downstream.credits`, …)
Leaving those metrics out doesn't mean we drop them right away, but we might change them between releases without prior notice.
Please let me know if you need any of the above (left out) metrics in the documented list or if I overlooked something.

[#645]: Document current metrics structure

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java

@sophokles73: While working on the integration tests, I detected that the tenant-id is used in place of the device-id during address validation. I don't want to mix this change with the ITs and is the reason for creating a separate PR.

[#643] Bug Fix: Use device-id of authenticated device

---

cli/src/main/java/org/eclipse/hono/cli/AbstractClient.java
cli/src/main/java/org/eclipse/hono/cli/AppConfiguration.java
cli/src/main/java/org/eclipse/hono/cli/Receiver.java
cli/src/main/resources/application.yml

With reference to #331, now connection timeout parameter and QueryResolverOptions are configurable.
Example:mvn spring-boot:run -Drun.arguments=--hono.client.host=localhost,--hono.client.username=consumer@HONO,--hono.client.password=verysecret,**--address.resolver.queryTimeout=5000**,**--connection.timeout=3000**

[#331] Make connection timeout params configurable

---

tests/pom.xml
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java
tests/src/test/java/org/eclipse/hono/tests/amqp/EventAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/amqp/TelemetryAmqpIT.java
tests/src/test/resources/amqp/application.yml
tests/src/test/resources/amqp/logback-spring.xml

@sophokles73: Integration tests for the AMQP adapter. This implementation uses `ProtonClient` instead of `HonoClient`. This patch relies on #739 to be merged first before the travis build can pass. If merged, i will rebase this PR

[#643] AMQP adapter integration tests

---

adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/KuraProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/CommandConstants.java
core/src/main/java/org/eclipse/hono/util/EndpointType.java
core/src/main/java/org/eclipse/hono/util/MessageTap.java
core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoConsumerBase.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/command/CommandSubscription.java
service-base/src/test/java/org/eclipse/hono/service/command/CommandSubscriptionTest.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingMessageFilter.java
site/content/concepts/command-and-control.md
site/content/release-notes.md
site/content/user-guide/mqtt-adapter.md

- subscription for commands (long and short version).
- send ttl events on subscription and unsubscribe.
- get commands for a device and publish it to subscription.
- command response endpoint to send the result of a received command.
- allow empty event bodies (for the ttl events).

[#633] Command and Control for MQTT.

---

site/content/admin-guide/amqp-adapter-config.md
site/content/user-guide/amqp-adapter.md

Documentation for the AMQP adapter (for the hono website)
@sophokles73:  If i have #727 on master, i will rebase this PR on master

[#643] AMQP Adapter documentation

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HttpAdapterMetrics.java
deploy/src/main/config/grafana/dashboard-definitions/grafana_dashboard.json
deploy/src/main/deploy/influxdb.conf
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
site/content/api/Metrics.md
site/content/release-notes.md

Below metrics are added for Command and Control (HTTP).
- Commands delivered (command delivered to device before ttd expires)
- TTD expiries (ttd expired with no command received from applications)
- Commad responses delivered (command response delivered from device to application)
Also the Grafana dashboard has been changed to accommodate the above metrics from command and control for both HTTP and MQTT adapters. For more info refer #632.

[#632] Add metrics for Command and Control to HTTP adapter

---

core/src/main/java/org/eclipse/hono/config/VertxProperties.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java

This PR introduces a common way to configure vertx specific options. As a first option is allows to set whether to prefer native TCP sockets or not.
Using native sockets still requires e.g. the netty epoll or kqueue implementation. However simply adding this dependency doesn't enable it unless the flag in the vertx option is set.
This is independent of the native TLS implementation!

Allow to customize vertx options and set option to prefer native sockets

---

.travis.yml
bom/pom.xml
cli/pom.xml
core/pom.xml
service-base/pom.xml

This change also contains the necessary upgrades and fixes for
successfully running the unit tests on Travis.
---
Please see this a a preview PR, which we can use for discussions.

Enable JDK 10 build on Travis in addition to JDK 8

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/CommandClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TenantClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
client/src/test/java/org/eclipse/hono/client/impl/CommandClientImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/TenantClientImplTest.java
core/src/main/java/org/eclipse/hono/util/BufferResult.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoConsumerBase.java
service-base/src/main/java/org/eclipse/hono/service/command/Command.java
site/content/api/Command-And-Control-API.md
site/content/user-guide/http-adapter.md
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java

So far, the C&C API doesn't explicitly support the usage of Content-Type. IMHO it is worth doing so, even if not all protocol adapters will be able to forward the type information hence and forth due to limitations of the transport protocols.

Support content type in command messages

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
tests/pom.xml
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/resources/amqp/application.yml
tests/src/test/resources/qpid/qdrouterd-with-broker.json

@sophokles73: this patch adds support for client certificate authentication. now the auth providers are known only to the SaslAuthenticator class. i plan to test feature in the ITs. 

[#643] Add support for client certificate based authentication

---

cli/src/main/java/org/eclipse/hono/cli/AmqpSend.java

@sophokles73: The amqp command-line should include the `SASL PLAIN` mechanism in its connection options. Otherwise, the AMQP adapter picks `SASL EXTERNAL` as the best matching mechanism when authenticating to the adapter.

Bug Fix: AMQP command-line client

---

adapters/coap-vertx-base/pom.xml
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAdapterMetrics.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapAdapterProperties.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapErrorResponse.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/coap-vertx-base/src/test/resources/logback-test.xml
adapters/coap-vertx/pom.xml
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/Application.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/CoapRequestHandler.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/Config.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/ExtendedDevice.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxBasedCoapAdapter.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxCoapResource.java
adapters/coap-vertx/src/main/resources/banner.txt
adapters/coap-vertx/src/main/resources/logback-spring.xml
adapters/coap-vertx/src/test/resources/logback-test.xml
adapters/pom.xml
bom/pom.xml
core/src/main/java/org/eclipse/hono/util/Constants.java

coap adapter update to work with hono 0.7-SNAPSHOT after hono 07-M2.
Supports x.509 client authentication.
Obsoletes my old PR #599 

Coap adapter 0.7

---

client/src/main/java/org/eclipse/hono/client/MessageSender.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java

All send method variants accepting a send queue drain handler have been
deprecated.

Deprecate usage of send queue drain handler.

---

tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java

@sophokles73: In the MQTT C&C integration test, the wrong variable names were used in the `testSendCommandFailsForMalformedMessage` test. this trivial patch fixes that.

BugFix: Fix wrong variable names in C&C ITs for the MQTT adapter

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
cli/src/main/java/org/eclipse/hono/cli/Receiver.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/AuthenticationServerClient.java
client/src/main/java/org/eclipse/hono/client/impl/TenantClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
core/src/main/java/org/eclipse/hono/util/MessageTap.java
core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
core/src/test/java/org/eclipse/hono/util/MessageTapTest.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoConsumerBase.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoReceiver.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/command/CommandResponseSenderImpl.java
service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsMessageFilter.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationMessageFilter.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantMessageFilter.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingMessageFilter.java
services/messaging/src/test/java/org/eclipse/hono/TestSupport.java
site/content/api/Credentials-API.md
site/content/api/Device-Registration-API.md
site/content/api/Tenant-API.md
site/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/jms/DeviceRegistrationIT.java
tests/src/test/java/org/eclipse/hono/tests/jms/RegistrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/jms/SendReceiveIT.java

This PR switches to always use the the 'Data' type for AMQP body sections. As of now, it still can receive AmqpValue body sections of type byte[] or String in addition. However I am not sure if we should keep this.

[#607]: Use 'Data' type for AMQP body section

---

pom.xml
tests/pom.xml

This change does enable the code coverage agent for containers when
running the integration tests in hono-tests.

Enable code coverage for integration tests

---

jmeter/src/main/java/org/eclipse/hono/jmeter/HonoCommanderSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSamplerUtils.java
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoCommander.java
jmeter/src/main/java/org/eclipse/hono/jmeter/sampleresult/HonoCommanderSampleResult.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoCommanderSamplerUI.java

This PR contains HonoCommanderSampler, using which settings required to perform load test for feature Command and Control can be configured. Users can choose the type of protocol being used (http or mqtt) for communication between devices and hono. This sampler establishes connection to hono, get devices that are ready to receive commands under a particular tenant, send commands and receive command responses.This sampler can be combined with standard Jmeter samplers (for example HTTP Request Sampler) to create a test plan for C&C.

[#624] Jmeter client for Command and Control to enable load tests

---

.travis.yml

This PR simply replaces the currently used OracleJDK 11 with OpenJDK 11 because OpenJDK is what we also use in our Docker images.

Use OpenJDK 11 instead of OracleJDK 10 on Travis.

---

jenkins/Hono-CI-Pipeline.groovy
jenkins/Hono-PipelineUtils.groovy

With reference to #557,  all the jenkins build jobs are to be implemented as pipelines. To start with, jenkins [Hono-CI](https://ci.eclipse.org/hono/job/Hono-CI/) build job is to be implemented as a pipeline. This PR contains respective pipeline scripts.
Below screen shot is from a local jenkins after deploying above scripts:

[#557] Pipeline script for Hono-CI jenkins build job

---

service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java

The computation of a password hash can be quite time consuming if e.g.
bcrypt is used as the hash algorithm. Thus it seems feasible to move the
password hash validation from the event loop to a worker thread.

[#825] Run password hash validation on vert.x worker thread.

---

jenkins/Hono-Nightly-Pipeline.groovy
jenkins/Hono-PipelineUtils.groovy

Hono repo can be checked out without credentials for the nightly build and this PR contains changes for that.

Checkout git repo without credentials for nightly build pipeline

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/command/Command.java
service-base/src/main/java/org/eclipse/hono/service/command/CommandResponse.java
tests/pom.xml
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpAdapterTestBase.java

@sophokles73 This patch address #784, with two separate commits:
* 6b67f7b: allow clients to subscribe to commands + unit tests
* 86bb838: allow clients to publish command responses + unit tests

[#784] AMQP Adapter: Implement Command & Control

---

core/src/main/java/org/eclipse/hono/config/VertxProperties.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java

This disables the external vertx metrics configurations, as Spring Boot is the main driver of this now. Vertx itself can be enabled, using the vertx options of Hono. However it is disabled by default, as some of the vertx metrics can really blow the metrics backends.

Drop the vert.x metrics options, and allow disabling vertx metrics.

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java

When devices try to connect to the Mqtt adapter with credentials, then the Mqtt adapter checks for the device registration in addition to the credentials validation, before establishing a connection.

[#876] Deleted devices should not be able to connect to the Mqtt adapter

---

adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/CommandConnection.java
client/src/main/java/org/eclipse/hono/client/ResourceConflictException.java
client/src/main/java/org/eclipse/hono/client/StatusCodeMapper.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConnectionImpl.java
client/src/test/java/org/eclipse/hono/client/impl/CommandConnectionImplTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
site/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java

The CommandConnection.getOrCreatedCommandConsumer method has been renamed to
createCommandConsumer and will no longer return an already existing
instance of a command consumer for a given device but will instead fail
the returned future with an
org.eclipse.hono.client.ResourceConflictException to indicate that a
consumer for the given device is already in use.
The original behavior allowed an implementation to return a consumer
that was scoped to another message handler than the one passed into the
method as an argument. However, client code had no chance to determine
whether it got back a newly created instance or an existing one. This
has been resolved with the new method semantics.
There is now also an integration test for the HTTP adapter which
verifies the correct behavior when a …

Do not return cached command consumers

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/CommandConnection.java
client/src/main/java/org/eclipse/hono/client/CommandConsumer.java
client/src/main/java/org/eclipse/hono/client/StatusCodeMapper.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConnectionImpl.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/CommandConnectionImplTest.java

This PR addresses #830 
A straightforward approach for solving the issue would be to simply re-create all links once the connection is re-restablished. However, with a large number of devices connected to the adapter instance, this might result in a *burst* of link establishment traffic whose outcome is hard to predict.
The approach taken by this PR is therefore a different one: when a device subscribes to commands and a corresponding CommandConsumer is created, a device specific liveness check is registered which periodically checks for the link to be *alive* and, if not, tries to re-create the link. This should provide for much better distribution of re-creation attempts while being able to automatically recover from the connection loss.

Handle command connection loss

---

client/src/main/java/org/eclipse/hono/client/Command.java
client/src/main/java/org/eclipse/hono/client/CommandClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
client/src/test/java/org/eclipse/hono/client/CommandTest.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractHonoClientTest.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
client/src/test/java/org/eclipse/hono/client/impl/CommandClientImplTest.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java

This is step 1 of a sequence of PRs for implementing #669 : it provides the base for sending one-way commands in a different implementation (not using `createAndSend` methods anymore, but still sharing the `sendRequest` method with the AbstractRequestResponseClient).
The commandClient can decide for each command if a response from the device is expected or not by choosing different send methods:
`sendCommand` or `sendOneWayCommand`.
It was tested with the HTTP adapter and an extended example app - both are not part of this PR though and follow in a subsequent PR.

[#669] Alternative implementation for one-way pattern for commands.

---

client/src/main/java/org/eclipse/hono/client/CreditBasedSender.java
client/src/main/java/org/eclipse/hono/client/MessageSender.java
client/src/main/java/org/eclipse/hono/client/RequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
site/content/release-notes.md

Added interface `CreditBasedSender` with methods to check credits and to set a drain handler. With reference to the issue #888, this PR also provides possibility for the command client to retrieve the _available credits_ and also to set a _drain handler_.

[#888] Added interface CreditBasedSender with methods to check credits and to set a drain handler

---

service-base/src/main/java/org/eclipse/hono/service/metric/AbstractLegacyMetricsConfig.java
service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplication.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplicationConfig.java
services/messaging/src/main/java/org/eclipse/hono/messaging/LegacyMetricsConfig.java
services/messaging/src/main/java/org/eclipse/hono/messaging/MicrometerBasedMessagingMetrics.java
services/messaging/src/test/java/org/eclipse/hono/messaging/MicrometerBasedMessagingMetricsTest.java

Use separate LegacyMetricsConfig component for mapping Hono Messaging
metrics to Graphite meter names to minimize dependencies.

Add missing tags to Hono Messaging metrics.

---

service-base/src/main/java/org/eclipse/hono/service/EventBusService.java

This is for #914:
Making a `Tracer` instance available to the `CredentialsService`, `TenantService` and `RegistrationService` implementations.

[#914] Add Tracer instance in EventBusService

---

services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/Application.java

Currently the tenant service is not considered for health checks. I know that currently it doesn't implement it, but the pattern is the same for the other services.

Allow tenant service to participate in the health checks

---

service-base/src/main/java/org/eclipse/hono/service/AbstractApplication.java

This change makes it easier to implement custom services using existing Hono functionality. Instead of requiring the return of a `Future<Void>` it is possible to return a `Future<?>`, making it possible to also return e.g. a `CompositeFuture`.
As the return turn "value" of `Void` is never used anyway, and the wildcard (`?`) is less strict than the current `Void`, this should have no effect on existing implementations.

Make it easier to implement custom services

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandler.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
jmeter/src/main/java/org/eclipse/hono/jmeter/sampleresult/HonoCommanderSampleResult.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoChainAuthHandler.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordCredentialsTest.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/FileBasedAuthenticationService.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java
services/messaging/src/main/java/org/eclipse/hono/messaging/ForwardingDownstreamAdapter.java
services/messaging/src/main/java/org/eclipse/hono/messaging/HonoMessagingApplication.java

* In some tests, the arguments to `assertEqual(expected, actual)` are swapped, resulting in `assertEqual(actual, expected)`
* `AbstractServiceBase` defines a logger instance to be shared by all subclasses. child classes (esp. protocol adapters) can simply use that instance.
* `receiversPerConnection` and `activeSenders` instances can never be null
* ...

trivial fixes/improvements

---

core/src/main/java/org/eclipse/hono/tracing/MultiMapExtractAdapter.java
core/src/main/java/org/eclipse/hono/tracing/MultiMapInjectAdapter.java
core/src/test/java/org/eclipse/hono/tracing/MultiMapInjectExtractAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantAmqpEndpoint.java
service-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsAmqpEndpointTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/RegistrationAmqpEndpointTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/TenantAmqpEndpointTest.java

Put the `SpanContext`, extracted from an AMQP message received at a `RequestResponseEndpoint`, into the delivery headers of the vert.x event bus message.
This is for #914.

[#914] Put extracted SpanContext into EventBusMessage delivery headers

---

client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java

This adds a missing `finish()` invocation on the `Span` created in `AbstractRequestResponseClient.createAndSendRequest()`.

Finish Span created in createAndSendRequest()

---

core/src/main/java/org/eclipse/hono/util/EventBusMessage.java
service-base/src/main/java/org/eclipse/hono/service/EventBusService.java

Followup of #935: 
Extract the `SpanContext` from the delivery headers of the vert.x event bus message and put the `SpanContext` in the `EventBusMessage`.
This is for #914.

[#914] Extract SpanContext in EventBusService; put in EventBusMessage

---

service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyRegistrationService.java
site/content/release-notes.md

Alternative to #955.
Create and pass on span in "processAssertRequest" method.
Use Span instead of SpanContext parameter in "assertRegistration" methods.
This is for #914.

[#914] Create span in "assertRegistration" methods (2)

---

service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantService.java
service-base/src/test/java/org/eclipse/hono/service/tenant/BaseTenantServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/CompleteBaseTenantServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyTenantService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
site/content/release-notes.md

Create and pass on span in "TenantService#processGetRequest" method.
Use Span instead of SpanContext parameter in "TenantService#get" methods.
This is for #914.

[#914] Create span for TenantService.get

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java

Expose metrics to sub classes of `AbstractVertxBasedHttpProtocolAdapter`.

Http/Mqtt adapter: Add getter for metrics.

---

core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java

Currently the `logError(Span, Map<String, ?>)` method creates an output in the Jaeger UI like this:
````
15.67ms:    message=device not enabled
15.67ms:    event=error
````
This commit causes just _one_ log entry to be created here - with the `event=error` item added to the given items.

Let "logError" only create one log entry (with event=error included).

---

deploy/src/main/deploy/openshift_s2i/containers/custom-base/Dockerfile
deploy/src/main/deploy/openshift_s2i/hono-template.yml

This PR changes the OpenShift S2I deployment to use Java 11 as a JRE.

Switch OpenShift S2I to Java 11

---

tests/pom.xml
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttPublishTestBase.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttTestBase.java
tests/src/test/resources/mqtt/logback-spring.xml

Added tests for verifying connection establishment using an X.509 client
certificate with the MQTT adapter and for publishing messages.

[#349] Add integration tests for X.509 based authentication.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/VertxBasedAmqpProtocolAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandler.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/HonoBasicAuthHandlerTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/vertx/VertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/CredentialsClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java
core/src/main/java/org/eclipse/hono/tracing/JsonObjectExtractAdapter.java
core/src/main/java/org/eclipse/hono/tracing/JsonObjectInjectAdapter.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
core/src/test/java/org/eclipse/hono/tracing/JsonObjectInjectExtractAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/HonoClientBasedAuthProvider.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/X509AuthProvider.java
service-base/src/test/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProviderTest.java
service-base/src/test/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProviderTest.java

The `CredentialsClient` interface has been extended here to include a `SpanContext` param. The span context is used in the `CredentialsClientImpl` to create a span for the `get Credentials` operation.
In order to get the span context in the `CredentialsClient`, it has to be passed along via the `io.vertx.ext.auth.AuthProvider` interface implementation. 
As it was desired to keep using the standard `io.vertx.ext.web.handler.AuthHandler` implementation (and therefore only the standard `io.vertx.ext.auth.AuthProvider#authenticate` method could be used), the SpanContext is serialized and passed along via the 'authInfo' JsonObject param of the `io.vertx.ext.auth.AuthProvider#authenticate` method (see `CredentialsApiAuthProvider#injectSpanContextIntoAuthInfo` and …

[#974] Add Tracing support for CredentialsClient

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
core/src/main/java/org/eclipse/hono/config/ProtocolAdapterProperties.java
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java

Connections are rejected once the connection limit is reached.
Currently the limit is fixed on Long.MAX_VALUE, needs to be made
configurable and/or auto-configurable later on.

[#931] Limit number of connections in MQTT adapter

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
deploy/src/main/config/grafana/dashboard-definitions/message-details.json
deploy/src/main/config/grafana/dashboard-definitions/overview.json
service-base/src/main/java/org/eclipse/hono/service/metric/AbstractLegacyMetricsConfig.java
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java
service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
site/content/api/Metrics.md

The payload size has been added as a parameter to the reportTelemetry
methods. The type of the meter for the payload size has been changed to
DistributionSummary in order to be able to track the distribution of
payload sizes as well.

[#961] Include payload size in reporting of telemetry messages.

---

pom.xml

We do know that Hono no longer builds with the Java 8 compiler. And we moved on to Java 11 in general.
So I think it makes sense enforcing this in the maven build, so that you get a proper error instead of a weird compiler error.

Enforce Java 11 during the build

---

core/src/main/java/org/eclipse/hono/util/TenantObject.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java

When the parsing of the trusted-ca cert (trust anchor) of the tenant failed this did not show up in the logs of the protocol adapter. It's is helpful to see this in logs when trying of client certs locally.

Log the exception when parsing the trust anchor from the tenant.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandHandler.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/Command.java
deploy/src/main/config/grafana/dashboard-definitions/overview.json
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/metric/LegacyMetrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/Metrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/MetricsTags.java
service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedLegacyMetrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/NoopBasedMetrics.java
service-base/src/main/java/org/eclipse/hono/service/metric/NoopLegacyMetrics.java
service-base/src/test/java/org/eclipse/hono/service/metric/LegacyMetricsConfigTest.java
site/content/api/Metrics.md

Command messages are now tracked analogously to telemetry and events
using a Timer meter and tags indicating the direction and outcome of
processing the messages.
The Overview dashboard has been changed to display C&C related
information alogously to telemetry and event messages.
Here's the adapted Overview dashboard with a separate graph for the rate of messages which could not be processed/delivered and threshold markers:
Here's the original dashboard:
FMPOV the numerical displays do not provide any information in addition to the graphs but require more queries being run on the Prometheus back end.

[#961] Use "Timer" meter for command messages.

---

services/device-registry/src/test/resources/device-identities.json

Fixed the location of the comment in file `device-identities.json` in test resources of device registry.

Fix in file `device-identities.json` in test resources

---

service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
site/content/admin-guide/device-registry-config.md
site/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java

Device registration service now supports multiple gateway identifiers to
be specified in a device's registration information's "via" property.
The "via" property can be set to either a string or a JSON array of
strings.

[#926] Support authorization of multiple gateways per device.

---

client/src/main/java/org/eclipse/hono/client/CommandConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractRequestResponseClientTest.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
client/src/test/java/org/eclipse/hono/client/impl/TenantClientImplTest.java
core/src/main/java/org/eclipse/hono/tracing/MessageAnnotationsExtractAdapter.java
core/src/main/java/org/eclipse/hono/tracing/MessageAnnotationsInjectAdapter.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
core/src/test/java/org/eclipse/hono/tracing/MessageAnnotationsInjectExtractAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java

The span context will now be injected in and extracted from the map value of a "x-opt-trace-context" message annotation.
Fix for #1046 and #1012.

[#1046][#1012] Fix encoding of OpenTracing span context in AMQP message

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/Application.java
adapters/pom.xml
bom/pom.xml
deploy/src/main/config/grafana/dashboard-definitions/overview.json
deploy/src/main/deploy/docker/swarm_deploy.sh
deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yml
deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-auth/hono-service-auth-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-deployment.yaml
deploy/src/main/deploy/resource-descriptors/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
deploy/src/main/deploy/resource-descriptors/hono-adapter-http/hono-adapter-http-vertx-deployment.yml
deploy/src/main/deploy/resource-descriptors/hono-adapter-kura/hono-adapter-kura-deployment.yaml
deploy/src/main/deploy/resource-descriptors/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
deploy/src/main/deploy/resource-descriptors/hono-service-auth/hono-service-auth-deployment.yaml
deploy/src/main/deploy/resource-descriptors/hono-service-device-registry/hono-service-device-registry-deployment.yaml
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/VertxBasedHealthCheckServer.java
service-base/src/main/java/org/eclipse/hono/service/metric/PrometheusScrapingResource.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/Application.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/ApplicationConfig.java
services/pom.xml
tests/pom.xml
tests/src/test/resources/amqp/application.yml
tests/src/test/resources/auth/application.yml
tests/src/test/resources/deviceregistry/application.yml
tests/src/test/resources/http/application.yml
tests/src/test/resources/mqtt/application.yml

Use the vertx-web based HealthCheckServer's HTTP server to expose a
resource for scraping the PrometheusMeterRegistry of Hono components.
This way we do not need to spawn up a jetty server just for serving the Prometheus scraping endpoint and can prevent including a bunch of additional jars when we already have a (running) HTTP server in place.
In this initial version, the scraping and health check endpoints are exposed on an unsecured port (no TLS) without authentication. However, this can be added in a subsequent PR.

Replace Spring Boot Actuator with vertx-web based Prometheus endpoint.

---

services/device-registry/readme.md

The readme of module `device-registry` mentioned that it implements the Credentials and the Registration APIs. Added the Tenant API to the description for more clarity on this level of information.

Fix description of device registry in readme: add tenant API.

---

.travis.yml
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/vertx/VertxBasedCoapAdapter.java
core/src/main/java/org/eclipse/hono/util/AuthenticationConstants.java
core/src/main/java/org/eclipse/hono/util/Hostnames.java
core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
pom.xml
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/FileBasedAuthenticationService.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java

As Hono has problems building on Java 8, and we already ship Java 11
images, we decided to fully switch to Java 11. But keeping the
classpath model.
This PR switches to Java 11 for source+target, and also makes use
of a few Java 11-only features, just test it.

Set Java 11 as source+target version

---

services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AbstractFileBasedRegistryConfigProperties.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationServiceTest.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationOptionalAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantAmqpIT.java
tests/src/test/resources/deviceregistry/application.yml

Hi, 
This is a quick draft to raise some discussion on how to implement a way to populate the device registry with the data needed for the integration tests, as stated in issue #1056. 
Here I used a `@Before` method and used the `DeviceRegistryHttpClient` to push the data in the device registry. 
Maybe a it would be better to directly load the Json file and push it as it is in the DR, to have a single source of data. Imo, that would improve maintainability (and readibility, as creating those JSON object programatically isn't very pleasant)..
What do you guys thinks ?

[#1056] Populate the device registry with the expected data before running Integration Tests

---

site/content/release-notes.md

The PR that adds support for connection limits to the AMQP protocol
adapter has been merged after the release of 0.9, but the release notes
mentioned it under 0.9.

Fix Release Notes: Connection limit for AMQP is not Hono 0.9.

---

adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
client/src/main/java/org/eclipse/hono/client/ConnectionLifecycle.java
client/src/main/java/org/eclipse/hono/client/CredentialsClientFactory.java
client/src/main/java/org/eclipse/hono/client/DisconnectListener.java
client/src/main/java/org/eclipse/hono/client/DownstreamSenderFactory.java
client/src/main/java/org/eclipse/hono/client/HonoClient.java
client/src/main/java/org/eclipse/hono/client/ReconnectListener.java
client/src/main/java/org/eclipse/hono/client/RegistrationClientFactory.java
client/src/main/java/org/eclipse/hono/client/TenantClientFactory.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java

The factory methods for creating the arbitrary service clients have been
refactored into dedicated interfaces.
This is the first step in splitting up `HonoClient` into multiple factories with dedicated scope. In subsequent PRs, I intend to
* rename `HonoClient` to `HonoConnection` and limit its responsibility to just the establishment and maintenance of the AMQP connection and serve as a factory for sender and receiver links
* let the dedicated factories *wrap* around a `HonoConnection`
* refactor protocol adapters to use the dedicated factories instead of `HonoConnection` and be no longer directly involved with connection management

[#780] Extract dedicated client factory interfaces.

---

cli/src/main/java/org/eclipse/hono/cli/AmqpSend.java
site/content/user-guide/amqp-adapter.md

The AMQP CLI application can now be used for client certificate based
authentication against the AMQP protocol adapter.
+ Added example to User Guide.

[#1066] Add client certificate based authentication to CLI.

---

client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
client/src/main/java/org/eclipse/hono/client/AsyncCommandClient.java
client/src/main/java/org/eclipse/hono/client/HonoClient.java
client/src/main/java/org/eclipse/hono/client/impl/AsyncCommandClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/AsyncCommandResponseConsumerImpl.java
client/src/main/java/org/eclipse/hono/client/impl/HonoClientImpl.java

This PR is not intended do be merged (yet), but to discuss API for fix of #775!
Idea is to have a consumer that receives all command responses to address control/<tenantId>/<replyId> and to have a sender to send commands with reply-to set to control/<tenantId>/<replyId>.
I am fine with the consumer part, but I am not happy with the sender part regarding 2 points myself:
- I not have found a better name as "sendCommandWithTenantScopedResponse" in the CommandClient interface to send commands with according reply-to
- If someone creates a command client without setting replyId explicitly he ends up with a CommandClient that sends commands with tenant scoped responses with a random reply-to and therefore is not able to receive the response at all.
WDYT?
Signed-off-by: Daniel Maier …

Fix for #775 Support tenant-scoped command response link in HonoClient

---

service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyRegistrationService.java
site/content/admin-guide/device-registry-config.md

First part of the solution for #930:
When "assertRegistration" is called on a device that has multiple "via"
gateways configured, the id of the gateway doing this request is put
into a "last-via" property in the device's registration data.
Example of the updated device registration data:
````
{
"device-id": "4712",
"data": {
"enabled": true,
"via": ["gw-1", "gw-2"],
"last-via": {
"device-id": "gw-1",
"update-date": "2019-03-18T15:19:28.186970Z"
}
}
}
````

[#930] Add "last-via" property to device data on "assertRegistration"

---

service-base/src/main/java/org/eclipse/hono/service/tenant/CompleteBaseTenantService.java
service-base/src/test/java/org/eclipse/hono/service/tenant/CompleteBaseTenantServiceTest.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java

@sophokles73: This PR contains the validation of trust configurations during a tenant add request.

TenantService: Add support for enforcing valid Base64 encoding

---

CONTRIBUTING.md
demo-certs/README.md
site/content/admin-guide/amqp-adapter-config.md
site/content/admin-guide/amqp-network-config.md
site/content/admin-guide/auth-server-config.md
site/content/admin-guide/device-registry-config.md
site/content/admin-guide/http-adapter-config.md
site/content/admin-guide/kura-adapter-config.md
site/content/admin-guide/monitoring-tracing-config.md
site/content/admin-guide/mqtt-adapter-config.md
site/content/admin-guide/secure_communication.md
site/content/community/contributing.md
site/content/deployment/docker-swarm.md
site/content/deployment/kubernetes.md
site/content/deployment/resource-limitation.md
site/content/dev-guide/java_client_consumer.md
site/content/download.md
site/content/getting-started.md
site/content/user-guide/amqp-adapter.md
site/content/user-guide/device-registry.md
site/content/user-guide/http-adapter.md
site/content/user-guide/mqtt-adapter.md
tests/readme.md

Prompts are completely removed in front of shell commands to enable easy
copy & paste. Paths are usually relative to the base directory of the
Hono repository. Where relevant the directory in which a command needs
to be executed is given in a comment.
Some commands (starting adapters with Spring Boot) are fixed.

[#1083] Unified file paths in documentation, removed shell prompts.

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
bom/pom.xml
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/plan/NoopResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/plan/ResourceLimitChecks.java

This PR introduces an interface `TenantPlanValidator` which contains methods to check if further connections are allowed. A default Implementation of this interface based on the metrics data retrieved from the prometheus back end is provided. This validates the number of connections by comparing with the configured limit. Mqtt adapter uses the above method to limit the number of connections.

[#927] Limit number of connections per tenant

---

cli/src/main/java/org/eclipse/hono/cli/AmqpCliClient.java
cli/src/main/java/org/eclipse/hono/cli/CommandAndControlClient.java
cli/src/main/java/org/eclipse/hono/cli/TelemetryAndEventCli.java
cli/src/main/resources/application.yml
site/content/user-guide/amqp-adapter.md

@sophokles73: This patch adds an example to the adapter user guide to test command and control

Add command and control example to AMQP adpater user guide.

---

site/content/release-notes.md

Signed-off-by: Marian Bäuerle <marian.baeuerle@bosch-si.com>

Fix typo in class name in 1.0M1 release notes

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/MessageSender.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
client/src/test/java/org/eclipse/hono/client/impl/AbstractSenderTest.java
client/src/test/java/org/eclipse/hono/client/impl/EventSenderImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/TelemetrySenderImplTest.java
jmeter/src/jmeter/amqp_messaging_throughput_test.jmx
jmeter/src/main/java/org/eclipse/hono/jmeter/HonoSenderSampler.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoSender.java
jmeter/src/main/java/org/eclipse/hono/jmeter/ui/HonoSenderSamplerUI.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
site/content/release-notes.md

MessageSender's send methods no longer accept a registration assertion
token which became obsolete with the removal of the Hono Messaging
component.

Do not include registration assertion in downstream messages anymore.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java

With this PR, in the AMQP adapter before accepting connection from any device it is being checked that if the maximum number of existing connections exceeded the configured limit or not.

[#927] Limit the number of simultaneously connected devices per tenant in Amqp adapter.

---

service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
site/content/admin-guide/device-registry-config.md

Set 'last-via' also for devices with a single 'via' property.
This is needed to distinguish between the cases where a device connects via the gateway and where it connects directly.

[#930] Set 'last-via' also for devices with a single 'via' property

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/Config.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/Config.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/Config.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Config.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/Config.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
site/content/release-notes.md

The protocol adapters have been changed to use the
RegistrationClientFactory instead of the HonoClient
for creating RegistrationClient instances.

[#780] Use RegistrationClientFactory instead of HonoClient.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/Config.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapPreSharedKeyHandler.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/Config.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/Config.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Config.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/Config.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/CredentialsApiAuthProvider.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/UsernamePasswordAuthProvider.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/X509AuthProvider.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
site/content/release-notes.md

The protocol adapters have been changed to use the
CredentialsClientFactory instead of the HonoClient
for creating CredentialsClient instances.

[#780] Use CredentialsClientFactory instead of HonoClient.

---

client/pom.xml
core/pom.xml
core/src/main/java/org/eclipse/hono/tracing/MessageAnnotationsExtractAdapter.java
core/src/main/java/org/eclipse/hono/util/AuthenticationConstants.java
core/src/main/java/org/eclipse/hono/util/Hostnames.java
core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
pom.xml
site/content/release-notes.md

The target level of the core and client modules has been reduced to Java
8 level in order to still allow the Hono client to be used in existing
applications.
The Anmial Sniffer Maven plugin is used to check that only Java 8 API is
used by these modules.

[#1137] Use Java target level 1.8 for core and client modules.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/Config.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/Config.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/Config.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Config.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/Config.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/HonoEventConnectionEventProducer.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
site/content/release-notes.md

The protocol adapters have been changed to use the
DownstreamSenderFactory instead of the HonoClient
for creating MessageSender instances.

#780] Use DownstreamSenderFactory instead of HonoClient.

---

site/content/api/Credentials-API.md
site/content/api/Device-Registration-API.md
site/content/api/Tenant-API.md
site/content/release-notes.md

The API specifications now contain distinct sections for the mandatory
vs optional to implement operations.
I wonder if we shouldn't remove the *optional* operations from the API spec altogether. I do not think that anybody wants to implement them based on AMQP anyway. With #1130 under way, they probably do not add much value at all. WDYT?

Split operations into mandatory and optional to implement.

---

adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/plan/NoopResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/plan/ResourceLimitChecks.java

AMQP and MQTT Protocol adapters check the _connection limit_, if configured, before accepting any new connections. The issue is that they allow one more connection above the configured limit. i.e if the _limit_ `max-connection` is set as 2, then the adapters allow 3 connections for that tenant. This PR fixes this issue.

Fix checking logic of connection limit.

---

site/content/deployment/kubernetes.md

Concerning deployment docs chapter "Deploying Hono without using Helm’s Tiller Service":
Just using the described command
````
kubectl apply -f ./eclipse-hono --namespace hono
````
doesn't work:
- hono namespace has not been created yet
- the command gives the error `error: error reading [./eclipse-hono]: recognized file extensions are [.json .yaml .yml]`
- after adding `-R`, there is the error `the namespace from the provided object "kube-system" does not match the namespace "hono". You must pass '--namespace=kube-system' to perform this operation.`
- after fixing this by setting `hono` as default namespace and removing the `--namespace` param, I got errors regarding CRDs not created yet; to fix this, the CRDs can be deployed first: `find . -path "./eclipse-hono/*" -name crd*.yaml -exec …

Fix K8s docs concerning deployment without using Tiller service

---

service-base/src/main/java/org/eclipse/hono/service/limiting/ConnectionLimitAutoConfigException.java
service-base/src/main/java/org/eclipse/hono/service/limiting/DefaultConnectionLimitManager.java

Throw a exception if the connection limit is auto-configured to 0. 
Currently the protocol adapter only prints a warning to the logs, but then completes the startup. So, possibly nobody would notice that it would not accept any connections.

Fix: Do not start protocol adapter if not enough memory.

---

deploy/src/main/deploy/helm/requirements.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yml
deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-deployment.yaml
deploy/src/main/deploy/helm/templates/jaeger/jaeger.yaml
deploy/src/main/deploy/helm/values.yaml
site/content/admin-guide/monitoring-tracing-config.md
site/content/deployment/kubernetes.md

This is for #1055.
An option to deploy Hono along with the Jaeger tracing component has been added (`deployJaeger`).
This uses the [Jaeger Operator](https://github.com/jaegertracing/jaeger-operator) as a Helm dependency.

[#1055] Add support for Jaeger in the Helm-based K8s deployment

---

pom.xml

I would like to put the nexus plugin into a dedicated profile. I know this, most likely has an impact in the Eclipse CI infrastructure as well.
The reason behind that is that the plugin completely takes control of the deployment. And causes some problems in our internal build. And currently there is no other way to remove this plugin, than to manually patch the main POM file.

Configure nexus plugin in a dedicated profile

---

service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java

Fix for #1205:
Expose HonoConnection objects as beans - for autowiring to work. Otherwise the `Tracer` instance in the `HonoConnectionImpl` object doesn't get set.

[#1205] Expose HonoConnection objects as beans

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java

Using the (in JDK 8) unsupported attributes cause a compile error in my IDE, which is correct btw. The reason for that is, that we are using Java X (X being the Java version available to the Maven compiler plugin) to compile against JDK X for JVM 8.
The animal sniffer plugin will detect when methods of a newer version than JDK 8 are used during runtime, but it seems to ignore the additional field in the annotation. That should not cause any issues during runtine, btw.
However if the available Java version is 8, then the compilation will fail, as those fields are only available after Java 8.

Ensure code compiles with JDK 8

---

bom/pom.xml
service-base/pom.xml
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/AbstractServiceBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/EventBusServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCompleteCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/credentials/CredentialsMessageFilterTest.java
service-base/src/test/java/org/eclipse/hono/service/limiting/DefaultConnectionLimitManagerTest.java
service-base/src/test/java/org/eclipse/hono/service/limiting/MemoryBasedConnectionLimitStrategyTest.java
service-base/src/test/java/org/eclipse/hono/service/metric/LegacyMetricsConfigTest.java
service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/AbstractCompleteRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/RegistrationAssertionHelperImplTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/RegistrationMessageFilterTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractCompleteTenantServiceTest.java
services/device-registry/pom.xml
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationServiceTest.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java

This is a POC on the tests to experiment the junit 5 tests, as discussed in a recent community call. 
As expected, it's needed to rewrite a bunch of things, but nothing really complicated.
Also, there is currently no support for class-wide `@Rule` timeout, as we currently use in hono. Each test must have a Timeout specified. However, this feature should be introduced back in the next jupiter release, as this is a popular demand ( https://github.com/junit-team/junit5/issues/80).
On the plus side there are some nice features such as nested tests that would allow to improve the maintainability of the tests ( see  `FileBasedCredentialsServiceTest.testLoadCredentialsCanReadOutputOfSaveToFile` where I needed `countdownLatch` to replace the vertx `Async`. This could be factored the `@BeforeEach` …

POC of junit5/jupiter test migration

---

core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksTest.java

1. This is the first part of the PR for #929. This PR adds provision to set the volume limit (max-bytes-per-month) to the tenant configuration.
2. As [discussed](https://github.com/eclipse/hono/pull/1133#discussion_r273019726), the tenant configuration parameter `limits` has been renamed to `resource-limits`.

[#929 Part-1]  Add data volume limits to the tenant config

---

client/src/main/java/org/eclipse/hono/client/Command.java
client/src/main/java/org/eclipse/hono/client/CommandResponse.java
client/src/test/java/org/eclipse/hono/client/CommandTest.java

This is for #930:
- EDIT: removed: `Command.from()` is changed to not manipulate the given `Message` object anymore.
- EDIT: removed: `Command.getReplyToId()` has been renamed to `Command.getOriginalReplyToId()`: For #930 this method will be needed when forwarding the command AMQP message Hono-internally (restoring the original reply-to id of the AMQP message). The new name reflects its sematics in a better way.
- EDIT: added `getInvalidCommandReason()` - useful for inclusion in trace span logs.

Minor Command improvements

---

service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCompleteCredentialsServiceTest.java

remove an unused checkpoint that slipped in PR #1195 
Signed-off-by: Trystram Jean-Baptiste <jbtrystram@redhat.com>

removed ununsed checkpoint in tests

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
client/src/test/java/org/eclipse/hono/client/impl/RegistrationClientImplTest.java
core/src/main/java/org/eclipse/hono/util/Constants.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
site/content/api/Device-Registration-API.md
site/content/api/Tenant-API.md
site/content/release-notes.md
site/content/user-guide/amqp-adapter.md
site/content/user-guide/http-adapter.md
site/content/user-guide/kura-adapter.md
site/content/user-guide/mqtt-adapter.md
tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java

This PR extends the concept of *default properties* to the tenant level and then uses this concept to support setting a default *time-to-live* on downstream messages.

Support setting default TTL for downstream messages

---

client/src/main/java/org/eclipse/hono/client/CommandConsumerFactory.java
client/src/main/java/org/eclipse/hono/client/CommandContext.java
client/src/main/java/org/eclipse/hono/client/DelegatedCommandSender.java
client/src/main/java/org/eclipse/hono/client/GatewayMapper.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/ConnectionLifecycleWrapper.java
client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/DelegatingCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/DeviceSpecificCommandConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/GatewayMapperImpl.java
client/src/main/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/TenantScopedCommandConsumer.java
client/src/test/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImplTest.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java

For #930:
This introduces a new command consumer on a tenant-scoped address.
This consumer handler will map the device id in the command message 'To' address to a corresponding 'via' device id (if applicable) and delegate the command either to a local command handler or to a consumer on another protocol adapter instance by way of the AMQP network.
As the existing command consumer address scheme isn't changed (yet), this change doesn't cause any incompatibilities.
Additional changes for getting this to work are in #1156 and #1157.

[#930] Add tenant-scoped command consumer

---

deploy/src/main/deploy/example-permissions.json
deploy/src/main/sandbox/sandbox-permissions.json
services/auth/src/main/resources/permissions.json
services/auth/src/test/resources/authentication-service-test-permissions.json
tests/src/test/resources/auth/permissions.json

This is for #930 / #1145, allowing protocol adapters to invoke `getDevice` from the Device Registration API.

[#930] Add "registration/*:get" permissions for protocol adapters

---

core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java
deploy/src/main/config/qpid/qdrouterd-with-broker.json
deploy/src/main/sandbox/qpid/sandbox-qdrouterd.json
tests/src/test/resources/qpid/qdrouterd-with-broker.json

This is for #930 / #1145, allowing protocol adapters to create anonymous sender links. 
These sender links are used for forwarding the commands, that were received on the tenant-scoped address, back to the AMQP network, so that they can be consumed by the device-specific consumers.

[#930] Allow creation of anonymous sender links

---

client/src/main/java/org/eclipse/hono/client/CredentialsClientFactory.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/CredentialsClientImplTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java

With reference to the issue #1203, this PR aims to support caching of the response data to the `CredentialsClientFactoryImpl` as in the other client factories.

[#1203] Add caching mechanism to credentials client factory implementation.

---

client/src/main/java/org/eclipse/hono/client/RegistrationClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientImpl.java

Adds an additional `RegistrationClient#get` method with a `SpanContext` parameter.
This relates to #1215 (`RegistrationClient#get` being now a mandatory operation).

Add 'get' method in RegistrationClient with SpanContext parameter

---

service-base/src/main/java/org/eclipse/hono/service/registration/CompleteRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/CompleteBaseRegistrationServiceTest.java
site/content/api/Device-Registration-API.md
site/content/release-notes.md

This is for #930:
The `Get Registration Information` operation is mandatory now.

[#930] Make getDevice() a mandatory operation

---

client/src/main/java/org/eclipse/hono/client/CommandContext.java
client/src/main/java/org/eclipse/hono/client/GatewayMapper.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/GatewayMapperImpl.java
client/src/main/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandler.java
client/src/test/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandlerTest.java
client/src/test/java/org/eclipse/hono/client/impl/GatewayMapperImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandlerTest.java

For #930:
This renames the `DelegatingCommandHandler` class to `DelegateViaDownstreamPeerCommandHandler`, making the class only responsible for one thing, namely delegating the handling of a command message (received on a tenant-scoped link) to a device-specific command consumer by sending the command message (with a modified `To` address) back to the downstream peer.
Furthermore, tests for the classes introduced in #1145 have been added. And tracing of command messages is improved by properly adding the tracing context in `CommandContext`.
The `CommandContext` class is not `final` anymore here, so that it can be mocked (configuring Mockito so that it can also mock final methods doesn't seem worth it regarding effort and the possible performance hit here, imho).

[#930] Rename DelegatingCommandHandler, add tests and improve tracing.

---

client/src/main/java/org/eclipse/hono/client/impl/ApplicationClientFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/CredentialsClientFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/DownstreamSenderFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/RegistrationClientFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TenantClientFactoryImpl.java
client/src/test/java/org/eclipse/hono/client/impl/CachingClientFactoryTest.java
client/src/test/java/org/eclipse/hono/client/impl/DownstreamSenderFactoryImplTest.java

This will perform a retry in `CachingClientFactory#getOrCreateClient()` in case there is a concurrent attempt with the same key.
Needed for C&C integration tests after changes for #930. Frequent error there (e.g. in AMQP adapter):
````
14:59:25.305 [vert.x-eventloop-thread-0] ERROR o.e.h.c.i.GatewayMappingCommandHandler - error getting last-via for device f9647e8d-ce54-4585-aa2a-9496bd5de194
org.eclipse.hono.client.ServerErrorException: already creating client for key
at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:167)
at org.eclipse.hono.client.impl.RegistrationClientFactoryImpl.lambda$getOrCreateRegistrationClient$2(RegistrationClientFactoryImpl.java:68)
at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java …
```

Introduce retries in CachingClientFactory#getOrCreateClient()

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/CommandContext.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java

Use the recently introduced `CommandContext#disposition` method in the `onCommandReceived` method of the AMQP adapter.
Some further logging/tracing improvements.

Use common disposition method; improve logging/tracing

---

service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/plan/NoopResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksConfig.java
service-base/src/main/java/org/eclipse/hono/service/plan/ResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksTest.java

`ResourceLimitChecks` API is now extended with the method `isMessageLimitExceeded(...)` to check the messages limit. This method is intended to be used by the _protocol adapters_ to verify the messages limit before accepting any telemetry or event messages. 
The _protocol adapters_ using this api to verify the messages limit will be part of the next PR.

[#929 Part-2] Extend ResourceLimitChecks API to verify the messages limit.

---

client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/AsyncCommandClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java

This concludes the implementation for #930:
The command client will now create a sender link on the tenant-scoped address. The `To` property of the command message is set to the device-specific address.
Documentation changes and additions to the release notes will go in a separate PR.

[#930] Let command client use a tenant-scoped sender link address

---

core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
core/src/test/java/org/eclipse/hono/util/ResourceIdentifierTest.java

`ResourceIdentifier.fromString("control///req/cmd-req-id").getPathWithoutBase()` 
was returning `null/req/cmd-req-id`.
With this fix it will return `/req/cmd-req-id`.

Fix getPathWithoutBase(), extend javadocs and tests

---

service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java

In `PrometheusBasedResourceLimitChecks.calculateDataUsagePeriod(...)`, when the calculated data usage period (in days) is equal to the configured `period-in-days`, then `zero` is being returned instead of the `period-in-days`.
_Example_: For the below config, the data usage period as on "2019-05-22" should be _30 days_ but currently _0 days_ is being returned. This has been fixed with this PR.
```
"resource-limits": {
"data-volume": {
"max-bytes": 10000000,
"period-in-days": 30,
"effective-since": "2019-04-23"
}
```

[#929] Fix calculation of data usage period during message limit check.

---

core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
site/content/api/Device-Registration-API.md
site/content/release-notes.md

This is for #1245.
The intention of #1245 is that the update of the `last_via` property shall be done in a separate request. In order to decide whether we actually need to do that request, this PR changes the `assertRegistration` return JSON to include the `via` property value.

[#1245] Add indication of GW usage to assertRegistration response JSON

---

adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/Command.java
client/src/main/java/org/eclipse/hono/client/CommandResponse.java
client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
client/src/test/java/org/eclipse/hono/client/CommandTest.java

For #1245:
Extract methods for the bit flag used in the Command request id (denoting whether the original reply-to address contained the device id).
Encoding and decoding of the bit flag used in `Command.getDeviceFacingReplyToId`
and `CommandResponse.getReplyToId` has been refactored to use the new
methods as well. Note that for this, the bit flag value in these methods has been switched, making it identical to the flag value used for the Command request id.
This is a preparation for storing an additional option in the bit flag,
denoting whether the old or new command response address pattern was
used.

[#1245] Extract methods for handling the bit flag used in the Command class

---

site/content/release-notes.md
site/static/api/device-registry-v1.yaml

Documented:
This PR contains an OpenAPI 3 model, which can be rendered and tested using the following command:
~~~
docker run -ti --rm -p 8080:8080 -e SWAGGER_JSON=/foo/device-registry.yaml  -v "$(pwd):/foo:z" swaggerapi/swagger-ui
~~~
Or directly from GitHub (without the option to make local changes):
~~~
docker run -ti --rm -p 8080:8080 -e URL=https://raw.githubusercontent.com/ctron/hono/feature/devreg_api_1/site/static/api/device-registry.yaml swaggerapi/swagger-ui
~~~
You can also directly use the hosted version here:
* Current API – https://current-api-hono-device-registry-api.wonderful.iot-playground.org
* Revised API – https://revised-api-hono-device-registry-api.wonderful.iot-playground.org
You can actually use the "Try it out" feature, as currently the API describes the "as is" …

Device Registry HTTP API

---

adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraCommandProperties.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraConstants.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraMessageType.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Application.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Config.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ActilityProvider.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/EverynetProvider.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/KerlinkProvider.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProvider.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProviderDownlinkException.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraProviderMalformedPayloadException.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/LoraUtils.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ObjeniousProvider.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ProximusProvider.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ThingsNetworkProvider.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/LoraUtilsTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapterTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ActilityProviderTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/EverynetProviderTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/LoraTestUtil.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ObjeniousProviderTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ProximusProviderTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ThingsNetworkProviderTest.java

Fixes #1190: LoRaWAN adapter does not pass through the metadata

Pass through original message in LoRaWAN adapter

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java

Equip _MQTT adapter_ to check the _message limit_ (if configured) before accepting any _telemetry/event_ messages.

[#929] Equip MQTT adapter to check the message limit

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java

This has dependency to the PR #1249 and that need to be merged first. 
This PR equips _HTTP_, _AMQP_ and _COAP_ protocol adapters to check the _message limit_ before accepting any _telemetry/event_ messages. The commit corresponding to this PR is [[#929] Equip HTTP, AMQP and COAP adapters to check message limit.](https://github.com/eclipse/hono/commit/f0fb971751ec4ff2a612339590a7bb09bfd8186b)

[#929] Equip HTTP, AMQP and COAP protocol adapters to check message limit

---

service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksTest.java

With reference to the [discussion](https://github.com/eclipse/hono/pull/1256#discussion_r287791194),  the `effective-since` config parameter now supports `combined date and time representation in extended format`.

[#929] Support combined date and time representation for message limit config parameter "effective-since"

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java

Based on the [discussion](https://github.com/eclipse/hono/pull/1256#discussion_r288483310), when message limit exceeds, _AMQP Adapter_ sends notifies the device with `amqp:resource-limit-exceeded` error.

[#929 AMQP Adapter] Use "amqp:resource-limit-exceeded" when message limit exceeds.

---

adapters/pom.xml
adapters/sigfox-vertx/pom.xml
adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Application.java
adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Config.java
adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/Constants.java
service-base/src/main/java/org/eclipse/hono/service/http/DefaultFailureHandler.java
site/content/release-notes.md
site/content/user-guide/sigfox-adapter.md

This adds a first version of a Sigfox protocol adapter. The current limitations are:
* ~~Telemetry only~~
* Supports only `DATA` callbacks
* Does not yet support command and control
I would consider this "tech preview" for the moment.

Add a basic Sigfox protocol adapter

---

site/static/api/device-registry-v1.yaml

It looks like we are missing the "via" field and the  "defaults" section on both the Tenant and Device entity.

Add missing "via" and "defaults" section

---

site/content/admin-guide/secure_communication.md
site/content/api/Authentication-API.md
site/content/api/Command-And-Control-API.md
site/content/api/Credentials-API.md
site/content/api/Device-Registration-API.md
site/content/api/Event-API.md
site/content/api/Telemetry-API.md

The page title is always h1. The content should not contain further headings on level h1, because this is punished by search engines. So on all pages containing h1 headings I just pushed every heading one level down.

Adjust heading levels to start with h2 per page.

---

jenkins/Hono-Website-Pipeline.groovy

Removed the exclusion of directory `copyrighted-logos` when deleting
the directory to which the web site is build. The command seemingly
did not work on Jenkins. Todo: add the exception later in a way that
works on the Jenkins machine.

[#1109] Delete old files when building web site.

---

deploy/src/main/config/grafana/dashboard-definitions/jvm-details.json

In Grafana dashboard for JVM details, the values corresponding to the `Threads` and `Open Files` are always empty. In this PR, this has been addressed by fixing the query expressions with appropriate time series.

Fix grafana dashboard for JVM details

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterLegacyEndpointTest.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterLegacyEndpointTest.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterLegacyEndpointTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionLegacyEndpointTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/MqttContextTest.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
core/src/main/java/org/eclipse/hono/util/CommandConstants.java
core/src/test/java/org/eclipse/hono/util/ResourceIdentifierTest.java
example/src/main/java/org/eclipse/hono/devices/HonoHttpDevice.java
service-base/src/main/java/org/eclipse/hono/service/metric/MetricsTags.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlLegacyEndpointAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/http/EventLegacyCommandEndpointHttpIT.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/http/TelemetryLegacyCommandEndpointHttpIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlLegacyEndpointMqttIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java

This is for #1073:
The default prefix for the southbound command & control endpoints has been renamed from `control` to `command`. The old `control` endpoints are still exposed and working.
(For the AMQP adapter, there is still one "command" endpoint used both for receiving commands and sending back the command response. Usage of a "command_response" endpoint for the responses shall be introduced following this commit.)

[#1073] Change southbound control endpoint names

---

site/homepage/layouts/partials/head.html

Build the page title for pages on homepage the same way it is done for the documentation. E.g. show "Getting started :: Eclipse Hono" instead of only "Getting started" (the old web site used the form "Getting started - Eclipse Hono").

Append the site title to the page title in pages on the homepage.

---

site/documentation/config.toml
site/documentation/layouts/partials/custom-header.html
site/homepage/config.toml

Added configuration that causes Twitter to generate a "card" with
logo, title and a reference to the Hono Twitter account, when a link
to the Hono site appears in a Twitter message.

Add preview card to be used by twitter.

---

site/documentation/static/api/device-registry-v1.yaml

Currently we are missing the field "algorithm" in the trust anchor configuration of the tenant.

Add missing "algorithm" field to the trust-ca object

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/Command.java
client/src/test/java/org/eclipse/hono/client/CommandTest.java
core/src/main/java/org/eclipse/hono/util/CommandConstants.java
service-base/src/main/java/org/eclipse/hono/service/metric/MetricsTags.java

This is for #1073:
A device, sending a command response to the AMQP adapter, should now use `command_response` instead of `command` as prefix in the response message address (as also mandated now by the `reply-to` property of the command message).
The old `control` prefix is still supported as well.

[#1073] Use "command_response" endpoint for AMQP command responses

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/DeviceSpecificCommandConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TenantScopedCommandConsumer.java
client/src/test/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImplTest.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java

This fixes #1289.
Adds a new `createReceiver` method in `HonoConnection` with an `autoAccept` param.
CommandConsumer classes use this to disable `autoAccept`.
(An alternative solution would have been to just set `receiver.setAutoAccept(false)` on the returned receiver, but letting the flag be set inside the `createReceiver` method *before* `receiver.open()` is called is the cleaner solution IMHO.)

[#1289] Disable auto-accept for command receiver links

---

site/documentation/content/deployment/create-kubernetes-cluster.md
site/documentation/content/deployment/docker-swarm.md
site/documentation/content/deployment/helm-based-deployment.md
site/documentation/content/dev-guide/building_hono.md
site/documentation/content/dev-guide/java_client_consumer.md
site/homepage/content/downloads.md
site/homepage/content/getting-started.md

The Getting Started guide is based on the Sandbox (if the user can access it) or a local Minikube instance.
In a next step I would then like to remove "official" support for Docker Swarm as well and remove the Swarm deploy scripts.

[#1317] Use Minikube in Getting Started guide.

---

adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
client/src/main/java/org/eclipse/hono/client/GatewayMapper.java
client/src/main/java/org/eclipse/hono/client/impl/GatewayMapperImpl.java
client/src/main/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandler.java
client/src/test/java/org/eclipse/hono/client/impl/GatewayMapperImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/GatewayMappingCommandHandlerTest.java
client/src/test/java/org/eclipse/hono/client/impl/HonoClientUnitTestHelper.java
deploy/src/main/deploy/example-permissions.json
deploy/src/main/sandbox/sandbox-permissions.json
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
tests/src/test/resources/auth/permissions.json

This is for #1245.
With the changes here, the protocol adapters invoke the `setLastKnownGatewayForDevice` method of the Device Connection API whenever a device (that has one or more `via` gateways defined) sends a telemetry, event, command response or ttd event.
The gateway mapping logic (that is part of processing a command message in the protocol adapter) now uses the `getLastKnownGatewayForDevice` method.
The old code for storing a `last-via` property in the device registration data is still present and will be removed later.

[#1245] Use Device Connection API for the gateway mapping feature

---

site/documentation/static/api/device-registry-v1.yaml

This change alters the model of the device registry HTTP API in way
that redundant parts of the secrets (type, auth-id, enabled) get pulled
up one level. And that new level gets the "ext" extensions as well.
The "enabled" flag is still present on the "secrets" level, as it might
be beneficial to e.g. disable a single secret temporarily.

Change credentials model and drop "delete" operation

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java

This PR address the issue #1262 with reference to the [MQTT 3.1.1 spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718042). When a _telemetry/event_ message is not able to be processed successfully then the device connection is closed.

[#1262] Close mqtt connection when a telemetry/event message cannot be processed.

---

cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
client/src/main/java/org/eclipse/hono/client/ApplicationClientFactory.java
client/src/main/java/org/eclipse/hono/client/CommandClient.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
client/src/main/java/org/eclipse/hono/client/impl/ApplicationClientFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/CommandClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/CommandClientImplTest.java
example/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java
jmeter/src/main/java/org/eclipse/hono/jmeter/client/HonoCommander.java
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java

This is for #1255.
With this PR, the `CommandClient` is scoped to a tenant, not a device anymore. The device id is given as a parameter to the individual `sendCommand` invocation.
Note: The `AsyncCommandClient` is not changed here - this will come in a follow-up commit.

[#1255] Let CommandClient instance be scoped to a tenant

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapPreSharedKeyHandler.java
adapters/lora-vertx/pom.xml
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
bom/pom.xml
legal/legal/LICENSE.Spring.txt
legal/legal/NOTICE.Spring.txt
legal/legal/NOTICE.md
pom.xml
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
site/documentation/content/deployment/openshift.md
site/homepage/content/getting-started/index.md

**Not to merge until necessary CQs are created and approved.**
1. The spring artifacts are upgraded as below.
| **Artifact** | **Version** |
| ------------- | ------------- |
| Spring Boot | 2.1.5.RELEASE |
| Spring  | 5.1.8.RELEASE |
| Spring  Security | 5.1.5.RELEASE |
2. The below dependencies/plug-ins are updated to be in compatible with the above spring version.
| **Artifact** | **Version** |
| ------------- | ------------- |
| snakeyaml | 1.23 |
| maven-deploy-plugin  | 2.8.2 |
| maven-assembly-plugin |3.1.0 |
3. Support for Guava has been [dropped](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#guavacachemanager) in Spring Framework 5. Instead of `GuavaCacheManager`,  `CaffeineCacheManager` is being used and the corresponding dependency …

[#1297] Upgrade to Spring Boot 2

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java

With this PR, the Protocol Adapters are now equipped to check the _message limits_ before sending any _commands_ and accepting any _command responses_ as described in #1284.

[#1284] Extend message limits for command and control

---

site/homepage/content/downloads.md
site/homepage/content/faq.md
site/homepage/content/release-notes.md
site/homepage/content/sandbox.md

Use "doclink" shortcode for all links from homepage to documentation.

---

jenkins/Hono-Website-Pipeline.groovy
site/documentation/config.toml
site/homepage/menu_main.toml

Improve calculation of the order of versions in the menu.
Make sure that the "old version hint" banner always points the current
stable version.
Display "Getting started" as first menu item on homepage.

[#1302] Fix build of documentation versions.

---

service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementHttpEndpoint.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceRegistrationHttpIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java

this fixes https://github.com/eclipse/hono/issues/1370

Management API : allow empty body for creating tenant or device with generated ID

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/test/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapterTest.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpContextTenantAndAuthIdProvider.java
service-base/src/main/java/org/eclipse/hono/service/http/TenantTraceSamplingHandler.java
service-base/src/main/java/org/eclipse/hono/service/tenant/BaseExecutionContextTenantAndAuthIdProvider.java
service-base/src/main/java/org/eclipse/hono/service/tenant/ExecutionContextTenantAndAuthIdProvider.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantObjectWithAuthId.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantTraceSamplingHelper.java
service-base/src/test/java/org/eclipse/hono/service/http/TenantTraceSamplingHandlerTest.java

Fix for #896. 
This introduces config options to enable forced sampling of traces (i.e. recording of traces in the tracing backend) for a specific tenant or device.
**Per tenant:**
In the Json structure returned by the Tenant API, a field `trace-sampling-mode` can be set with a value of "all" (meaning sampling of all traces is enforced) or "default".
````
{
"tenant-id": "DEFAULT_TENANT",
"enabled": true,
"trace-sampling-mode": "all"
}
````
**Per device (auth id):**
In the Json structure returned by the Tenant API, a field `trace-sampling-mode-per-auth-id` can be set with a map value where a field with a device auth id as name and a value of "all" (meaning sampling of all traces is enforced) or "default" is set.
````
{
"tenant-id": "DEFAULT_TENANT",
"enabled": true, …
```

[#896] Implement trace sampling mode option in HTTP adapter

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContextTenantAndAuthIdProvider.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java

This fixes  #1389.
The Tenant JSON config options described in #1382 are used to set a trace sampling priority in the MQTT adapter.
(Feature is also implemented in the Kura protocol adapter, using the `AbstractVertxBasedMqttProtocolAdapter` base class.)

[#1389] Implement trace sampling mode option in MQTT adapter

---

service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
site/homepage/content/release-notes.md

Remove deprecated variant of `AbstractProtocolAdapterBase.getRegistrationAssertion` method and its usage.

Remove deprecated variant of getRegistrationAssertion.

---

service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
site/homepage/content/release-notes.md

The deprecated methods in `AbstractProtocolAdapterBase` have been removed.

Remove deprecated methods from AbstractProtocolAdapterBase.

---

service-base/src/main/java/org/eclipse/hono/service/management/tenant/Adapter.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/ResourceLimits.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
tests/src/test/java/org/eclipse/hono/tests/Tenants.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantApiTests.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java

This patch attempts to restrict the usage of the `TenantObject` value to what it is created for: encapsulating the tenant payload retrieved through the get operation of the tenant API.
This restriction avoids the unnecessary/costly mapping from a `TenantObject` to a `JsonObject`, as we currently do in test cases performing tenant API client requests

Remove usage of TenantObject in code performing tenant API client requests

---

core/src/main/java/org/eclipse/hono/config/ClientConfigProperties.java

Seems to me like it had been forgotten to add the new properties to the copy constructor.

Add missing properties to copy constructor of ClientConfigProperties

---

core/src/main/java/org/eclipse/hono/util/ConfigurationSupportingVerticle.java
service-base/src/main/java/org/eclipse/hono/service/EventBusService.java
service-base/src/main/java/org/eclipse/hono/service/credentials/BaseCredentialsService.java
service-base/src/main/java/org/eclipse/hono/service/credentials/CompleteBaseCredentialsService.java
service-base/src/main/java/org/eclipse/hono/service/credentials/EventBusCompleteCredentialsAdapter.java
service-base/src/main/java/org/eclipse/hono/service/credentials/EventBusCredentialsAdapter.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/BaseDeviceConnectionService.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/EventBusDeviceConnectionAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/EventBusCredentialsManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/device/EventBusDeviceManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/EventBusRegistrationAdapter.java
service-base/src/main/java/org/eclipse/hono/service/tenant/BaseTenantService.java
service-base/src/main/java/org/eclipse/hono/service/tenant/EventBusTenantAdapter.java
service-base/src/test/java/org/eclipse/hono/service/EventBusServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/deviceconnection/BaseDeviceConnectionServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredCredentialsAdapter.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredCredentialsManagementAdapter.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredDeviceConnectionAdapter.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredDeviceManagementAdapter.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredRegistrationAdapter.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredTenantAdapter.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredTenantManagementAdapter.java

This change drops inheritance on `ConfigurationSupportingVerticle` as most classes implement this now with `<Void>`.

Drop the unnecessary type argument to event bus classes

---

site/homepage/content/community/get-in-touch.md

Freenode had changed their web chat software. This fix adapts the link
so that the channel is again configured correctly in the login form.

Fix webchat link.

---

client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java

The `updateLastGateway` invocation shouldn't delay or possibly fail the surrounding operation (sending a telemetry/event/command-response message).

Let the updateLastGateway operation run asynchronously

---

core/src/main/java/org/eclipse/hono/util/RequestResponseResult.java

This is necessary in order to allow making a copy of the object.

Give read-only access to the application properties.

---

site/documentation/content/deployment/create-kubernetes-cluster.md

This fixes #1445:
Keeping things simpler by using the default profile.
This way the user doesn't have to deal with different profiles, potentially using the wrong minikube profile or the wrong kubectl profile.

[#1445] Omit minikube profile parameter

---

bom/pom.xml

This fixes several CVEs around HTTP/2.
Also upgrades tcnative to 2.0.25.

[#1450] Upgrade to Netty 4.1.39.

---

service-base/src/main/java/org/eclipse/hono/service/registration/AbstractRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/BaseRegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/DummyRegistrationService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java

This change adds the Span parameter to the `getDevice` method of the `AbstractRegistrationService`.
It already is present in the "assert" methods, but doesn't get passed on to the `getDevice` method.
As all touched classes are part of the new API, which wasn't released yet, no wrapper method with the existing signature is provided.
The change does not make any changes in the old class hierarchy, and thus the old `getDevice` method in the old "base" class is left untouched, and the parameter was not added there. This allows makes the "legacy" class hierarchy compatible with the previous version.

Add Span parameter to getDevice method

---

bom/pom.xml
deploy/pom.xml
deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-auth/hono-service-auth-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-pvc.yaml
deploy/src/main/deploy/helm/values.yaml
pom.xml
site/documentation/content/deployment/create-kubernetes-cluster.md
site/documentation/content/deployment/helm-based-deployment.md

I added a few improvements for AKS or k8s deployments in general.
* Aligned image tagging between build and (helm) deployment, i.e.
* Align to set a custom registry (which was possible to deploy in with Helm but not to tag in the build).
* Align to set a custom org (which was possible tag in build but not to deploy with Helm)
* Registry deployment improvements:
* Add Azure AKS docs how to set storage class with retain policy.
* Switch from k8s `deployment` to `StatefulSet` in order to avoid deadlock situations at update/redeployment time due to the `ReadWriteOnce` access.
* Allow for registry to configure a custom storage class and disable the example storage override at container startup.
* Fix helm folder according to helm spec (i.e. needs to be identical to chart name for instance to …

Align image tags with helm deployment and registry deployment improvements.

---

service-base/src/main/java/org/eclipse/hono/service/annotation/HonoTimestamp.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
service-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
service-base/src/test/java/org/eclipse/hono/service/management/credentials/SecretsTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java

This change sets up explicit encoding of the timestamp, and also enforces this when encoding.
Instead of expecting the user of the classes to register an additional data type module, the fields explicitly declare their serializer now.

Fix an issue encoding the timestamp.

---

client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
core/src/test/java/org/eclipse/hono/connection/impl/ConnectionFactoryImplTest.java
tests/src/test/java/org/eclipse/hono/tests/client/HonoClientImplIT.java
tests/src/test/resources/logback-test.xml

The HonoClient now stops a connection attempt if it runs into an
SSLException which indicates a permanent problem with the TLS handshake.
Fixes #1424

Consider SSLException terminal for connection attempt.

---

core/pom.xml
core/src/main/java/org/eclipse/hono/annotation/HonoTimestamp.java
core/src/main/java/org/eclipse/hono/util/DataVolume.java
core/src/main/java/org/eclipse/hono/util/DataVolumePeriod.java
core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
core/src/main/java/org/eclipse/hono/util/ResourceLimits.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
service-base/src/test/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
site/documentation/content/api/management/device-registry-v1.yaml
site/documentation/content/api/tenant/index.md
tests/src/test/java/org/eclipse/hono/tests/registry/TenantApiTests.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantHttpIT.java

This PR implements #1460 
- Management and Tenant API now supports data limit configuration.
- Updated default resource limit checks implementation due to changes in the Tenant API.

[#1460] Extend support to data limit in Management and Tenant APIs

---

client/src/main/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/test/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandlerTest.java

This fixes #1457:
Instead of using a long-lived sender link on the anonymous relay in `DelegatedCommandSenderImpl`, the link is created with the device-specific command address now and is closed after the command is sent.

[#1457] Create sender link with device specific address.

---

client/src/test/java/org/eclipse/hono/client/impl/TenantClientImplTest.java
core/src/main/java/org/eclipse/hono/util/DataVolume.java
core/src/main/java/org/eclipse/hono/util/ResourceLimits.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
site/documentation/content/api/management/device-registry-v1.yaml
site/documentation/content/api/tenant/index.md
site/documentation/content/concepts/resource-limits.md
site/documentation/content/user-guide/amqp-adapter.md
site/documentation/content/user-guide/http-adapter.md
site/documentation/content/user-guide/kura-adapter.md
site/documentation/content/user-guide/mqtt-adapter.md
site/homepage/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantApiTests.java

Support definition of a maximum TTL per tenant to limit the default TTL applied to downstream events from devices.

[#1448] Use max-ttl to limit downstream event TTL.

---

service-base/src/main/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/plan/PrometheusBasedResourceLimitChecksTest.java

This PR implements #1337. 
With this PR,  Hono now also supports _monthly_ mode of calculation. In the _monthly_ mode, the data usage is calculated from the beginning till the end of the current calendar month and compared with the limits already set using the `max-bytes` parameter. There is an exception to this calculation in the first month on which this limit becomes effective. In this case, the `max-bytes` value is recalculated based on the remaining days in the month from the `effective-since` date. The data usage for these remaining days is compared with the above recalculated value.
Below configurations illustrate how the `mode` can be set to _monthly_ or _days_.
```
"data-volume": {
"max-bytes": 2147483648,
"period": {
"mode": "monthly",
},
"effective-since": "2019-07-27T14:30Z"
} …
```

[#1337] Message limit checks now also supports monthly calculation.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
site/documentation/content/user-guide/amqp-adapter.md

This fixes #1488:
When sending commands to gateway devices, a "device_id" application property is added to the command AMQP message, containing the device id of the original command message.
The AMQP adapter documentation has been updated to describe the scenario that an authenticated gateway wants to receive commands.

[#1488] Add 'device_id' property for gateway commands; update docs

---

site/documentation/content/api/credentials/index.md
site/documentation/content/architecture/auth/index.md
site/documentation/content/architecture/component-view/index.md

File names of markdown files are generated to a directory with that name
by Hugo, except for index files. Therefore relative links to images in
the same source directory (page bundle) need to point to the same dir
in case of index files and to the parent dir in case of files with
other names.

Fix: look up files in page bundle in same directory for index files.

---

cli/src/main/java/org/eclipse/hono/cli/adapter/AmqpCliClient.java
cli/src/main/resources/application.yml

The AmqpCliClient did not set TLS options when username and password
where used for configuration.

[#1484] CLI: Allow TLS for basic auth.

---

service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
service-base/src/test/java/org/eclipse/hono/service/metric/MicrometerBasedMetricsTest.java
site/homepage/content/release-notes.md

This is a PR to solve #1227. Since the tenant timeout is already managed by the metrics implementation (#1475), this is quite straight forward.  
This PR replaces #1456.

Remove metrics when tenant times out.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
core/src/main/java/org/eclipse/hono/util/Constants.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/http/HttpUtilsTest.java
site/documentation/content/user-guide/http-adapter.md
site/homepage/content/release-notes.md

This  PR address the issue #266. The devices can now specify *time-to-live* for _event_ messages it publishes to Hono using the HTTP adapter by setting the *hono-ttl* property in requests explicitly.

[#266] Equip HTTP Adapter to support setting TTL value for events published by devices.

---

site/documentation/config.toml
site/documentation/layouts/partials/menu.html

Adds static links to the "Getting Started" and the homepage to the "shortcuts" menu of the documentation.

[#1508] Add links to "Getting Started" and "Home" to documentation menu.

---

service-base/src/main/java/org/eclipse/hono/service/auth/AddressAuthzHelper.java
services/auth/src/main/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServer.java
services/auth/src/test/java/org/eclipse/hono/service/auth/impl/SimpleAuthenticationServerTest.java

This extracts the code for supporting the Qpid Dispatch Router `ADDRESS-AUTHZ` capability out of the `SimpleAuthenticationServer` into its own class in the service-base module.
This makes it easier to write own Hono Auth server implementations that also support the Qpid authorization feature.

Extract AddressAuthzHelper out of SimpleAuthenticationServer

---

jmeter/src/jmeter/http_messaging_throughput_test.jmx

While testing my Hono deployment I figured that the test scripts seem to be written for a different (outdated?) Hono API version.
I adapted it to the current version. Works with current Hono master at least.
kai
Signed-off-by: Kai Zimmermann <kai.zimmermann@microsoft.com>

Adapt http jmeter tests to current Hono API.

---

cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
site/homepage/content/getting-started/index.md

The second part of the Getting started Guide, which explains Command and
Control, didn't work anymore because he expected Hono on localhost.
There were also some redundancies because first the sample application
was used and then the same thing was done again with the CLI.
Now only the CLI is used and the explanation uses the MQTT adapter.
In addition, the log output of the CLI has been improved a little.

Improve Getting started Guide part that covers C & C.

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/PropertyBag.java
adapters/mqtt-vertx-base/src/test/java/PropertyBagTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/MqttContextTest.java
site/documentation/content/user-guide/mqtt-adapter.md
site/homepage/content/release-notes.md

The devices can now specify *time-to-live* for _event_ messages it publishes to Hono using the MQTT adapter. This can be done by setting the *hono-ttl* property in the *property-bag* explicitly. This  PR address the issue #267.

[#267] Equip MQTT Adapter to support setting TTL for events published by devices. 

---

site/documentation/content/deployment/helm-based-deployment.md

The _Minikube_ networking guide has been moved to a new location under https://minikube.sigs.k8s.io/docs/tasks/loadbalancer/. This has been updated in the deployment guide.

Update actual link in deployment guide.

---

site/homepage/content/faq.md

As discussed in the community call, the answers were replaced by links to the corresponding questions on Stackoverflow.

Replace the answers in FAQ with links to the questions on Stackoverflow.

---

site/homepage/layouts/partials/footer.html

The links to _Github_ repository and _Twitter_ already exist in homepage footer. This PR adds one more link for the _Gitter chat_ in the footer as in the below image. Right now a link to the _Gitter chat_ is only available in the _Get in touch_ page and IMHO it is also better to have it in the footer too.

Add link to hono gitter chat in homepage footer.

---

tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/amqp/AmqpUploadTestBase.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java

Improve log output of parameterized tests; fix typos.
Before, the log output for parameterized tests was just:
````
o.e.h.t.mqtt.CommandAndControlMqttIT - running [6] gateway device: true, southbound endpoint: control, northbound endpoint: command, topic filter: control/+/+/req/#
````
With this commit, it will be:
````
o.e.h.t.mqtt.CommandAndControlMqttIT - running testSendCommandFailsForMalformedMessage(MqttCommandEndpointConfiguration, VertxTestContext) [6]; parameters: gateway device: true, southbound endpoint: control, northbound endpoint: command, topic filter: control/+/+/req/#
````

Improve log output of parameterized tests

---

core/src/main/java/org/eclipse/hono/util/MessageHelper.java
core/src/main/java/org/eclipse/hono/util/ResourceIdentifier.java
core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
legal/src/main/resources/checkstyle/default.xml
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
site/homepage/content/release-notes.md

The factory methods for creating new downstream messages have been moved from `AbstractProtocolAdapterBase` to `MessageHelper` so that implementors of custom adapters can profit from using these methods without requiring them to extend the abstract base class.
This addresses #1544

Add convenience methods for creating new downstream messages.

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java

This fixes #1541.
Note that using an empty string as target address is still supported by means of a corresponding check in `isLinkEstablished`.

[#1541] Allow null link address for anonymous relay in createSender()

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapErrorResponse.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/KuraProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/VertxBasedMqttProtocolAdapter.java
cli/src/main/java/org/eclipse/hono/cli/AbstractCliClient.java
cli/src/main/java/org/eclipse/hono/cli/Application.java
cli/src/main/java/org/eclipse/hono/cli/adapter/AmqpCliClient.java
cli/src/main/java/org/eclipse/hono/cli/adapter/CommandAndControlClient.java
cli/src/main/java/org/eclipse/hono/cli/app/Commander.java
cli/src/main/java/org/eclipse/hono/cli/app/Receiver.java
client/src/main/java/org/eclipse/hono/client/CommandContext.java
client/src/main/java/org/eclipse/hono/client/CommandResponse.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java
core/src/main/java/org/eclipse/hono/auth/AuthoritiesImpl.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
example/src/main/java/org/eclipse/hono/devices/HonoHttpDevice.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/AbstractServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/amqp/AmqpServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CredentialsManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementHttpEndpoint.java
tests/src/test/java/org/eclipse/hono/tests/CrudHttpClient.java

Change Summary:
* Use the specialized IntPredicate instead of Predicate<Integer> for HTTP status codes
* Replace occurrences of non-constant "LOG" variable to "log"
plus other minor fixes

Minor cosmetic changes

---

service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapterTest.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java

This PR fixes the issue #1555. A solution to issue #1555 shall be validating the _tenant management payload_ before _adding_ or _updating_ a tenant in the `file based device registry`.

[#1555] Validate tenant management payload before adding or updating a tenant.

---

service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapterTest.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java

[#1566] No two adapters can have same type during tenant registration.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TrustedCertificateAuthority.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapterTest.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TrustedCertificateAuthorityTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java
site/documentation/content/api/management/device-registry-v1.yaml
site/documentation/content/api/tenant/index.md
site/homepage/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/Tenants.java
tests/src/test/java/org/eclipse/hono/tests/registry/TenantApiTests.java

The Device Registry Management API now supports defining multiple
trusted certificate authorities for a tenant. The Tenant API has also
been changed to include a list of CAs in the response to a Tenant
request.

[#623] Support multiple CAs in Registry Management and Tenant APIs.

---

adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/Constants.java
site/documentation/content/user-guide/http-adapter.md

This is for #1523.
When the HTTP adapter sends a command to a gateway, acting on behalf of a device, a HTTP header will be set with the target device id.
(An integration test for this can be added once #1580 has been merged.)

[#1523] HTTP adapter: Add http header with command target device

---

deploy/src/main/deploy/helm/templates/_helpers.tpl

I have no real experience with Helm, but to me it looks like we are missing the namespace in the metadata section. Otherwise using `helm template --namespace foo` will not work.

Add namespace to the templates

---

site/documentation/config.toml
site/documentation/content/admin-guide/device-registry-config.md
site/documentation/content/deployment/helm-based-deployment.md
site/documentation/content/dev-guide/custom_http_adapter.md
site/documentation/content/user-guide/amqp-adapter.md
site/documentation/content/user-guide/http-adapter.md
site/documentation/content/user-guide/mqtt-adapter.md

Make links from the documentation to the Hono homepage to end with a slash. + The link to https://www.lora-alliance.org/ gets redirected to the one without "www".
Could/should be cherrypicked to branch "1.0.0-docfix".

Change URLs that produce redirects to speed up browsing.

---

deploy/src/main/deploy/azure/arm/honoInfrastructureDeployment.json
deploy/src/main/deploy/azure/arm/templates/kubernetesDeploy.json
site/documentation/content/deployment/create-kubernetes-cluster.md

- Fixed an issue where the templates where not valid.
- Added option to define k8s version of AKS (especially necessary when the default in the template is no longer supported by Azure).
- Small fix on shell command as provided in Azure deployment guidance.
Kai
Signed-off-by: Kai Zimmermann <kai.zimmermann@microsoft.com>

Azure: Fix ARM template and provide option to define k8s version for AKS

---

tests/pom.xml
tests/src/test/resources/amqp/application.yml
tests/src/test/resources/coap/application.yml
tests/src/test/resources/http/application.yml
tests/src/test/resources/mqtt/application.yml

This is to prevent 
`org.eclipse.hono.client.ServerErrorException: request timed out after 200ms`
errors in the integration tests with regards to slower machines running them.
The `requestTimeout` setting of the `HonoConnection` `ClientConfigProperties`, used for request/response operations, is increased here to 500ms.

Increase request timeout in integration tests

---

bom/pom.xml
jmeter/Dockerfile
jmeter/pom.xml
jmeter/readme.md
jmeter/src/jmeter/http_messaging_throughput_test.jmx
jmeter/src/jmeter/load-test-http-router-docker.sh
jmeter/src/jmeter/load-test-http-router.sh
jmeter/src/jmeter/load-test-messaging-router-docker.sh
jmeter/src/jmeter/load-test-mqtt-router-docker.sh
jmeter/src/jmeter/load-test-mqtt-router.sh
jmeter/src/jmeter/mqtt_messaging_throughput_test.jmx
legal/src/main/resources/legal/NOTICE.md

Hi,
as I tried to execute the JMeter tests against my sample Hono installation on an AKS cluster they did not work as expected.
I mainly edited the RESTful calls to the device registry (JMeter scripts used outdated API) and upgraded the JMeter scripts that they are runnable with Apache JMeter 5.1.1 and MQTT XMeter 1.0.1. In addition to that I wrapped everything in a container that the current three load test bash scripts can be run from directly without having to worry about installation of JMeter and the plugins (XMeter and Hono). 
I used a dockerfile instead of the build style of fabric8io in pom, but included a link to this dockerfile so that fabric8io plugin will generate the load test image within a full Hono build as well.
Waiting for your questions, remarks and update requests! …

Update and docker-wrap JMeter tests.

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java

This prevents an NPE like this:
````
2019-11-18 10:34:59.443 [vert.x-eventloop-thread-0] DEBUG o.e.h.client.impl.AbstractHonoClient - locally closing receiver link [command_response/someTenant/someDevice]
Nov 18, 2019 10:34:59 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:221)
at org.eclipse.hono.util.HonoProtonHelper.closeAndFree(HonoProtonHelper.java:236)
at org.eclipse.hono.util.HonoProtonHelper.closeAndFree(HonoProtonHelper.java:207)
at org.eclipse.hono.client.impl.HonoConnectionImpl.closeAndFree(HonoConnectionImpl.java:582)
at org.eclipse.hono.client.impl.AbstractHonoClient.lambda$closeLinks$1(AbstractHonoClient.java:183)
at …
```

Prevent NPE in closeAndFree() if connection is not established

---

deploy/src/main/deploy/helm/requirements.yaml
deploy/src/main/deploy/helm/values.yaml
site/documentation/content/deployment/helm-based-deployment.md
site/homepage/content/release-notes.md

Updated Prometheus and Grafana charts to more recent versions which
support deployment to Kubernetes 1.16 and later.
This might also be a candidate for a 1.0.2 service release as IMHO people will quickly start to use Kubernetes 1.16 ...

Fix example deployment to Kubernetes 1.16

---

client/src/main/java/org/eclipse/hono/client/impl/CommandConsumer.java
client/src/main/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImpl.java
client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/DestinationCommandConsumer.java
client/src/test/java/org/eclipse/hono/client/impl/DelegateViaDownstreamPeerCommandHandlerTest.java

This fixes the `delegate Command request` tracing span containing `null` values for tenant and device id.
It also sets a `gateway_id` span tag if applicable.

Fix tracing of received commands

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactory.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/AmqpAdapterSaslAuthenticatorFactoryTest.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/resourcelimits/NoopResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/resourcelimits/ResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecksTest.java

This is a PR for  #1440. 
_Summary of changes:_
* The _ResourceLimitChecks_ interface has been extended here with methods to include an argument of type `SpanContext` to support tracing and the old methods are deprecated.
* Now in the default Prometheus based _resource-limits_ implementation several events are being traced.
* The existing methods `checkConnectionLimit(...)` and `checkMessageLimit(..)` in the base adapter class are deprecated and new methods that take an extra argument of type `SpanContext`are added.
* The protocol adapters now support the tracing of resource limit checks by making use of the above methods with an extra `SpanContext` argument.

[#1440] Track resource limit checks using OpenTracing.

---

site/documentation/content/user-guide/amqp-adapter.md
site/documentation/content/user-guide/mqtt-adapter.md

This fixes #1644.
Document limitations of gateways subscribing for single device
commands (concerning MQTT and AMQP adapter).

[#1644] Improve documentation on Command & Control and gateways

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/JsonBackedValueObject.java
core/src/main/java/org/eclipse/hono/util/JsonHelper.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
site/documentation/content/user-guide/http-adapter.md
site/homepage/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java

This fixes #1645.
This prevents issues with commands not reaching the correct adapter instance in case of concurrent HTTP requests. 
The solution here is to effectively disable the command gateway mapping for HTTP adapters by:
- always creating a device specific command consumer link (even if a gateway is involved)
- always mapping the `last-known-gateway` to the device id itself, not the gateway.
This changed behaviour is only enabled for tenants having the new `support-concurrent-gateway-device-command-requests` option set to `true` in the `adapters/ext` field.
This change can probably be reverted again once #1272 is implemented and adapter-specific command consumer links are introduced.

[#1645] Add tenant option disabling gateway mapping (HTTP adapter)

---

client/src/main/java/org/eclipse/hono/client/CommandContext.java
client/src/main/java/org/eclipse/hono/client/impl/DestinationCommandConsumer.java
client/src/test/java/org/eclipse/hono/client/impl/CommandConsumerFactoryImplTest.java

[#1515] Use configured initial credits in DestinationCommandConsumer

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandler.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/X509AuthHandler.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/ConnectPacketAuthHandlerTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/X509AuthHandlerTest.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/AuthHandler.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/ExecutionContextAuthHandler.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
site/documentation/content/user-guide/mqtt-adapter.md

The MQTT adapter now always includes the device's MQTT client identifier
in the *client context* which is sent to the Credentials service in the
get request.
In order for this to work, the example Credentials service
implementation had to be changed so that it no longer asserts that a
device's credentials on record also contain the properties submitted in
the client context. This check doesn't seem to make much sense in the
context of the use case at hand anyway. The overall idea of including
the client context was not to have additional matching criteria for
credentials but to allow a Credentials service implementation to e.g.
use information from the client context as the device ID or
authentication identifier (as in the Kapua case)
Fixes #1661
Signed-off-by: Kai Hudalla …

[#1661, #504] Include MQTT client ID in Credentials.get request

---

deploy/src/main/deploy/helm/templates/artemis/artemis-deployment.yaml
deploy/src/main/deploy/helm/templates/dispatch-router/dispatch-router-deployment.yaml
deploy/src/main/deploy/helm/templates/example-data-grid/statefulset.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-amqp/hono-adapter-amqp-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-coap/hono-adapter-coap-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-kura/hono-adapter-kura-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-lora/hono-adapter-lora-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-adapter-mqtt/hono-adapter-mqtt-vertx-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-auth/hono-service-auth-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-connection/hono-service-device-connection-deployment.yaml
deploy/src/main/deploy/helm/templates/hono-service-device-registry/hono-service-device-registry-deployment.yaml
deploy/src/main/deploy/helm/templates/jaeger/jaeger-deployment.yaml
deploy/src/main/deploy/helm/values.yaml

All containers' resource requests and limits can now be configured using
configuration properties of the Helm chart. Reasonable defaults for the
example deployment have also been added.

[#1674] Make resource requests/limits of containers configurable

---

core/src/main/java/org/eclipse/hono/util/Adapter.java
core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/Tenant.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java

In this PR, `TenantObject` is refactored to use `Adapter` as a data model instead of `List<Map<String, Object>>` to store adapter configurations. This also enables to share the same value object for Adapter configurations between the Management API and Tenant API.
In this PR,
- The `Adapter` class has been moved to the `core` module from the `service-base`.
- The below new methods are added to directly deal with objects of type `Adapter`.
```
List<Adapter> getAdapters();
TenantObject setAdapters(final List<Adapter> adapters) ;
Adapter getAdapter(final String type);
```
- The below methods are deprecated in favor of the above.
```
List<Map<String, Object>> getAdapterConfigurationsAsMaps()
JsonArray getAdapterConfigurations()
JsonObject getAdapterConfiguration(final String type) …
```

Share the same value object for adapter configurations between the Management and Tenant APIs

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
client/src/test/java/org/eclipse/hono/client/impl/HonoClientUnitTestHelper.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java

This adds a tag to tracing spans created by `AbstractHonoClient` implementations, containing the remote container id of the AMQP connection (as advertised in the `open` frame by the peer).
For that, a `HoneConnection#getRemoteContainer` method is added.
The remote container id information in traces can be useful in cases where the AMQP messaging network is represented by multiple containers behind a load balancer. For debugging error scenarios, it can be helpful to know to which container exactly a connection has been established.

Add HonoConnection#getRemoteContainer, use it in client span

---

tests/readme.md

The readme file in the tests module points now to the section in the developer guide that explains how to build the docker images from source.

[#1696] Fix link to documentation for building images in readme file.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantTraceSamplingHelper.java

Adds `try-catch` for `ProtonReceiver` handler code, acting as a safety net to ensure that receiver credit handling won't get corrupted by an exception in the handler code.
Also fixes a wrong span object being used in AMQP adapter receiver handler (incoming telemetry/event message handling spans should not get the span created during link creation as parent).

Add receiver exception handling; fix wrong span being used

---

adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterLegacyEndpointTest.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/amqp-vertx/src/test/resources/logback-test.xml
core/pom.xml
core/src/test/java/org/eclipse/hono/auth/SpringBasedHonoPasswordEncoderTest.java
core/src/test/java/org/eclipse/hono/config/KeyLoaderTest.java
core/src/test/java/org/eclipse/hono/connection/impl/ConnectionFactoryImplTest.java
core/src/test/java/org/eclipse/hono/tracing/MessageAnnotationsInjectExtractAdapterTest.java
core/src/test/java/org/eclipse/hono/tracing/TracingHelperTest.java
core/src/test/java/org/eclipse/hono/util/CredentialsObjectTest.java
core/src/test/java/org/eclipse/hono/util/JwtHelperTest.java
core/src/test/java/org/eclipse/hono/util/MessageTapTest.java
core/src/test/resources/logback-test.xml
pom.xml

Added configuration properties to the Surefire plugin that allows JUnit
5 based unit test classes to be run in parallel. The individual test
methods of each class are still run on the same thread in order to
prevent race conditions arising from field access.

Allow unit tests to be run in parallel

---

adapters/http-vertx-base/pom.xml
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
bom/pom.xml
legal/src/main/resources/legal/NOTICE.md
service-base/pom.xml
service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/http/ComponentMetaDataDecorator.java
service-base/src/main/java/org/eclipse/hono/service/http/HonoBasicAuthHandler.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
service-base/src/main/java/org/eclipse/hono/service/http/TenantTraceSamplingHandler.java
service-base/src/main/java/org/eclipse/hono/service/http/TracingHandler.java
service-base/src/main/java/org/eclipse/hono/service/http/WebSpanDecorator.java
service-base/src/main/java/org/eclipse/hono/service/http/X509AuthHandler.java
service-base/src/test/java/org/eclipse/hono/service/http/TenantTraceSamplingHandlerTest.java
service-base/src/test/java/org/eclipse/hono/service/http/X509AuthHandlerTest.java
site/homepage/content/release-notes.md

The TracingHandler classes have been copied to the service-base module
so that we can more easily adapt them to our needs. The upstream project
doesn't seem to be very active and it is just a few classes.
Also upgraded to Jaeger java-client 0.35.2 and Jaeger backend 1.16.

[#1681] Upgrade Opentracing and Jaeger

---

pom.xml
tests/pom.xml

Hono's container images use a base image with a jre-11 tag only, i.e.
there is no specific version being set. In order to always build using
the most recent Java 11 JRE, the image pull policy has been changed to
Always for the service components.
For running the integration tests, the image pull policy is still
IfNotPresent because the snapshot images being tested usually won't be
available from the Docker registry.

Use Always image pull policy for JRE base image

---

service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/Util.java
service-base/src/main/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementHttpEndpoint.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredDeviceManagementHttpEndpoint.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedRegistrationService.java

This is the first PR aiming to remove event bus from endpoint implementations. The idea is to do it step by step, so that we can review changes more easily in series of smaller PRs. More code improvements (and removal) will be done once all HTTP endpoints are refactored.

[#1346] Remove event bus from device management endpoint

---

core/src/main/java/org/eclipse/hono/util/ConnectionDuration.java
core/src/main/java/org/eclipse/hono/util/DataVolume.java
core/src/main/java/org/eclipse/hono/util/DataVolumePeriod.java
core/src/main/java/org/eclipse/hono/util/ResourceLimits.java
core/src/main/java/org/eclipse/hono/util/ResourceLimitsPeriod.java
core/src/main/java/org/eclipse/hono/util/TenantConstants.java
service-base/src/main/java/org/eclipse/hono/service/resourcelimits/NoopResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecks.java
service-base/src/main/java/org/eclipse/hono/service/resourcelimits/ResourceLimitChecks.java
service-base/src/test/java/org/eclipse/hono/service/management/tenant/TenantTest.java
service-base/src/test/java/org/eclipse/hono/service/resourcelimits/PrometheusBasedResourceLimitChecksTest.java
site/documentation/content/api/management/device-registry-v1.yaml

This PR is for the issue #1716. This PR extends the Tenant API to support a new additional _resource-limit_ configuration for _device connection duration_. Also the `ResourceLimitChecks` API has been extended to validate if the max connection duration of a tenant is reached or not.
NB: This PR has been raised even though the implementation is not complete, so that the concept can be reviewed at an early stage.

[#1716] Add new resource-limits based on the device connection duration

---

client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
core/src/main/java/org/eclipse/hono/util/HonoProtonHelper.java

This fixes #1718.
Fix onLinkEstablishmentTimeout(), not calling link.free()
there anymore (has caused session to get into invalid state).
Exceptions now get caught in disconnect/detach/close handlers
used in HonoConnectionImpl. A disconnect during link creation
now causes the creation attempt to be failed directly,
without waiting for the link establishment timeout.

[#1718] Add exception handling; improve link creation logic

---

core/src/main/java/org/eclipse/hono/config/ServiceConfigProperties.java
service-base/src/main/java/org/eclipse/hono/service/AbstractEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/amqp/RequestResponseEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
site/homepage/content/release-notes.md

This PR is intended for the issue #1441. 
The hard-coded send time out value can now be configured.

[#1441] Make hard-coded event bus send timeout configurable.

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java

This fixes #1750.
The timeout used in `closeConnection()` and in `shutdown()`, `disconnect()`
has also been reduced to *half* the connect timeout.
IMHO, waiting 2,5s (= half the 5s default connect timeout) should be enough by default.

[#1750] Fix shutdown/disconnect if used on event loop thread.

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
site/homepage/content/release-notes.md

Creating a new vertx instance in the `HonoConnectionImpl` constructor will likely cause issues on application shutdown, as this instance won't get closed automatically and therefore can prevent termination of the application.

Require vertx param in HonoConnection to be not null

---

client/src/main/java/org/eclipse/hono/client/impl/AbstractSender.java
client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/EventSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/TelemetrySenderImpl.java

This changes the log level of message sending errors from DEBUG to INFO in the {EventSenderImpl} class. 
Event messages are usually brokered and so issues when sending event messages may point to issues with the broker infrastructure, deserving a log level that gets more attention than DEBUG here.
Also the message address was added to log entries here.

Improve logging in Sender classes

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java

[#1726] Fix: accept command responses without payload in AMQP adapter.

---

adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/KerlinkProviderTest.java
client/src/main/java/org/eclipse/hono/client/Command.java
client/src/test/java/org/eclipse/hono/client/CommandResponseTest.java
client/src/test/java/org/eclipse/hono/client/CommandTest.java

The command message reply-to address must contain a non-empty
reply-id, otherwise preparing the CommandResponse message will
result in an exception. The missing check has been added,
along with corresponding tests.

Add missing check for Command without replyId in reply-to

---

service-base/src/main/java/org/eclipse/hono/service/management/Util.java
service-base/src/main/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementHttpEndpoint.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/AutowiredTenantManagementHttpEndpoint.java

First stab at converting Tenant API to direct implementation. Note that this is merely conversion of existing code. I think we can do more work in aligning and improving implementation across services, but I would leave that for the separate PR considering the time we have for the release

[#1346] Remove event bus from tenant management endpoint

---

core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericSecret.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordSecret.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
site/documentation/content/api/management/device-registry-v1.yaml
site/documentation/content/user-guide/device-registry.md
site/homepage/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsHttpIT.java

The device registry now only returns metadata and a secret ID for each secret.

[#1710] stop registry to return hashed-passwords details

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/CommandResponse.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttCommandEndpointConfiguration.java

This fixes #1781.
Fix use of command response MQTT topic with device but no tenant (`command//${device-id}/res/${req-id}/${status}`). Such a topic is to be used by authenticated gateways.
Also fixes integration tests - that topic wasn't used there.

[#1781] Fix use of command response topic with device but no tenant

---

client/src/main/java/org/eclipse/hono/client/Command.java
client/src/test/java/org/eclipse/hono/client/CommandTest.java
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java

This fixes #1785.
The target device id instead of the gateway id has to be set in the reply-to address of a command message. Otherwise command response messages will get the wrong `device_id` property value.
AMQP integration tests now check for the correct property value.

[#1785] Fix gateway id getting set in reply-to address

---

tests/src/test/java/org/eclipse/hono/tests/http/HttpCommandEndpointConfiguration.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java

The wrong command response URI was getting used in HTTP adapter integration tests involving a gateway.
This caused a wrong `device_id` property value to get set on the command response message.

Fix wrong command response URI getting used in tests

---

service-base/src/main/java/org/eclipse/hono/service/management/credentials/AbstractCredentialsManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CredentialsManagementService.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/EventBusCredentialsManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackend.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementService.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackendTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsService.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedDeviceBackend.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantBackend.java
services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/FileBasedTenantService.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedCredentialsServiceTest.java
services/device-registry/src/test/java/org/eclipse/hono/deviceregistry/FileBasedTenantServiceTest.java

Improve the consistency in method names and parameters order across the 3 components of the management API.
The parameters order is always following the same pattern, obviously when applicable : `tenantId, deviceId, PayloadDetails, ResourceVersion, Span, resultHandler`

[#1774] Align management API signatures

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapErrorResponse.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/TracingSupportingHonoResource.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
bom/pom.xml

Use query-parameter for "hono-ttd" instead of option and replace
content-type "application/vnd.eclipse-hono-empty-notification" by
query-parameter "empty". Both, custom option and content-type, would
require a code-point reservation at IANA. Though the use-case is very
hono specific, I think using query-parameters is more appropriate.

Add command and control to coap.

---

deploy/src/main/sandbox/sandbox_deploy.sh
jenkins/Hono-Deploy-Eclipse-Pipeline.groovy
jenkins/Hono-Deploy-Maven-Central-Pipeline.groovy
jenkins/Hono-Nightly-Pipeline.groovy
push_hono_images.sh
site/documentation/content/admin-guide/device-registry-config.md
site/documentation/content/deployment/helm-based-deployment.md

The jenkins pipeline scripts have been updated to use the  artifact _hono-service-device-registry-file_ instead of _hono-service-device-registry_, which exists no more after the device registry got refactored. Once the _mongodb_ based device registry is available then in addition to the _hono-service-device-registry-file_ it (_hono-service-device-registry-mongodb_) could also be added.

Update pipeline scripts in accordance with the refactored device registry

---

tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
tests/src/test/java/org/eclipse/hono/tests/coap/TelemetryCoapIT.java

Add coap one-way command integration test.
Assert coap-response-code instead of translated http-code.

Add coap oneway cmd and ctrl integration test

---

service-base/src/main/java/org/eclipse/hono/service/management/device/AbstractDeviceManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackend.java
service-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementService.java
service-base/src/main/java/org/eclipse/hono/service/management/device/EventBusDeviceManagementAdapter.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackendTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationServiceTest.java

The idea is to incrementally address the issue #1802 in a series of PRs, so that it is easier to review. As part of this PR the `DeviceManagementService` is refactored to return _vertx_ futures and also the related implementations.

[#1802] Refactor device management service to return future

---

core/src/main/java/org/eclipse/hono/util/RequestResponseApiConstants.java
service-base/src/main/java/org/eclipse/hono/service/amqp/AbstractRequestResponseEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/AbstractTenantAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/EventBusTenantAdapter.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantAmqpEndpoint.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AutowiredTenantAmqpEndpoint.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/AutowiredTenantManagementAdapter.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java

This is a first stub at creating a base and tenant AMQP endpoint implementation that doesn't use event bus. It's mostly based on the existing implementation. There are things I would improve, but I think it's a solid base we can continue working on (implement other services and improve things on the go).

Refactor Tenant AMQP endpoint not to use event bus

---

service-base/src/main/java/org/eclipse/hono/service/registration/AbstractRegistrationService.java
service-base/src/main/java/org/eclipse/hono/service/registration/EventBusRegistrationAdapter.java
service-base/src/main/java/org/eclipse/hono/service/registration/RegistrationService.java
service-base/src/test/java/org/eclipse/hono/service/registration/AbstractRegistrationServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/registration/BaseRegistrationServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/DummyRegistrationService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java

As part of this PR, the `RegistrationService` is refactored to return _vertx_ futures and also the related implementations. This should to be merged after PR #1803.

[#1802] Refactor device registration service

---

service-base/src/main/java/org/eclipse/hono/service/credentials/AbstractCredentialsAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsService.java
service-base/src/main/java/org/eclipse/hono/service/credentials/EventBusCredentialsAdapter.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/credentials/BaseCredentialsServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/DummyCredentialsService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java

In this PR, the `CredentialsService` is refactored to return _vertx_ futures and also the related classes have been adapted. This should to be merged after PR #1810.

[#1802] Refactor credentials service

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionClientFactory.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionInfo.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCacheConfig.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionInfoTest.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/ApplicationConfig.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionService.java

A Tracer instance is now available in `HotrodBasedDeviceConnectionInfo`, making it possible to create extra spans in the `DeviceConnectionInfo` method implementations. 
This will be extra useful for the additional Device Connection API methods to be created for #1272.

Add tracer instance in HotrodBasedDeviceConnectionInfo

---

service-base/src/main/java/org/eclipse/hono/service/management/credentials/AbstractCredentialsManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CredentialsManagementService.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/EventBusCredentialsManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackend.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackendTest.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java

In this PR, the `CredentialsManagementService` is refactored to return _vertx_ futures and also the related classes have been adapted. This should to be merged after PR #1814.

[#1802] Refactor credentials management service

---

service-base/src/main/java/org/eclipse/hono/service/management/credentials/AbstractCredentialsManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/CredentialsManagementService.java
service-base/src/main/java/org/eclipse/hono/service/management/credentials/EventBusCredentialsManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackend.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/AbstractTenantManagementHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/EventBusTenantManagementAdapter.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementService.java
service-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
service-base/src/test/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackendTest.java
service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedDeviceBackend.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantBackend.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantServiceTest.java

In this PR, the `TenantManagementService` is refactored to return _vertx_ futures and also the related classes have been adapted. This should to be merged after PR #1815.

[#1802] Refactor tenant management service

---

service-base/src/main/java/org/eclipse/hono/service/tenant/AbstractTenantAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/EventBusTenantAdapter.java
service-base/src/main/java/org/eclipse/hono/service/tenant/TenantService.java
service-base/src/test/java/org/eclipse/hono/service/tenant/AbstractTenantServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/DummyTenantService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantBackend.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java

In this PR, the `TenantService` is refactored to return _vertx_ futures and also the related classes have been adapted. This should to be merged after PR #1816.

[#1802] Refactor tenant service

---

service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/EventBusDeviceConnectionAdapter.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionService.java
services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
site/homepage/content/release-notes.md

In this PR, the `DeviceConnectionService` is refactored to return _vertx_ future and also the related classes have been adapted. Also the release notes has been updated for #1802.

[#1802] Refactor device connection service

---

service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/metric/MicrometerBasedMetrics.java
service-base/src/main/java/org/eclipse/hono/service/util/ServiceBaseUtils.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java

[#1823] Calculate payload size of the incoming message based on the configured minimum message size

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionClient.java
client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
core/src/main/java/org/eclipse/hono/util/DeviceConnectionConstants.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/EventBusDeviceConnectionAdapter.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionService.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java

This is the first step for #1272:
Three new methods have been added to the Device Connection API.
In order to keep this PR smaller, the implementation for the `HotrodBasedDeviceConnectionClient` will be added in a subsequent commit (see TODO comments in this PR).

[#1272] Add new Device Connection API methods

---

core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java

During the implementation of _mongodb_ based device registry, I came across the below tracing helper methods that takes either a _message_ or an _error_ as an argument. 
```
logError(final Span span, final String message)
logError(final Span span, final Throwable error)
```
In some cases, I prefer to log both the custom message and also the thrown exception. Hence as part of this PR, I have added the below method that takes both _message_ and _error_ as arguments and then logs them.
`logError(final Span span, final String message, final Throwable error)`

Extend tracing with provsion to accept message and error as arguments

---

services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedRegistrationService.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantService.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedTenantServiceTest.java

While working on #1679, I noticed that these methods in this PR could be reused among various device registry implementations and hence extracted them to a utility class in the device registry base module.

[#1679] Extract utility methods for reuse in device registry implementations

---

bom/pom.xml
client-device-connection-infinispan/pom.xml
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionClient.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionInfo.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCache.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/RemoteCache.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/Versioned.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionInfoTest.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCacheTest.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionService.java
services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheBasedDeviceConnectionServiceTest.java

This is for #1272:
Adds an implementation for the new Device Connection API methods to the Infinispan client.

[#1272] Implement new Device Connection API methods

---

client/src/main/java/org/eclipse/hono/client/impl/AbstractRequestResponseClient.java
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java

Running the command & control integration tests, there is a potential issue when one command gets sent while another is still not acknowledged (no delivery update received yet).
This is caused by the same command client instance getting used via the cache. The command client instance might get closed in one `sendCommand` invocation while the corresponding sender link is still used in another concurrent `sendCommand` invocation.
This PR fixes that.

Fix test issues with commands sent concurrently

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
site/documentation/content/user-guide/amqp-adapter.md
site/documentation/content/user-guide/coap-adapter.md
site/documentation/content/user-guide/http-adapter.md
site/documentation/content/user-guide/mqtt-adapter.md
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java

This is for #1272:
The workarounds introduced for #1645 and #1644 are obsolete with the new Command & Control implementation and are therefore removed here.
The `AbstractProtocolAdapterBase#isGatewayMappingEnabled()` method has also been removed - the gateway mapping can't be disabled with the new approach.

[#1272] Remove workaround to support concurrent TTD requests

---

bom/pom.xml
core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/util/DeviceRegistryUtils.java
services/device-registry-mongodb/pom.xml
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/Application.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/AbstractMongoDbBasedRegistryConfigProperties.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbBasedRegistrationConfigProperties.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbConfigProperties.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/BaseDto.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/DeviceDto.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceBackend.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbCallExecutor.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDeviceRegistryUtils.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java
services/device-registry-mongodb/src/main/resources/banner.txt
services/device-registry-mongodb/src/main/resources/logback-spring.xml
services/pom.xml

This PR is for the issue #1679, which is to provide a _mongodb_ based device registry. As a first step towards it, in this PR `DeviceManagementService `and `RegistrationService` have been implemented. In spite of some work left, I have raised this PR to collect some feedback. The tests will be added incrementally. Also some optimisations like pulling common configuration properties to the base module is in progress.

[#1679] Add mongodb based implementation of device registration and management services

---

services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsService.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/device/AbstractRegistrationService.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/tenant/NoopTenantInformationService.java

The NOOP implementation always succeeds and serves as the default
implementation being used if no TenantInformationService is set
explicitly.

Add NOOP TenantInformationService

---

services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java

To process the update device request, a function named `findOneAndReplace(...)` provided by the _MongoDB_ _Vert.x_ client has been used. By default, the handler for this method returns the document to be updated and not the updated document. This version in the returned document is used to set the _ETag_ header in the response. In order to get the newly updated document instead of the old one, _MongoDB_ client requires an extra flag be set. This is fixed in this PR, so that the new version is returned as _ETag_ instead of the old one.

[#1679] Return the version of the updated device.

---

service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java

Fix for #1860 for the 1.2.x branch (fix for master is in #1861).
This fixes Command & Control errors if the protocol adapter is configured with hono.app.maxInstances > 1.

(1.2.x) [#1860] Use unique adapter instance id per consumer factory

---

service-base/src/main/java/org/eclipse/hono/service/credentials/CredentialsService.java
service-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementService.java
service-base/src/main/java/org/eclipse/hono/service/management/tenant/TenantManagementService.java

The _JavaDoc_ of the _device management_ interface has been fixed now with the missing response codes to make it sync with that of the API definition in https://www.eclipse.org/hono/docs/api/management/.

[#1679] Update JavaDoc of the Device Management APIs for status codes

---

client/src/main/java/org/eclipse/hono/client/HonoConnection.java
client/src/main/java/org/eclipse/hono/client/ProtocolAdapterCommandConsumerFactory.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractHonoClient.java
client/src/main/java/org/eclipse/hono/client/impl/AdapterInstanceCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/HonoConnectionImpl.java
client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
client/src/test/java/org/eclipse/hono/client/impl/DisconnectHandlerProvidingConnectionFactory.java
client/src/test/java/org/eclipse/hono/client/impl/HonoConnectionImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
core/src/main/java/org/eclipse/hono/config/ClientConfigProperties.java
core/src/main/java/org/eclipse/hono/connection/ConnectionFactory.java
core/src/main/java/org/eclipse/hono/connection/impl/ConnectionFactoryImpl.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
site/homepage/content/release-notes.md

Fix for #1860.
Makes sure that each `ProtocolAdapterCommandConsumerFactory` instance gets assigned its own unique `adapterInstanceId` (which then kind of represents the `AbstractProtocolAdapterBase` instance that the command consumer factory instance is used in).

[#1860] Use unique adapter instance id per consumer factory

---

services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java

In this PR, an implementation of the `AbstractRegistrationService.resolveGroupMembers(...)` has been added to the _MongoDB_ based device registry.

[#1679] Add implementation to resolve group members in MongoDB based device registry

---

services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDeviceRegistryUtils.java

In the existing  `processAssertRegistration(...)` implementation of the device registry, the retrieved _device_ is first mapped to a `JsonObject`  before creating a `RegistrationResult`. In this PR, this device mapping to `JsonObject` has been avoided considering the potential performance setback. @sophokles73 Would you mind taking a look?

[#1679] Avoid conversion from Device to JsonObject in MongoDB based assertRegistration

---

core/src/main/java/org/eclipse/hono/util/RegistrationConstants.java
core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java

The unused constants and methods from `RegistrationConstants` and `RegistryManagementConstants` have been removed.

Remove unused constants and methods

---

bom/pom.xml
services/device-registry-mongodb/pom.xml
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
services/device-registry-mongodb/src/test/resources/logback-test.xml

This PR uses an embedded MongoDB (`de.flapdoodle.embed.mongo`) for running unit tests.

[#1679] Add tests for MongoDB based device registration services

---

services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java

The service instances are currently being set _manually_ by creating a new instance of the services using the keyword `new`. Those service implementations also contain `@Autowired` expecting the needed _beans_ to be injected automatically. But the corresponding _beans_ fail to get injected as the service instances are created with the keyword `new`. This has been fixed by creating those service instances using `@Bean` and then set _manually_.

Fix auto-wiring of service instances in MongoDB based device registry.

---

services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java

The password encoder has not been set for the file based credentials service, which leads to error while updating credentials. This has been fixed in this PR.

Fix missing password encoder for the file based device registry

---

pom.xml
tests/pom.xml
tests/readme.md

This adds the possibility to run Integration Tests on Docker containers left running from a previous test run.
With this, running the Integration Tests multiple times while developing new tests will be much faster, since docker containers don't need to be built, started and stopped each time.
Note that there is a new dependenc added here:
`properties-maven-plugin`
A possibility to set the logging level in the Docker containers has been added as well.

Enable Integration Tests to use already running docker containers

---

service-base/src/main/java/org/eclipse/hono/service/amqp/AbstractRequestResponseEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/credentials/DelegatingCredentialsAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DelegatingDeviceConnectionAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/registration/DelegatingRegistrationAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/tenant/DelegatingTenantAmqpEndpoint.java

This ensures that spans created as part of the `AbstractRequestResponseEndpoint#handleRequestMessage` operation get associated as _child_ spans to the "process request message" span, not as spans alongside each other, as it is done now:

Add spanContext param for handleRequestMessage()

---

bom/pom.xml
tests/pom.xml
tests/readme.md

This adds an option to run the integration tests in such a way that the created traces can later on be viewed in the Jaeger UI.

Add option to run integration tests with Jaeger

---

adapters/pom.xml
cli/pom.xml
client/pom.xml
core/pom.xml
example/pom.xml
pom.xml
services/pom.xml

For the `core` and `client` modules we use the *animal-sniffer-maven-plugin* in order to detect (and prevent) usage of language features that are not available on the target platform (Java 8).
The *maven-compiler-plugin* supports specifying the Java compiler's *release* option which serves the same purpose for for Java >= 9.

Prevent usage of Java > 11 language features

---

site/documentation/content/api/device-connection/index.md

This is for #1858:
See discussion here:
https://github.com/eclipse/hono/pull/1908#discussion_r412792617

[#1858] Describe 'lifespan' as mandatory for API implementations

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CommonCacheConfig.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCacheConfig.java
core/src/main/java/org/eclipse/hono/util/DeviceConnectionConstants.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/ApplicationConfig.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/EmbeddedCacheConfig.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/RemoteCacheConfig.java
site/documentation/content/admin-guide/device-connection-config.md

This allows providing a cache name for the Infinispan backend.
Additionally it mentions the *SASL realm* explicitly in the documentation.

Allow setting the name of the cache, explicitly mention sasl realm

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java

This is for #1858 and replaces #1922:
"Command handling adapter instance" entries may expire.
Therefore, getting a NOT FOUND result when invoking `removeCommandHandlingAdapterInstance()` shouldn't be treated as an error.
For that, the `DeviceConnectionClient.removeCommandHandlingAdapterInstance` method has been changed to return a `Future<Boolean>` now (instead of `Future<Void>`), with a `false` value returned if a NOT FOUND was received from the server.
When a command consumer is closed, the `removeCommandHandlingAdapterInstance` method is still called every time - just to be on the safe side, even though the entry might have been already deleted because it has expired.

[#1858] Don't treat removeCmdHandlingAdapterInstance 404 as error

---

client/pom.xml
core/pom.xml
site/homepage/content/release-notes.md

This removes the embedded OpenTracing API dependencies and adds a new profile named `embed-opentracing` which brings back the original behavior. However, this profile is not enabled by default.
IIRC this was the plan I discussed with @sophokles73 during BCX, the make it possible not-include the opentracing API, but also keep the current behavior as an option.
Additionally this PR fixes the OSGi ExecutionEnvironment configuration, which was still using the `java.level` property, which was removed a while back.

Externalize opentracing by default

---

bom/pom.xml
service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceConfigProperties.java
services/device-registry-mongodb/pom.xml
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbConfigProperties.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbCallExecutor.java
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java

This PR provides _basic authentication_ support for the _MongoDB_ based device registry. _Vert.x MongodB Auth Provider_ is used in this implementation. It makes use of the user credentials stored in a _MongoDB_ collection to authenticate client credentials.

[#1864] Add basic authentication support for the MongoDB based device registry

---

client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
site/documentation/content/api/device-connection/index.md
tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java

This is based on the discussion in https://github.com/eclipse/hono/pull/1936#discussion_r419448211:
The Device Connection API method `removeCommandHandlingAdapterInstance` now returns a `412` status code if no entry has been removed.
Previously, a return status code of `404` was documented, with `412` being an optional alternative.
Now using `412` aligns the definition with the one from the `setCommandHandlingAdapterInstance` method (see #1936).
This PR also fixes a bug in `CacheBasedDeviceConnectionService.removeCommandHandlingAdapterInstance()` where a "not found" result wasn't propagated in the `DeviceConnectionResult` (relates to https://github.com/eclipse/hono/pull/1926).

Let removeCommandHandlingAdapterInstance() return 412 if not removed

---

client/src/main/java/org/eclipse/hono/client/DownstreamSender.java
client/src/main/java/org/eclipse/hono/client/impl/AbstractDownstreamSender.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/ConnectionEventProducer.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java

fixes #1714
-  I placed the TTL config parameter in the `ClientConfigProperties` since protocol adapters connect to the messaging network to forward the `connection event` downstream. 
- I  currently set a default TTL value of 5 secs. Users can change the default  value  to any non-negative value by changing the corresponding config property.
@sophokles73 I was thinking of allowing  the  option  to set the value to `-1` if  a connection event message should be  keep in the broker (forever) until  it is consumed. WDYT? maybe this value would make a more sensible default?

[#1714] Set TTL for connection event messages.

---

service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java

Revision c2819c3 removes usage of the deprecate `setHandler()` API with `onComplete()`. This affects the recently merged #1923 pull request.

Removes the usage of setHandler()

---

core/src/main/java/org/eclipse/hono/util/TenantObject.java
core/src/test/java/org/eclipse/hono/util/TenantObjectTest.java
service-base/src/main/java/org/eclipse/hono/service/auth/device/TenantServiceBasedX509Authentication.java

According to the spec, the field "auto-provisioning-enabled" is not
mandatory. However the method TenantObject#addTrustAnchor throws a
NPE, while allowing a Boolean (vs boolean) parameter to be passed.
Additionally the method TenantObject#isAutoProvinsingEnabled() fails
with a NPE if the field is missing on the trust anchor.
This change also logs the full stack trace.
I think this should also be backported to 1.2.x.

Fix a NPE in the TenantObject

---

adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscription.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/CommandSubscriptionsManager.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java

This takes over the refactorings and tracing fixes done in https://github.com/eclipse/hono/pull/1941, but keeps the behaviour in case of a command ack timeout (i.e. the MQTT connection is kept open).

Refactor MQTT "afterCommandPublished" handling, fix tracing, add test

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
site/homepage/content/release-notes.md
tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java

Based on the discussion in #1632, the command link to the device is now kept open when the device hasn't sent a disposition update in time.

[#1632] Keep link open on cmd disposition update timeout

---

site/documentation/content/api/management/device-registry-v1.yaml

minor grammar fixes in the *code generation* section of the device registry API description.

Minor grammar fixes

---

services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/credentials/AbstractCredentialsManagementService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/config/MongoDbBasedCredentialsConfigProperties.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/CredentialsDto.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceBackend.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDeviceRegistryUtils.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java

This PR provides a mongo db based implementation of the credentials service and management APIs.
Some of the features such as merging of the secrets based on the secret ids, making use of the _ClientContext_ during _get_ operation are to be implemented incrementally. There are some more scope for improvements such as moving few validations and configurations to the abstract classes which will be implemented in next iterations.

[#1679] Part 1: Add mongo db based implementation of credentials service and management APIs

---

client/src/main/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandler.java
client/src/test/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandlerTest.java
client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java

When mapping and delegating a command message, the tenant is now being
extracted from the message's address instead of using the (static)
tenant used for creating the tenant scoped command receiver link.
Signed-off-by: Kai Hudalla <kai.hudalla@bosch.io>

Verify tenant from command target address

---

services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/EmbeddedCacheConfig.java
tests/pom.xml
tests/src/test/resources/amqp/application.yml
tests/src/test/resources/coap/application.yml
tests/src/test/resources/deviceconnection/application.yml
tests/src/test/resources/deviceconnection/cache-config.xml
tests/src/test/resources/deviceconnection/logback-spring.xml
tests/src/test/resources/http/application.yml
tests/src/test/resources/mqtt/application.yml

The integration tests are now run with the DeviceConnectionService
configured with an embedded cache instead of the Map based
implementation provided by the example registry.
This will make it easier to run the ITs with other registry
implementations once they are available.
Signed-off-by: Kai Hudalla <kai.hudalla@bosch.io>

Use DeviceConnectionService with embedded cache for ITs

---

services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordSecret.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskSecret.java
services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/CredentialsDto.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDeviceRegistryUtils.java

With this PR, the Mongo DB based device registry extends support for updating the credentials with existing secret identifiers.
This PR needs to merged after the #1947.

[#1679] Part 2: Support updating credentials with secret ids

---

services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java

This PR contains unit tests for the MongoDB based implementation of credentials service and management APIs. 
It also contains the below fixes in the `AbstractCredentialsServiceTest` class which are required for the for the above unit tests.
1. Now the test devices are created first before adding credentials to those devices.
2. The values being set during the _Future_ completion are being used even before that Future completes. This has been fixed.

[#1679] Part 3: Add tests for mongo db based credentials services

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java

This fixes #1998.
Applies a fixed lifespan for the `lastKnownGateway` cache entries. This is a minimalistic sotution for #1998. We should probably make this lifespan configurable. This can be done in a subsequent PR (possibly along with renaming `CommonCacheConfig` for that).

[#1998] Set lifespan for lastKnownGateway cache entries

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/BasicCache.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/Cache.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
client/src/main/java/org/eclipse/hono/client/DeviceConnectionClient.java
client/src/main/java/org/eclipse/hono/client/impl/DeviceConnectionClientImpl.java
client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java
client/src/test/java/org/eclipse/hono/client/impl/DeviceConnectionClientImplTest.java
client/src/test/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImplTest.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DelegatingDeviceConnectionAmqpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
site/documentation/content/api/device-connection/index.md
tests/src/test/java/org/eclipse/hono/tests/jms/JmsBasedDeviceConnectionClient.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java

This is for #1858.
The `updateOnly` parameter won't be needed anymore.

[#1858] Remove 'updateOnly' param in setCommandHandlingAdapterInstance

---

services/device-registry-mongodb/pom.xml
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialServiceTest.java
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationServiceTest.java
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedTenantServiceTest.java
services/device-registry-mongodb/src/test/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbTestUtils.java

The unit tests are now run using a single Mongo DB instance that is
started during the pre-integration-test phase and stopped in the
post-integration-test phase. The building of the Docker image has been
bould to the post-integration-test phase as well in order to not build
the image if any of the tests fail.
The downloaded Mongo DB artifacts are downloaded once only, cached
locally and re-used on subsequent builds.

[#1983] Run single Mongo DB instance for unit tests

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionClient.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodBasedDeviceConnectionClientFactory.java
core/src/main/java/org/eclipse/hono/tracing/TracingHelper.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java

This adopts the changes for #2008 in the 1.2.x branch. Compared to #2008, method signatures in the `DeviceConnectionInfo` interface have not been changed.

1.2: Add tracing in HotrodBasedDeviceConnectionClient

---

core/src/main/java/org/eclipse/hono/util/Futures.java
core/src/test/java/org/eclipse/hono/util/FuturesTest.java

[#2001] Use current vert.x context in Futures.create()

---

client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClient.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionClientFactory.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfo.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/DeviceConnectionInfo.java
client-device-connection-infinispan/src/test/java/org/eclipse/hono/deviceconnection/infinispan/client/CacheBasedDeviceConnectionInfoTest.java
service-base/src/main/java/org/eclipse/hono/service/deviceconnection/DeviceConnectionService.java
services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionServiceTest.java

Currently device connection requests only get traced when using the `DelegatingDeviceConnectionAmqpEndpoint`, i.e. when using a separate device connection service component.
This PR adds the corresponding trace spans also for the Hotrod client based device connection client.
Furthermore, when using `DelegatingDeviceConnectionAmqpEndpoint`, there are now no duplicate "getCommandHandlingAdapterInstances" spans anymore.

Add tracing in CacheBasedDeviceConnectionClient

---

site/documentation/content/admin-guide/mqtt-adapter-config.md
site/documentation/content/api/device-registration/index.md
site/documentation/content/api/management/device-registry-v1.yaml
site/documentation/content/user-guide/mqtt-adapter.md

Added documentation of the MQTT adapter's experimental "custom message
mapping" feature to Device Registry Management API, Device Registration
API, MQTT adapter user and admin guides.

[#1790] Add documentation

---

client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java

This fixes #2017.
Adopting changes from #2018 in 1.2.x.

[#2017] 1.2.x: Fix reconnect-handling concerning command_internal links

---

client/src/main/java/org/eclipse/hono/client/impl/DelegatedCommandSenderImpl.java
client/src/main/java/org/eclipse/hono/client/impl/MappingAndDelegatingCommandHandler.java
client/src/main/java/org/eclipse/hono/client/impl/ProtocolAdapterCommandConsumerFactoryImpl.java

This fixes #2017.
The sender links on the "command_internal/[adapterId]" address didn't get removed from the cache on connection close, so that these then invalid links still got used on the new proton connection, causing timeout exceptions.
Also the receiver on the "command_internal/[adapterId]" address might not have been recreated on connection close (if the link was still marked as "open" locally).

[#2017] Fix reconnect-handling concerning command_internal links

---

adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/providers/ThingsNetworkProvider.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/LoraTestUtil.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/LoraUtilsTest.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/providers/ThingsNetworkProviderTest.java
adapters/lora-vertx/src/test/resources/payload/ttn.uplink.with-null-payload.json

The TTN provider allows to send an empty payload message. This is indicated by an explicit `null` value in the `payload_raw` field.
This PR adds support for properly parsing and testing the TTN provider for this type of payload and also corrects the content type for that case for all providers.

Allow to use empty payloads with the TTN provider

---

site/homepage/content/release-notes.md

IMHO the link to the _user guide_ of the MongoDB Device registry is more appropriate in the _release notes_ than the configuration guide. The user guide also contains the link to the configuration page.

Add link to the user guide in the release notes for the MongoDB device registry

---

services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonSecret.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericSecret.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordSecret.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskSecret.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateSecret.java
services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/SecretsTest.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model/CredentialsDto.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedCredentialsService.java
site/documentation/content/api/management/device-registry-v1.yaml

I have added more thorough descriptive text to the PUT credentials operation, specifying the behavior to be implemented in a registry.
Also improved code for merging credentials and secrets and added unit
tests.

Improve description of credentials resources

---

services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpoint.java
services/device-registry-base/src/test/java/org/eclipse/hono/service/management/device/DeviceTest.java
tests/src/test/java/org/eclipse/hono/tests/IntegrationTestSupport.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceManagementIT.java

Added explicit error handling in case of failure to process requests.
Removed obsolete request payload parsing/modification.
Improved integration tests.

[#2020] Reject unknown properties in Device Management HTTP endpoint

---

core/src/main/java/org/eclipse/hono/util/CredentialsConstants.java
service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
services/base-jdbc/src/test/java/org/eclipse/hono/service/base/jdbc/store/device/JsonStoreTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/AbstractDelegatingRegistryHttpEndpoint.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/CommonCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/DelegatingCredentialsManagementHttpEndpoint.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/GenericCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PskCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/X509CertificateCredential.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/AutoProvisioningEnabledDeviceBackend.java
services/device-registry-base/src/test/java/org/eclipse/hono/service/credentials/AbstractCredentialsServiceTest.java
services/device-registry-base/src/test/java/org/eclipse/hono/service/management/credentials/CredentialsTest.java
services/device-registry-file/src/test/java/org/eclipse/hono/deviceregistry/file/FileBasedCredentialsServiceTest.java
tests/src/test/java/org/eclipse/hono/tests/DeviceRegistryHttpClient.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/MqttConnectionIT.java
tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsApiTests.java
tests/src/test/java/org/eclipse/hono/tests/registry/CredentialsManagementIT.java

Added explicit error handling in case of failure to process requests.
Improved integration tests.
Improved credentials and secret data objects to implicitly check
constraints on property values during de-serialization/instantiation.

[#2020] Reject unknown properties in Credentials Management endpoint

---

.travis.yml

The Travis build now starts two jobs in parallel, one for building and
testing the file based registry and another for testing the MongoDB
based registry.

Use parallel jobs to test both registry variants

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
bom/pom.xml

Requires Californium 2.3.0 release, scheduled for 16.06.2020.
So, on hold, as preview.

Use peers based deduplicator for coap-adapter

---

bom/pom.xml
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCache.java
client-device-connection-infinispan/src/main/java/org/eclipse/hono/deviceconnection/infinispan/client/HotrodCacheConfig.java
site/homepage/content/release-notes.md

The Hotrod client does no longer enforce (previous) values being
returned from the remote cache in the put and removeWithVersion methods
as in the former case the returned value isn't used anyway and in the
latter case the flag should not have any impact at all.

Do not enforce values to be returned from remote cache

---

adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/LoraConstants.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java

This changes the content type of the telemetry messages sent by the LoRaWAN adapter to drop the `+json` suffix.
The payload wasn't JSON before the refactoring, but also currently it is not JSON. So that is a bug IMHO. And it causes problems with JMS clients.
In the past this wasn't a big deal, because the payload contained an actual string (base 64 encoded payload). So the message could be decoded as a JMS text message.
Now the payload is a BLOB/byte array and decoding as a String will not always work. If the decoding as a string doesn't work, JMS libraries fail to decode the message into a JMS text message, and you cannot process them.
Dropping the `+json` suffix seems to be the right cause of action IMHO, as the payload never did contain a JSON structure.

Fix content type of the LoRaWAN adapter

---

services/device-connection/src/main/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionService.java
services/device-connection/src/test/java/org/eclipse/hono/deviceconnection/infinispan/CacheBasedDeviceConnectionServiceTest.java
services/device-registry-base/src/main/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionService.java
services/device-registry-base/src/test/java/org/eclipse/hono/deviceregistry/service/deviceconnection/MapBasedDeviceConnectionServiceTest.java
tests/src/test/java/org/eclipse/hono/tests/registry/DeviceConnectionApiTests.java

The status codes returned by the "Remove command-handling protocol
adapter instance for device" operation did not match the ones specified
by the API.
The API defines 404 to be the status code to be returned in case of
non-existing/non-matching entries and 412 being allowed in case of
non-matching entries only.

Fix return codes of Device Connection service implementations

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/SaslResponseContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java
adapters/http-vertx-base/src/test/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapterTest.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/VertxBasedHttpProtocolAdapter.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
adapters/lora-vertx/src/test/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
client/src/main/java/org/eclipse/hono/client/CommandContext.java
core/src/main/java/org/eclipse/hono/util/ExecutionContext.java
core/src/main/java/org/eclipse/hono/util/MapBasedExecutionContext.java
core/src/main/java/org/eclipse/hono/util/MessageHelper.java
core/src/main/java/org/eclipse/hono/util/QoS.java
core/src/test/java/org/eclipse/hono/util/MessageHelperTest.java
service-base/src/main/java/org/eclipse/hono/service/AbstractProtocolAdapterBase.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpUtils.java
service-base/src/main/java/org/eclipse/hono/service/http/TenantTraceSamplingHandler.java
service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
service-base/src/test/java/org/eclipse/hono/service/AbstractProtocolAdapterBaseTest.java
service-base/src/test/java/org/eclipse/hono/service/http/HttpContextTest.java

I started to implement this and it became a bigger change than I initially thought. Hence I am opening this PR to ask for feedback / guidance 😃 :
1. In my opinion the right place for the QoS property are the subclasses of `ExecutionContext`. However the HTTP adapter didn't have one so far (although I found such a class in the code base). Hence I decided to adapt the HTTP adapter to make the adapter implementations more consistent. This is the main reason why the change came out a lot bigger than I thought.
2. Currently there are 2 QoS enums. I am tempted to refactor this as well, but the change will be bigger then. Hence I thought I will add this in a separate commit (if we agree on it) to make this a bit easier to digest.
3. The QoS enum I introduced also has a `NOT_APPLICABLE` (used for …

[#2049] Adding AMQP application property "qos" for northbound consumers

---

adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Application.java

The package `org.eclipse.hono.service.credentials` can't be resolved here because it got moved from `service-base` to `device-registry-base` (which isn't used as a dependency here). Furthermore, the corresponding `Application` class from the MQTT adapter (as an adapter using the same base classes) also doesn't have this ComponentScan.

Remove obsolete ComponentScan

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapter.java
adapters/amqp-vertx/src/test/java/org/eclipse/hono/adapter/amqp/impl/VertxBasedAmqpProtocolAdapterTest.java
adapters/mqtt-vertx-base/src/test/java/org/eclipse/hono/adapter/mqtt/AbstractVertxBasedMqttProtocolAdapterTest.java

The AMQP adapter now always checks the adapter's connection limit
regardless of whether the device is authenticated or not.

[#2075] Check adapter connection limit for unauthenticated devices

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/Config.java
adapters/coap-vertx/src/main/java/org/eclipse/hono/adapter/coap/impl/Config.java
adapters/http-vertx/src/main/java/org/eclipse/hono/adapter/http/impl/Config.java
adapters/kura/src/main/java/org/eclipse/hono/adapter/kura/impl/Config.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/Config.java
adapters/mqtt-vertx/src/main/java/org/eclipse/hono/adapter/mqtt/impl/Config.java
adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/Config.java
core/src/main/java/org/eclipse/hono/config/AuthenticatingClientConfigProperties.java
service-base/src/main/java/org/eclipse/hono/service/AbstractAdapterConfig.java
site/homepage/content/release-notes.md

This fixes #1607.
Also introduce a new `getAdapterName` method, with which the default `config.name` on client configurations is set. This makes all of the currently used overridden `customize*Config` methods obsolete.

[#1607] Rename customize*Config methods to get*ConfigDefaults

---

adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/PreSharedKeyDeviceIdentity.java

The top level `PSK-getDeviceIdentityInfo` trace span (created as part of the TLS handshake handling) will be a 0ms operation with no child spans if the device id is taken from a previous lookup. Therefore the creation of such a span should better be skipped in that case, so that the span is only created if an actual device id lookup is done (in case of a session resumption).
With this PR, instead of the two `PSK-getSecretKey` and `PSK-getDeviceIdentityInfo` spans, there will only be one `PSK-getDeviceSecretKeyAndIdentityInfo` span.

CoAP adapter: Skip 'PSK-getDeviceIdentityInfo' span if no lookup is done

---

jenkins/Hono-Website-Pipeline.groovy

The stable version is always present one URL level above the other versions
(i.e. without a version number in the URL). This change makes the stable
version additionally available under its version number, allowing to chose
if external (or even internal) links should point to a specific version
(e.g. /docs/1.3/user-guide/http-adapter/) or the latest stable version
(e.g. /docs/user-guide/http-adapter/).

Docu: adding the stable version additionally under its version number.

---

site/documentation/content/admin-guide/device-registry-config.md
site/documentation/content/user-guide/device-registry.md

Fixes #2095. 
Needs to be cherrypicked into the docfix branch for version 1.3.

[#2095] Restore links to device registry user guide and admin guide.

---

site/documentation/content/concepts/connecting-devices/index.md

Adds a reference in the documentation to the MQTT Protocol Gateway Template in
the hono-extras repository.

Add link to MQTT protocol gateway template.

---

adapters/amqp-vertx/src/main/java/org/eclipse/hono/adapter/amqp/impl/AmqpContext.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/CoapContext.java
adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/impl/VertxBasedCoapAdapter.java
adapters/coap-vertx-base/src/test/java/org/eclipse/hono/adapter/coap/AbstractVertxBasedCoapAdapterTest.java
adapters/lora-vertx/src/main/java/org/eclipse/hono/adapter/lora/impl/LoraProtocolAdapter.java
adapters/mqtt-vertx-base/src/main/java/org/eclipse/hono/adapter/mqtt/MqttContext.java
adapters/sigfox-vertx/src/main/java/org/eclipse/hono/adapter/sigfox/impl/SigfoxProtocolAdapter.java
core/src/main/java/org/eclipse/hono/util/ExecutionContext.java
core/src/main/java/org/eclipse/hono/util/MapBasedTelemetryExecutionContext.java
core/src/main/java/org/eclipse/hono/util/TelemetryExecutionContext.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpContext.java

All protocol adapters now consistently retrieve the authenticated device
from the ExecutionContext used for processing a message from a device.

Add authenticated device to execution context

---

site/documentation/content/api/management/device-registry-v1.yaml

The GET request used for retrieving devices of a tenant now uses query
parameters instead of the request body to specify search criteria.

[#1958] Use query parameters instead of request body

---

core/src/main/java/org/eclipse/hono/util/RegistryManagementConstants.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DelegatingDeviceManagementHttpEndpoint.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceManagementService.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/DeviceWithId.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Filter.java
services/device-registry-base/src/main/java/org/eclipse/hono/service/management/device/Sort.java

This PR focuses on extending the device registry base classes to support the implementation of the search devices operation in the _MongoDB_ based device registry.

[#2112] Part 1: Extend device registry base classes for search devices operation

---

services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedDeviceBackend.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/service/MongoDbBasedRegistrationService.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/utils/MongoDbDocumentBuilder.java

With this PR, the _MongoDB based device registry_ supports search devices operation as specified in the OpenAPI spec by #1958. The tests are in progress.

[#2112] Add search devices operation in MongoDB based device registry

---

tests/src/test/java/org/eclipse/hono/tests/amqp/CommandAndControlAmqpIT.java
tests/src/test/java/org/eclipse/hono/tests/coap/CoapTestBase.java
tests/src/test/java/org/eclipse/hono/tests/http/HttpTestBase.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/CommandAndControlMqttIT.java
tests/src/test/java/org/eclipse/hono/tests/mqtt/EventMqttIT.java

Exit test methods when `vertxTestContext.failNow(t)` has been called.
Otherwise a subsequent exception in the following code might hide the original exception.
Happened in a recent integration test run:
The original error
````
20:33:51.417 [main] INFO  o.e.h.t.amqp.CommandAndControlAmqpIT - running testSendOneWayCommandSucceeds(AmqpCommandEndpointConfiguration, VertxTestContext) [1]; parameters: subscribe as: DEVICE, southbound endpoint: command, northbound endpoint: command
20:33:52.250 [vert.x-eventloop-thread-2] ERROR o.e.h.t.amqp.CommandAndControlAmqpIT - failed to establish connection to AMQP adapter [host: localhost, port: 32785]
javax.security.sasl.AuthenticationException: Failed to authenticate
at io.vertx.proton.impl.ProtonSaslClientAuthenticatorImpl.handleSaslFail(ProtonSaslClien …
```

Exit tests after vertxTestContext.failNow(t)

---

tests/src/test/java/org/eclipse/hono/tests/CrudHttpClient.java

The `HttpClient#handler` API has been deprecated and the deprecation warning suppressed in revision ed756f8f. This patch replaces the usage of the `HttpClient` in the integration tests module with the new `WebClient` API 

Use Vert.x WebClient API in integration tests

---

core/src/main/java/org/eclipse/hono/util/Constants.java
deploy/src/main/sandbox/hono-service-device-registry-config.yml
service-base/src/main/java/org/eclipse/hono/service/http/AbstractHttpEndpoint.java
service-base/src/main/java/org/eclipse/hono/service/http/HttpServiceBase.java
services/device-registry-file/src/main/java/org/eclipse/hono/deviceregistry/file/FileBasedServiceConfig.java
services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/ApplicationConfig.java
site/documentation/content/admin-guide/file-based-device-registry-config.md
tests/src/test/resources/deviceregistry/application.yml

Added support for using hono.registry.http for configuring the file
based registry's HTTP endpoint instead. The old prefix is still
supported but marked as deprecated.

Mark hono.registry.rest property prefix as deprecated
